const u = [
    "https://www.baume-et-mercier.com/us/en/collections/baume-/watch-baume-10587-date.html",
    "https://www.baume-et-mercier.com/us/en/collections/baume-/watch-baume-10590.html",
    "https://www.baume-et-mercier.com/us/en/collections/baume-/watch-baume-10599-small-seconds.html",
    "https://www.baume-et-mercier.com/us/en/collections/baume-/watch-baume-10600-small-seconds.html",
    "https://www.baume-et-mercier.com/us/en/collections/baume-/watch-baume-10601-date.html",
    "https://www.baume-et-mercier.com/us/en/collections/baume-/watch-baume-10602-date.html",
    "https://www.baume-et-mercier.com/us/en/collections/baume-/watch-baume-10603-date.html",
    "https://www.baume-et-mercier.com/us/en/collections/baume-/watch-baume-10604-small-seconds.html",
    "https://www.baume-et-mercier.com/us/en/collections/classima-men/watch-classima-10416-date.html",
    "https://www.baume-et-mercier.com/us/en/collections/classima-men/watch-classima-10597-date.html",
    "https://www.baume-et-mercier.com/us/en/collections/classima-men/watch-classima-10607-date.html",
    "https://www.baume-et-mercier.com/us/en/collections/classima-men/watch-classima-10608-date.html",
    "https://www.baume-et-mercier.com/us/en/collections/classima-women/watch-classima-10598-date.html",
    "https://www.baume-et-mercier.com/us/en/collections/classima-women/watch-classima-10609-date.html",
    "https://www.baume-et-mercier.com/us/en/collections/classima-women/watch-classima-10610-date.html",
    "https://www.baume-et-mercier.com/us/en/collections/classima-women/watch-classima-10633-moon-phase.html",
    "https://www.baume-et-mercier.com/us/en/collections/clifton-club-men/watch-clifton-club-10338-date.html",
    "https://www.baume-et-mercier.com/us/en/collections/hampton-women/watch-hampton-10628.html",
    "https://www.baume-et-mercier.com/us/en/collections/hampton-women/watch-hampton-10629.html",
    "https://www.baume-et-mercier.com/us/en/collections/hampton-women/watch-hampton-10630.html",
    "https://www.baume-et-mercier.com/us/en/collections/hampton-women/watch-hampton-10631.html",
    "https://www.baume-et-mercier.com/us/en/collections/promesse-women/watch-promesse-10252.html",
    "https://www.baume-et-mercier.com/us/en/collections/riviera-men/watch-riviera-10616-date.html",
    "https://www.baume-et-mercier.com/us/en/collections/riviera-men/watch-riviera-10617-date.html",
    "https://www.baume-et-mercier.com/us/en/collections/riviera-men/watch-riviera-10619-date.html",
    "https://www.baume-et-mercier.com/us/en/collections/riviera-men/watch-riviera-10620-date.html",
    "https://www.baume-et-mercier.com/us/en/collections/riviera-men/watch-riviera-10621-date.html",
    "https://www.baume-et-mercier.com/us/en/collections/riviera-men/watch-riviera-10622-date.html",
    "https://www.baume-et-mercier.com/us/en/collections/riviera-women/watch-riviera-10612-date.html",
    "https://www.baume-et-mercier.com/us/en/collections/riviera-women/watch-riviera-10613-date.html",
    "https://www.baume-et-mercier.com/us/en/collections/riviera-women/watch-riviera-10614-date.html",
    "https://www.baume-et-mercier.com/us/en/collections/riviera-women/watch-riviera-10615-date.html",
];

module.exports = u;