const u = [
    "https://www.iwc.com/en/past-collections/ingenieur/iw381802-ingenieur-perpetual-calendar-digital-date-month.html",
    "https://www.iwc.com/en/past-collections/portofino/iw458108-portofino-automatic-37.html",
    "https://www.iwc.com/en/watch-collections/pilot-watches/iw329301-big-pilots-watch-43.html",
    "https://www.iwc.com/en/watch-collections/pilot-watches/iw329303-big-pilots-watch-43.html",
    "https://www.iwc.com/en/watch-collections/pilot-watches/iw329304-big-pilots-watch-43.html",
    "https://www.iwc.com/en/watch-collections/pilot-watches/iw357201-big-pilots-watch-shock-absorber-xpl.html",
    "https://www.iwc.com/en/watch-collections/pilot-watches/iw387903-pilot_s-watch-chronograph-spitfire.html",
    "https://www.iwc.com/en/watch-collections/pilot-watches/iw387905-pilot_s-watch-chonograph-edition-tribute-to-3705.html",
    "https://www.iwc.com/en/watch-collections/pilot-watches/iw388101-pilot_s-watch-chronograph-41.html",
    "https://www.iwc.com/en/watch-collections/pilot-watches/iw388102-pilot_s-watch-chronograph-41.html",
    "https://www.iwc.com/en/watch-collections/pilot-watches/iw388103-pilot_s-watch-chronograph-41.html",
    "https://www.iwc.com/en/watch-collections/pilot-watches/iw388104-pilot_s-watch-chronograph-41.html",
    "https://www.iwc.com/en/watch-collections/pilot-watches/iw392202-pilot_s-watch-perpetual-calendar-chronograph-edition-le.html",
    "https://www.iwc.com/en/watch-collections/pilot-watches/iw501015-big-pilots-watch.html",
    "https://www.iwc.com/en/watch-collections/pilot-watches/iw503001-big-pilots-watch-perpetual-calendar-edition-rodeo-drive.html",
    "https://www.iwc.com/en/watch-collections/pilot-watches/iw503004-big-pilots-watch-perpetual-calendar-top-gun-edition-moj.html",
    "https://www.iwc.com/en/watch-collections/pilot-watches/iw503605-big-pilots-watch-perpetual-calendar.html",
    "https://www.iwc.com/en/watch-collections/pilot-watches/iw506003-big-pilots-watch-top-gun-edition-mojave-desert.html",
    "https://www.iwc.com/en/watch-collections/portofino/iw357401-portofino-automatic-34.html",
    "https://www.iwc.com/en/watch-collections/portofino/iw357403-portofino-automatic-34.html",
    "https://www.iwc.com/en/watch-collections/portofino/iw357406-portofino-automatic-34.html",
    "https://www.iwc.com/en/watch-collections/portugieser/iw344001-portugieser-yacht-club-moon--tide.html",
    "https://www.iwc.com/en/watch-collections/portugieser/iw371614-portugieser-chronograph-boutique-edition.html",
    "https://www.iwc.com/en/watch-collections/portugieser/iw390701-portugieser-yacht-club-chronograph.html",
    "https://www.iwc.com/en/watch-collections/portugieser/iw394006-portugieser-tourbillon-retrograde-chronograph.html",
    "https://www.iwc.com/en/watch-collections/portugieser/iw500713-portugieser-automatic-boutique-edition.html",
    "https://www.iwc.com/en/watch-collections/portugieser/iw503501-portugieser-annual-calendar.html",
];

module.exports = u;