export const mkt = {
    'aboutvintage': ['JPN', 'USA', 'DNK',],
    'alangesoehne': [],
    'alpina': ['USA', 'DNK'],
    'armani': ['JPN', 'USA', 'DNK', 'HKG', 'CAN', 'DEU', 'FRA', 'ITA', 'GRC', 'GBR'],
    'audemarspiguet': ['JPN', 'USA', 'HKG', 'DEU', 'FRA', 'ITA', 'GBR', 'SGP'],
    'ball': ['USA', 'SGP'],
    'baumemercier': ['JPN', 'USA', 'HKG', 'DEU', 'FRA', 'ITA', 'GBR', 'SGP'],
    'bellross': ['SGP'],
    'blancpain': ['USA', 'SGP'],
    'breguet': ['USA', 'SGP'],
    'breitling': ['JPN', 'USA', 'DNK', 'HKG', 'CAN', 'DEU', 'FRA', 'ITA', 'GRC', 'GBR', 'SGP', 'TWN'],
    'bremont': ['USA', 'HKG', 'DEU', 'FRA', 'GBR'],
    'briston': [],
    'bulgari': ['JPN', 'USA', 'HKG', 'CAN', 'DEU', 'FRA', 'ITA', 'GBR', 'SGP', 'TWN'],
    'bulova': [],
    'burberry': [],
    'cartier': ['JPN', 'USA', 'DNK', 'HKG', 'CAN', 'DEU', 'FRA', 'ITA', 'GRC', 'GBR', 'SGP', 'TWN'],
    'casio': ['JPN', 'USA', 'HKG', 'CAN', 'DEU', 'FRA', 'ITA', 'GBR', 'SGP', 'TWN'],
    'chanel': ['JPN', 'USA', 'DEU', 'FRA', 'GBR'],
    'chaumet': ['JPN', 'FRA'],
    'chopard': ['JPN', 'USA', 'DEU', 'FRA', 'GBR'],
    'citizen': ['USA', 'CAN'],
    'cvstos': [],
    'diesel': ['JPN', 'USA', 'DNK', 'CAN', 'DEU', 'FRA', 'ITA', 'GRC', 'GBR'],
    'festina': ['DEU', 'FRA', 'ITA', 'GBR'],
    'fossil': ['JPN', 'USA', 'CAN', 'DEU', 'FRA', 'ITA', 'GBR'],
    'frederiqueconstant': ['USA', 'DNK', 'SGP', 'ITA', 'FRA', 'DEU'],
    'gagamilano': [],
    'garmin': ['JPN', 'USA', 'DNK', 'HKG', 'CAN', 'DEU', 'FRA', 'ITA', 'GBR', 'SGP', 'TWN'],
    'geraldgenta': [],
    'girardperregaux': ['JPN', 'USA', 'GBR'],
    'glashuette': ['USA', 'DNK', 'SGP'],
    'grandseiko': ['JPN', 'USA', 'DEU', 'FRA', 'ITA', 'GBR', 'TWN'],
    'gucci': ['JPN', 'USA', 'HKG', 'CAN', 'DEU', 'FRA', 'ITA', 'GBR'],
    'guess': ['USA'],
    'hamilton': ['JPN', 'USA', 'HKG', 'CAN', 'DEU', 'FRA', 'ITA', 'GRC', 'GBR', 'SGP', 'TWN'],
    'hermes': [],
    'hublot': ['JPN', 'USA', 'HKG', 'CAN', 'DEU', 'FRA', 'ITA', 'GRC', 'GBR', 'TWN'],
    'hugoboss': ['USA', 'DNK', 'DEU', 'FRA', 'ITA', 'GBR', 'TWN'],
    'hyt': ['USA'],
    'iwc': ['JPN', 'USA', 'DNK', 'HKG', 'CAN', 'DEU', 'FRA', 'ITA', 'GRC', 'GBR', 'SGP', 'TWN'],
    'jaguar': [],
    'jaquetdroz': [],
    'jlc': ['JPN', 'USA', 'DNK', 'HKG', 'CAN', 'DEU', 'FRA', 'ITA', 'GBR', 'SGP', 'TWN'],
    'longines': ['JPN', 'USA', 'HKG', 'DEU', 'FRA', 'ITA', 'GBR'],
    'louisvuitton': ['JPN', 'USA', 'HKG', 'CAN', 'ITA', 'SGP', 'TWN'],
    'marcbymarcjacobs': [],
    'marcjacobs': ['JPN', 'USA', 'DNK'],
    'maserati': ['JPN', 'USA', 'DNK', 'HKG', 'CAN', 'DEU', 'FRA', 'ITA', 'GRC', 'GBR', 'SGP', 'TWN'],
    'mauricelacroix': ['JPN', 'USA', 'DEU'],
    'meistersinger': ['USA', 'DEU'],
    'memorigin': ['HKG'],
    'michaelkors': ['DNK', 'HKG', 'GRC', 'SGP', 'TWN'],
    'mido': ['JPN', 'USA', 'HKG', 'CAN', 'DEU', 'FRA', 'ITA', 'GBR', 'SGP', 'TWN'],
    'montblanc': ['JPN', 'USA', 'DNK', 'HKG', 'CAN', 'DEU', 'FRA', 'ITA', 'GRC', 'GBR', 'SGP', 'TWN'],
    'muhleglashuette': [],
    'nomosglashuette': ['USA', 'DNK', 'SGP'],
    'omega': ['USA', 'DNK', 'GBR', 'SGP'],
    'orient': ['USA'],
    'oris': ['USA', 'DNK', 'SGP'],
    'panerai': ['JPN', 'USA', 'HKG', 'CAN', 'DEU', 'FRA', 'ITA', 'GRC', 'GBR', 'SGP', 'TWN'],
    'parmigiani': [],
    'patekphilippe': ['JPN', 'USA', 'HKG', 'DEU', 'FRA', 'ITA', 'GBR', 'SGP', 'TWN'],
    'piaget': ['JPN', 'USA', 'DNK', 'HKG', 'CAN', 'DEU', 'FRA', 'ITA', 'GBR', 'SGP', 'TWN'],
    'rado': ['USA', 'DNK', 'DEU', 'GBR', 'SGP'],
    'rolex': ['JPN', 'USA', 'DNK', 'HKG', 'CAN', 'DEU', 'FRA', 'ITA', 'GBR', 'SGP', 'TWN'],
    'seiko': ['JPN', 'USA', 'CAN', 'DEU', 'FRA', 'ITA', 'GBR', 'TWN'],
    'sevenfriday': ['USA'],
    'sinn': [],
    'skagen': ['JPN', 'USA', 'DEU', 'GBR'],
    'suunto': ['JPN', 'USA', 'DNK', 'HKG', 'CAN', 'DEU', 'FRA', 'ITA', 'GBR', 'SGP', 'TWN'],
    'tagheuer': ['JPN', 'USA', 'DNK', 'HKG', 'CAN', 'DEU', 'FRA', 'ITA', 'GRC', 'GBR', 'SGP', 'TWN'],
    'tissot': ['JPN', 'USA', 'DNK', 'HKG', 'CAN', 'DEU', 'FRA', 'ITA', 'GRC', 'GBR', 'SGP'],
    'tommyhilfiger': [],
    'tudor': ['USA', 'DNK', 'SGP'],
    'tutimaglashuette': [],
    'ulyssenardin': ['JPN', 'USA', 'GBR'],
    'vacheronconstantin': ['JPN', 'USA', 'HKG', 'CAN', 'DEU', 'FRA', 'ITA', 'GRC', 'GBR', 'SGP', 'TWN'],
    'victorinox': ['JPN', 'USA', 'HKG', 'CAN', 'DEU', 'FRA', 'GBR', 'TWN'],
    'watchstation': ['USA', 'CAN'],
};
