export const color_zh = {
  "Skeleton": "镂空表盘",
  "Transparent": "透明表盘",
  "Beige Gold": "米色金",
  "Beige": "米色",
  "Black": "黑色",
  "Black Mother of Pearl": "黑珍珠色",
  "Blue": "藍色",
  "Blue Mother of Pearl": "藍珍珠色",
  "Brown": "棕色",
  "Brown Mother of Pearl": "棕珍珠色",
  "Champagne": "香檳色",
  "Diamond": "鑽石",
  "Green": "綠色",
  "Green Mother of Pearl": "綠珍珠色",
  "Grey": "灰色",
  "Khaki": "黄褐色",
  "Multi-color": "彩色",
  "Navy": "深藍色",
  "Orange": "橘色",
  "Rose Gold": "玫瑰金色",
  "Pink": "粉紅",
  "Pink Mother of Pearl": "粉红珍珠色",
  "Purple": "紫色",
  "Purple Mother of Pearl": "紫珍珠色",
  "Red": "紅色",
  "Red Mother of Pearl": "紅珍珠色",
  "Silver": "銀色",
  "White Gold": "白金色",
  "White": "白色",
  "White Mother of Pearl": "白珍珠色",
  "Yellow Gold": "黄金色",
  "Yellow": "黄色",
  "Yellow Mother of Pearl": "黄珍珠色",
  "Gold": "金色",
  "Mother Of Pearl": "珍珠色",
  "Diamond paved": "鑽石密鑲",
  "Crystal paved": "水晶密鑲",
};

export const style_zh = {
  "Luxury": "奢華手錶",
  "Casual": "休閒手錶",
  "Dive": "潛水手錶",
  "Dress": "正裝手錶",
  "Sport": "運動手錶",
  "Fashion": "時尚手錶",
  "Military": "軍事手錶",
  "Pilot": "飛行員手錶",
  "Smart": "智能手錶",
  "Travel": "旅遊手錶",
};

export const band_zh = {
  "Strap": "普通錶帶",
  "Bracelet": "金屬錶帶",
  "Jubilee": "紀念型錶帶",
  "Oyster": "蠔式錶帶",
  "President": "元首型錶帶",
  "Pearlmaster": "Pearlmaster錶帶",
};

export const shape_zh = {
  "Round": "圓形手錶",
  "Rectangle": "長方形手錶",
  "Oval": "橢圓手錶",
  "Cushion": "枕型手錶",
  "Octagon": "八角形手錶",
  "Square": "方形手錶",
  "Unique": "特別形",
  "Other": "其它",
  "Rectangular": "矩形手錶",
  "Rhombus": "菱形手錶",
  "Tonneau": "酒桶形狀",
  "Star": "其它",
};

export const dialType_zh = {
  "Analog": "指針式手錶",
  "Digital": "電子錶",
  "Analog-Digital": "指針電子錶",
};

export const gender_zh = {
  "M": "男士",
  "F": "女士",
  "X": "男女通用",
};

export const movement_zh = {
  "Automatic": "自動機械錶",
  "Processor": "電子手錶",
  "Quartz": "石英錶",
  "Spring Drive": "Spring Drive",
  "Manual": "手動上鏈手錶",
  "Kinetic": "動能手錶",
  "Smart Watch": "智能手錶",
  "Eco-Drive": "Eco-Drive",
};

export const material_zh = {
  "18K Red Gold": "18K 紅金",
  "Red Gold": "紅金",
  "18K Everose Gold": "18K 玫瑰金",
  "Everose Gold": "玫瑰金",
  "18K Gold": "18K 金",
  "18K Pink Gold": "18K 粉紅金",
  "Pink Gold": "粉紅金",
  "18K Rose Gold": "18K 玫瑰金",
  "Rose Gold": "玫瑰金",
  "18K White Gold": "18K 白金",
  "White Gold": "白金",
  "18K Yellow Gold": "18K 黃金",
  "Yellow Gold": "黃金",
  "Acrylic": "壓克力",
  "Alloy": "合金",
  "Aluminum": "鋁合金",
  "Brass": "黃銅",
  "Bronze": "青銅",
  "Ceramic": "陶瓷",
  "Composite": "複合材料",
  "Diamond": "鑽石",
  "Fiber": "繊維",
  "Glass": "玻璃",
  "Gold": "金",
  "Palladium": "鈀金",
  "Plastic": "塑膠",
  "Platinum": "鉑金",
  "Polycarbonate": "聚碳酸脂",
  "Polyurethane": "聚氨酯",
  "Resin": "樹脂",
  "Rubber": "橡膠",
  "Sapphire": "藍寶石水晶",
  "Silicone": "矽膠",
  "Silver": "銀",
  "Stainless Steel": "不銹鋼",
  "Titanium": "鈦金",
  "Titanium and Rose Gold": "鈦金與玫瑰金",
  "Titanium and White Gold": "鈦金與白金",
  "Tungsten": "鎢鋼",
  "Steel": "鋼",
  "Leather": "皮革",
  "Alligator Leather": "鱷魚皮",
  "Crocodile Leather": "鱷魚皮",
  "Calfskin Leather": "小牛皮",
  "Base Metal": "金屬",
  "Acetate": "醋酸鹽",
  "Enamel": "搪瓷",
  "Canvas": "帆布料",
  "Crystal": "水晶",
  "Fabric": "布料",
  "Nylon": "尼龍",
  "Polycarbon": "聚碳酸酯",
  "Quartz": "石英",
  "Satin": "緞帶",
  "Wood": "木料",
  "Mother of Pearl": "珍珠母",
  "Carbon Fiber": "碳纖維",
  "Fiber Glass": "玻璃纖維",
};

export const buckle_zh = {
  "Fold-Over Push Button Deployant Clasp": "折疊式按鈕展開式錶扣",
  "Push Button Deployant Clasp": "按鈕展開式錶扣",
  "Flip Clasp": "翻轉式錶扣",
  "Butterfly Clasp": "蝴蝶扣",
  "Jewelry Clasp": "手镯扣",
  "Safety Strap Clasp": "安全扣",
  "Deployant Clasp": "展開式錶扣",
  "Buckle": "錶扣",
};