const it = [
	"Minute Markers around an inner ring",
	"Stick / Dot",
	"Minute Markers",
	"Diamond",
	"Roman Numerals",
	"Minute Markers around the outer rim",
	"Mixed",
	"Minute Markers Around The Outer Rim",
	"Arabic Numerals",
	"Highly legible Chromalight display with long-lasting blue luminescence",
	"Diamonds",
	"Index",
	"Luminous Stick",
	"Stick Hour Markers, Minute Markers around the outer rim",
	"Dot",
	"Luminous Dot",
	"Yaucht Race Markings. Minute Markers around the outer rim",
	"Dial with snailed small counters",
	"Minute markers around the outer rim",
	"Roman Numerals mark the 6 and 12 o'clock positions. Minute Markers around the outer rim",
	"Roman Numerals mark the 6 and 12 o'clock position. Minute Markers around the outer rim",
	"None",
	"Arabic Numeral marks the 12 o'clock position. Minute Markers. Pulse rate scale appears around the outer rim",
	"Minute markers around the inner ring",
	"Diamond filled Roman Numeral 6",
	"Roman Numeral",
	"Arabic Numerals appear at the 3, 6, 9 and 12 o'clock positions. Minute Markers around the outer rim",
	"Arabic Numeral appears at the 12 o'clock position. Minute Markers around the outer rim",
	"Arabic Numerals mark the 3, 9 and 12 o'clock positions. Date Scale around the outer rim",
	"Arabic Numeral appears at the 12 o'clock position. Minute Markers. Tachymeter markings around the outer rim",
	"Arabic Numeral mark the 12 o'clock position. Minute Markers around the outer rim",
	"Arabic Numerals mark the 6, 9 and 12 o'clock positions. Minute Markers around the outer rim",
	"Arabic Numeral appears at the 12 o'clock positions. Minute Markers around the outer rim",
	"Minute Markers arond an inner ring",
	"24 Hour Markers. Minute Markers around the inner ring",
	"Minute Markers around the inner ring",
	"Minute Markers on an inner ring",
	"24 Hour Markers. Minute Markers around the outer rim",
	"Roman Numeral marks the 12 o'clock position. Minute Markers aroundan inner ring",
	"Date, Power Reserve, Hour, Minute, Second and Chronograph",
	"Date, Power Reserve and Hour, Minute, Second",
	"Arabic Numerals mark the 3, 6, 9 and 12 o'clock positions. Minute Markers around the outer rim",
	"24 Hour (GMT) Markers. Minute Markers around the outer rim",
	"Minute Markers. 'Estimated Time Over' scale. Fly Back Function",
	"Minute markers around the outer rim,",
	"24 Hour (GMT) Markings. Minute Markers around the outer rim",
	"date; seconds",
	"Seconds sub-dial",
	"Arabic Numeral marks the 12 o'clock position. Minute Markers around the outer rim",
	"chronograph; date; seconds",
	"Arabic numerals mark the 3, 6, 9 and 12 o'clock positions. Minute Markers around the outer rim",
	"Arabic Numeral Minute Markers (at 5 minute intervals). Minute Markers around the outer rim",
	"Arabic Numerals mark the 6 and 12 o'clock positions. Minute Markers around the outer rim",
	"Arabic Numerals mark the 3, 6, 9 and 12 o'clock positions, Minute Markers around the outer rim",
	"Arabic numerals mark the 6, 9 and 12 o'clock positions. Minute markers around the outer rim",
	"24 Hour (GMT) markers around an inner ring. Minute Markers Around The Outer Rim",
	"Minute Markers. 24 Hour (GMT) Scale on inner ring",
	"Roman Numeral and Dot",
	"24 Hour Markings. Minute Markers around the outer rim",
	"Minute Markers. 24 Hour (GMT) Markers around an inner ring",
	"24 Hour Markings. Minute Markers around the outer rim.",
	"Minute markers around outter rim",
	"Minute markers appear around outter rim",
	"24 Hour (GMT) Scale. Minute Markers around the outer rim",
	"Arabic Numerals mark the 6, 9 and 12 o'clock positions. Minute Markers. 24 Hour Markers around the outer rim",
	"Minute Markers around the outer rim. 24 Hour (GMT) Markers around an inner ring",
	"minute Markers around the outer rim. GMT Scale around the inner ring",
	"Minute Markers around the outer rim. GMT Scale",
	"24 Hour Scale. Minute Markers around the outer rim.",
	"Arabic Numerals mark the 3, 6, 9 and 12 o'clock positions",
	"chronograph; date; day of the week; seconds",
	"seconds",
	"Arabic Numerals mark the 3, 6, 9 and 12 o'clock positions. Minute markers around the outer rim",
	"Minute Scale around the inner rim",
	"Arabic Numeral Minute Markers. Minute Markers around the outer rim",
	"date; 24-hours display; seconds",
	"Minute Markers around the outer rim. 24 Hour Markings",
	"Minute Markers around the outer rim. 24 Hour Scale around the inner ring",
	"Arabic Numeralsa mark the 3, 6, 9 and 12 o'clock positions. Minute Markers around the outer rim",
	"Arabic Numerals mark the 3, 9 and 12 o'clock positions. Minute Markers around the outer rim",
	"Date, Hour, Minute, Second and Chronograph",
	"Roman Numeral marks the 12 o'clock position. Minute Markers around the outer rim",
	"Arabic Numerals mark the 6, 9 and 12 o'clock positions",
	"Arabic Numerals mark the 6 and 12 o'clock positions",
	"Date and Hour, Minute, Second",
	"Minute Markers. 24 Hour Markers. World Time Cities around the outer rim",
	"Arabic NUmerals mark the 3, 6, 9 and 12 o'clock positions. Minute Markers around the outer rim",
	"Arabic Numerals mark the 6 and 12 o'clock poisitions. Minute Markers around the outer rim",
	"Arabic NUmeral appears at the 12 o'clock position. Minute Markers around the outer rim",
	"index",
	"24 Hour Markers. Minute Markers. Cross Wind Markings around the outer rim",
	"Arabic Numerals mark the 3, 9 and 12 o'clock positions. Minute Markers around an inner ring",
	"Arabic Numerals Mark the 6, 9, and 12 o'clock Position",
	"Arabic Numerals mark the 6 and 12 o'clock position",
	"Arabic Numerals mark the 3, 6 and 12 o'clock positions",
	"Power Reserve and Hour, Minute, Second",
	"Arabic Numerals mark the 3, 6, 9 and 12 o'clock p[ositions",
	"Arabic Numerals mark the 6 and 12 o'clock positions. Minute Markers around an inner ring",
	"Arabic Numerals mark the 6, 9 and 12 o'clock positions.",
	"24 hour Markers. Minute Markers around the outer rim",
	"24 Hour Scale around the inner ring. Minute Markers around the outer rim",
	"Minute Markers. Air Speed Scale around the outer rim",
	"Minute Markers. Air Speed markings around the outer rim",
	"Minute Markers. Cross Wind Markers around the outer rim",
	"second time zone; date; seconds",
	"Stick",
	"Tachymeter",
	"Index Markers at the 3, 6, 9 and 12 o'clock positions",
	"Minute Markers around the outer rim. Arabic Numeral Hour Markers around an inner ring",
	"Minute Markers. Cross Wind Markings around the outer rim",
	"Digital",
	"Arabic Numerals mark the 6, 9 and 12 o'clock positions. Minute markers around the outer rim",
	"Minute markers around the outer rim. GMT Scale",
	"@4 Hour Markings. Minute Markers around the outer rim",
	"Applied polished index hour markers.",
	"Date, Power Reserve, Hour, Minute, Second and GMT",
	"Aravic Numerals mark the 3, 6, 9 and 12 o'clock positions. Minute Markers around an inner ring",
	"Applied index hour markers.",
	"Minute Markers. Tachymeter Markers around the outer rim",
	"date",
	"date; day of the week; seconds",
	"24 hour (GMT) Markings. Minute Markers around the outer rim",
	"24 Hour Markers. Minute Markers. Cross wind Markings around the outer rim",
	"Hour, Minute",
	"Tachymeter Scale around the outer rim",
	"GMT and World Time scale around the outer rim",
	"seconds; open heart",
	"Metal applique skeleton Superluminova®-filled numerals and indices",
	"Metal appliqué numerals and indices",
	"Numerals and indices coated in white Superluminova®",
	"Sand Superluminova® numerals and indices",
	"Index-Arabic Numerals",
	"Roman Numerals mark the 3, 6, 9,. and 12 o'clock position",
	"Roman Numerals mark the 3, 6, 9 and 12 o'clock positions",
	"Baguette Diamond",
	"Arabic Numerals mark the 3, 6 and 9 o'clock positions. Minute Markers around the outer rim",
	"GMT Scale. Minute markers around the outer rim",
	"Arabic Numerals mark the 6 and 12 o'clock positions. 24 Hour (GMT) Markers around the outer rim",
	"Minute Markers. World Time Cities around the outer rim",
	"Minute Markers around the outer rim, GMT scale around an inner ring",
	"Diamonds mark the 3, 6, 9 and 12 o'clock positions. Minute Markers around the outer rim",
	"Date, Power Reserve, Hour, Minute, Second and Alarm Clock",
	"Microblasted grey upper insert, cut away around the numerals and indices, revealing the black Superluminova® covering the lower insert",
	"Hands, numerals and indices coated in Superluminova®C3",
	"Arabic Numeral",
	"Diamonds mark the 3, 6, 9 and 12 o'clock positions",
	"Arabic Numerals mark the 6 and 12 o'clock positions. 24 hours (GMT) Markers around the outer rim",
	"Arabic Numerals mark the 3, 6 and 12 o'clock position",
	"Arabic Numerla smark the 6 and 12 o'clock positions",
	"Arabic Numerals amrk the 6 and 12 o'clock positions. Minute Markers around the outer rim",
	"Appliqué metal indices with Super-LumiNova® inserts",
	"Arabic Numerals mark the 6 and 12 o'clock positions.",
	"Arabic Numerals mark the 6, 9, and 12 o'clock position",
	"Arabic Numerals mak the 6, 9 and 12 o'clock positions. Minute Markers around the outer rim",
	"Roman Numerals mark the 6, 9 and 12 o'clock positions.",
	"24-hours display; seconds",
	"Minute Markers. Tachymeter Markings around the outer rim",
	"Hours, Minutes, Seconds, Date and Day of the Week",
	"Diamond-set Roman Numeral at 6 o'clock position",
	"Roman Numerals mark the 3, 6, 9 and 12 o'clock positions, Minute Markers around the outer rim",
	"Teardrop Index marker at the 12 o'clock position",
	"Roman Numeral marks the 12 o'clock position",
	"Arabic Numerals mark the 6, 9 and 12 o'clock positions. Minute Markers. Tachymeter around the outer rim",
	"Roman Numerals mark the 6 and 12 o'clock positions",
	"roman and indexes",
	"Arabic Numerals mark the 3, 9 and 12 o'clock positions",
	"Applied Arabic numerals and indexes",
	"Roman Numerals mark the 3, 9 and 12 o'clock positions. Minute Markers around an inner ring",
	"Arabic Numerals mark the 6, 9 and 12 o'clock position. Minute Markers. Tachymeter around the outer rim",
	"Roman Numeral marks the 12 o'clock position. Minute Markers. Tachymeter around the outer rim",
	"Roman Numerals mark the 6, 9 and 12 o'clock positions. Minute Markers around the outer rim",
	"Roman Numerals mark the 3, 6, 9 and 12 o'clock positions. Minute Markers around the outer rim",
	"Roman Numerals mark the 3, 6, 9 and 12 o'clock positions. Minute Markers around an inner ring",
	"Arabic numerals mark the 6, 9 and 12 o'clock positions. Minute Markers. Tachymeter around the outer rim",
	"Arabic Numerals mark the 3, 6, and 9 o'clock position",
	"Arabic Numerals mark the 3, 6 and 9 o'clock positions",
	"arabic and indexes",
	"Arabic numerals mark the 6 and 12 o'clock positions. 24 Hour (GMT) Markers. Minute Markers around the outer rim",
	"Tachymeter Markers around the outer rim",
	"Diamonds Mark the 3, 9 and 12 o'clock positions",
	"Minute Markers around the inner bezel",
	"Date, GPS Tracking and Navigation, Alarm and Bluetooth",
	"Diamonds Mark the 3, 6, 9 and 12 o'clock positions",
	"Tachymeter scale appears around the outer rim",
	"Arabic Numerals mark the 3, 9 and 12 o'clock positions. Minute Markers. Tachymeter around the outer rim",
	"Arabic Numerals mark the 6, 9 and 12 o'clock positions. Minute Markers. Tachymeter Scale around the inner bezel",
	"Minute Markers. 24 hour (GMT) Markings. Tachymeter Markings around the outer rim",
	"Tachymeter around the outer rim",
	"World Time Cities. Minute Markers around the outer rim",
	"Arabic numerals mark the 6, 9 and 12 o'clock positions.. Minute Markers around the outer rim",
	"roman",
	"Date, Hour, Minute, Second and Calendar",
	"red gold-plated",
	"Arabic Numerals marking the 3, 6, 9 and 12 o'clock positions. Minute Markers around the outer rim",
	"Power Reserve, Hour, Minute, Second and Chronograph",
	"Chronograph seconds hand that runs counter clockwise on the back; tachymeter;",
	"Index-Arabic at the 12 o' clock",
	"24 hour Markings. Minute Markers",
	"bronze indexes",
	"arabic Numeral appears at the 12 o'clock position. Minute Markers around the outer rim",
	"Arabic numerals mark the 6 and 12 o'clock positions. Minute Markers around the outer rim",
	"Roman numeral hour-markers",
	"Hour markers & Number 12",
	"Arabic Numeral appears at the 12 o'clock position. Minute Markers. 1/100th Markers around the outer rim",
	"Arabic Numeral marks the 12 o'clock position",
	"Roman Numeral appears at the 12 o'clock position. Minute Markers around an inner ring",
	"No Markers",
	"Date, 24 Hour and Hour, Minute, Second",
	"Date, Power Reserve, Hour, Minute, Second, Chronograph and Moonphase",
	"Minute Markers. Tachymeter around the outer rim",
	"Arabic Numerals ark the 6, 9 and 12 o'clock positions. Minute Markers around the outer rim",
	"Black Arabic Numeral",
	"Arabic Numerals mark the 6 and 12 o'clock positions. Minute Markers. Regatta Countdown around the outer rim",
	"Black Roman Numeral",
	"Date Scale around an inner ring. Minute Markers",
	"Minute Markers on Bezel",
	"Diamond indexes",
	"Painted Roman numerals",
	"24-Hour Markings. Minute Markers around an inner ring",
	"Painted Arabic numerals",
	"Gilt applique numerals and indices",
	"Indices and numerals coated in sand-coloured Superluminova®",
	"Minute Markers. 1/100 markers around the outer rim",
	"hours-minutes; seconds sub-dial; power reserve",
	"hour numerals and indexes with white superluminova minute markers green",
	"hours-minutes; seconds sub-dial; power reserve; world time",
	"date; hours-minutes; seconds sub-dial; power reserve indicator",
	"hours-minutes; seconds sub-dial",
	"arabic",
	"Pulsometer",
	"indexes and diamonds",
	"Alternating Arabic Numeral and Index",
	"Date, Hour, Minute, Second and Battery End Of Life Indicator",
	"black Arabic numerals",
	"Applied indexes",
	"black luminescent numerals and indexes",
	"diamonds",
	"Hour, Minute, Second",
	"red gold-coated indexes and numerals",
	"Pyramid Markers at the 3, 6, 9 and 12 o'clock positions",
	"Rhodium plated appliques with luminescent coating",
	"18-ct rose gold appliques",
	"Diamond-set Index Markers at the 3, 6, 9 and 12 o'clock positions. The Rado name appears below the 12 o'clock position",
	"Rose gold plated appliques",
	"Indicies mark the 6, 9 and 12 o'clock positions",
	"Diamonds set at the 3, 6, 9 and 12 o'clock positions",
	"Diamond-set Roman Numeral marks the 12 o'clock position",
	"Rhodium plated appliques, set at 6h and 12h",
	"18 white gold appliques",
	"No Markers. Gucci Bee logo appears at the 12 o'clock position",
	"The Gucci name apperas below the 12 o'clock position",
	"Rhodium plated appliques",
	"date, hours-minutes, seconds sub-dial, power reserve",
	"No Markers. The Gucci name appears below the 12 o'clock position",
	"Rose gold plated appliques with luminescent coating",
	"Applied",
	"roman and diamonds",
	"Painted Arabic numerals and applied indexes",
	"rhodium-coated indexes and numerals",
	"Diamond Index markers at the 3, 6, 9 and 12 o'clock positions",
	"Index markers at the 6, 9 and 12 o'clock positions",
	"Roman Numerals appear at the 6 and 12 o'clock positions",
	"Roman Numerals mark the 6 and 12 o'clock positions. Gucci Name appears at the 3 o'clock position",
	"Diamonds Mark the 3, 6 and 9 o'clock positions",
	"Arabic",
	"Painted indexes",
	"Wesselton Diamond",
	"Index and Roman Numeral",
	"No Markers. Gucci Bee Motif logo at the 12 o'clock position",
	"Date, Hour, Minute, Second, Chronograph and Alarm Clock",
	"Arabic Numberal marks the 12 o'clock position. Minute markers appear around the outer rim",
	"Arabic Numeral and Index",
	"Bee, Star and Rose Gold Colored Heart",
	"Index - Rhodium Plated",
	"24 Hour Markers. Minute Markers around an inner ring",
	"Painted Arabic numerals and indexes",
	"White Diamonds mark the 3, 6, 9 and 12 o'clock positions",
	"Rhodium plated luminescent indexes",
	"No markers",
	"Hour, Minute, Second and Chronograph",
	"Arabic Numerals mark the 6 and 9 o'clock positions",
	"hours-minutes, power reserve, flying tourbillon",
	"Minute Markers. Slide Rule Markings around the outer rim",
	"Arabic Numerals mark the 3, 6, 9 and 12 o'clock positions. Minute Markers",
	"Diamond-Filled Index",
	"Diamond- Filled Index",
	"Roman NUmerals mark the 3, 6, 9 and 12 o'clock position. Minute Markers",
	"diamond indexes",
	"Arabic Numerals mark the 2, 10 and 12 o'clock positions. Roman Numerals appear at the 4 and 8 o'clock positions. Minute Markers around the outer rim",
	"date, central second, hours-minutes, power reserve",
	"Gold-plated applique indices with Super-LumiNova® inserts",
	"stamped indexes",
	"Numerals and indices coated in Super-LumiNova®",
	"date, hours-minutes, central second, power reserve, open heart",
	"Hours, minutes, and seconds",
	"Roman numerals",
	"indices and numerals coated in Super-LumiNova®",
	"Metal applique indices",
	"Indices coated in beige Superluminova®",
	"Arabic Numeral & Index Hour Markers",
	"Indexes",
	"arabic and indexes and diamond",
	"24 Hours",
	"date, hours-minutes, central second, power reserve",
	"Arabic numerals mark the 6, 9 and 12 o'clock positions",
	"Rhodium-plated",
	"chronometer, date, hours-minutes, seconds sub-dial, power reserve indicator",
	"Minute Markers. Date Scale around the outer rim",
	"Arabic numerals and diamonds",
	"cut away around the numerals and indices",
	"hours-minutes, tourbillon",
	"Chronograph",
	"Diamond index",
	"hours-minutes, tourbillon, power reserve",
	"Date, Hour, Minute, Second, Calendar and Alarm Clock",
	"Rhodium plated appliques with black lack",
	"Rose gold plated",
	"Roman Numeral/Index hour markers with minute markers around the outer rim",
	"Index-Roman Numerals",
	"Index hour markers with minute markers around the outer rim",
	"Applique numerals and indices coated in Super-LumiNova®",
	"Metal applique numerals and indices",
	"hours-minutes, central second, power reserve",
	"Roman",
	"Tachymeter Markings. Minute Markers around the outer rim",
	"Arabic & Stick",
	"Black painted numerals and indices",
	"hours and minutes, seconds, date",
	"hours and minutes, seconds",
	"Arabic numerals and indexes",
	"indices and hour and minute hands",
	"applied indexes",
	"hours-minutes, power reserve",
	"hours-minutes, power reserve, tourbillon",
	"Arabic Numerals mark the 3, 6, 9 and 12 o'clock positions. Minute Markers around an inner ring",
	"indices and numerals filled with Superluminova®",
	"hours-minutes, power reserve, toir",
	"Diamond Markers at the 3, 6, 9 and 12 o'clock positions",
	"hours-minutes, seconds sub-dial, power reserve indicator",
	"hours-minutes",
	"Alternating Index and Arabic Numeral",
	"Roman Numeral and Index",
	"Date, Power Reserve, Hour, Minute, Second, Chronograph and Flyback Chronograph",
	"DIamond",
	"18kt White Gold Index",
	"Alternating Diamond and Roman Numeral",
	"Applied index hour markers",
	"Arabic Numeral/Index",
	"Alternating between Arabic Numerals & indexes.",
	"hours-minutes; central second; power reserve; stop seconds mechanism",
	"Dots",
	"Index- Roman Numerals",
	"Alternating Arabic Numeral and Diamond",
	"Applied Indexes",
	"Index- Arabic Numerals",
	"12 Diamond",
	"Diamond and Roman Numeral",
	"Arabic & Index",
	"Diamond Indexes",
	"Red 12",
	"Red 12 and Mixed Indexes",
	"Arabic Numeral Large VI set with diamonds",
	"Dots asd Sticks",
	"",
	"Grey printed hour markers in a mix of Arabic Numerals & indexes.",
	"Roman numeral hour markers",
	"Multi-color Arabic Numeral",
	"Yellow numberals",
	"Painted Luminescent Block Index Hour Markers",
	"Applied Arabic numerals",
	"Combination of index hour markers",
	"Index and Arabic Numeral",
	"Index hour markers with luminous fill",
	"Gilt applied Arabic and index hour markers.",
	"Index hour markers with luminous fill.",
	"Applied steel index hour markers",
	"Printed hour markers alternating between Arabic Numerals & indexes.",
	"Applied blued steel index hour with luminous fill.",
	"White printed hour markers alternating between Roman Numerals & indexes.",
	"Applied polished yellow gold index hour markers.",
	"Arabic numerals, Roman numerals & indexes",
	"Stick/Dot",
	"Roman Numerals Hour Markers",
	"Crystal Stick",
	"Crystal Index",
	"Arabic numbers",
	"Geometrics",
	"Indexes & Arabic numerals.",
	"Applied index hour markers with luminous fill.",
	"Circle & Stick",
	"Arabic Numeral / Dot",
	"Black printed hour markers in a mix of Arabic Numerals & indexes.",
	"Crystal-tipped Index",
	"Roman numbers",
	"Without indexes",
	"Swarovski Crystal Index",
	"Crystal",
	"Alternating Index and Arabic Numeral Hour Markers",
	"Swarovski Crystal",
	"Mix of Arabic Numerals & indexes.",
	"Alternating Arabic Numeral and Stick",
	"Index with Crystal",
	"Letter (BY MARC JACOBS)",
	null,
	"Alternating between Arabic Numerals & indexes",
	"Numbers and indices coated with luminescent colour",
	"Indices coated with luminescent colour",
	"Ivory-coloured coating on the indices, hands",
	"Arabic numeral",
	"Applied polished rose gold index & Roman Numeral hour markers.",
	"Luminous index hour markers",
	"18K White Gold Index",
	"Roman Numeral/Index",
	"SuperLumiNova-coated indices",
	"Arabic Numeral & Index",
	"Logo",
	"Index/ Arabic Numeral",
	"Index hour markers with Superluminova.",
	"House Motifs",
	"House Motif",
	"Arabic numerals",
	"Index / Arabic Numeral",
	"Index-Arabic Numeral",
	"Arabic and index hour markers",
	"Index hour markers",
	"Index & numeral hour markers",
	"Applied polished hour markers in a combination of indexes & Arabic Numerals.",
	"white SLN indexes",
	"Mocha-brown printed hour markers in a mix of Roman Numerals & indexes.",
	"Gold toned printed hour markers alternating between Arabic Numerals & indexes.",
	"Fine printed hour markers alternating between Arabic Numerals & indexes.",
	"Black Roman Numerals"
];

module.exports = it;
