const u = [
    "https://nomos-glashuette.com/en/ahoi/ahoi-datum-fur-aerzte-ohne-grenzen-deutschland-551-s2",
    "https://nomos-glashuette.com/en/ahoi/ahoi-neomatik-fur-aerzte-ohne-grenzen-deutschland-560-s1",
    "https://nomos-glashuette.com/en/club/club-automatic-navy-753-s2",
    "https://nomos-glashuette.com/en/club/club-automatic-olive-753-s3",
    "https://nomos-glashuette.com/en/club/club-automatic-onyx-753-s1",
    "https://nomos-glashuette.com/en/club/club-campus-38-absolute-gray-727",
    "https://nomos-glashuette.com/en/club/club-campus-38-future-orange-729",
    "https://nomos-glashuette.com/en/club/club-campus-absolute-gray-712",
    "https://nomos-glashuette.com/en/club/club-campus-future-orange-710",
    "https://nomos-glashuette.com/en/lambda/lambda-175-years-watchmaking-glashutte-960-s1",
    "https://nomos-glashuette.com/en/lambda/lambda-175-years-watchmaking-glashutte-960-s2",
    "https://nomos-glashuette.com/en/lambda/lambda-175-years-watchmaking-glashutte-960-s3",
    "https://nomos-glashuette.com/en/ludwig/ludwig-175-years-watchmaking-glashutte-205-s2",
    "https://nomos-glashuette.com/en/ludwig/ludwig-33-duo-enamel-white-242",
    "https://nomos-glashuette.com/en/ludwig/ludwig-38-enamel-white-236",
    "https://nomos-glashuette.com/en/ludwig/ludwig-neomatik-39-175-years-watchmaking-glashutte-250-s1",
    "https://nomos-glashuette.com/en/ludwig/ludwig-neomatik-39-250",
    "https://nomos-glashuette.com/en/ludwig/ludwig-neomatik-41-date-175-years-watchmaking-glashutte-261-s1",
    "https://nomos-glashuette.com/en/ludwig/ludwig-neomatik-41-date-261",
    "https://nomos-glashuette.com/en/metro/metro-neomatik-41-update-1165",
    "https://nomos-glashuette.com/en/tangente/tangente-38-50-ans-de-medecins-sans-frontieres-165-s50",
    "https://nomos-glashuette.com/en/tangente/tangente-neomatik-41-update-midnight-blue-182",
];

module.exports = u;