const axios = require('axios');
const cheerio = require('cheerio');
const urls = [
    "https://www.citizenwatch.com/us/en/product/CA0710-58L.html",
    "https://www.citizenwatch.com/us/en/product/BJ7128-59E.html",
    "https://www.citizenwatch.com/us/en/product/CB5880-54L.html",
    // "https://www.citizenwatch.com/us/en/product/BM7490-52E.html",
    // "https://www.citizenwatch.com/us/en/product/JR4061-00F.html",
    // "https://www.citizenwatch.com/us/en/product/CA4210-24E.html",
    // "https://www.citizenwatch.com/us/en/product/CA4215-21H.html",
    // "https://www.citizenwatch.com/us/en/product/AT2240-51A.html",
    // "https://www.citizenwatch.com/us/en/product/AT2245-57E.html",
    // "https://www.citizenwatch.com/us/en/product/AU1060-51E.html",
    // "https://www.citizenwatch.com/us/en/product/AU1060-51G.html",
    // "https://www.citizenwatch.com/us/en/product/AU1062-56E.html",
    // "https://www.citizenwatch.com/us/en/product/AU1062-56G.html",
    // "https://www.citizenwatch.com/us/en/product/AU1065-07E.html",
    // "https://www.citizenwatch.com/us/en/product/AU1065-58E.html",
    // "https://www.citizenwatch.com/us/en/product/AU1065-58G.html",
    // "https://www.citizenwatch.com/us/en/product/BJ6510-51L.html",
    // "https://www.citizenwatch.com/us/en/product/BJ6512-56P.html",
    // "https://www.citizenwatch.com/us/en/product/BJ6517-52E.html",
    // "https://www.citizenwatch.com/us/en/product/BL6000-55E.html",
    // "https://www.citizenwatch.com/us/en/product/BL6005-01E.html",
    // "https://www.citizenwatch.com/us/en/product/BL6008-53E.html",
    // "https://www.citizenwatch.com/us/en/product/AW1591-01L.html",
    // "https://www.citizenwatch.com/us/en/product/AW1593-06X.html",
    // "https://www.citizenwatch.com/us/en/product/AW1598-70X.html",
    // "https://www.citizenwatch.com/us/en/product/BL5551-14H.html",
    // "https://www.citizenwatch.com/us/en/product/BL5558-58L.html",
    // "https://www.citizenwatch.com/us/en/product/BL5563-58E.html",
    // "https://www.citizenwatch.com/us/en/product/BL5567-57E.html",
    // "https://www.citizenwatch.com/us/en/product/BL5568-54L.html",
    // "https://www.citizenwatch.com/us/en/product/BM6929-56L.html",
    // "https://www.citizenwatch.com/us/en/product/CA0349-51L.html",
    // "https://www.citizenwatch.com/us/en/product/CA0648-09L.html",
    // "https://www.citizenwatch.com/us/en/product/CA0649-06X.html",
    // "https://www.citizenwatch.com/us/en/product/CA0649-14E.html",
    // "https://www.citizenwatch.com/us/en/product/CA4258-87E.html",
    // "https://www.citizenwatch.com/us/en/product/CA4359-55E.html",
    // "https://www.citizenwatch.com/us/en/product/BU2020-29X.html",
    // "https://www.citizenwatch.com/us/en/product/BU2020-70E.html",
    // "https://www.citizenwatch.com/us/en/product/BU2021-51H.html",
    // "https://www.citizenwatch.com/us/en/product/BU2021-51L.html",
    // "https://www.citizenwatch.com/us/en/product/BU2025-76E.html",
    // "https://www.citizenwatch.com/us/en/product/BU2080-51H.html",
    // "https://www.citizenwatch.com/us/en/product/BU2082-56E.html",
    // "https://www.citizenwatch.com/us/en/product/BU2088-50E.html",
    // "https://www.citizenwatch.com/us/en/product/BN0208-54W.html",
    // "https://www.citizenwatch.com/us/en/product/AT0200-05E.html",
    // "https://www.citizenwatch.com/us/en/product/AT0550-11X.html",
    // "https://www.citizenwatch.com/us/en/product/CB5887-55H.html",
    // "https://www.citizenwatch.com/us/en/product/CB5886-58H.html",
    // "https://www.citizenwatch.com/us/en/product/CB5896-54X.html",
    // "https://www.citizenwatch.com/us/en/product/JY8051-08E.html",
    // "https://www.citizenwatch.com/us/en/product/JY8051-59E.html",
    // "https://www.citizenwatch.com/us/en/product/JY8058-50L.html",
    // "https://www.citizenwatch.com/us/en/product/JY8070-54E.html",
    // "https://www.citizenwatch.com/us/en/product/JY8075-51E.html",
    // "https://www.citizenwatch.com/us/en/product/JY8076-07E.html",
    // "https://www.citizenwatch.com/us/en/product/JY8078-01L.html",
    // "https://www.citizenwatch.com/us/en/product/JY8078-52L.html",
    // "https://www.citizenwatch.com/us/en/product/JY8101-52L.html",
    // "https://www.citizenwatch.com/us/en/product/JY8108-53E.html",
    // "https://www.citizenwatch.com/us/en/product/AT8020-03L.html",
    // "https://www.citizenwatch.com/us/en/product/AT8020-54L.html",
    // "https://www.citizenwatch.com/us/en/product/AT8060-09E.html",
    // "https://www.citizenwatch.com/us/en/product/AT8110-53E.html",
    // "https://www.citizenwatch.com/us/en/product/AT8113-04H.html",
    // "https://www.citizenwatch.com/us/en/product/AT8116-57E.html",
    // "https://www.citizenwatch.com/us/en/product/CB0160-51L.html",
    // "https://www.citizenwatch.com/us/en/product/CB0166-54H.html",
    // "https://www.citizenwatch.com/us/en/product/CB0168-08E.html",
    // "https://www.citizenwatch.com/us/en/product/CC7000-01L.html",
    // "https://www.citizenwatch.com/us/en/product/CC3035-50E.html",
    // "https://www.citizenwatch.com/us/en/product/CC3038-51E.html",
    // "https://www.citizenwatch.com/us/en/product/CC7015-55E.html",
    // "https://www.citizenwatch.com/us/en/product/CC3039-08E.html",
    // "https://www.citizenwatch.com/us/en/product/BJ6530-54L.html",
    // "https://www.citizenwatch.com/us/en/product/BJ6535-51E.html",
    // "https://www.citizenwatch.com/us/en/product/AT2440-51L.html",
    // "https://www.citizenwatch.com/us/en/product/AW0087-58H.html",
    // "https://www.citizenwatch.com/us/en/product/AW1146-55H.html",
    // "https://www.citizenwatch.com/us/en/product/AW1147-52L.html",
    // "https://www.citizenwatch.com/us/en/product/AW1148-09E.html",
    // "https://www.citizenwatch.com/us/en/product/AW1150-07E.html",
    // "https://www.citizenwatch.com/us/en/product/AW1151-04E.html",
    // "https://www.citizenwatch.com/us/en/product/AW1157-08H.html",
    // "https://www.citizenwatch.com/us/en/product/AW1158-05L.html",
    // "https://www.citizenwatch.com/us/en/product/BM6980-08E.html",
    // "https://www.citizenwatch.com/us/en/product/BM6983-00H.html",
    // "https://www.citizenwatch.com/us/en/product/BM6985-55E.html",
    // "https://www.citizenwatch.com/us/en/product/BM6988-57E.html",
    // "https://www.citizenwatch.com/us/en/product/BM7410-51L.html",
    // "https://www.citizenwatch.com/us/en/product/BM7410-51X.html",
    // "https://www.citizenwatch.com/us/en/product/BU4020-01L.html",
    // "https://www.citizenwatch.com/us/en/product/BU4023-54E.html",
    // "https://www.citizenwatch.com/us/en/product/BU4025-59E.html",
    // "https://www.citizenwatch.com/us/en/product/BV1112-05A.html",
    // "https://www.citizenwatch.com/us/en/product/BV1112-56E.html",
    // "https://www.citizenwatch.com/us/en/product/CA0435-51E.html",
    // "https://www.citizenwatch.com/us/en/product/CA0665-00E.html",
    // "https://www.citizenwatch.com/us/en/product/EM0234-59D.html",
    // "https://www.citizenwatch.com/us/en/product/EM0688-78L.html",
    // "https://www.citizenwatch.com/us/en/product/EM0756-53A.html",
    // "https://www.citizenwatch.com/us/en/product/FD2052-07A.html",
    // "https://www.citizenwatch.com/us/en/product/FD2052-58A.html",
    // "https://www.citizenwatch.com/us/en/product/FD3003-58X.html",
    // "https://www.citizenwatch.com/us/en/product/FE6080-71X.html",
    // "https://www.citizenwatch.com/us/en/product/FE6081-51A.html",
    // "https://www.citizenwatch.com/us/en/product/FE6136-01A.html",
    // "https://www.citizenwatch.com/us/en/product/FE7053-51X.html",
    // "https://www.citizenwatch.com/us/en/product/FE7070-52A.html",
    // "https://www.citizenwatch.com/us/en/product/CA0660-54E.html",
    // "https://www.citizenwatch.com/us/en/product/FE6143-56A.html",
    // "https://www.citizenwatch.com/us/en/product/FE6140-54A.html",
    // "https://www.citizenwatch.com/us/en/product/CA4190-54E.html",
    // "https://www.citizenwatch.com/us/en/product/BU4025-08E.html",
    // "https://www.citizenwatch.com/us/en/product/AT2441-08X.html",
    // "https://www.citizenwatch.com/us/en/product/AT2447-01E.html",
    // "https://www.citizenwatch.com/us/en/product/AW0080-57A.html",
    // "https://www.citizenwatch.com/us/en/product/AW0083-08X.html",
    // "https://www.citizenwatch.com/us/en/product/AW1350-83M.html",
    // "https://www.citizenwatch.com/us/en/product/AW1354-82E.html",
    // "https://www.citizenwatch.com/us/en/product/AW1585-04E.html",
    // "https://www.citizenwatch.com/us/en/product/AW1585-55L.html",
    // "https://www.citizenwatch.com/us/en/product/BJ7006-56L.html",
    // "https://www.citizenwatch.com/us/en/product/BJ7007-02L.html",
    // "https://www.citizenwatch.com/us/en/product/CB5848-57L.html",
    // "https://www.citizenwatch.com/us/en/product/BN7020-17E.html",
    // "https://www.citizenwatch.com/us/en/product/BN5050-09X.html",
    // "https://www.citizenwatch.com/us/en/product/BN5055-05E.html",
    // "https://www.citizenwatch.com/us/en/product/BN5058-07E.html",
    // "https://www.citizenwatch.com/us/en/product/BN2037-03E.html",
    // "https://www.citizenwatch.com/us/en/product/BN2038-01L.html",
    // "https://www.citizenwatch.com/us/en/product/BN2039-59E.html",
    // "https://www.citizenwatch.com/us/en/product/BN2029-01E.html",
    // "https://www.citizenwatch.com/us/en/product/BJ8050-08E.html",
    // "https://www.citizenwatch.com/us/en/product/BN0085-01E.html",
    // "https://www.citizenwatch.com/us/en/product/BN0150-28E.html",
    // "https://www.citizenwatch.com/us/en/product/BN0151-09L.html",
    // "https://www.citizenwatch.com/us/en/product/BN0191-55L.html",
    // "https://www.citizenwatch.com/us/en/product/BN0195-54E.html",
    // "https://www.citizenwatch.com/us/en/product/BN0198-56H.html",
    // "https://www.citizenwatch.com/us/en/product/BN0200-56E.html",
    // "https://www.citizenwatch.com/us/en/product/CA0715-03E.html",
    // "https://www.citizenwatch.com/us/en/product/CA0719-53E.html",
    // "https://www.citizenwatch.com/us/en/product/BJ7128-59G.html",
    // "https://www.citizenwatch.com/us/en/product/CB5840-59E.html",
    // "https://www.citizenwatch.com/us/en/product/CB5841-05E.html",
    // "https://www.citizenwatch.com/us/en/product/BX1010-02E.html",
    // "https://www.citizenwatch.com/us/en/product/BX1010-11L.html",
    // "https://www.citizenwatch.com/us/en/product/JR4068-01E.html",
    // "https://www.citizenwatch.com/us/en/product/JW0137-51E.html",
    // "https://www.citizenwatch.com/us/en/product/JW0138-08L.html",
    // "https://www.citizenwatch.com/us/en/product/JW0139-05L.html",
    // "https://www.citizenwatch.com/us/en/product/BN0211-09X.html",
    // "https://www.citizenwatch.com/us/en/product/BN0211-50E.html",
    // "https://www.citizenwatch.com/us/en/product/BN0217-02E.html",
    // "https://www.citizenwatch.com/us/en/product/AT2340-56L.html",
    // "https://www.citizenwatch.com/us/en/product/BM6560-54H.html",
    // "https://www.citizenwatch.com/us/en/product/BM7431-51L.html",
    // "https://www.citizenwatch.com/us/en/product/AV0081-51X.html",
    // "https://www.citizenwatch.com/us/en/product/AW1490-50E.html",
    // "https://www.citizenwatch.com/us/en/product/BM7431-51H.html",
    // "https://www.citizenwatch.com/us/en/product/AW0060-54H.html",
    // "https://www.citizenwatch.com/us/en/product/AQ6021-51E.html",
    // "https://www.citizenwatch.com/us/en/product/AW1490-50A.html",
    // "https://www.citizenwatch.com/us/en/product/AW1540-88A.html",
    // "https://www.citizenwatch.com/us/en/product/AW1548-86W.html",
    // "https://www.citizenwatch.com/us/en/product/EX1500-52A.html",
    // "https://www.citizenwatch.com/us/en/product/EX1503-54A.html",
    // "https://www.citizenwatch.com/us/en/product/EX1500-01E.html",
    // "https://www.citizenwatch.com/us/en/product/EX1513-00Y.html",
    // "https://www.citizenwatch.com/us/en/product/EM0796-75D.html",
    // "https://www.citizenwatch.com/us/en/product/EM0790-55N.html",
    // "https://www.citizenwatch.com/us/en/product/EM0794-54D.html",
    // "https://www.citizenwatch.com/us/en/product/EM0796-59Y.html",
    // "https://www.citizenwatch.com/us/en/product/AR3072-09A.html",
    // "https://www.citizenwatch.com/us/en/product/AR3074-54E.html",
    // "https://www.citizenwatch.com/us/en/product/AR3076-08A.html",
    // "https://www.citizenwatch.com/us/en/product/CA0727-12E.html",
    // "https://www.citizenwatch.com/us/en/product/CA0720-54H.html",
    // "https://www.citizenwatch.com/us/en/product/AV0070-57L.html",
    // "https://www.citizenwatch.com/us/en/product/AV0071-03A.html",
    // "https://www.citizenwatch.com/us/en/product/AV0073-08E.html",
    // "https://www.citizenwatch.com/us/en/product/AV0077-82E.html",
    // "https://www.citizenwatch.com/us/en/product/AV0078-04X.html",
    // "https://www.citizenwatch.com/us/en/product/AV0079-01A.html",
    // "https://www.citizenwatch.com/us/en/product/AR5014-04E.html",
    // "https://www.citizenwatch.com/us/en/product/BN5057-00E.html",
    // "https://www.citizenwatch.com/us/en/product/EM0741-51E.html",
    // "https://www.citizenwatch.com/us/en/product/EM0743-55D.html",
    // "https://www.citizenwatch.com/us/en/product/EW2443-55X.html",
    // "https://www.citizenwatch.com/us/en/product/FB2000-03D.html",
    // "https://www.citizenwatch.com/us/en/product/FB2003-05A.html",
    // "https://www.citizenwatch.com/us/en/product/EG7050-54A.html",
    // "https://www.citizenwatch.com/us/en/product/EG7055-51E.html",
    // "https://www.citizenwatch.com/us/en/product/EM0630-51D.html",
    // "https://www.citizenwatch.com/us/en/product/EM0633-53A.html",
    // "https://www.citizenwatch.com/us/en/product/EM0638-50P.html",
    // "https://www.citizenwatch.com/us/en/product/EM0732-51P.html",
    // "https://www.citizenwatch.com/us/en/product/EM0733-08A.html",
    // "https://www.citizenwatch.com/us/en/product/EM0734-56D.html",
    // "https://www.citizenwatch.com/us/en/product/EX1320-54E.html",
    // "https://www.citizenwatch.com/us/en/product/EX1410-53A.html",
    // "https://www.citizenwatch.com/us/en/product/EX1420-50E.html",
    // "https://www.citizenwatch.com/us/en/product/EX1422-54E.html",
    // "https://www.citizenwatch.com/us/en/product/GA1050-51E.html",
    // "https://www.citizenwatch.com/us/en/product/GA1052-55E.html",
    // "https://www.citizenwatch.com/us/en/product/GA1053-01A.html",
    // "https://www.citizenwatch.com/us/en/product/GA1055-06E.html",
    // "https://www.citizenwatch.com/us/en/product/EM0490-08A.html",
    // "https://www.citizenwatch.com/us/en/product/EM0492-02A.html",
    // "https://www.citizenwatch.com/us/en/product/EW1670-59D.html",
    // "https://www.citizenwatch.com/us/en/product/JY8077-04H.html",
    // "https://www.citizenwatch.com/us/en/product/AT9016-56H.html",
    // "https://www.citizenwatch.com/us/en/product/AT2205-01E.html",
    // "https://www.citizenwatch.com/us/en/product/AW1150-07A.html",
    // "https://www.citizenwatch.com/us/en/product/AW1588-57E.html",
    // "https://www.citizenwatch.com/us/en/product/AW1605-09E.html",
    // "https://www.citizenwatch.com/us/en/product/AW1607-03H.html",
    // "https://www.citizenwatch.com/us/en/product/BN0190-07E.html",
    // "https://www.citizenwatch.com/us/en/product/EM0768-54E.html",
    // "https://www.citizenwatch.com/us/en/product/FE7073-54A.html",
    // "https://www.citizenwatch.com/us/en/product/EM0763-07A.html",
    // "https://www.citizenwatch.com/us/en/product/FE7073-71A.html",
    // "https://www.citizenwatch.com/us/en/product/EM0766-50A.html",
    // "https://www.citizenwatch.com/us/en/product/FE7056-02D.html",
    // "https://www.citizenwatch.com/us/en/product/EM0753-01A.html",
    // "https://www.citizenwatch.com/us/en/product/EM0682-58P.html",
    // "https://www.citizenwatch.com/us/en/product/EM0683-04D.html",
    // "https://www.citizenwatch.com/us/en/product/EM0680-53D.html",
    // "https://www.citizenwatch.com/us/en/product/EM0688-01E.html",
    // "https://www.citizenwatch.com/us/en/product/FE6086-74A.html",
    // "https://www.citizenwatch.com/us/en/product/FE6082-08P.html",
    // "https://www.citizenwatch.com/us/en/product/FE6133-09A.html",
    // "https://www.citizenwatch.com/us/en/product/FE6142-08A.html",
    // "https://www.citizenwatch.com/us/en/product/FE6140-03A.html",
    // "https://www.citizenwatch.com/us/en/product/FE6110-55A.html",
    // "https://www.citizenwatch.com/us/en/product/AR5044-03E.html",
    // "https://www.citizenwatch.com/us/en/product/AR5000-76E.html",
    // "https://www.citizenwatch.com/us/en/product/AR5004-75H.html",
    // "https://www.citizenwatch.com/us/en/product/AR5024-01E.html",
    // "https://www.citizenwatch.com/us/en/product/AR5025-08E.html",
    // "https://www.citizenwatch.com/us/en/product/AR5026-05A.html",
    // "https://www.citizenwatch.com/us/en/product/AW0061-01W.html",
    // "https://www.citizenwatch.com/us/en/product/CB1020-54E.html",
    // "https://www.citizenwatch.com/us/en/product/EC1030-50L.html",
    // "https://www.citizenwatch.com/us/en/product/EC1114-51W.html",
    // "https://www.citizenwatch.com/us/en/product/EC1142-05B.html",
    // "https://www.citizenwatch.com/us/en/product/EC1144-51W.html",
    // "https://www.citizenwatch.com/us/en/product/ES9354-51A.html",
    // "https://www.citizenwatch.com/us/en/product/BZ4000-07L.html",
    // "https://www.citizenwatch.com/us/en/product/AQ1030-57H.html",
    // "https://www.citizenwatch.com/us/en/product/AQ1040-53A.html",
    // "https://www.citizenwatch.com/us/en/product/EW1676-52D.html",
    // "https://www.citizenwatch.com/us/en/product/EW2520-56Y.html",
    // "https://www.citizenwatch.com/us/en/product/EW2522-51D.html",
    // "https://www.citizenwatch.com/us/en/product/EW2524-55N.html",
    // "https://www.citizenwatch.com/us/en/product/BM6983-51H.html",
    // "https://www.citizenwatch.com/us/en/product/FD2053-04A.html",
    // "https://www.citizenwatch.com/us/en/product/FD2050-53L.html",
    // "https://www.citizenwatch.com/us/en/product/AR3077-56W.html",
    // "https://www.citizenwatch.com/us/en/product/BZ7000-60L.html",
    // "https://www.citizenwatch.com/us/en/product/BZ7005-74E.html",
    // "https://www.citizenwatch.com/us/en/product/BZ7005-74X.html",
    // "https://www.citizenwatch.com/us/en/product/BZ7007-61E.html",
    // "https://www.citizenwatch.com/us/en/product/AT4127-52H.html",
    // "https://www.citizenwatch.com/us/en/product/CA0429-53W.html",
    // "https://www.citizenwatch.com/us/en/product/GA1052-04E.html",
    // "https://www.citizenwatch.com/us/en/product/EW5552-53D.html",
    // "https://www.citizenwatch.com/us/en/product/EW5553-51D.html",
    // "https://www.citizenwatch.com/us/en/product/EW5556-52D.html",
    // "https://www.citizenwatch.com/us/en/product/EM0596-58W.html",
    // "https://www.citizenwatch.com/us/en/product/EW2294-53L.html",
    // "https://www.citizenwatch.com/us/en/product/EM0716-58A.html",
    // "https://www.citizenwatch.com/us/en/product/GA1056-54W.html",
    // "https://www.citizenwatch.com/us/en/product/FB1230-50A.html",
    // "https://www.citizenwatch.com/us/en/product/EW5551-56N.html",
    // "https://www.citizenwatch.com/us/en/product/BU0050-02L.html",
    // "https://www.citizenwatch.com/us/en/product/EM0796-08Y.html",
    // "https://www.citizenwatch.com/us/en/product/BM6835-15E.html",
    // "https://www.citizenwatch.com/us/en/product/BM6838-09X.html",
    // "https://www.citizenwatch.com/us/en/product/BM6838-17L.html",
    // "https://www.citizenwatch.com/us/en/product/AU1044-58E.html",
    // "https://www.citizenwatch.com/us/en/product/EW9334-52E.html",
    // "https://www.citizenwatch.com/us/en/product/AR3073-06E.html",
    // "https://www.citizenwatch.com/us/en/product/FE6083-13E.html",
    // "https://www.citizenwatch.com/us/en/product/EX1516-52E.html",
    // "https://www.citizenwatch.com/us/en/product/CA7000-55E.html",
    // "https://www.citizenwatch.com/us/en/product/FE7040-53E.html",
    // "https://www.citizenwatch.com/us/en/product/AU1062-05E.html",
    // "https://www.citizenwatch.com/us/en/product/AW1232-04A.html",
    // "https://www.citizenwatch.com/us/en/product/FE1082-05A.html",
    // "https://www.citizenwatch.com/us/en/product/EW2494-54A.html",
    // "https://www.citizenwatch.com/us/en/product/EW1264-50A.html",
    // "https://www.citizenwatch.com/us/en/product/BM7330-59L.html",
    // "https://www.citizenwatch.com/us/en/product/EW2290-54L.html",
    // "https://www.citizenwatch.com/us/en/product/BM7334-58L.html",
    // "https://www.citizenwatch.com/us/en/product/BU2055-16E.html",
    // "https://www.citizenwatch.com/us/en/product/BM8180-03E.html",
    // "https://www.citizenwatch.com/us/en/product/AO9003-08E.html",
    // "https://www.citizenwatch.com/us/en/product/AO9020-84E.html",
    // "https://www.citizenwatch.com/us/en/product/AP1053-15W.html",
    // "https://www.citizenwatch.com/us/en/product/AP1053-23W.html",
    // "https://www.citizenwatch.com/us/en/product/AP1058-11W.html",
    // "https://www.citizenwatch.com/us/en/product/AR3075-51E.html",
    // "https://www.citizenwatch.com/us/en/product/AR3102-51E.html",
    // "https://www.citizenwatch.com/us/en/product/AR3103-58E.html",
    // "https://www.citizenwatch.com/us/en/product/AR3104-55E.html",
    // "https://www.citizenwatch.com/us/en/product/AR3107-57E.html",
    // "https://www.citizenwatch.com/us/en/product/AT0200-21L.html",
    // "https://www.citizenwatch.com/us/en/product/AT2450-58E.html",
    // "https://www.citizenwatch.com/us/en/product/AT2452-52E.html",
    // "https://www.citizenwatch.com/us/en/product/AT4004-52E.html",
    // "https://www.citizenwatch.com/us/en/product/AT4106-52X.html",
    // "https://www.citizenwatch.com/us/en/product/AU1040-08E.html",
    // "https://www.citizenwatch.com/us/en/product/AU1043-00E.html",
    // "https://www.citizenwatch.com/us/en/product/AU1067-52W.html",
    // "https://www.citizenwatch.com/us/en/product/AU1068-50W.html",
    // "https://www.citizenwatch.com/us/en/product/AU1069-06W.html",
    // "https://www.citizenwatch.com/us/en/product/AU1069-57W.html",
    // "https://www.citizenwatch.com/us/en/product/AW0050-82E.html",
    // "https://www.citizenwatch.com/us/en/product/AW0075-06W.html",
    // "https://www.citizenwatch.com/us/en/product/AW1013-59W.html",
    // "https://www.citizenwatch.com/us/en/product/AW1017-58W.html",
    // "https://www.citizenwatch.com/us/en/product/AW1155-03W.html",
    // "https://www.citizenwatch.com/us/en/product/AW1156-01W.html",
    // "https://www.citizenwatch.com/us/en/product/AW1236-03A.html",
    // "https://www.citizenwatch.com/us/en/product/AW1366-83W.html",
    // "https://www.citizenwatch.com/us/en/product/AW1367-05W.html",
    // "https://www.citizenwatch.com/us/en/product/AW1430-86A.html",
    // "https://www.citizenwatch.com/us/en/product/AW1430-86E.html",
    // "https://www.citizenwatch.com/us/en/product/AW1431-24W.html",
    // "https://www.citizenwatch.com/us/en/product/AW1513-05W.html",
    // "https://www.citizenwatch.com/us/en/product/AW1529-81W.html",
    // "https://www.citizenwatch.com/us/en/product/AW1552-54E.html",
    // "https://www.citizenwatch.com/us/en/product/AW1578-51W.html",
    // "https://www.citizenwatch.com/us/en/product/AW1596-08W.html",
    // "https://www.citizenwatch.com/us/en/product/AW1597-05W.html",
    // "https://www.citizenwatch.com/us/en/product/AW1599-00W.html",
    // "https://www.citizenwatch.com/us/en/product/AW1608-01E.html",
    // "https://www.citizenwatch.com/us/en/product/AW1615-05W.html",
    // "https://www.citizenwatch.com/us/en/product/AW1650-04W.html",
    // "https://www.citizenwatch.com/us/en/product/AW1660-51H.html",
    // "https://www.citizenwatch.com/us/en/product/AW2037-04W.html",
    // "https://www.citizenwatch.com/us/en/product/AW2047-51W.html",
    // "https://www.citizenwatch.com/us/en/product/BJ7129-56E.html",
    // "https://www.citizenwatch.com/us/en/product/BJ7135-02E.html",
    // "https://www.citizenwatch.com/us/en/product/BJ7138-04E.html",
    // "https://www.citizenwatch.com/us/en/product/BM6550-58E.html",
    // "https://www.citizenwatch.com/us/en/product/BM6552-52E.html",
    // "https://www.citizenwatch.com/us/en/product/BM7100-59H.html",
    // "https://www.citizenwatch.com/us/en/product/BM7103-51L.html",
    // "https://www.citizenwatch.com/us/en/product/BM7107-50E.html",
    // "https://www.citizenwatch.com/us/en/product/BM7193-07B.html",
    // "https://www.citizenwatch.com/us/en/product/BM7251-53H.html",
    // "https://www.citizenwatch.com/us/en/product/BM7251-53L.html",
    // "https://www.citizenwatch.com/us/en/product/BM7252-51E.html",
    // "https://www.citizenwatch.com/us/en/product/BM7252-51G.html",
    // "https://www.citizenwatch.com/us/en/product/BM7256-50E.html",
    // "https://www.citizenwatch.com/us/en/product/BM7257-57W.html",
    // "https://www.citizenwatch.com/us/en/product/BM7258-54H.html",
    // "https://www.citizenwatch.com/us/en/product/BM7332-53P.html",
    // "https://www.citizenwatch.com/us/en/product/BM7344-54E.html",
    // "https://www.citizenwatch.com/us/en/product/BM7417-01W.html",
    // "https://www.citizenwatch.com/us/en/product/BM7431-51X.html",
    // "https://www.citizenwatch.com/us/en/product/BM7492-57A.html",
    // "https://www.citizenwatch.com/us/en/product/BM7494-51L.html",
    // "https://www.citizenwatch.com/us/en/product/BM7495-59G.html",
    // "https://www.citizenwatch.com/us/en/product/BM7496-56G.html",
    // "https://www.citizenwatch.com/us/en/product/BM8471-01E.html",
    // "https://www.citizenwatch.com/us/en/product/BM8475-00F.html",
    // "https://www.citizenwatch.com/us/en/product/BM8477-04W.html",
    // "https://www.citizenwatch.com/us/en/product/BM8478-01L.html",
    // "https://www.citizenwatch.com/us/en/product/BU0054-52L.html",
    // "https://www.citizenwatch.com/us/en/product/BU0056-57A.html",
    // "https://www.citizenwatch.com/us/en/product/BU0057-54E.html",
    // "https://www.citizenwatch.com/us/en/product/BU2010-57L.html",
    // "https://www.citizenwatch.com/us/en/product/BU2013-08E.html",
    // "https://www.citizenwatch.com/us/en/product/BU2055-08X.html",
    // "https://www.citizenwatch.com/us/en/product/BU2058-00W.html",
    // "https://www.citizenwatch.com/us/en/product/BU2070-04A.html",
    // "https://www.citizenwatch.com/us/en/product/BU2070-12L.html",
    // "https://www.citizenwatch.com/us/en/product/BV1088-08W.html",
    // "https://www.citizenwatch.com/us/en/product/BV1110-51L.html",
    // "https://www.citizenwatch.com/us/en/product/BV1138-01W.html",
    // "https://www.citizenwatch.com/us/en/product/BX1000-06L.html",
    // "https://www.citizenwatch.com/us/en/product/BX1000-57E.html",
    // "https://www.citizenwatch.com/us/en/product/BX1003-08E.html",
    // "https://www.citizenwatch.com/us/en/product/CA0295-58E.html",
    // "https://www.citizenwatch.com/us/en/product/CA0297-52W.html",
    // "https://www.citizenwatch.com/us/en/product/CA0621-05L.html",
    // "https://www.citizenwatch.com/us/en/product/CA0646-04W.html",
    // "https://www.citizenwatch.com/us/en/product/CA0688-04W.html",
    // "https://www.citizenwatch.com/us/en/product/CA0750-53E.html",
    // "https://www.citizenwatch.com/us/en/product/CA0752-58L.html",
    // "https://www.citizenwatch.com/us/en/product/CA0753-55E.html",
    // "https://www.citizenwatch.com/us/en/product/CA0760-09W.html",
    // "https://www.citizenwatch.com/us/en/product/CA0765-05W.html",
    // "https://www.citizenwatch.com/us/en/product/CA4184-81E.html",
    // "https://www.citizenwatch.com/us/en/product/CA4213-18L.html",
    // "https://www.citizenwatch.com/us/en/product/CA4281-00W.html",
    // "https://www.citizenwatch.com/us/en/product/CA4377-53H.html",
    // "https://www.citizenwatch.com/us/en/product/CA4439-07W.html",
    // "https://www.citizenwatch.com/us/en/product/CA7020-07A.html",
    // "https://www.citizenwatch.com/us/en/product/CA7021-04W.html",
    // "https://www.citizenwatch.com/us/en/product/CA7050-57H.html",
    // "https://www.citizenwatch.com/us/en/product/CA7058-55E.html",
    // "https://www.citizenwatch.com/us/en/product/CB1020-54A.html",
    // "https://www.citizenwatch.com/us/en/product/CC3064-01X.html",
    // "https://www.citizenwatch.com/us/en/product/CC5001-00W.html",
    // "https://www.citizenwatch.com/us/en/product/CC3067-02E.html",
    // "https://www.citizenwatch.com/us/en/product/CC5006-06L.html",
    // "https://www.citizenwatch.com/us/en/product/CC7005-16G.html",
    // "https://www.citizenwatch.com/us/en/product/CX0000-55L.html",
    // "https://www.citizenwatch.com/us/en/product/CX0000-71A.html",
    // "https://www.citizenwatch.com/us/en/product/CX0005-78E.html",
    // "https://www.citizenwatch.com/us/en/product/EC1164-53W.html",
    // "https://www.citizenwatch.com/us/en/product/EC1165-51W.html",
    // "https://www.citizenwatch.com/us/en/product/EG6012-59E.html",
    // "https://www.citizenwatch.com/us/en/product/EG6013-56A.html",
    // "https://www.citizenwatch.com/us/en/product/EG6016-58A.html",
    // "https://www.citizenwatch.com/us/en/product/EM0233-51A.html",
    // "https://www.citizenwatch.com/us/en/product/EM0320-59D.html",
    // "https://www.citizenwatch.com/us/en/product/EM0353-50D.html",
    // "https://www.citizenwatch.com/us/en/product/EM0374-50A.html",
    // "https://www.citizenwatch.com/us/en/product/EM0380-81D.html",
    // "https://www.citizenwatch.com/us/en/product/EM0460-50N.html",
    // "https://www.citizenwatch.com/us/en/product/EM0504-81A.html",
    // "https://www.citizenwatch.com/us/en/product/EM0550-83N.html",
    // "https://www.citizenwatch.com/us/en/product/EM0554-58N.html",
    // "https://www.citizenwatch.com/us/en/product/EM0556-87D.html",
    // "https://www.citizenwatch.com/us/en/product/EM0558-81Y.html",
    // "https://www.citizenwatch.com/us/en/product/EM0580-58N.html",
    // "https://www.citizenwatch.com/us/en/product/EM0586-51Y.html",
    // "https://www.citizenwatch.com/us/en/product/EM0594-53W.html",
    // "https://www.citizenwatch.com/us/en/product/EM0595-51W.html",
    // "https://www.citizenwatch.com/us/en/product/EM0680-70E.html",
    // "https://www.citizenwatch.com/us/en/product/EM0659-09E.html",
    // "https://www.citizenwatch.com/us/en/product/EM0682-74A.html",
    // "https://www.citizenwatch.com/us/en/product/EM0739-52W.html",
    // "https://www.citizenwatch.com/us/en/product/EM0748-51W.html",
    // "https://www.citizenwatch.com/us/en/product/EM0770-52Y.html",
    // "https://www.citizenwatch.com/us/en/product/EM0773-54D.html",
    // "https://www.citizenwatch.com/us/en/product/EM0774-51D.html",
    // "https://www.citizenwatch.com/us/en/product/EM0794-03Y.html",
    // "https://www.citizenwatch.com/us/en/product/EM0798-02D.html",
    // "https://www.citizenwatch.com/us/en/product/EM0865-58E.html",
    // "https://www.citizenwatch.com/us/en/product/EM0860-51D.html",
    // "https://www.citizenwatch.com/us/en/product/EM0862-56D.html",
    // "https://www.citizenwatch.com/us/en/product/EM0863-53D.html",
    // "https://www.citizenwatch.com/us/en/product/EM0870-58A.html",
    // "https://www.citizenwatch.com/us/en/product/EM0808-51W.html",
    // "https://www.citizenwatch.com/us/en/product/EM0843-51D.html",
    // "https://www.citizenwatch.com/us/en/product/EM0882-59A.html",
    // "https://www.citizenwatch.com/us/en/product/EM0880-54D.html",
    // "https://www.citizenwatch.com/us/en/product/EM0820-56N.html",
    // "https://www.citizenwatch.com/us/en/product/EM0883-05A.html",
    // "https://www.citizenwatch.com/us/en/product/EM0876-51D.html",
    // "https://www.citizenwatch.com/us/en/product/EM0844-58D.html",
    // "https://www.citizenwatch.com/us/en/product/EM0840-59N.html",
    // "https://www.citizenwatch.com/us/en/product/EO1116-57A.html",
    // "https://www.citizenwatch.com/us/en/product/EM0823-58D.html",
    // "https://www.citizenwatch.com/us/en/product/EM0874-57D.html",
    // "https://www.citizenwatch.com/us/en/product/ES9360-58L.html",
    // "https://www.citizenwatch.com/us/en/product/ES9420-58A.html",
    // "https://www.citizenwatch.com/us/en/product/ES9424-57A.html",
    // "https://www.citizenwatch.com/us/en/product/ES9440-51L.html",
    // "https://www.citizenwatch.com/us/en/product/ES9440-51W.html",
    // "https://www.citizenwatch.com/us/en/product/ES9442-04W.html",
    // "https://www.citizenwatch.com/us/en/product/EW1228-53D.html",
    // "https://www.citizenwatch.com/us/en/product/EW1410-50E.html",
    // "https://www.citizenwatch.com/us/en/product/EW2096-57D.html",
    // "https://www.citizenwatch.com/us/en/product/EW2251-81W.html",
    // "https://www.citizenwatch.com/us/en/product/EW2340-58A.html",
    // "https://www.citizenwatch.com/us/en/product/EW2344-57A.html",
    // "https://www.citizenwatch.com/us/en/product/EW2348-56A.html",
    // "https://www.citizenwatch.com/us/en/product/EW2440-53A.html",
    // "https://www.citizenwatch.com/us/en/product/EW2448-01W.html",
    // "https://www.citizenwatch.com/us/en/product/EW2448-51W.html",
    // "https://www.citizenwatch.com/us/en/product/EW2582-59A.html",
    // "https://www.citizenwatch.com/us/en/product/EW2584-53L.html",
    // "https://www.citizenwatch.com/us/en/product/EW2586-58E.html",
    // "https://www.citizenwatch.com/us/en/product/EW3144-51A.html",
    // "https://www.citizenwatch.com/us/en/product/EW5510-53N.html",
    // "https://www.citizenwatch.com/us/en/product/EW5554-58D.html",
    // "https://www.citizenwatch.com/us/en/product/EW5564-54D.html",
    // "https://www.citizenwatch.com/us/en/product/EX1190-58D.html",
    // "https://www.citizenwatch.com/us/en/product/EX1480-58L.html",
    // "https://www.citizenwatch.com/us/en/product/EX1483-50D.html",
    // "https://www.citizenwatch.com/us/en/product/EX1510-08N.html",
    // "https://www.citizenwatch.com/us/en/product/EX1510-59D.html",
    // "https://www.citizenwatch.com/us/en/product/EX1512-53A.html",
    // "https://www.citizenwatch.com/us/en/product/EX1513-18D.html",
    // "https://www.citizenwatch.com/us/en/product/EX1536-55E.html",
    // "https://www.citizenwatch.com/us/en/product/EX1538-50E.html",
    // "https://www.citizenwatch.com/us/en/product/EX1539-57E.html",
    // "https://www.citizenwatch.com/us/en/product/FD1030-56Y.html",
    // "https://www.citizenwatch.com/us/en/product/FE1140-86L.html",
    // "https://www.citizenwatch.com/us/en/product/FE1140-86X.html",
    // "https://www.citizenwatch.com/us/en/product/FB3008-57E.html",
    // "https://www.citizenwatch.com/us/en/product/FB3002-53P.html",
    // "https://www.citizenwatch.com/us/en/product/FE1190-53E.html",
    // "https://www.citizenwatch.com/us/en/product/FE1196-57A.html",
    // "https://www.citizenwatch.com/us/en/product/FE1210-07A.html",
    // "https://www.citizenwatch.com/us/en/product/FE1213-50A.html",
    // "https://www.citizenwatch.com/us/en/product/FE1218-05H.html",
    // "https://www.citizenwatch.com/us/en/product/FE2100-51E.html",
    // "https://www.citizenwatch.com/us/en/product/FE2102-55A.html",
    // "https://www.citizenwatch.com/us/en/product/FE2104-50A.html",
    // "https://www.citizenwatch.com/us/en/product/FE6083-05P.html",
    // "https://www.citizenwatch.com/us/en/product/FE6083-72A.html",
    // "https://www.citizenwatch.com/us/en/product/FE6101-05W.html",
    // "https://www.citizenwatch.com/us/en/product/FE6113-57X.html",
    // "https://www.citizenwatch.com/us/en/product/FE7043-55A.html",
    // "https://www.citizenwatch.com/us/en/product/FE7050-50W.html",
    // "https://www.citizenwatch.com/us/en/product/FE7060-56W.html",
    // "https://www.citizenwatch.com/us/en/product/FE7065-52W.html",
    // "https://www.citizenwatch.com/us/en/product/FE7079-58W.html",
    // "https://www.citizenwatch.com/us/en/product/FE7082-53W.html",
    // "https://www.citizenwatch.com/us/en/product/GA1051-58W.html",
    // "https://www.citizenwatch.com/us/en/product/GA1057-01W.html",
    // "https://www.citizenwatch.com/us/en/product/GA1058-16E.html",
    // "https://www.citizenwatch.com/us/en/product/GA1058-59Q.html",
    // "https://www.citizenwatch.com/us/en/product/HX0000-59L.html",
    // "https://www.citizenwatch.com/us/en/product/HX0000-59X.html",
    // "https://www.citizenwatch.com/us/en/product/HX0003-51E.html",
    // "https://www.citizenwatch.com/us/en/product/JY8097-58L.html",
    // "https://www.citizenwatch.com/us/en/product/MX0000-07X.html",
    // "https://www.citizenwatch.com/us/en/product/MX0001-12X.html",
    // "https://www.citizenwatch.com/us/en/product/MX0007-59X.html",
    // "https://www.citizenwatch.com/us/en/product/NB0040-58A.html",
    // "https://www.citizenwatch.com/us/en/product/CA0727-04E.html",
    // "https://www.citizenwatch.com/us/en/product/AW0090-02X.html",
    // "https://www.citizenwatch.com/us/en/product/AW0090-11Z.html",
    // "https://www.citizenwatch.com/us/en/product/AW0092-07Q.html",
    // "https://www.citizenwatch.com/us/en/product/AW0096-06L.html",
    // "https://www.citizenwatch.com/us/en/product/AW1655-01E.html",
    // "https://www.citizenwatch.com/us/en/product/AW1658-02E.html",
    // "https://www.citizenwatch.com/us/en/product/BJ2169-88E.html",
    // "https://www.citizenwatch.com/us/en/product/BJ2168-01E.html",
    // "https://www.citizenwatch.com/us/en/product/BJ2167-03E.html",
    // "https://www.citizenwatch.com/us/en/product/BL5570-01E.html",
    // "https://www.citizenwatch.com/us/en/product/BL5571-09L.html",
    // "https://www.citizenwatch.com/us/en/product/BL5578-51E.html",
    // "https://www.citizenwatch.com/us/en/product/CA0430-54M.html",
    // "https://www.citizenwatch.com/us/en/product/CA0438-52E.html",
    // "https://www.citizenwatch.com/us/en/product/CB5912-50E.html",
    // "https://www.citizenwatch.com/us/en/product/CB5918-02L.html",
    // "https://www.citizenwatch.com/us/en/product/CB5919-00X.html",
    // "https://www.citizenwatch.com/us/en/product/AW1609-08W.html",
    // "https://www.citizenwatch.com/us/en/product/CC4004-58E.html",
    // "https://www.citizenwatch.com/us/en/product/FD4018-55W.html",
    // "https://www.citizenwatch.com/us/en/product/JG2108-52W.html",
    // "https://www.citizenwatch.com/us/en/product/JG2109-50W.html",
    // "https://www.citizenwatch.com/us/en/product/FE7044-52W.html",
    // "https://www.citizenwatch.com/us/en/product/AW1351-56W.html",
    // "https://www.citizenwatch.com/us/en/product/AW1680-03W.html",
    // "https://www.citizenwatch.com/us/en/product/FE7045-09W.html",
    // "https://www.citizenwatch.com/us/en/product/BN0155-08E.html",
    // "https://www.citizenwatch.com/us/en/product/EX1492-59W.html",
    // "https://www.citizenwatch.com/us/en/product/EX1499-50W.html",
    // "https://www.citizenwatch.com/us/en/product/AR3110-52E.html",
    // "https://www.citizenwatch.com/us/en/product/AR3112-57E.html",
    // "https://www.citizenwatch.com/us/en/product/AT8220-55L.html",
    // "https://www.citizenwatch.com/us/en/product/AT8227-56X.html",
    // "https://www.citizenwatch.com/us/en/product/AW1690-51E.html",
    // "https://www.citizenwatch.com/us/en/product/AW1694-50A.html",
    // "https://www.citizenwatch.com/us/en/product/BM7534-59A.html",
    // "https://www.citizenwatch.com/us/en/product/BM7536-53X.html",
    // "https://www.citizenwatch.com/us/en/product/BN0152-06E.html",
    // "https://www.citizenwatch.com/us/en/product/EM0952-55A.html",
    // "https://www.citizenwatch.com/us/en/product/EM0954-50E.html",
    // "https://www.citizenwatch.com/us/en/product/EO1224-54D.html",
    // "https://www.citizenwatch.com/us/en/product/EO1226-59X.html",
    // "https://www.citizenwatch.com/us/en/product/FE1233-52A.html",
    // "https://www.citizenwatch.com/us/en/product/FE1234-50L.html",
    // "https://www.citizenwatch.com/us/en/product/AT8185-71E.html",
    // "https://www.citizenwatch.com/us/en/product/BL5607-54L.html",
    // "https://www.citizenwatch.com/us/en/product/BL5600-53E.html",
    // "https://www.citizenwatch.com/us/en/product/CC4016-75E.html",
    // "https://www.citizenwatch.com/us/en/product/MX0000-58X.html",
    // "https://www.citizenwatch.com/us/en/product/MX0002-52X.html",
    // "https://www.citizenwatch.com/us/en/product/MX0008-56X.html",
    // "https://www.citizenwatch.com/us/en/product/JG2110-51W.html",
    // "https://www.citizenwatch.com/us/en/product/JG2112-55P.html",
    // "https://www.citizenwatch.com/us/en/product/JG2115-57E.html",
    // "https://www.citizenwatch.com/us/en/product/JG2117-51A.html",
    // "https://www.citizenwatch.com/us/en/product/CB5921-59X.html",
    // "https://www.citizenwatch.com/us/en/product/CB5921-59E.html",
    // "https://www.citizenwatch.com/us/en/product/AW1651-52W.html"
];

const extraction = async (context) => {
    const { client, entry, base, ...rest } = context;
    const result = { ...rest, url: entry, spec: [], related: [], features: [] };
    result.source = "official";
    result.lang = "en";
    result.brand = "Citizen";
    result.brandID = 86;
    try {
        const res = await client.get(entry);
        const cUrl = res.request.res.responseUrl;
        if (cUrl != entry) {
            result.code = 404;
            return;
        }
        const { data } = res;
        const $ = cheerio.load(data);
        const title = $(".product-name").first().text();
        const subtitle = $(".product-subtitle").text();
        result.name = title + subtitle ? subtitle : "";
        result.reference = $(".product-id").text();
        result.retail = $(".price").find(".list").find(".value").attr("content");
        result.price = $(".price").find(".sales").find(".value").attr("content");
        if (result.price) result.price = result.price.replace(/\s+/g, " ").trim();
        if (!result.retail) result.retail = result.price;
        result.description = $(".show-more-text-content").text().trim();
        result.thumbnail = $(".primary-images-main").find(".slide").first().attr("data-zoom-image");
        if (result.url.match(/\bmens\b/)) result.gender = "M";
        $(".recommendation-thumbnail").each((idx, el) => {
            const url = $(el).find("a").attr("href");
            const u = url ? url.split('/') : null;
            const r = u ? u[u.length - 1].replace('.html', '') : null;
            if (r) result.related.push(r);
        })
        let key, value;
        $(".key-details-col-2").find(".row").find("div").each((idx, el) => {
            const c = $(el).attr("class");
            if (c.match(/pdp-detail-attribute-header/i)) {
                key = $(el).text();
                if (key) key = key.replace(/\s+/g, " ").trim();
            } else if (c.match(/pdp-detail-attribute-col/i)) {
                value = $(el).find(".pdp-detail-attribute-list").text();
                if (value) {
                    const v = value.split('\n');
                    let nval = "";
                    v.forEach(val => {
                        const vv = val.replace(/\n|\s+/g, " ").trim();
                        if (vv) nval = nval + vv + " | ";
                    })
                    value = nval.slice(0, nval.length - 3);
                }
            }
            if (key && value) {
                result.spec.push({ key, value });
                key = ""; value = "";
            }
        })
        $(".feature-text-list-item").each((idx, el) => {
            const key = "feature";
            const value = $(el).text().replace(/\s+/g, " ").trim();
            result.spec.push({ key, value });
        })
        key = ""; value = "";
        $(".features-attributes-row").find(".row").find("div").each((idx, el) => {
            const c = $(el).attr("class");
            if (c.match(/pdp-detail-attribute-header/i)) {
                key = $(el).text();
                if (key) key = key.replace(/\s+/g, " ").trim();
            } else if (c.match(/pdp-detail-attribute-col/i)) {
                value = $(el).find(".pdp-detail-attribute-list").text();
                if (value) {
                    const v = value.split('\n');
                    let nval = "";
                    v.forEach(val => {
                        const vv = val.replace(/\n|\s+/g, " ").trim();
                        if (vv) nval = nval + vv + " | ";
                    })
                    value = nval.slice(0, nval.length - 3);
                }
            }
            if (key && value) {
                result.spec.push({ key, value });
                key = ""; value = "";
            }
        })
        $(".pdp-additional-functions-list").each((idx, el) => {
            const key = "function";
            const value = $(el).text();
            if (value) {
                const v = value.split('\n');
                v.forEach(val => {
                    const value = val.replace(/\n|\s+/g, " ").trim();
                    if (value) result.spec.push({ key, value });
                })
            }
        })
    } catch (error) {
        logger.error('Failed extraction for Citizen with error : ' + error);
        logger.error('entry : ', entry)
        if (error.response) result.code = error.response.status;
        else result.code = 'UNKNOWN ERROR';
    }
    return result;
};

(async () => {
    const spec = [];
    for (let i = 0; i < urls.length; i++) {
        const ex = await extraction({
            client: axios,
            entry: urls[i],
        })
        console.log(ex);
        // ex.spec.forEach(s => {
        //     const sp = s.key + " --- " + s.value;
        //     if (spec.indexOf(sp) < 0) spec.push(sp);
        // })
    }
    // spec.sort().forEach(s => { console.log(s); });
    console.log();
    console.log('done.....');
})();