{
  source: 'official',
  lang: 'en',
  brand: 'Luminox',
  brandID: 442,
  url: 'https://luminox.com/products/original-navy-seal-3001',
  collection: 'SEA SERIES',
  name: 'Original Navy SEAL - 3001',
  reference: '3001',
  retail: '$395.00',
  thumbnail: 'https://cdn.shopify.com/s/files/1/2423/1151/products/3001-XS-S90-DNV-Day.png?v=1509046688',
  base: 'https://www.luminox.com',
  spec: [
    '43 mm',
    'Carbon reinforced polycarbonate case and case back',
    'Carbon reinforced unidirectional ratcheting bezel',
    'Tempered scratch resistant mineral crystal',
    'Water resistant to 200 meters',
    'Signature black PU strap with stainless steel signature buckle',
    'Luminox self-powered illumination',
    'Swiss Made'
  ],
  related: [],
  description: 'Description 43 mmCarbon reinforced polycarbonate case and case backCarbon reinforced unidirectional ratcheting bezelTempered scratch resistant mineral crystalWater resistant to 200 metersSignature black PU strap with stainless steel signature buckle More Details Luminox self-powered illuminationSwiss Made'
}
{
  source: 'official',
  lang: 'en',
  brand: 'Luminox',
  brandID: 442,
  url: 'https://luminox.com/products/modern-mariner-automatic-6502',
  collection: 'LUMINOX',
  name: 'Modern Mariner Automatic - 6502',
  reference: '6502',
  retail: '$1,395.00',
  thumbnail: 'https://cdn.shopify.com/s/files/1/2423/1151/products/6502-XS-S90-DNV-Day.png?v=1509049291',
  base: 'https://www.luminox.com',
  spec: [
    '45mm',
    'Stainless steel case, screw case back and screw down crown',
    'Unidirectional ratcheting bezel',
    'Antireflective sapphire crystal',
    "Sapphire crystal 'Skeleton' case back",
    'Water resistant to 200 meters',
    'Solid link stainless steel bracelet with security clasp',
    'Luminox self-powered illumination',
    'Swiss Made'
  ],
  related: [],
  description: "Description 45mmStainless steel case, screw case back and screw down crownUnidirectional ratcheting bezelAntireflective sapphire crystalSapphire crystal 'Skeleton' case backWater resistant to 200 metersSolid link stainless steel bracelet with security clasp More Details Luminox self-powered illuminationSwiss Made"
}
{
  source: 'official',
  lang: 'en',
  brand: 'Luminox',
  brandID: 442,
  url: 'https://luminox.com/products/navy-seal-steel-3252',
  collection: 'SEA SERIES',
  name: 'Navy SEAL Steel - 3252',
  reference: '3252',
  retail: '$655.00',
  thumbnail: 'https://cdn.shopify.com/s/files/1/2423/1151/products/3252-90.png?v=1512062920',
  base: 'https://www.luminox.com',
  spec: [
    '45 mm',
    'Stainless steel case, screw down crown &amp; case back',
    'Stainless steel unidirectional ratcheting bezel',
    'Sapphire Crystal with anti-reflective coating',
    'Water resistant to 200 meters',
    '316L Stainless Steel Bracelet',
    'Luminox self-powered illumination',
    'Swiss Made'
  ],
  related: [],
  description: 'Description 45 mmStainless steel case, screw down crown & case backStainless steel unidirectional ratcheting bezelSapphire Crystal with anti-reflective coatingWater resistant to 200 meters316L Stainless Steel Bracelet More Details Luminox self-powered illuminationSwiss Made'
}
{
  source: 'official',
  lang: 'en',
  brand: 'Luminox',
  brandID: 442,
  url: 'https://luminox.com/products/navy-seal-steel-3252-bo',
  collection: 'SEA SERIES',
  name: 'Navy SEAL Steel - 3252.BO.L',
  reference: '3252.BO.L',
  retail: '$765.00',
  thumbnail: 'https://cdn.shopify.com/s/files/1/2423/1151/products/3252.BO_2_-XS-S90-DNV-Day.png?v=1569252956',
  base: 'https://www.luminox.com',
  spec: [
    '45 mm',
    'Stainless steel case, screw down crown &amp; case back',
    'Carbon reinforced polycarbonate bezel',
    'Sapphire Crystal with anti-reflective coating',
    'Water resistant to 200 meters',
    'Solid Steel black brushed plated bracelet with black brushed stainless steel signature buckle with security clasp',
    'Luminox self-powered illumination',
    'Swiss Made'
  ],
  related: [],
  description: 'Description 45 mmStainless steel case, screw down crown & case backCarbon reinforced polycarbonate bezelSapphire Crystal with anti-reflective coatingWater resistant to 200 metersSolid Steel black brushed plated bracelet with black brushed stainless steel signature buckle with security clasp More Details Luminox self-powered illuminationSwiss Made'
}
{
  source: 'official',
  lang: 'en',
  brand: 'Luminox',
  brandID: 442,
  url: 'https://luminox.com/products/navy-seal-steel-3258',
  collection: 'SEA SERIES',
  name: 'Navy SEAL Steel - 3258.L',
  reference: '3258.L',
  retail: '$595.00',
  thumbnail: 'https://cdn.shopify.com/s/files/1/2423/1151/products/3258_2_-XS-S90-DNV-Day.png?v=1509480309',
  base: 'https://www.luminox.com',
  spec: [
    '45 mm',
    'Stainless steel case, screw down crown &amp; case back',
    'Stainless steel bezel',
    'Sapphire Crystal with anti-reflective coating',
    'Water resistant to 200 meters',
    'Solid Steel brushed bracelet with brushed stainless steel signature buckle with security clasp',
    'Luminox self-powered illumination',
    'Swiss Made'
  ],
  related: [],
  description: 'Description 45 mmStainless steel case, screw down crown & case backStainless steel bezelSapphire Crystal with anti-reflective coatingWater resistant to 200 metersSolid Steel brushed bracelet with brushed stainless steel signature buckle with security clasp More Details Luminox self-powered illuminationSwiss Made'
}
{
  source: 'official',
  lang: 'en',
  brand: 'Luminox',
  brandID: 442,
  url: 'https://luminox.com/products/navy-seal-steel-3253',
  collection: 'SEA SERIES',
  name: 'Navy SEAL Steel - 3253',
  reference: '3253',
  retail: '$595.00',
  thumbnail: 'https://cdn.shopify.com/s/files/1/2423/1151/products/3253_front.png?v=1572971001',
  base: 'https://www.luminox.com',
  spec: [
    '45 mm',
    'Stainless steel case, screw down crown &amp; case back',
    'Stainless steel unidirectional ratcheting bezel',
    'Sapphire Crystal with anti-reflective coating',
    'Water resistant to 200 meters',
    'Navy Blue EPDM Rubber Strap with brushed stainless steel signature buckle',
    'Luminox self-powered illumination',
    'Swiss Made'
  ],
  related: [],
  description: 'Description 45 mmStainless steel case, screw down crown & case backStainless steel unidirectional ratcheting bezelSapphire Crystal with anti-reflective coatingWater resistant to 200 metersNavy Blue EPDM Rubber Strap with brushed stainless steel signature buckle More Details Luminox self-powered illuminationSwiss Made'
}
{
  source: 'official',
  lang: 'en',
  brand: 'Luminox',
  brandID: 442,
  url: 'https://luminox.com/products/navy-seal-steel-3254',
  collection: 'SEA SERIES',
  name: 'Navy SEAL Steel - 3254',
  reference: '3254',
  retail: '$655.00',
  thumbnail: 'https://cdn.shopify.com/s/files/1/2423/1151/products/3254_face.png?v=1572972611',
  base: 'https://www.luminox.com',
  spec: [
    '45 mm',
    'Stainless steel case, screw down crown &amp; case back',
    'Stainless steel unidirectional ratcheting bezel',
    'Sapphire Crystal with anti-reflective coating',
    'Water resistant to 200 meters',
    '316L Stainless Steel Bracelet',
    'Luminox self-powered illumination',
    'Swiss Made'
  ],
  related: [],
  description: 'Description 45 mmStainless steel case, screw down crown & case backStainless steel unidirectional ratcheting bezelSapphire Crystal with anti-reflective coatingWater resistant to 200 meters316L Stainless Steel Bracelet More Details Luminox self-powered illuminationSwiss Made'
}
{
  source: 'official',
  lang: 'en',
  brand: 'Luminox',
  brandID: 442,
  url: 'https://luminox.com/products/navy-seal-3502',
  collection: 'SEA SERIES',
  name: 'Navy SEAL - 3502.L',
  reference: '3502.L',
  retail: '$445.00',
  thumbnail: 'https://cdn.shopify.com/s/files/1/2423/1151/products/350290.png?v=1536172801',
  base: 'https://www.luminox.com',
  spec: [
    '45 mm',
    'Carbon Compound case',
    'Stainless Steel case back',
    'Carbon Compound unidirectional turning bezel',
    'Tempered scratch resistant mineral crystal',
    'Water resistant to 200 meters',
    'Ultra-light Carbon Compound link bracelet with black PVD-plated stainless steel clasp',
    'Luminox self-powered illumination',
    'Swiss Made'
  ],
  related: [],
  description: 'Description 45 mmCarbon Compound caseStainless Steel case backCarbon Compound unidirectional turning bezelTempered scratch resistant mineral crystalWater resistant to 200 metersUltra-light Carbon Compound link bracelet with black PVD-plated stainless steel clasp More Details Luminox self-powered illuminationSwiss Made'
}
{
  source: 'official',
  lang: 'en',
  brand: 'Luminox',
  brandID: 442,
  url: 'https://luminox.com/products/navy-seal-3501',
  collection: 'SEA SERIES',
  name: 'Navy SEAL - 3501.L',
  reference: '3501.L',
  retail: '$395.00',
  thumbnail: 'https://cdn.shopify.com/s/files/1/2423/1151/products/3501-90.png?v=1536172532',
  base: 'https://www.luminox.com',
  spec: [
    '45 mm',
    'Carbon Compound case',
    'Stainless Steel case back',
    'Carbon Compound unidirectional turning bezel',
    'Tempered scratch resistant mineral crystal',
    'Water resistant to 200 meters',
    'Signature black PU strap with stainless steel signature buckle',
    'Luminox self-powered illumination',
    'Swiss Made'
  ],
  related: [],
  description: 'Description 45 mmCarbon Compound caseStainless Steel case backCarbon Compound unidirectional turning bezelTempered scratch resistant mineral crystalWater resistant to 200 metersSignature black PU strap with stainless steel signature buckle More Details Luminox self-powered illuminationSwiss Made'
}
{
  source: 'official',
  lang: 'en',
  brand: 'Luminox',
  brandID: 442,
  url: 'https://luminox.com/products/navy-seal-3501-bo',
  collection: 'SEA SERIES',
  name: 'Navy SEAL - 3501.BO.L',
  reference: '3501.BO.L',
  retail: '$395.00',
  thumbnail: 'https://cdn.shopify.com/s/files/1/2423/1151/products/3501.BO-8.png?v=1555421790',
  base: 'https://www.luminox.com',
  spec: [
    '45 mm',
    'Carbon Compound case',
    'Stainless Steel case back',
    'Carbon Compound unidirectional turning bezel',
    'Tempered scratch resistant mineral crystal',
    'Water resistant to 200 meters',
    'Signature black PU strap with stainless steel signature buckle',
    'Luminox self-powered illumination',
    'Swiss Made'
  ],
  related: [],
  description: 'Description 45 mmCarbon Compound caseStainless Steel case backCarbon Compound unidirectional turning bezelTempered scratch resistant mineral crystalWater resistant to 200 metersSignature black PU strap with stainless steel signature buckle More Details Luminox self-powered illuminationSwiss Made'
}
{
  source: 'official',
  lang: 'en',
  brand: 'Luminox',
  brandID: 442,
  url: 'https://luminox.com/products/navy-seal-3502-bo',
  collection: 'SEA SERIES',
  name: 'Navy SEAL - 3502.BO',
  reference: '3502.BO',
  retail: '$495.00',
  thumbnail: 'https://cdn.shopify.com/s/files/1/2423/1151/products/3502.BO-90.png?v=1511906512',
  base: 'https://www.luminox.com',
  spec: [
    '45 mm',
    'Carbon Compound case',
    'Stainless Steel case back',
    'Carbon Compound unidirectional turning bezel',
    'Tempered scratch resistant mineral crystal',
    'Water resistant to 200 meters',
    'Ultra-light Carbon Compund link bracelet with black PVD-plated stainless steel clasp',
    'Luminox self-powered illumination',
    'Swiss Made'
  ],
  related: [],
  description: 'Description 45 mmCarbon Compound caseStainless Steel case backCarbon Compound unidirectional turning bezelTempered scratch resistant mineral crystalWater resistant to 200 metersUltra-light Carbon Compund link bracelet with black PVD-plated stainless steel clasp More Details Luminox self-powered illuminationSwiss Made'
}
{
  source: 'official',
  lang: 'en',
  brand: 'Luminox',
  brandID: 442,
  url: 'https://luminox.com/products/navy-seal-3503-f-new',
  collection: 'SEA SERIES',
  name: 'Navy SEAL - 3503.F',
  reference: '3503.F',
  retail: '$395.00',
  thumbnail: 'https://cdn.shopify.com/s/files/1/2423/1151/products/3503_FRONT.png?v=1570636104',
  base: 'https://www.luminox.com',
  spec: [
    '45 mm',
    'Carbon Compound case back',
    'Stainless Steel case back',
    'Carbon reinforced unidirectional turning bezel',
    'Tempered scratch resistant mineral crystal',
    'Water resistant to 200 meters',
    'Signature black PU strap with stainless steel signature buckle',
    'Luminox self-powered illumination',
    'Swiss Made'
  ],
  related: [],
  description: 'Description 45 mmCarbon Compound case backStainless Steel case backCarbon reinforced unidirectional turning bezelTempered scratch resistant mineral crystalWater resistant to 200 metersSignature black PU strap with stainless steel signature buckle More Details Luminox self-powered illuminationSwiss Made'
}
{
  source: 'official',
  lang: 'en',
  brand: 'Luminox',
  brandID: 442,
  url: 'https://luminox.com/products/navy-seal-3507-wo',
  collection: 'SEA SERIES',
  name: 'Navy SEAL - 3507.WO',
  reference: '3507.WO',
  retail: '$435.00',
  thumbnail: 'https://cdn.shopify.com/s/files/1/2423/1151/products/FACE_e1b77771-aaee-46d3-9c04-2ab84b044987.png?v=1575569137',
  base: 'https://www.luminox.com',
  spec: [
    '45 mm',
    'White Fiberglass Case',
    'Stainless Steel case back',
    'Uni-directional turning bezel',
    'Tempered scratch resistant mineral crystal',
    'Water resistant to 200 meters',
    'Rubber strap with stainless steel signature buckle',
    'Luminox self-powered illumination',
    'Swiss Made'
  ],
  related: [],
  description: 'Description 45 mmWhite Fiberglass CaseStainless Steel case backUni-directional turning bezelTempered scratch resistant mineral crystalWater resistant to 200 metersRubber strap with stainless steel signature buckle More Details Luminox self-powered illuminationSwiss Made'
}
{
  source: 'official',
  lang: 'en',
  brand: 'Luminox',
  brandID: 442,
  url: 'https://luminox.com/products/navy-seal-3508-gold-holiday-edition',
  collection: 'SEA SERIES',
  name: 'Navy SEAL - 3508 Gold',
  reference: '3508 Gold',
  retail: '$435.00',
  thumbnail: 'https://cdn.shopify.com/s/files/1/2423/1151/products/3508-UVshot-fullsize.png?v=1605026989',
  base: 'https://www.luminox.com',
  spec: [
    'Origin: Swiss Made',
    'Always Visible: Permanent glow for up to 25 years',
    'Case diameter: 45 mm',
    'Function: time / date',
    'Water resistance (meters, feet, ATM): 200/660/20',
    'Movement: Swiss quartz',
    'Housing material: CARBONOX ™',
    'Bezel: unidirectional',
    'Caseback: 316L stainless steel screwed on',
    'Glass: Hardened mineral glass (550-650 Vickers)',
    'Crown: screwed with double seal and crown protection',
    'Strap: rubber',
    'Strap width: 24 mm',
    'Height: 14mm',
    'Weight: 76 g'
  ],
  related: [],
  description: 'Description Since time immemorial, the color gold has been used for the highest medals, awards, celebration of power and achievement as trophies have always been gold. In the Navy, the trident of the elite SEALs is gold, as are the rank stripes and buttons on military dress-uniforms. Gold represents success, power and accomplishment. Origin: Swiss Made Always Visible: Permanent glow for up to 25 years Case diameter: 45 mm Function: time / date Water resistance (meters, feet, ATM): 200/660/20 Movement: Swiss quartz Housing material: CARBONOX ™ Bezel: unidirectional Caseback: 316L stainless steel screwed on Glass: Hardened mineral glass (550-650 Vickers) Crown: screwed with double seal and crown protection Strap: rubber Strap width: 24 mm Height: 14mm Weight: 76 g More Details Luminox self-powered illuminationSwiss Made'
}
{
  source: 'official',
  lang: 'en',
  brand: 'Luminox',
  brandID: 442,
  url: 'https://luminox.com/products/f-117-nighthawk-6421',
  collection: 'LUMINOX',
  name: 'F-117 Nighthawk GMT Watch - 6421',
  reference: '117 Nighthawk GMT Watch',
  retail: '$990.00',
  thumbnail: 'https://cdn.shopify.com/s/files/1/2423/1151/products/6421-XA-S90-DNV-Day.png?v=1511288423',
  base: 'https://www.luminox.com',
  spec: [
    '44mm',
    'Matte gunmetal PVD-plated stainless steel case, screw case back and screw down crown',
    'Bidirectional rotating bezel',
    'Antireflective sapphire crystal',
    'Water resistant to 200 meters',
    'Black Kevlar strap with leather lining and accents',
    'Luminox self-powered illumination and SuperLuminova on numbers and bezel for unparalleled night visibility',
    'Swiss Made',
    '2 Year Limited Warranty',
    '10 Year Warranty for Tritium Tubes'
  ],
  related: [],
  description: 'Description 44mmMatte gunmetal PVD-plated stainless steel case, screw case back and screw down crownBidirectional rotating bezelAntireflective sapphire crystalWater resistant to 200 metersBlack Kevlar strap with leather lining and accentsLuminox self-powered illumination and SuperLuminova on numbers and bezel for unparalleled night visibility More Details Swiss Made 2 Year Limited Warranty 10 Year Warranty for Tritium Tubes'
}
{
  source: 'official',
  lang: 'en',
  brand: 'Luminox',
  brandID: 442,
  url: 'https://luminox.com/products/f-117-nighthawk-6422',
  collection: 'LUMINOX',
  name: 'F-117 Nighthawk GMT Watch - 6422',
  reference: '117 Nighthawk GMT Watch',
  retail: '$1,390.00',
  thumbnail: 'https://cdn.shopify.com/s/files/1/2423/1151/products/6422-XA-S90-DNV-Day.png?v=1511288706',
  base: 'https://www.luminox.com',
  spec: [
    '44mm',
    'Matte gunmetal PVD-plated stainless steel case, screw case back and screw down crown',
    'Bidirectional rotating bezel',
    'Antireflective sapphire crystal',
    'Water resistant to 200 meters',
    'Solid link matte gunmetal PVD-plated stainless steel bracelet with security clasp',
    'Luminox self-powered illumination and SuperLuminova on numbers and bezel for unparalleled night visibility',
    'Swiss Made',
    '2 Year Limited Warranty',
    '10 Year Warranty for Tritium Tubes',
    'The GMT bezel came about in the 1950s with the rise in commercial air travel. To help PanAm’s transatlantic pilots and their crews keep track of the local and Greenwich Mean Time (which was then used as the international time standard)',
    'For the busy men who are always on the go, a GMT watch is a must-have in your collection. What sets a GMT watch apart from other timepieces is its ability to display two to three different timezones at once. Providing a variety of useful features in a stylish package, these watches are both functional and modern. As such, they’re perfect for all kinds of wearers from the active outdoorsman to the office worker and just about all those in between.'
  ],
  related: [],
  description: 'Description 44mmMatte gunmetal PVD-plated stainless steel case, screw case back and screw down crownBidirectional rotating bezelAntireflective sapphire crystalWater resistant to 200 metersSolid link matte gunmetal PVD-plated stainless steel bracelet with security claspLuminox self-powered illumination and SuperLuminova on numbers and bezel for unparalleled night visibility More Details Swiss Made 2 Year Limited Warranty 10 Year Warranty for Tritium Tubes GMT FEATURE The GMT bezel came about in the 1950s with the rise in commercial air travel. To help PanAm’s transatlantic pilots and their crews keep track of the local and Greenwich Mean Time (which was then used as the international time standard) For the busy men who are always on the go, a GMT watch is a must-have in your collection. What sets a GMT watch apart from other timepieces is its ability to display two to three different timezones at once. Providing a variety of useful features in a stylish package, these watches are both functional and modern. As such, they’re perfect for all kinds of wearers from the active outdoorsman to the office worker and just about all those in between.'
}
{
  source: 'official',
  lang: 'en',
  brand: 'Luminox',
  brandID: 442,
  url: 'https://luminox.com/products/f-22-raptor-9241',
  collection: 'LUMINOX',
  name: 'F-22 Raptor - 9241',
  reference: '22 Raptor',
  retail: '$1,190.00',
  thumbnail: 'https://cdn.shopify.com/s/files/1/2423/1151/products/9241-90.png?v=1511380913',
  base: 'https://www.luminox.com',
  spec: [
    '44mm',
    'Brushed titanium case, screw down crown &amp; case back',
    'Antireflective sapphire crystal',
    'Bidirectional rotating bezel with black aluminum slide rule ring',
    'Dial ring with tachymetric scale',
    'Black leather strap with silver stitching and a titanium signature buckle',
    'Water resistant to 200 meters',
    'Luminox self-powered illumination',
    'Swiss Made',
    '2 Year Limited Warranty',
    '10 Year Warranty for Tritium Tubes'
  ],
  related: [],
  description: 'Description 44mmBrushed titanium case, screw down crown & case backAntireflective sapphire crystalBidirectional rotating bezel with black aluminum slide rule ringDial ring with tachymetric scaleBlack leather strap with silver stitching and a titanium signature buckleWater resistant to 200 metersLuminox self-powered illumination More Details Swiss Made 2 Year Limited Warranty 10 Year Warranty for Tritium Tubes'
}
{
  source: 'official',
  lang: 'en',
  brand: 'Luminox',
  brandID: 442,
  url: 'https://luminox.com/products/f-117-nighthawk-6441',
  collection: 'AIR',
  name: 'F-117 Nighthawk GMT Watch - 6441',
  reference: '117 Nighthawk GMT Watch',
  retail: '$875.00',
  thumbnail: 'https://cdn.shopify.com/s/files/1/2423/1151/products/face_23dc8d16-21a3-49ab-a713-9372bc4c28fa.png?v=1573502524',
  base: 'https://www.luminox.com',
  spec: [
    '44mm',
    'CARBONOX™+ Case w/ bi-directional rotating bezel',
    '316L Stainless Steel crown, double security gasket',
    'Antireflective sapphire crystal',
    'Water resistant to 200 meters',
    'Black Kevlar strap with leather lining and accents, 24mm',
    'Luminox self-powered illumination and SuperLuminova on numbers and bezel for unparalleled night visibility',
    'Swiss Made',
    '2 Year Limited Warranty',
    '10 Year Warranty for Tritium Tubes'
  ],
  related: [],
  description: 'Description 44mmCARBONOX™+ Case w/ bi-directional rotating bezel316L Stainless Steel crown, double security gasketAntireflective sapphire crystalWater resistant to 200 metersBlack Kevlar strap with leather lining and accents, 24mmLuminox self-powered illumination and SuperLuminova on numbers and bezel for unparalleled night visibility More Details Swiss Made 2 Year Limited Warranty 10 Year Warranty for Tritium Tubes'
}
{
  source: 'official',
  lang: 'en',
  brand: 'Luminox',
  brandID: 442,
  url: 'https://luminox.com/products/sr-71-blackbird-9098',
  collection: 'AIR',
  name: 'SR-71 Blackbird Automatic Chronograph - 9098',
  reference: '71 Blackbird Automatic Chronograph',
  retail: '$3,250.00',
  thumbnail: 'https://cdn.shopify.com/s/files/1/2423/1151/products/9098-XA-S90-DNV-Day_1.png?v=1565897252',
  base: 'https://www.luminox.com',
  spec: [
    '44mm',
    'Black PVD-plated stainless steel case, screw down crown &amp; case back',
    'Valjoux 7750 Automatic Chronograph movement',
    'Dark Midnight Green enamel dial',
    'Antireflective sapphire crystal',
    'Water resistant to 100 meters',
    'Solid link black PVD-plated stainless steel bracelet with security clasp',
    'Luminox self-powered illumination',
    'Swiss Made',
    '2 Year Limited Warranty 10 Year Warranty for Tritium Tubes'
  ],
  related: [],
  description: '44mmBlack PVD-plated stainless steel case, screw down crown & case backValjoux 7750 Automatic Chronograph movementDark Midnight Green enamel dialAntireflective sapphire crystalWater resistant to 100 metersSolid link black PVD-plated stainless steel bracelet with security claspLuminox self-powered illuminationSwiss Made 2 Year Limited Warranty 10 Year Warranty for Tritium Tubes'
}
{
  source: 'official',
  lang: 'en',
  brand: 'Luminox',
  brandID: 442,
  url: 'https://luminox.com/products/field-automatic-day-date-1801',
  collection: 'LUMINOX',
  name: 'Field Automatic Day Date - 1801',
  reference: '1801',
  retail: '$990.00',
  thumbnail: 'https://cdn.shopify.com/s/files/1/2423/1151/products/1801-90.png?v=1511295320',
  base: 'https://www.luminox.com',
  spec: [
    '43mm',
    'Stainless steel case, screw case back and screw down crown',
    'Antireflective sapphire crystal',
    'Water resistant to 100 meters',
    'Genuine brown buffalo leather strap with ivory contrast stitching and signature stainless steel buckle',
    'Luminox self-powered illumination',
    'Swiss Made'
  ],
  related: [],
  description: 'Description 43mmStainless steel case, screw case back and screw down crownAntireflective sapphire crystalWater resistant to 100 metersGenuine brown buffalo leather strap with ivory contrast stitching and signature stainless steel buckle More Details Luminox self-powered illuminationSwiss Made'
}
{
  source: 'official',
  lang: 'en',
  brand: 'Luminox',
  brandID: 442,
  url: 'https://luminox.com/products/leatherback-sea-turtle-0301',
  collection: 'SEA SERIES',
  name: 'Leatherback Sea Turtle - 0301',
  reference: '0301',
  retail: '$295.00',
  thumbnail: 'https://cdn.shopify.com/s/files/1/2423/1151/products/0301-S90-_2016.png?v=1558420204',
  base: 'https://www.luminox.com',
  spec: [
    '39 mm',
    'Carbon Compound case',
    'Black Carbon Compound caseback',
    'Carbon Compound unidirectional turning bezel',
    'Tempered scratch resistant mineral crystal',
    'Water resistant to 100 meters',
    'Black signature PU strap with brushed stainless steel signature buckle, loop-lock, 19mm',
    'Luminox self-powered illumination',
    'Swiss Made'
  ],
  related: [],
  description: 'Description 39 mmCarbon Compound case Black Carbon Compound casebackCarbon Compound unidirectional turning bezel Tempered scratch resistant mineral crystalWater resistant to 100 meters Black signature PU strap with brushed stainless steel signature buckle, loop-lock, 19mm More Details Luminox self-powered illuminationSwiss Made'
}
{
  source: 'official',
  lang: 'en',
  brand: 'Luminox',
  brandID: 442,
  url: 'https://luminox.com/products/leatherback-sea-turtle-0301-bo',
  collection: 'SEA SERIES',
  name: 'Leatherback Sea Turtle - 0301.BO.L',
  reference: '0301.BO.L',
  retail: '$295.00',
  thumbnail: 'https://cdn.shopify.com/s/files/1/2423/1151/products/0301.BO-S90-_2016.png?v=1536165758',
  base: 'https://www.luminox.com',
  spec: [
    '39 mm',
    'Carbon Compound case with Black Dial',
    'Black Carbon Compound caseback',
    'Uni-directional rotating bezel with Super-LumiNova dot at 12H',
    'Tempered scratch resistant mineral crystal',
    'Water resistant to 100 meters',
    'Black signature PU strap with brushed stainless steel signature buckle, loop-lock, 19mm',
    'Luminox self-powered illumination',
    'Swiss Made'
  ],
  related: [],
  description: 'Description 39 mmCarbon Compound case with Black Dial Black Carbon Compound casebackUni-directional rotating bezel with Super-LumiNova dot at 12H Tempered scratch resistant mineral crystalWater resistant to 100 meters Black signature PU strap with brushed stainless steel signature buckle, loop-lock, 19mm More Details Luminox self-powered illuminationSwiss Made'
}
{
  source: 'official',
  lang: 'en',
  brand: 'Luminox',
  brandID: 442,
  url: 'https://luminox.com/products/leatherback-sea-turtle-0307-wo-1',
  collection: 'SEA SERIES',
  name: 'Leatherback Sea Turtle - 0307.WO',
  reference: '0307.WO',
  retail: '$295.00',
  thumbnail: 'https://cdn.shopify.com/s/files/1/2423/1151/products/0307.WO-S90_1.png?v=1522350513',
  base: 'https://www.luminox.com',
  spec: [
    '39 mm',
    'Carbon Compound case with White Dial',
    'Stainless Steel 316L caseback',
    'Uni-directional rotating bezel with Super-LumiNova dot at 12H',
    'Tempered scratch resistant mineral crystal',
    'Water resistant to 100 meters',
    'White signature silicone strap with brushed stainless steel signature buckle, loop-lock, 19mm',
    'Luminox self-powered illumination',
    'Swiss Made'
  ],
  related: [],
  description: 'Description 39 mmCarbon Compound case with White Dial Stainless Steel 316L casebackUni-directional rotating bezel with Super-LumiNova dot at 12H Tempered scratch resistant mineral crystalWater resistant to 100 meters White signature silicone strap with brushed stainless steel signature buckle, loop-lock, 19mm More Details Luminox self-powered illuminationSwiss Made'
}
{
  source: 'official',
  lang: 'en',
  brand: 'Luminox',
  brandID: 442,
  url: 'https://luminox.com/products/leatherback-sea-turtle-giant-0321-bo',
  collection: 'SEA SERIES',
  name: 'Leatherback Sea Turtle Giant - 0321.BO',
  reference: '0321.BO',
  retail: '$295.00',
  thumbnail: 'https://cdn.shopify.com/s/files/1/2423/1151/products/0321.BO-S90_1.png?v=1556204460',
  base: 'https://www.luminox.com',
  spec: [
    '44 mm',
    'Carbon Compound case with Black Dial',
    'Black Carbon Compound caseback',
    'Uni-directional rotating bezel with Super-LumiNova dot at 12H',
    'Tempered scratch resistant mineral crystal',
    'Water resistant to 100 meters',
    'Black signature PU strap with brushed stainless steel signature buckle, loop lock, 22mm',
    'Luminox self-powered illumination',
    'Swiss Made'
  ],
  related: [],
  description: 'Description 44 mmCarbon Compound case with Black Dial Black Carbon Compound casebackUni-directional rotating bezel with Super-LumiNova dot at 12H Tempered scratch resistant mineral crystalWater resistant to 100 meters Black signature PU strap with brushed stainless steel signature buckle, loop lock, 22mm More Details Luminox self-powered illuminationSwiss Made'
}
{
  source: 'official',
  lang: 'en',
  brand: 'Luminox',
  brandID: 442,
  url: 'https://luminox.com/products/leatherback-sea-turtle-giant-0321',
  collection: 'SEA SERIES',
  name: 'Leatherback Sea Turtle Giant - 0321.L',
  reference: '0321.L',
  retail: '$295.00',
  thumbnail: 'https://cdn.shopify.com/s/files/1/2423/1151/products/0321-S90-_2016.png?v=1536166128',
  base: 'https://www.luminox.com',
  spec: [
    '44 mm',
    'Carbon Compound case with Black Dial',
    'Black Carbon Compound caseback',
    'Uni-directional rotating bezel with Super-LumiNova dot at 12H',
    'Tempered scratch resistant mineral crystal',
    'Water resistant to 100 meters',
    'Black signature PU strap with brushed stainless steel signature buckle, loop lock, 22mm',
    'Luminox self-powered illumination',
    'Swiss Made'
  ],
  related: [],
  description: 'Description 44 mmCarbon Compound case with Black Dial Black Carbon Compound casebackUni-directional rotating bezel with Super-LumiNova dot at 12H Tempered scratch resistant mineral crystalWater resistant to 100 meters Black signature PU strap with brushed stainless steel signature buckle, loop lock, 22mm More Details Luminox self-powered illuminationSwiss Made'
}
{
  source: 'official',
  lang: 'en',
  brand: 'Luminox',
  brandID: 442,
  url: 'https://luminox.com/products/leatherback-sea-turtle-giant-0337',
  collection: 'SEA SERIES',
  name: 'Leatherback Sea Turtle Giant - 0337',
  reference: '0337',
  retail: '$295.00',
  thumbnail: 'https://cdn.shopify.com/s/files/1/2423/1151/products/0337-90.png?v=1525816420',
  base: 'https://www.luminox.com',
  spec: [
    '44 mm',
    'CARBONOX™/ White fiberglass compound, with crown protection (316L stainless steel, Double-Security Gasket) and Orange Dial',
    'CARBONOX™ caseback',
    'CARBONOX™, unidirectional rotating bezel with Super-Luminova at 12H',
    'Movement Ronda 515, HH6',
    'Battery/Battery life 395 / 50 months',
    'Tempered scratch resistantMineral especially hardened',
    'Water resistant to 100 meters, 10 ATM, 330 feet, individually tested',
    'Black webbing strap with brushed stainless steel signature buckle, loop-lock, 22mm',
    'Height 12.15mm',
    'Weight 45g',
    'Luminox self-powered illumination',
    'Swiss Made'
  ],
  related: [],
  description: 'Description 44 mmCARBONOX™/ White fiberglass compound, with crown protection (316L stainless steel, Double-Security Gasket) and Orange Dial CARBONOX™ caseback CARBONOX™, unidirectional rotating bezel with Super-Luminova at 12H Movement Ronda 515, HH6 Battery/Battery life 395 / 50 months Tempered scratch resistantMineral especially hardenedWater resistant to 100 meters, 10 ATM, 330 feet, individually tested Black webbing strap with brushed stainless steel signature buckle, loop-lock, 22mm Height 12.15mm Weight 45g More Details Luminox self-powered illuminationSwiss Made'
}
{
  source: 'official',
  lang: 'en',
  brand: 'Luminox',
  brandID: 442,
  url: 'https://luminox.com/products/navy-seal-chronograph-3580-series',
  collection: 'SEA SERIES',
  name: 'Navy SEAL Chronograph - 3581',
  reference: '3581',
  retail: '$595.00',
  thumbnail: 'https://cdn.shopify.com/s/files/1/2423/1151/products/3581-90.png?v=1524173979',
  base: 'https://www.luminox.com',
  spec: [
    '45 mm',
    'CARBONOX™ case and',
    '316L stainless steel case back',
    'CARBONOX™, unidirectional rotating bezel, at 12h fitted with a protected colored light tube with sapphire crystal',
    'Tempered scratch resistant mineral crystal',
    'Movement RONDA 5030.D HH1',
    'Water resistant to 200 meters, 20 ATM, 660 feet, individually tested',
    'Black Rubber signature strap with stainless steel brushed signature buckle, 24/22mm',
    'Height: 14.80mm',
    'Weight: 84gr',
    'Luminox self-powered illumination, constant glow for up to 25 years in any light condition',
    'Swiss Made'
  ],
  related: [],
  description: 'Description 45 mm CARBONOX™ case and 316L stainless steel case backCARBONOX™, unidirectional rotating bezel, at 12h fitted with a protected colored light tube with sapphire crystalTempered scratch resistant mineral crystal Movement RONDA 5030.D HH1 Water resistant to 200 meters, 20 ATM, 660 feet, individually tested Black Rubber signature strap with stainless steel brushed signature buckle, 24/22mm Height: 14.80mm Weight: 84gr More Details Luminox self-powered illumination, constant glow for up to 25 years in any light conditionSwiss Made'
}
{
  source: 'official',
  lang: 'en',
  brand: 'Luminox',
  brandID: 442,
  url: 'https://luminox.com/products/navy-seal-chronograph-3581-bo',
  collection: 'SEA SERIES',
  name: 'Navy SEAL Chronograph - 3581.BO',
  reference: '3581.BO',
  retail: '$595.00',
  thumbnail: 'https://cdn.shopify.com/s/files/1/2423/1151/products/3581.BO.F-shot90.png?v=1524586647',
  base: 'https://www.luminox.com',
  spec: [
    '45 mm',
    'CARBONOX™ case and',
    '316L stainless steel case back',
    'CARBONOX™, unidirectional rotating bezel, at 12h fitted with a protected colored light tube with sapphire crystal',
    'Tempered scratch resistant mineral crystal',
    'Movement RONDA 5030.D HH1',
    'Water resistant to 200 meters, 20 ATM, 660 feet, individually tested',
    'Black Rubber signature strap with stainless steel brushed IP black signature buckle, 24/22mm',
    'Height: 14.80mm',
    'Weight: 84gr',
    'Luminox self-powered illumination, constant glow for up to 25 years in any light condition',
    'Swiss Made'
  ],
  related: [],
  description: 'Description 45 mm CARBONOX™ case and 316L stainless steel case backCARBONOX™, unidirectional rotating bezel, at 12h fitted with a protected colored light tube with sapphire crystalTempered scratch resistant mineral crystal Movement RONDA 5030.D HH1 Water resistant to 200 meters, 20 ATM, 660 feet, individually tested Black Rubber signature strap with stainless steel brushed IP black signature buckle, 24/22mm Height: 14.80mm Weight: 84gr More Details Luminox self-powered illumination, constant glow for up to 25 years in any light conditionSwiss Made'
}
{
  source: 'official',
  lang: 'en',
  brand: 'Luminox',
  brandID: 442,
  url: 'https://luminox.com/products/navy-seal-chronograph-3583',
  collection: 'SEA SERIES',
  name: 'Navy SEAL Chronograph - 3583',
  reference: '3583',
  retail: '$545.00',
  thumbnail: 'https://cdn.shopify.com/s/files/1/2423/1151/products/3583-90.png?v=1524588698',
  base: 'https://www.luminox.com',
  spec: [
    '45 mm',
    'CARBONOX™ case and',
    '316L stainless steel case back',
    'CARBONOX™, unidirectional rotating bezel, at 12h fitted with a protected colored light tube with sapphire crystal',
    'Tempered scratch resistant mineral crystal',
    'Movement RONDA 5030.D HH1',
    'Water resistant to 200 meters, 20 ATM, 660 feet, individually tested',
    'Black Rubber signature strap with stainless steel brushed signature buckle, 24/22mm',
    'Height: 14.80mm',
    'Weight: 84gr',
    'Luminox self-powered illumination, constant glow for up to 25 years in any light condition',
    'Swiss Made'
  ],
  related: [],
  description: 'Description 45 mm CARBONOX™ case and 316L stainless steel case backCARBONOX™, unidirectional rotating bezel, at 12h fitted with a protected colored light tube with sapphire crystalTempered scratch resistant mineral crystal Movement RONDA 5030.D HH1 Water resistant to 200 meters, 20 ATM, 660 feet, individually tested Black Rubber signature strap with stainless steel brushed signature buckle, 24/22mm Height: 14.80mm Weight: 84gr More Details Luminox self-powered illumination, constant glow for up to 25 years in any light conditionSwiss Made'
}
{
  source: 'official',
  lang: 'en',
  brand: 'Luminox',
  brandID: 442,
  url: 'https://luminox.com/products/atacama-field-automatic-1902',
  collection: 'LAND SERIES',
  name: 'Atacama Field Automatic\u000b 1902',
  reference: 'Atacama Field Automatic\u000b 1902',
  retail: '$990.00',
  thumbnail: 'https://cdn.shopify.com/s/files/1/2423/1151/products/1902-90.png?v=1525876464',
  base: 'https://www.luminox.com',
  spec: [
    '44mm',
    '316L stainless steel case, with 316L stainless steel fix bezel and 316L stainless steel screw-in caseback',
    'Black dial with orange second hand',
    'Antireflective Sapphire crystal',
    'Movement Swiss Automatic SW220-1 HH5',
    'Water resistant to 200 meters, 20 ATM, 660 feet, individually tested',
    'Stainless Steel bracelet with stainless steel brushed signature buckle, 24mm',
    'Height 14.30mm',
    'Weight 200gr',
    'Luminox self-powered illumination',
    'Swiss Made'
  ],
  related: [],
  description: 'Description 44mm316L stainless steel case, with 316L stainless steel fix bezel and 316L stainless steel screw-in casebackBlack dial with orange second handAntireflective Sapphire crystal Movement Swiss Automatic SW220-1 HH5Water resistant to 200 meters, 20 ATM, 660 feet, individually testedStainless Steel bracelet with stainless steel brushed signature buckle, 24mm Height 14.30mm Weight 200gr More Details Luminox self-powered illuminationSwiss Made'
}
{
  source: 'official',
  lang: 'en',
  brand: 'Luminox',
  brandID: 442,
  url: 'https://luminox.com/products/atacama-field-automatic-1907-nf',
  collection: 'LAND SERIES',
  name: 'Atacama Field Automatic\u000b 1907.NF',
  reference: 'Atacama Field Automatic\u000b 1907.NF',
  retail: '$975.00',
  thumbnail: 'https://cdn.shopify.com/s/files/1/2423/1151/products/1907.NF-90.png?v=1525877605',
  base: 'https://www.luminox.com',
  spec: [
    '44mm',
    '316L stainless steel case, with 316L stainless steel fix bezel and 316L stainless steel screw-in caseback',
    'Black dial with orange second hand',
    'Antireflective Sapphire crystal',
    'Movement Swiss Automatic SW220-1 HH5',
    'Water resistant to 200 meters, 20 ATM, 660 feet, individually tested',
    'Green Webbing strap with stainless steel brushed signature buckle, 24mm',
    'Height 14.30mm',
    'Weight 115gr',
    'Luminox self-powered illumination',
    'Swiss Made'
  ],
  related: [],
  description: 'Description 44mm316L stainless steel case, with 316L stainless steel fix bezel and 316L stainless steel screw-in casebackBlack dial with orange second handAntireflective Sapphire crystal Movement Swiss Automatic SW220-1 HH5Water resistant to 200 meters, 20 ATM, 660 feet, individually testedGreen Webbing strap with stainless steel brushed signature buckle, 24mm Height 14.30mm Weight 115gr More Details Luminox self-powered illuminationSwiss Made'
}
{
  source: 'official',
  lang: 'en',
  brand: 'Luminox',
  brandID: 442,
  url: 'https://luminox.com/products/automatic-sport-timer-0921',
  collection: 'SEA SERIES',
  name: 'Automatic Sport Timer 0921',
  reference: 'Automatic Sport Timer 0921',
  retail: '$1,365.00',
  thumbnail: 'https://cdn.shopify.com/s/files/1/2423/1151/products/0921-fullsize.png?v=1601527020',
  base: 'https://www.luminox.com',
  spec: [
    'Automatic',
    'Size/Diameter: 42mm',
    'Water Resistance: 200 meters, 20 ATM, 660 feet, individually tested',
    'Movement: SW-220',
    'Case: Stainless steel 316L case',
    'Bezel: 316L stainless steel with black ceramic ring, uni-directional turning bezel',
    'Case back: 316L stainless steel, transparent, screw in',
    'Crystal: Sapphire crystal with anti-reflection coating',
    'Crown: 316L stainless steel, screw down, protected crown',
    'Height: 13mm',
    'Weight: 95grams with leather strap',
    'Luminox self-powered illumination',
    'Swiss Made'
  ],
  related: [],
  description: 'Automatic Description Size/Diameter: 42mm Water Resistance: 200 meters, 20 ATM, 660 feet, individually tested Movement: SW-220 Case: Stainless steel 316L case Bezel: 316L stainless steel with black ceramic ring, uni-directional turning bezel Case back: 316L stainless steel, transparent, screw in Crystal: Sapphire crystal with anti-reflection coating Crown: 316L stainless steel, screw down, protected crown Height: 13mm Weight: 95grams with leather strap More Details Luminox self-powered illuminationSwiss Made'
}
{
  source: 'official',
  lang: 'en',
  brand: 'Luminox',
  brandID: 442,
  url: 'https://luminox.com/products/automatic-sport-timer-0924',
  collection: 'SEA SERIES',
  name: 'Automatic Sport Timer 0924',
  reference: 'Automatic Sport Timer 0924',
  retail: '$1,425.00',
  thumbnail: 'https://cdn.shopify.com/s/files/1/2423/1151/products/0924-fullsize.png?v=1601525899',
  base: 'https://www.luminox.com',
  spec: [
    'Automatic',
    'Size/Diameter: 42mm',
    'Water Resistance: 200 meters, 20 ATM, 660 feet, individually tested',
    'Movement: SW-220',
    'Case: Stainless steel 316L case',
    'Bezel: 316L stainless steel with black ceramic ring, uni-directional turning bezel',
    'Case back: 316L stainless steel, transparent, screw in',
    'Crystal: Sapphire crystal with anti-reflection coating',
    'Crown: 316L stainless steel, screw down, protected crown',
    'Height: 13mm',
    'Weight: 185gr with stainless steel bracelet',
    'Luminox self-powered illumination',
    'Swiss Made'
  ],
  related: [],
  description: 'Automatic Description Size/Diameter: 42mm Water Resistance: 200 meters, 20 ATM, 660 feet, individually tested Movement: SW-220 Case: Stainless steel 316L case Bezel: 316L stainless steel with black ceramic ring, uni-directional turning bezel Case back: 316L stainless steel, transparent, screw in Crystal: Sapphire crystal with anti-reflection coating Crown: 316L stainless steel, screw down, protected crown Height: 13mm Weight: 185gr with stainless steel bracelet More Details Luminox self-powered illuminationSwiss Made'
}
{
  source: 'official',
  lang: 'en',
  brand: 'Luminox',
  brandID: 442,
  url: 'https://luminox.com/products/bear-grylls-survival-air-series-3761-gmt-watch',
  collection: 'BEAR GRYLLS',
  name: 'Bear Grylls Survival AIR Series 3761 GMT Watch',
  reference: 'Bear Grylls Survival AIR Series 3761 GMT Watch',
  retail: '$695.00',
  thumbnail: 'https://cdn.shopify.com/s/files/1/2423/1151/products/BG-AIR-STRAP.png?v=1622659145',
  base: 'https://www.luminox.com',
  spec: [
    'Bear Grylls x Luminox:',
    'Luminox’s motto, Every Second Counts, dovetails flawlessly with Grylls’ Never Give Up. There is no better watch to be on Bear Grylls’ wrist than a Luminox.',
    '“It’s incredibly important to me to work alongside world class trusted partners and Luminox have proved that and more. The rugged watch range has been carefully crafted featuring multi-functional design and state of the art materials – set to inspire and encourage the adventurer in everyone – men and women, boys and girls, outdoor novices and experts.” - Bear Grylls',
    'Description:',
    'Origin: Swiss Made',
    'Always Visible: Constant glow for up to 25 years in any light condition',
    'Size/Diameter:  45mm',
    'Water Resistance: 200 meters, 20 ATM, 660 feet, individually tested',
    'Movement: Ronda 515 HF 6',
    'Battery/Battery life: 395 / 50 months',
    'Case: 316L stainless steel',
    'Bezel: CARBONOX™+, bi-directional rotating bezel',
    'Case back: 316L stainless steel, screw in',
    'Crystal: Sapphire with anti-reflection coating',
    'Crown: 316L stainless steel, crown protected',
    'Height: 13mm',
    'GMT Multiple Timezone Feature:',
    'The GMT bezel came about in the 1950s with the rise in commercial air travel. To help PanAm’s transatlantic pilots and their crews keep track of the local and Greenwich Mean Time (which was then used as the international time standard)',
    'For the busy men who are always on the go, a GMT watch is a must-have in your collection. What sets a GMT watch apart from other timepieces is its ability to display two to three different timezones at once. Providing a variety of useful features in a stylish package, these watches are both functional and modern. As such, they’re perfect for all kinds of wearers from the active outdoorsman to the office worker and just about all those in between.'
  ],
  related: [],
  description: 'Bear Grylls x Luminox: Luminox’s motto, Every Second Counts, dovetails flawlessly with Grylls’ Never Give Up. There is no better watch to be on Bear Grylls’ wrist than a Luminox.“It’s incredibly important to me to work alongside world class trusted partners and Luminox have proved that and more. The rugged watch range has been carefully crafted featuring multi-functional design and state of the art materials – set to inspire and encourage the adventurer in everyone – men and women, boys and girls, outdoor novices and experts.” - Bear Grylls Description: Origin: Swiss Made Always Visible: Constant glow for up to 25 years in any light condition Size/Diameter: 45mm Water Resistance: 200 meters, 20 ATM, 660 feet, individually tested Movement: Ronda 515 HF 6 Battery/Battery life: 395 / 50 months Case: 316L stainless steel Bezel: CARBONOX™+, bi-directional rotating bezel Case back: 316L stainless steel, screw in Crystal: Sapphire with anti-reflection coating Crown: 316L stainless steel, crown protected Height: 13mm GMT Multiple Timezone Feature: The GMT bezel came about in the 1950s with the rise in commercial air travel. To help PanAm’s transatlantic pilots and their crews keep track of the local and Greenwich Mean Time (which was then used as the international time standard) For the busy men who are always on the go, a GMT watch is a must-have in your collection. What sets a GMT watch apart from other timepieces is its ability to display two to three different timezones at once. Providing a variety of useful features in a stylish package, these watches are both functional and modern. As such, they’re perfect for all kinds of wearers from the active outdoorsman to the office worker and just about all those in between.'
}
{
  source: 'official',
  lang: 'en',
  brand: 'Luminox',
  brandID: 442,
  url: 'https://luminox.com/products/bear-grylls-survival-air-series-3762-gmt-watch',
  collection: 'BEAR GRYLLS',
  name: 'Bear Grylls Survival AIR Series 3762 GMT Watch',
  reference: 'Bear Grylls Survival AIR Series 3762 GMT Watch',
  retail: '$795.00',
  thumbnail: 'https://cdn.shopify.com/s/files/1/2423/1151/products/BG-AIR-SILVER-FRONT.png?v=1622658994',
  base: 'https://www.luminox.com',
  spec: [
    'Bear Grylls x Luminox:',
    'Luminox’s motto, Every Second Counts, dovetails flawlessly with Grylls’ Never Give Up. There is no better watch to be on Bear Grylls’ wrist than a Luminox.',
    '“It’s incredibly important to me to work alongside world class trusted partners and Luminox have proved that and more. The rugged watch range has been carefully crafted featuring multi-functional design and state of the art materials – set to inspire and encourage the adventurer in everyone – men and women, boys and girls, outdoor novices and experts.” - Bear Grylls',
    'Description:',
    'Origin: Swiss Made',
    'Always Visible: Constant glow for up to 25 years in any light condition',
    'Size/Diameter:  45mm',
    'Water Resistance: 200 meters, 20 ATM, 660 feet, individually tested',
    'Movement: Ronda 515 HF 6',
    'Battery/Battery life: 395 / 50 months',
    'Case: 316L stainless steel',
    'Bezel: CARBONOX™+, bi-directional rotating bezel',
    'Case back: 316L stainless steel, screw in',
    'Crystal: Sapphire with anti-reflection coating',
    'Crown: 316L stainless steel, crown protected',
    'Height: 13mm',
    'GMT Multiple Timezone Feature:',
    'The GMT bezel came about in the 1950s with the rise in commercial air travel. To help PanAm’s transatlantic pilots and their crews keep track of the local and Greenwich Mean Time (which was then used as the international time standard)',
    'For the busy men who are always on the go, a GMT watch is a must-have in your collection. What sets a GMT watch apart from other timepieces is its ability to display two to three different timezones at once. Providing a variety of useful features in a stylish package, these watches are both functional and modern. As such, they’re perfect for all kinds of wearers from the active outdoorsman to the office worker and just about all those in between.'
  ],
  related: [],
  description: 'Bear Grylls x Luminox: Luminox’s motto, Every Second Counts, dovetails flawlessly with Grylls’ Never Give Up. There is no better watch to be on Bear Grylls’ wrist than a Luminox.“It’s incredibly important to me to work alongside world class trusted partners and Luminox have proved that and more. The rugged watch range has been carefully crafted featuring multi-functional design and state of the art materials – set to inspire and encourage the adventurer in everyone – men and women, boys and girls, outdoor novices and experts.” - Bear Grylls Description: Origin: Swiss Made Always Visible: Constant glow for up to 25 years in any light condition Size/Diameter: 45mm Water Resistance: 200 meters, 20 ATM, 660 feet, individually tested Movement: Ronda 515 HF 6 Battery/Battery life: 395 / 50 months Case: 316L stainless steel Bezel: CARBONOX™+, bi-directional rotating bezel Case back: 316L stainless steel, screw in Crystal: Sapphire with anti-reflection coating Crown: 316L stainless steel, crown protected Height: 13mm GMT Multiple Timezone Feature: The GMT bezel came about in the 1950s with the rise in commercial air travel. To help PanAm’s transatlantic pilots and their crews keep track of the local and Greenwich Mean Time (which was then used as the international time standard) For the busy men who are always on the go, a GMT watch is a must-have in your collection. What sets a GMT watch apart from other timepieces is its ability to display two to three different timezones at once. Providing a variety of useful features in a stylish package, these watches are both functional and modern. As such, they’re perfect for all kinds of wearers from the active outdoorsman to the office worker and just about all those in between.'
}
{
  source: 'official',
  lang: 'en',
  brand: 'Luminox',
  brandID: 442,
  url: 'https://luminox.com/products/revo-x-luminox-giftset-navy-seal-watch-sunglasses',
  collection: '',
  name: '',
  reference: null,
  retail: '',
  thumbnail: undefined,
  base: 'https://www.luminox.com',
  spec: [],
  related: [],
  description: '',
  code: 'UNKNOWN ERROR'
}
{
  source: 'official',
  lang: 'en',
  brand: 'Luminox',
  brandID: 442,
  url: 'https://luminox.com/products/ice-sar-arctic-1001',
  collection: 'LAND SERIES',
  name: 'ICE-SAR ARCTIC - 1001',
  reference: 'SAR ARCTIC',
  retail: '$545.00',
  thumbnail: 'https://cdn.shopify.com/s/files/1/2423/1151/products/1001-90.png?v=1534351409',
  base: 'https://www.luminox.com',
  spec: [
    'Luminox is the Official Partner of ICE-SAR',
    '46 mm',
    'CARBONOX™ case with crown protection and 316L stainless steel case back',
    'CARBONOX™, ufixed bezel, at 12h fitted with a protected orange light tube as well as hour and Minutes hands.',
    '1-12H green light tubes.',
    '316L stainless steel, double O-ring crown',
    'Sapphire with anti-reflection coating',
    'Movement RONDA 515 HF 6',
    'Water resistant to 200 meters, 20 ATM, 660 feet, individually tested',
    'Black genuine rubber signature strap with black textile inlay, black stitching and CARBONOX™ signature buckle, 24mm',
    'Height: 13mm',
    'Weight: 72gr',
    'Luminox self-powered illumination, constant glow for up to 25 years in any light condition',
    'Swiss Made'
  ],
  related: [],
  description: 'Description Luminox is the Official Partner of ICE-SAR 46 mmCARBONOX™ case with crown protection and 316L stainless steel case backCARBONOX™, ufixed bezel, at 12h fitted with a protected orange light tube as well as hour and Minutes hands. 1-12H green light tubes. 316L stainless steel, double O-ring crown Sapphire with anti-reflection coating Movement RONDA 515 HF 6 Water resistant to 200 meters, 20 ATM, 660 feet, individually tested Black genuine rubber signature strap with black textile inlay, black stitching and CARBONOX™ signature buckle, 24mm Height: 13mm Weight: 72gr More Details Luminox self-powered illumination, constant glow for up to 25 years in any light conditionSwiss Made'
}
{
  source: 'official',
  lang: 'en',
  brand: 'Luminox',
  brandID: 442,
  url: 'https://luminox.com/products/ice-sar-arctic-1002',
  collection: 'LAND SERIES',
  name: 'ICE-SAR ARCTIC - 1002',
  reference: 'SAR ARCTIC',
  retail: '$545.00',
  thumbnail: 'https://cdn.shopify.com/s/files/1/2423/1151/products/1002-90.png?v=1545148503',
  base: 'https://www.luminox.com',
  spec: [
    'Luminox is the Official Partner of ICE-SAR',
    '46 mm',
    'CARBONOX™ case, black dial with crown protection and 316L stainless steel case back',
    'CARBONOX™, fixed bezel, at 12h fitted with a protected orange light tube as well as hour and Minutes hands.',
    '1-12H green light tubes.',
    '316L stainless steel, double O-ring crown',
    'Sapphire with anti-reflection coating',
    'Movement RONDA 515 HF 6',
    'Water resistant to 200 meters, 20 ATM, 660 feet, individually tested',
    'Black genuine rubber signature strap with red stitching and CARBONOX™ signature buckle, 24mm',
    'Height: 13mm',
    'Weight: 72gr',
    'Luminox self-powered illumination, constant glow for up to 25 years in any light condition',
    'Swiss Made'
  ],
  related: [],
  description: 'Description Luminox is the Official Partner of ICE-SAR 46 mmCARBONOX™ case, black dial with crown protection and 316L stainless steel case backCARBONOX™, fixed bezel, at 12h fitted with a protected orange light tube as well as hour and Minutes hands. 1-12H green light tubes. 316L stainless steel, double O-ring crown Sapphire with anti-reflection coating Movement RONDA 515 HF 6 Water resistant to 200 meters, 20 ATM, 660 feet, individually tested Black genuine rubber signature strap with red stitching and CARBONOX™ signature buckle, 24mm Height: 13mm Weight: 72gr More Details Luminox self-powered illumination, constant glow for up to 25 years in any light conditionSwiss Made'
}
{
  source: 'official',
  lang: 'en',
  brand: 'Luminox',
  brandID: 442,
  url: 'https://luminox.com/products/ice-sar-arctic-1003',
  collection: 'LAND SERIES',
  name: 'ICE-SAR ARCTIC - 1003',
  reference: 'SAR ARCTIC',
  retail: '$545.00',
  thumbnail: 'https://cdn.shopify.com/s/files/1/2423/1151/products/1003-XL-S90.png?v=1608167090',
  base: 'https://www.luminox.com',
  spec: [
    'Luminox is the Official Partner of ICE-SAR',
    '46 mm',
    'CARBONOX™ case with crown protection and 316L stainless steel case back',
    'CARBONOX™, ufixed bezel, at 12h fitted with a protected orange light tube as well as hour and Minutes hands.',
    '1-12H green light tubes.',
    '316L stainless steel, double O-ring crown',
    'Sapphire with anti-reflection coating',
    'Movement RONDA 515 HF 6',
    'Water resistant to 200 meters, 20 ATM, 660 feet, individually tested',
    'Black genuine rubber signature strap with black textile inlay, black stitching and CARBONOX™ signature buckle, 24mm',
    'Height: 13mm',
    'Weight: 72gr',
    'Luminox self-powered illumination, constant glow for up to 25 years in any light condition',
    'Swiss Made'
  ],
  related: [],
  description: 'Description Luminox is the Official Partner of ICE-SAR 46 mmCARBONOX™ case with crown protection and 316L stainless steel case backCARBONOX™, ufixed bezel, at 12h fitted with a protected orange light tube as well as hour and Minutes hands. 1-12H green light tubes. 316L stainless steel, double O-ring crown Sapphire with anti-reflection coating Movement RONDA 515 HF 6 Water resistant to 200 meters, 20 ATM, 660 feet, individually tested Black genuine rubber signature strap with black textile inlay, black stitching and CARBONOX™ signature buckle, 24mm Height: 13mm Weight: 72gr More Details Luminox self-powered illumination, constant glow for up to 25 years in any light conditionSwiss Made'
}
{
  source: 'official',
  lang: 'en',
  brand: 'Luminox',
  brandID: 442,
  url: 'https://luminox.com/products/ice-sar-arctic-1007',
  collection: 'LAND SERIES',
  name: 'ICE-SAR ARCTIC - 1007',
  reference: 'SAR ARCTIC',
  retail: '$495.00',
  thumbnail: 'https://cdn.shopify.com/s/files/1/2423/1151/products/1007-90.png?v=1536259859',
  base: 'https://www.luminox.com',
  spec: [
    'Luminox is the Official Partner of ICE-SAR',
    '46 mm',
    'CARBONOX™ case with crown protection and 316L stainless steel case back',
    'CARBONOX™, ufixed bezel, at 12h fitted with a protected orange light tube as well as hour and Minutes hands.',
    '1-12H green light tubes.',
    '316L stainless steel, double O-ring crown',
    'Sapphire with anti-reflection coating',
    'Movement RONDA 515 HF 6',
    'Water resistant to 200 meters, 20 ATM, 660 feet, individually tested',
    'Black genuine rubber signature strap with white stitching and CARBONOX™ signature buckle, 24mm',
    'Height: 13mm',
    'Weight: 72gr',
    'Luminox self-powered illumination, constant glow for up to 25 years in any light condition',
    'Swiss Made'
  ],
  related: [],
  description: 'Description Luminox is the Official Partner of ICE-SAR 46 mmCARBONOX™ case with crown protection and 316L stainless steel case backCARBONOX™, ufixed bezel, at 12h fitted with a protected orange light tube as well as hour and Minutes hands. 1-12H green light tubes. 316L stainless steel, double O-ring crown Sapphire with anti-reflection coating Movement RONDA 515 HF 6 Water resistant to 200 meters, 20 ATM, 660 feet, individually tested Black genuine rubber signature strap with white stitching and CARBONOX™ signature buckle, 24mm Height: 13mm Weight: 72gr More Details Luminox self-powered illumination, constant glow for up to 25 years in any light conditionSwiss Made'
}
{
  source: 'official',
  lang: 'en',
  brand: 'Luminox',
  brandID: 442,
  url: 'https://luminox.com/products/copy-of-ice-sar-arctic-1003',
  collection: 'LAND SERIES',
  name: 'ICE-SAR ARCTIC - 1003.ICE',
  reference: 'SAR ARCTIC',
  retail: '$545.00',
  thumbnail: 'https://cdn.shopify.com/s/files/1/2423/1151/products/LUM_ICE_FACE.png?v=1590523646',
  base: 'https://www.luminox.com',
  spec: [
    'Description',
    'Luminox is the Official Partner of ICE-SAR',
    '46 mm',
    'CARBONOX™ case with crown protection and 316L stainless steel case back',
    'CARBONOX™, ufixed bezel',
    'Constant Glow for up to 25 years in any condition.',
    '316L stainless steel, double O-ring crown',
    'Sapphire with anti-reflection coating',
    'Movement RONDA 515 HF 6',
    'Water resistant to 200 meters, 20 ATM, 660 feet, individually tested',
    'Blue genuine rubber signature strap with blue textile inlay, blue stitching and CARBONOX™ signature buckle, 24mm',
    'Height: 13mm',
    'Weight: 72gr',
    'Luminox self-powered illumination, constant glow for up to 25 years in any light condition',
    'Swiss Made'
  ],
  related: [],
  description: 'Description Luminox is the Official Partner of ICE-SAR 46 mmCARBONOX™ case with crown protection and 316L stainless steel case backCARBONOX™, ufixed bezel Constant Glow for up to 25 years in any condition. 316L stainless steel, double O-ring crown Sapphire with anti-reflection coating Movement RONDA 515 HF 6 Water resistant to 200 meters, 20 ATM, 660 feet, individually tested Blue genuine rubber signature strap with blue textile inlay, blue stitching and CARBONOX™ signature buckle, 24mm Height: 13mm Weight: 72gr More Details Luminox self-powered illumination, constant glow for up to 25 years in any light conditionSwiss Made'
}
{
  source: 'official',
  lang: 'en',
  brand: 'Luminox',
  brandID: 442,
  url: 'https://luminox.com/products/navy-seal-3601',
  collection: 'SEA SERIES',
  name: 'Navy SEAL Magnifying Glass - 3601',
  reference: '3601',
  retail: '$545.00',
  thumbnail: 'https://cdn.shopify.com/s/files/1/2423/1151/products/3601face.png?v=1567799040',
  base: 'https://www.luminox.com',
  spec: [
    'Origin: Swiss Made',
    'Always Visible: Constant glow for up to 25 years',
    'Size of case (diameter): 45 mm',
    'Function: Time Date',
    'Water Resistance: 200 meters, 20 ATM, 660 feet',
    'Movement: Swiss Quartz',
    'Case material: CARBONOX™',
    'Bezel: Uni-directional rotating',
    'Case Back: 316L Stainless steel screw in',
    'Crystal glass material: Sapphire crystal, anti-reflective coating',
    'Crown: Double security gasket, crown protected',
    'Strap / bracelet: Genuine rubber',
    'Width of Strap: 24 mm',
    'Case Height: 14 mm',
    'Weight: 73 g'
  ],
  related: [],
  description: 'Description Origin: Swiss Made Always Visible: Constant glow for up to 25 years Size of case (diameter): 45 mm Function: Time Date Water Resistance: 200 meters, 20 ATM, 660 feet Movement: Swiss Quartz Case material: CARBONOX™ Bezel: Uni-directional rotating Case Back: 316L Stainless steel screw in Crystal glass material: Sapphire crystal, anti-reflective coating Crown: Double security gasket, crown protected Strap / bracelet: Genuine rubber Width of Strap: 24 mm Case Height: 14 mm Weight: 73 g More Details Luminox self-powered illuminationSwiss Made'
}
{
  source: 'official',
  lang: 'en',
  brand: 'Luminox',
  brandID: 442,
  url: 'https://luminox.com/products/navy-seal-3603',
  collection: 'SEA SERIES',
  name: 'Navy SEAL Magnifying Glass - 3603',
  reference: '3603',
  retail: '$545.00',
  thumbnail: 'https://cdn.shopify.com/s/files/1/2423/1151/products/3603face.png?v=1567799098',
  base: 'https://www.luminox.com',
  spec: [
    'Origin: Swiss Made',
    'Always Visible: Constant glow for up to 25 years',
    'Size of case (diameter): 45 mm',
    'Function: Time Date',
    'Water Resistance: 200 meters, 20 ATM, 660 feet',
    'Movement: Swiss Quartz',
    'Case material: CARBONOX™',
    'Bezel: Uni-directional rotating',
    'Case Back: 316L Stainless steel screw in',
    'Crystal glass material: Sapphire crystal, anti-reflective coating',
    'Crown: Double security gasket, crown protected',
    'Strap / bracelet: Genuine rubber',
    'Width of Strap: 24 mm',
    'Case Height: 14 mm',
    'Weight: 75 g'
  ],
  related: [],
  description: 'Description Origin: Swiss Made Always Visible: Constant glow for up to 25 years Size of case (diameter): 45 mm Function: Time Date Water Resistance: 200 meters, 20 ATM, 660 feet Movement: Swiss Quartz Case material: CARBONOX™ Bezel: Uni-directional rotating Case Back: 316L Stainless steel screw in Crystal glass material: Sapphire crystal, anti-reflective coating Crown: Double security gasket, crown protected Strap / bracelet: Genuine rubber Width of Strap: 24 mm Case Height: 14 mm Weight: 75 g More Details Luminox self-powered illuminationSwiss Made'
}
{
  source: 'official',
  lang: 'en',
  brand: 'Luminox',
  brandID: 442,
  url: 'https://luminox.com/products/navy-seal-3617-set',
  collection: 'SEA SERIES',
  name: 'Navy SEAL Date Magnifier - 3617.SET',
  reference: '3617.SET',
  retail: '$595.00',
  thumbnail: 'https://cdn.shopify.com/s/files/1/2423/1151/products/3617_box.png?v=1576609478',
  base: 'https://www.luminox.com',
  spec: [
    'Origin: Swiss Made',
    'Always Visible: Constant glow for up to 25 years',
    'Size of case (diameter): 45 mm',
    'Function: Time Date',
    'Water Resistance: 200 meters, 20 ATM, 660 feet',
    'Movement: Swiss Quartz',
    'Case material: CARBONOX™',
    'Bezel: Uni-directional rotating',
    'Case Back: 316L Stainless steel screw in',
    'Crystal glass material: Sapphire crystal, anti-reflective coating',
    'Crown: Double security gasket, crown protected',
    'Strap / bracelet: Genuine rubber',
    'Width of Strap: 24 mm',
    'Case Height: 14 mm',
    'Weight: 73 g'
  ],
  related: [],
  description: 'Description Origin: Swiss Made Always Visible: Constant glow for up to 25 years Size of case (diameter): 45 mm Function: Time Date Water Resistance: 200 meters, 20 ATM, 660 feet Movement: Swiss Quartz Case material: CARBONOX™ Bezel: Uni-directional rotating Case Back: 316L Stainless steel screw in Crystal glass material: Sapphire crystal, anti-reflective coating Crown: Double security gasket, crown protected Strap / bracelet: Genuine rubber Width of Strap: 24 mm Case Height: 14 mm Weight: 73 g More Details Luminox self-powered illuminationSwiss Made'
}
{
  source: 'official',
  lang: 'en',
  brand: 'Luminox',
  brandID: 442,
  url: 'https://luminox.com/products/copy-of-commando-frogman-3301',
  collection: 'SEA SERIES',
  name: 'Commando Frogman - 3301',
  reference: '3301',
  retail: '$595.00',
  thumbnail: 'https://cdn.shopify.com/s/files/1/2423/1151/products/FACE_8a288fb6-8c4d-4b28-888b-b09e2a386a83.png?v=1573575148',
  base: 'https://www.luminox.com',
  spec: [
    '46 mm',
    'CARBONOX™ Carbon Compound case',
    '316L Stainless Steel screw-in case back',
    'Carbon Compound unidirectional turning bezel w/ aluminum ring',
    'Sapphire Crystal w/ anti-reflective coating',
    'Water resistant to 200 meters',
    'Black Genuine Rubber strap with stainless steel signature buckle, 24mm',
    'Luminox self-powered illumination',
    'Swiss Made'
  ],
  related: [],
  description: 'Description 46 mmCARBONOX™ Carbon Compound case316L Stainless Steel screw-in case backCarbon Compound unidirectional turning bezel w/ aluminum ringSapphire Crystal w/ anti-reflective coatingWater resistant to 200 metersBlack Genuine Rubber strap with stainless steel signature buckle, 24mm More Details Luminox self-powered illuminationSwiss Made'
}
{
  source: 'official',
  lang: 'en',
  brand: 'Luminox',
  brandID: 442,
  url: 'https://luminox.com/products/bear-grylls-survival-master-series-3749',
  collection: 'BEAR GRYLLS',
  name: 'Bear Grylls Survival Chronograph MASTER Series - 3749',
  reference: '3749',
  retail: '$975.00',
  thumbnail: 'https://cdn.shopify.com/s/files/1/2423/1151/products/3749_FACE.png?v=1590085540',
  base: 'https://www.luminox.com',
  spec: [
    'Origin: Swiss Made',
    'Always Visible: Constant glow for up to 25 years',
    'Size of case (diameter): 45 mm',
    'Water Resistance: 300 meters, 30 ATM, 1000 feet',
    'Movement: RONDA 5030.D',
    'Case material: CARBONOX™+',
    'Bezel: CARBONOX™+, uni-directional turning, count-up and compass',
    'Case Back: 316L Stainless steel, screw in',
    'Crystal: Sapphire crystal, anti-reflective coating',
    'Crown: 316L Stainless Steel, screw on',
    'Strap / bracelet: Orange rubber EPDM strap, stainless steel buckle',
    'Width of Strap: 24 mm',
    'Case Height: 14 mm',
    'Weight: 98 g'
  ],
  related: [],
  description: 'Description Luminox x Bear Grylls Official Watch Collection Origin: Swiss Made Always Visible: Constant glow for up to 25 years Size of case (diameter): 45 mm Water Resistance: 300 meters, 30 ATM, 1000 feet Movement: RONDA 5030.D Case material: CARBONOX™+ Bezel: CARBONOX™+, uni-directional turning, count-up and compass Case Back: 316L Stainless steel, screw in Crystal: Sapphire crystal, anti-reflective coating Crown: 316L Stainless Steel, screw on Strap / bracelet: Orange rubber EPDM strap, stainless steel buckle Width of Strap: 24 mm Case Height: 14 mm Weight: 98 g More Details Luminox self-powered illumination, constant glow for up to 25 years in any light conditionSwiss Made'
}
{
  source: 'official',
  lang: 'en',
  brand: 'Luminox',
  brandID: 442,
  url: 'https://luminox.com/products/bear-grylls-survival-master-series-3741',
  collection: 'BEAR GRYLLS',
  name: 'Bear Grylls Survival Chronograph MASTER Series - 3741',
  reference: '3741',
  retail: '$975.00',
  thumbnail: 'https://cdn.shopify.com/s/files/1/2423/1151/products/3741_FACE.png?v=1590085307',
  base: 'https://www.luminox.com',
  spec: [
    'Origin: Swiss Made',
    'Always Visible: Constant glow for up to 25 years',
    'Size of case (diameter): 45 mm',
    'Water Resistance: 300 meters, 30 ATM, 1000 feet',
    'Movement: RONDA 5030.D',
    'Case material: CARBONOX™+',
    'Bezel: CARBONOX™+, uni-directional turning, count-up and compass',
    'Case Back: 316L Stainless steel, screw in',
    'Crystal: Sapphire crystal, anti-reflective coating',
    'Crown: 316L Stainless Steel, screw on',
    'Strap / bracelet: Dark Grey rubber EPDM strap, stainless steel buckle',
    'Accessory: Compass Loop',
    'Width of Strap: 24 mm',
    'Case Height: 14 mm',
    'Weight: 98 g'
  ],
  related: [],
  description: 'Description Luminox x Bear Grylls Official Watch Collection Origin: Swiss Made Always Visible: Constant glow for up to 25 years Size of case (diameter): 45 mm Water Resistance: 300 meters, 30 ATM, 1000 feet Movement: RONDA 5030.D Case material: CARBONOX™+ Bezel: CARBONOX™+, uni-directional turning, count-up and compass Case Back: 316L Stainless steel, screw in Crystal: Sapphire crystal, anti-reflective coating Crown: 316L Stainless Steel, screw on Strap / bracelet: Dark Grey rubber EPDM strap, stainless steel buckle Accessory: Compass Loop Width of Strap: 24 mm Case Height: 14 mm Weight: 98 g More Details Luminox self-powered illumination, constant glow for up to 25 years in any light conditionSwiss Made'
}
{
  source: 'official',
  lang: 'en',
  brand: 'Luminox',
  brandID: 442,
  url: 'https://luminox.com/products/bear-grylls-survival-chronograph-master-series-3745',
  collection: 'BEAR GRYLLS',
  name: 'Bear Grylls Survival Chronograph MASTER Series - 3745',
  reference: '3745',
  retail: '$975.00',
  thumbnail: 'https://cdn.shopify.com/s/files/1/2423/1151/products/BEAR_GRYLLS_x_LUMINOX_Master_Series_Survival_Watch_Black_Yellow_Dial-removebg.png?v=1622658702',
  base: 'https://www.luminox.com',
  spec: [
    'Origin: Swiss Made',
    'Always Visible: Constant glow for up to 25 years',
    'Size of case (diameter): 45 mm',
    'Water Resistance: 300 meters, 30 ATM, 1000 feet',
    'Movement: RONDA 5030.D',
    'Case material: CARBONOX™+',
    'Bezel: CARBONOX™+, uni-directional turning, count-up and compass',
    'Case Back: 316L Stainless steel, screw in',
    'Crystal: Sapphire crystal, anti-reflective coating',
    'Crown: 316L Stainless Steel, screw on',
    'Strap / bracelet: Dark Grey rubber EPDM strap, stainless steel buckle',
    'Accessory: Compass Loop',
    'Width of Strap: 24 mm',
    'Case Height: 14 mm',
    'Weight: 98 g'
  ],
  related: [],
  description: 'Description The Bear Grylls Master Outdoor watch is a chronograph with an additional date display. The case is made of CARBONOX ™ + and the SOS Morse Code is applied to the dial as a small reminder for extreme situations. The chronograph pushers are made of solid stainless steel , while an orange rubber ring on the crown ensures optimal grip. This survival watch is water resistant to 300 meters and equipped with a sapphire crystal . The watch strap is made of black rubber . There is also a small compass on the strap that can be easily pulled on and off. More Details Luminox x Bear Grylls Official Watch Collection Origin: Swiss Made Always Visible: Constant glow for up to 25 years Size of case (diameter): 45 mm Water Resistance: 300 meters, 30 ATM, 1000 feet Movement: RONDA 5030.D Case material: CARBONOX™+ Bezel: CARBONOX™+, uni-directional turning, count-up and compass Case Back: 316L Stainless steel, screw in Crystal: Sapphire crystal, anti-reflective coating Crown: 316L Stainless Steel, screw on Strap / bracelet: Dark Grey rubber EPDM strap, stainless steel buckle Accessory: Compass Loop Width of Strap: 24 mm Case Height: 14 mm Weight: 98 g'
}
{
  source: 'official',
  lang: 'en',
  brand: 'Luminox',
  brandID: 442,
  url: 'https://luminox.com/products/bear-grylls-survival-sea-series-3723',
  collection: 'BEAR GRYLLS',
  name: 'Bear Grylls Survival SEA Series - 3723',
  reference: '3723',
  retail: '$495.00',
  thumbnail: 'https://cdn.shopify.com/s/files/1/2423/1151/products/3723.png?v=1590085825',
  base: 'https://www.luminox.com',
  spec: [
    'Origin: Swiss Made',
    'Always Visible: Constant glow for up to 25 years',
    'Size of case (diameter): 42 mm',
    'Water Resistance: 200 meters, 20 ATM, 660 feet',
    'Movement: RONDA 515 HF 6',
    'Battery Life: 395 / 50 months',
    'Case material: CARBONOX™ with crown protection',
    'Bezel: CARBONOX™, uni-directional turning',
    'Case Back: 316L Stainless steel, screw in',
    'Crystal: Hardened Mineral',
    'Crown: 316L Stainless Steel, screw on',
    'Strap / bracelet: Black genuine rubber w/ stainless steel buckle',
    'Width of Strap: 24 mm',
    'Case Height: 14 mm',
    'Weight: 76 g'
  ],
  related: [],
  description: 'Description Luminox x Bear Grylls Official Watch Collection Origin: Swiss Made Always Visible: Constant glow for up to 25 years Size of case (diameter): 42 mm Water Resistance: 200 meters, 20 ATM, 660 feet Movement: RONDA 515 HF 6 Battery Life: 395 / 50 months Case material: CARBONOX™ with crown protection Bezel: CARBONOX™, uni-directional turning Case Back: 316L Stainless steel, screw in Crystal: Hardened Mineral Crown: 316L Stainless Steel, screw on Strap / bracelet: Black genuine rubber w/ stainless steel buckle Width of Strap: 24 mm Case Height: 14 mm Weight: 76 g More Details Luminox self-powered illumination, constant glow for up to 25 years in any light conditionSwiss Made'
}
{
  source: 'official',
  lang: 'en',
  brand: 'Luminox',
  brandID: 442,
  url: 'https://luminox.com/products/bear-grylls-survival-sea-series-3729',
  collection: 'BEAR GRYLLS',
  name: 'Bear Grylls Survival SEA Series - 3729',
  reference: '3729',
  retail: '$495.00',
  thumbnail: 'https://cdn.shopify.com/s/files/1/2423/1151/products/3729_FACE.png?v=1590085618',
  base: 'https://www.luminox.com',
  spec: [
    'Origin: Swiss Made',
    'Always Visible: Constant glow for up to 25 years',
    'Size of case (diameter): 42 mm',
    'Water Resistance: 200 meters, 20 ATM, 660 feet',
    'Movement: RONDA 515 HF 6',
    'Battery Life: 395 / 50 months',
    'Case material: CARBONOX™ with crown protection',
    'Bezel: CARBONOX™, uni-directional turning',
    'Case Back: 316L Stainless steel, screw in',
    'Crystal: Hardened Mineral',
    'Crown: 316L Stainless Steel, screw on',
    'Strap / bracelet: Black genuine rubber w/ stainless steel buckle',
    'Width of Strap: 24 mm',
    'Case Height: 14 mm',
    'Weight: 76 g'
  ],
  related: [],
  description: 'Description Luminox x Bear Grylls Official Watch Collection Origin: Swiss Made Always Visible: Constant glow for up to 25 years Size of case (diameter): 42 mm Water Resistance: 200 meters, 20 ATM, 660 feet Movement: RONDA 515 HF 6 Battery Life: 395 / 50 months Case material: CARBONOX™ with crown protection Bezel: CARBONOX™, uni-directional turning Case Back: 316L Stainless steel, screw in Crystal: Hardened Mineral Crown: 316L Stainless Steel, screw on Strap / bracelet: Black genuine rubber w/ stainless steel buckle Width of Strap: 24 mm Case Height: 14 mm Weight: 76 g More Details Luminox self-powered illumination, constant glow for up to 25 years in any light conditionSwiss Made'
}
{
  source: 'official',
  lang: 'en',
  brand: 'Luminox',
  brandID: 442,
  url: 'https://luminox.com/products/bear-grylls-survival-land-series-3782',
  collection: 'BEAR GRYLLS',
  name: 'Bear Grylls Survival LAND Series - 3782',
  reference: '3782',
  retail: '$655.00',
  thumbnail: 'https://cdn.shopify.com/s/files/1/2423/1151/products/3782_FACE.png?v=1590085131',
  base: 'https://www.luminox.com',
  spec: [
    'Origin: Swiss Made',
    'Always Visible: Constant glow for up to 25 years',
    'Size of case (diameter): 45 mm',
    'Water Resistance: 200 meters, 20 ATM, 660 feet',
    'Movement: Chronograph, RONDA 5021.D',
    'Battery / Battery Life: 395 / 50 months',
    'Case material: CARBONOX™',
    'Bezel: CARBONOX™, fixed bezel',
    'Case Back: 316L Stainless steel, screw in',
    'Crystal: Hardened Mineral',
    'Crown: 316L Stainless Steel, screw on',
    'Strap / bracelet: Black Genuine rubber strap w/ stainless steel buckle',
    'Accessory: Compass Loop',
    'Width of Strap: 24mm',
    'Case Height: 14mm',
    'Weight: 89g'
  ],
  related: [],
  description: 'Description Luminox x Bear Grylls Official Watch Collection Origin: Swiss Made Always Visible: Constant glow for up to 25 years Size of case (diameter): 45 mm Water Resistance: 200 meters, 20 ATM, 660 feet Movement: Chronograph, RONDA 5021.D Battery / Battery Life: 395 / 50 months Case material: CARBONOX™ Bezel: CARBONOX™, fixed bezel Case Back: 316L Stainless steel, screw in Crystal: Hardened Mineral Crown: 316L Stainless Steel, screw on Strap / bracelet: Black Genuine rubber strap w/ stainless steel buckle Accessory: Compass Loop Width of Strap: 24mm Case Height: 14mm Weight: 89g More Details Luminox self-powered illumination, constant glow for up to 25 years in any light conditionSwiss Made'
}
{
  source: 'official',
  lang: 'en',
  brand: 'Luminox',
  brandID: 442,
  url: 'https://luminox.com/products/bear-grylls-survival-land-series-3798',
  collection: 'BEAR GRYLLS',
  name: 'Bear Grylls Survival LAND Series - 3798',
  reference: '3798',
  retail: '$695.00',
  thumbnail: 'https://cdn.shopify.com/s/files/1/2423/1151/products/3798_FACE.png?v=1590085072',
  base: 'https://www.luminox.com',
  spec: [
    'Origin: Swiss Made',
    'Always Visible: Constant glow for up to 25 years',
    'Size of case (diameter): 45 mm',
    'Water Resistance: 200 meters, 20 ATM, 660 feet',
    'Movement: Chronograph, RONDA 5021.D',
    'Battery / Battery Life: 395 / 50 months',
    'Case material: CARBONOX™',
    'Bezel: CARBONOX™, fixed bezel',
    'Case Back: 316L Stainless steel, screw in',
    'Crystal: Hardened Mineral',
    'Crown: 316L Stainless Steel, screw on',
    'Strap / bracelet: Black paracord strap w/ stainless steel buckle',
    'Width of Strap: 24mm',
    'Case Height: 14mm',
    'Weight: 89g'
  ],
  related: [],
  description: 'Description Luminox x Bear Grylls Official Watch Collection Origin: Swiss Made Always Visible: Constant glow for up to 25 years Size of case (diameter): 45 mm Water Resistance: 200 meters, 20 ATM, 660 feet Movement: Chronograph, RONDA 5021.D Battery / Battery Life: 395 / 50 months Case material: CARBONOX™ Bezel: CARBONOX™, fixed bezel Case Back: 316L Stainless steel, screw in Crystal: Hardened Mineral Crown: 316L Stainless Steel, screw on Strap / bracelet: Black paracord strap w/ stainless steel buckle Width of Strap: 24mm Case Height: 14mm Weight: 89g More Details Luminox self-powered illumination, constant glow for up to 25 years in any light conditionSwiss Made'
}
{
  source: 'official',
  lang: 'en',
  brand: 'Luminox',
  brandID: 442,
  url: 'https://luminox.com/products/pacific-diver-3123',
  collection: 'SEA SERIES',
  name: 'Pacific Diver - 3123',
  reference: '3123',
  retail: '$695.00',
  thumbnail: 'https://cdn.shopify.com/s/files/1/2423/1151/products/3123_FRONT.png?v=1591388593',
  base: 'https://www.luminox.com',
  spec: [
    '44mm Diameter',
    'Origin - Swiss Made',
    'Constant glow for up to 25 years in any light condition',
    'Water Resistance - 200 Meters, 20 ATM, 660 feet, individually tested',
    'Movement - Ronda 515',
    'Battery/Battery Life - 395 / 50 Months',
    'Case - 316L Stainless steel case',
    'Bezel - Uni-directional rotating CARBONOX™',
    'Case Back - 316l stainless steel, screwed in',
    'Crystal - Sapphire with anti-reflective coating',
    'Crown - 316L Stainless steel, screw in, protected crown',
    'Height - 12mm',
    'Weight - 175g'
  ],
  related: [],
  description: 'Description 44mm Diameter Origin - Swiss Made Constant glow for up to 25 years in any light condition Water Resistance - 200 Meters, 20 ATM, 660 feet, individually tested Movement - Ronda 515 Battery/Battery Life - 395 / 50 Months Case - 316L Stainless steel case Bezel - Uni-directional rotating CARBONOX™ Case Back - 316l stainless steel, screwed in Crystal - Sapphire with anti-reflective coating Crown - 316L Stainless steel, screw in, protected crown Height - 12mm Weight - 175g More Details Luminox self-powered illumination Superluminova dial markingsSwiss Made'
}
{
  source: 'official',
  lang: 'en',
  brand: 'Luminox',
  brandID: 442,
  url: 'https://luminox.com/products/pacific-diver-3122',
  collection: 'SEA SERIES',
  name: 'Pacific Diver - 3122',
  reference: '3122',
  retail: '$695.00',
  thumbnail: 'https://cdn.shopify.com/s/files/1/2423/1151/products/3122_FACE.png?v=1591388551',
  base: 'https://www.luminox.com',
  spec: [
    '44mm Diameter',
    'Origin - Swiss Made',
    'Constant glow for up to 25 years in any light condition',
    'Water Resistance - 200 Meters, 20 ATM, 660 feet, individually tested',
    'Movement - Ronda 515',
    'Battery/Battery Life - 395 / 50 Months',
    'Case - 316L Stainless steel case',
    'Bezel - Uni-directional rotating CARBONOX™',
    'Case Back - 316l stainless steel, screwed in',
    'Crystal - Sapphire with anti-reflective coating',
    'Crown - 316L Stainless steel, screw in, protected crown',
    'Height - 12mm',
    'Weight - 175g'
  ],
  related: [],
  description: 'Description 44mm Diameter Origin - Swiss Made Constant glow for up to 25 years in any light condition Water Resistance - 200 Meters, 20 ATM, 660 feet, individually tested Movement - Ronda 515 Battery/Battery Life - 395 / 50 Months Case - 316L Stainless steel case Bezel - Uni-directional rotating CARBONOX™ Case Back - 316l stainless steel, screwed in Crystal - Sapphire with anti-reflective coating Crown - 316L Stainless steel, screw in, protected crown Height - 12mm Weight - 175g More Details Luminox self-powered illumination Superluminova dial markingsSwiss Made'
}
{
  source: 'official',
  lang: 'en',
  brand: 'Luminox',
  brandID: 442,
  url: 'https://luminox.com/products/pacific-diver-3121',
  collection: 'SEA SERIES',
  name: 'Pacific Diver - 3121',
  reference: '3121',
  retail: '$595.00',
  thumbnail: 'https://cdn.shopify.com/s/files/1/2423/1151/products/3121_FACE.png?v=1591388454',
  base: 'https://www.luminox.com',
  spec: [
    '44mm Diameter',
    'Origin - Swiss Made',
    'Constant glow for up to 25 years in any light condition',
    'Water Resistance - 200 Meters, 20 ATM, 660 feet, individually tested',
    'Movement - Ronda 515',
    'Battery/Battery Life - 395 / 50 Months',
    'Case - 316L Stainless steel case',
    'Bezel - Uni-directional rotating CARBONOX™',
    'Case Back - 316l stainless steel, screwed in',
    'Crystal - Sapphire with anti-reflective coating',
    'Crown - 316L Stainless steel, screw in, protected crown',
    'Height - 12mm',
    'Weight - 150g'
  ],
  related: [],
  description: 'Description 44mm Diameter Origin - Swiss Made Constant glow for up to 25 years in any light condition Water Resistance - 200 Meters, 20 ATM, 660 feet, individually tested Movement - Ronda 515 Battery/Battery Life - 395 / 50 Months Case - 316L Stainless steel case Bezel - Uni-directional rotating CARBONOX™ Case Back - 316l stainless steel, screwed in Crystal - Sapphire with anti-reflective coating Crown - 316L Stainless steel, screw in, protected crown Height - 12mm Weight - 150g More Details Luminox self-powered illumination Superluminova dial markingsSwiss Made'
}
{
  source: 'official',
  lang: 'en',
  brand: 'Luminox',
  brandID: 442,
  url: 'https://luminox.com/products/pacific-diver-3121-bo',
  collection: 'SEA SERIES',
  name: 'Pacific Diver - 3121.BO',
  reference: '3121.BO',
  retail: '$655.00',
  thumbnail: 'https://cdn.shopify.com/s/files/1/2423/1151/products/3121BO_FACE.png?v=1591388508',
  base: 'https://www.luminox.com',
  spec: [
    '44mm Diameter',
    'Origin - Swiss Made',
    'Constant glow for up to 25 years in any light condition',
    'Water Resistance - 200 Meters, 20 ATM, 660 feet, individually tested',
    'Movement - Ronda 515',
    'Battery/Battery Life - 395 / 50 Months',
    'Case - 316L Stainless steel case',
    'Bezel - Uni-directional rotating CARBONOX™',
    'Case Back - 316l stainless steel, screwed in',
    'Crystal - Sapphire with anti-reflective coating',
    'Crown - 316L Stainless steel, screw in, protected crown',
    'Height - 12mm',
    'Weight - 150g'
  ],
  related: [],
  description: 'Description 44mm Diameter Origin - Swiss Made Constant glow for up to 25 years in any light condition Water Resistance - 200 Meters, 20 ATM, 660 feet, individually tested Movement - Ronda 515 Battery/Battery Life - 395 / 50 Months Case - 316L Stainless steel case Bezel - Uni-directional rotating CARBONOX™ Case Back - 316l stainless steel, screwed in Crystal - Sapphire with anti-reflective coating Crown - 316L Stainless steel, screw in, protected crown Height - 12mm Weight - 150g More Details Luminox self-powered illumination Swiss Made'
}
{
  source: 'official',
  lang: 'en',
  brand: 'Luminox',
  brandID: 442,
  url: 'https://luminox.com/products/pacific-diver-3127',
  collection: 'SEA SERIES',
  name: 'Pacific Diver - 3137',
  reference: '3137',
  retail: '$695.00',
  thumbnail: 'https://cdn.shopify.com/s/files/1/2423/1151/products/PacificDiverLuminoxDiveWatchXS.3137EmeraldGreenDialSilverStainlessSteelCaseBraceletStrapWatch.png?v=1623121312',
  base: 'https://www.luminox.com',
  spec: [
    '44mm Diameter',
    'Origin - Swiss Made',
    'Constant glow for up to 25 years in any light condition',
    'Water Resistance - 200 Meters, 20 ATM, 660 feet, individually tested',
    'Movement - Ronda 515',
    'Battery/Battery Life - 395 / 50 Months',
    'Case - 316L Stainless steel case',
    'Bezel - Uni-directional rotating CARBONOX™',
    'Case Back - 316l stainless steel, screwed in',
    'Crystal - Sapphire with anti-reflective coating',
    'Crown - 316L Stainless steel, screw in, protected crown',
    'Height - 12mm',
    'Weight - 175g'
  ],
  related: [],
  description: 'Description 44mm Diameter Origin - Swiss Made Constant glow for up to 25 years in any light condition Water Resistance - 200 Meters, 20 ATM, 660 feet, individually tested Movement - Ronda 515 Battery/Battery Life - 395 / 50 Months Case - 316L Stainless steel case Bezel - Uni-directional rotating CARBONOX™ Case Back - 316l stainless steel, screwed in Crystal - Sapphire with anti-reflective coating Crown - 316L Stainless steel, screw in, protected crown Height - 12mm Weight - 175g More Details Luminox self-powered illumination Superluminova dial markingsSwiss Made'
}
{
  source: 'official',
  lang: 'en',
  brand: 'Luminox',
  brandID: 442,
  url: 'https://luminox.com/products/pacific-diver-3135',
  collection: 'SEA SERIES',
  name: 'Pacific Diver - 3135',
  reference: '3135',
  retail: '$595.00',
  thumbnail: 'https://cdn.shopify.com/s/files/1/2423/1151/products/PacificDiverLuminoxDiveWatchXS.3135CrimsonRedDialSilverStainlessSteelCasewithBlackRubberStrapWatch.png?v=1623121472',
  base: 'https://www.luminox.com',
  spec: [
    '44mm Diameter',
    'Origin - Swiss Made',
    'Constant glow for up to 25 years in any light condition',
    'Water Resistance - 200 Meters, 20 ATM, 660 feet, individually tested',
    'Movement - Ronda 515',
    'Battery/Battery Life - 395 / 50 Months',
    'Case - 316L Stainless steel case',
    'Bezel - Uni-directional rotating CARBONOX™',
    'Case Back - 316l stainless steel, screwed in',
    'Crystal - Sapphire with anti-reflective coating',
    'Crown - 316L Stainless steel, screw in, protected crown',
    'Height - 12mm',
    'Weight - 150g'
  ],
  related: [],
  description: 'Description 44mm Diameter Origin - Swiss Made Constant glow for up to 25 years in any light condition Water Resistance - 200 Meters, 20 ATM, 660 feet, individually tested Movement - Ronda 515 Battery/Battery Life - 395 / 50 Months Case - 316L Stainless steel case Bezel - Uni-directional rotating CARBONOX™ Case Back - 316l stainless steel, screwed in Crystal - Sapphire with anti-reflective coating Crown - 316L Stainless steel, screw in, protected crown Height - 12mm Weight - 150g More Details Luminox self-powered illumination Superluminova dial markingsSwiss Made'
}
{
  source: 'official',
  lang: 'en',
  brand: 'Luminox',
  brandID: 442,
  url: 'https://luminox.com/products/navy-seal-foundation-exclusive-3503-nsf',
  collection: 'SEA SERIES',
  name: 'Navy SEAL Foundation Exclusive - 3503.NSF',
  reference: '3503.NSF',
  retail: '$435.00',
  thumbnail: 'https://cdn.shopify.com/s/files/1/2423/1151/products/3503.NSF_FRONT.png?v=1593611575',
  base: 'https://www.luminox.com',
  spec: [
    '45 mm',
    'Carbon Compound case back',
    'Stainless Steel case back',
    'Carbon reinforced unidirectional turning bezel',
    'Tempered scratch resistant mineral crystal',
    'Water resistant to 200 meters',
    'Signature black PU strap with stainless steel signature buckle',
    'Luminox self-powered illumination',
    'Swiss Made',
    'Established in 2000 to serve U.S. Navy SEALs, Special Warfare Combatant-craft Crewmen, Naval Special Warfare support personnel and their families. The Navy SEAL Foundation provides a comprehensive set of programs specifically designed to improve health and welfare, build and enhance resiliency, empower and educate families and provide critical support during times of illness, injury, loss and transition.',
    'The Navy SEAL Foundation is a 501(c)(3), tax-exempt, national, non-profit benevolent organization headquartered in Virginia Beach, VA. The Foundation is a resolute cornerstone for the Naval Special Warfare community and their families in times of adversity and triumph.'
  ],
  related: [],
  description: 'Description 45 mmCarbon Compound case backStainless Steel case backCarbon reinforced unidirectional turning bezelTempered scratch resistant mineral crystalWater resistant to 200 metersSignature black PU strap with stainless steel signature buckle Luminox self-powered illuminationSwiss Made About the NAVY SEAL Foundation Established in 2000 to serve U.S. Navy SEALs, Special Warfare Combatant-craft Crewmen, Naval Special Warfare support personnel and their families. The Navy SEAL Foundation provides a comprehensive set of programs specifically designed to improve health and welfare, build and enhance resiliency, empower and educate families and provide critical support during times of illness, injury, loss and transition. The Navy SEAL Foundation is a 501(c)(3), tax-exempt, national, non-profit benevolent organization headquartered in Virginia Beach, VA. The Foundation is a resolute cornerstone for the Naval Special Warfare community and their families in times of adversity and triumph.'
}
{
  source: 'official',
  lang: 'en',
  brand: 'Luminox',
  brandID: 442,
  url: 'https://luminox.com/products/bear-grylls-survival-sea-series-never-give-up-model-3729-ngu',
  collection: 'BEAR GRYLLS',
  name: 'Bear Grylls Survival SEA Series Never Give Up Model - 3729.NGU',
  reference: '3729.NGU',
  retail: '$495.00',
  thumbnail: 'https://cdn.shopify.com/s/files/1/2423/1151/products/BEARGRYLLSxLUMINOXNeverGiveUpWatch_2.png?v=1622658644',
  base: 'https://www.luminox.com',
  spec: [
    'Origin: Swiss Made',
    'Always Visible: Constant glow for up to 25 years',
    'Size of case (diameter): 42 mm',
    'Water Resistance: 200 meters, 20 ATM, 660 feet',
    'Movement: RONDA 515 HF 6',
    'Battery Life: 395 / 50 months',
    'Case material: CARBONOX™ with crown protection',
    'Bezel: CARBONOX™, uni-directional turning',
    'Case Back: 316L Stainless steel, screw in',
    'Crystal: Hardened Mineral',
    'Crown: 316L Stainless Steel, screw on',
    'Strap / bracelet: Black genuine rubber w/ stainless steel buckle',
    'Width of Strap: 24 mm',
    'Case Height: 14 mm',
    'Weight: 76 g'
  ],
  related: [],
  description: `Description The Bear Grylls Survival Series model has a CARBONOX ™ case . CARBONOX ™ is an exclusive Luminox material based on carbon that is light, hypoallergenic, extremely durable and resistant. Like all outdoor watches in the Bear Grylls Survival 3720 series, this timepiece also has the Bear Grylls logo and the motto "Never Give Up" on the dial. The eye-catching diver's bezel in orange forms a strong contrast to the dark dial. His motto can also be found together with his signature as an engraving on the case back. This tactical watch comes with a rubber watch strap . Product Details Luminox x Bear Grylls Official Watch Collection Origin: Swiss Made Always Visible: Constant glow for up to 25 years Size of case (diameter): 42 mm Water Resistance: 200 meters, 20 ATM, 660 feet Movement: RONDA 515 HF 6 Battery Life: 395 / 50 months Case material: CARBONOX™ with crown protection Bezel: CARBONOX™, uni-directional turning Case Back: 316L Stainless steel, screw in Crystal: Hardened Mineral Crown: 316L Stainless Steel, screw on Strap / bracelet: Black genuine rubber w/ stainless steel buckle Width of Strap: 24 mm Case Height: 14 mm Weight: 76 g More Details Luminox self-powered illumination, constant glow for up to 25 years in any light conditionSwiss Made`
}
{
  source: 'official',
  lang: 'en',
  brand: 'Luminox',
  brandID: 442,
  url: 'https://luminox.com/products/navy-seal-colormark-3051-go-nsf-navy-seal-foundation-exclusive-watch',
  collection: 'SEA SERIES',
  name: 'Navy SEAL Colormark 3051.GO.NSF - Navy SEAL Foundation Exclusive Watch',
  reference: 'Navy SEAL Foundation Exclusive Watch',
  retail: '$435.00',
  thumbnail: 'https://cdn.shopify.com/s/files/1/2423/1151/products/LuminoxNavySEALColormarkNavySEALFoundationDiveWatch3051grayout_1.png?v=1622659402',
  base: 'https://www.luminox.com',
  spec: [
    'Origin: Swiss Made',
    'Always Visible: Permanent glow for up to 25 years',
    'Case diameter: 44 mm',
    'Function: time / date',
    'Water resistance (meters, feet, ATM): 200/660/20',
    'Movement Swiss Quartz',
    'Housing material : CARBONOX ™',
    'Bezel: unidirectional',
    'Caseback: 316L stainless steel screwed on',
    'Glass: Hardened mineral glass (550-650 Vickers)',
    'Crown: double seal and crown protection',
    'Strap: rubber',
    'Strap width: 23 mm',
    'Height: 14mm',
    'Weight: 64 g'
  ],
  related: [],
  description: `The 3051.GO.NSF military watch was designed in collaboration with the Navy SEAL Foundation (NSF) and bears their logo on the case back. In terms of color tone-on-tone, the monochrome Luminox logo on the dial catches the eye. The design of the Navy SEAL series impresses with its distinctive "turtle shape". Thanks to its protected crown and diver's bezel, it is also water-resistant up to 200 meters. The tried-and-tested Luminox lighting system also ensures that the time can be read easily in every situation, and without any additional energy supply. Product Details Origin: Swiss Made Always Visible: Permanent glow for up to 25 years Case diameter: 44 mm Function: time / date Water resistance (meters, feet, ATM): 200/660/20 Movement Swiss Quartz Housing material : CARBONOX ™ Bezel: unidirectional Caseback: 316L stainless steel screwed on Glass: Hardened mineral glass (550-650 Vickers) Crown: double seal and crown protection Strap: rubber Strap width: 23 mm Height: 14mm Weight: 64 g About The Navy SEAL Foundation Established in 2000 to serve U.S. Navy SEALs, Special Warfare Combatant-craft Crewmen, Naval Special Warfare support personnel and their families. The Navy SEAL Foundation provides a comprehensive set of programs specifically designed to improve health and welfare, build and enhance resiliency, empower and educate families and provide critical support during times of illness, injury, loss and transition. The Navy SEAL Foundation is a 501(c)(3), tax-exempt, national, non-profit benevolent organization headquartered in Virginia Beach, VA. The Foundation is a resolute cornerstone for the Naval Special Warfare community and their families in times of adversity and triumph.`
}

done...
