  "Sapphire crystal 'Skeleton' case back",
  '“It’s incredibly important to me to work alongside world class trusted partners and Luminox have proved that and more. The rugged watch range has been carefully crafted featuring multi-functional design and state of the art materials – set to inspire and encourage the adventurer in everyone – men and women, boys and girls, outdoor novices and experts.” - Bear Grylls',
  '“It’s incredibly important to me to work alongside world class trusted partners and Luminox have proved that and more. The rugged watch range has been carefully crafted featuring multi-functional design and state of the art materials – set to inspire and encourage the adventurer in everyone – men and women, boys and girls, outdoor novices and experts.” - Bear Grylls',
  '1-12H green light tubes.',
  '1-12H green light tubes.',
  '1-12H green light tubes.',
  '1-12H green light tubes.',
  '10 Year Warranty for Tritium Tubes'
  '10 Year Warranty for Tritium Tubes'
  '10 Year Warranty for Tritium Tubes'
  '10 Year Warranty for Tritium Tubes',
  '2 Year Limited Warranty 10 Year Warranty for Tritium Tubes'
  '2 Year Limited Warranty',
  '2 Year Limited Warranty',
  '2 Year Limited Warranty',
  '2 Year Limited Warranty',
  '316L Stainless Steel Bracelet',
  '316L Stainless Steel Bracelet',
  '316L Stainless Steel crown, double security gasket',
  '316L Stainless Steel screw-in case back',
  '316L stainless steel case back',
  '316L stainless steel case back',
  '316L stainless steel case back',
  '316L stainless steel case, with 316L stainless steel fix bezel and 316L stainless steel screw-in caseback',
  '316L stainless steel case, with 316L stainless steel fix bezel and 316L stainless steel screw-in caseback',
  '316L stainless steel, double O-ring crown',
  '316L stainless steel, double O-ring crown',
  '316L stainless steel, double O-ring crown',
  '316L stainless steel, double O-ring crown',
  '316L stainless steel, double O-ring crown',
  '39 mm',
  '39 mm',
  '39 mm',
  '43 mm',
  '43mm',
  '44 mm',
  '44 mm',
  '44 mm',
  '44mm Diameter',
  '44mm Diameter',
  '44mm Diameter',
  '44mm Diameter',
  '44mm Diameter',
  '44mm Diameter',
  '44mm',
  '44mm',
  '44mm',
  '44mm',
  '44mm',
  '44mm',
  '44mm',
  '45 mm',
  '45 mm',
  '45 mm',
  '45 mm',
  '45 mm',
  '45 mm',
  '45 mm',
  '45 mm',
  '45 mm',
  '45 mm',
  '45 mm',
  '45 mm',
  '45 mm',
  '45 mm',
  '45 mm',
  '45mm',
  '46 mm',
  '46 mm',
  '46 mm',
  '46 mm',
  '46 mm',
  '46 mm',
  'Accessory: Compass Loop',
  'Accessory: Compass Loop',
  'Accessory: Compass Loop',
  'Always Visible: Constant glow for up to 25 years in any light condition',
  'Always Visible: Constant glow for up to 25 years in any light condition',
  'Always Visible: Constant glow for up to 25 years',
  'Always Visible: Constant glow for up to 25 years',
  'Always Visible: Constant glow for up to 25 years',
  'Always Visible: Constant glow for up to 25 years',
  'Always Visible: Constant glow for up to 25 years',
  'Always Visible: Constant glow for up to 25 years',
  'Always Visible: Constant glow for up to 25 years',
  'Always Visible: Constant glow for up to 25 years',
  'Always Visible: Constant glow for up to 25 years',
  'Always Visible: Constant glow for up to 25 years',
  'Always Visible: Constant glow for up to 25 years',
  'Always Visible: Permanent glow for up to 25 years',
  'Always Visible: Permanent glow for up to 25 years',
  'Antireflective Sapphire crystal',
  'Antireflective Sapphire crystal',
  'Antireflective sapphire crystal',
  'Antireflective sapphire crystal',
  'Antireflective sapphire crystal',
  'Antireflective sapphire crystal',
  'Antireflective sapphire crystal',
  'Antireflective sapphire crystal',
  'Antireflective sapphire crystal',
  'Automatic',
  'Automatic',
  'Battery / Battery Life: 395 / 50 months',
  'Battery / Battery Life: 395 / 50 months',
  'Battery Life: 395 / 50 months',
  'Battery Life: 395 / 50 months',
  'Battery Life: 395 / 50 months',
  'Battery/Battery Life - 395 / 50 Months',
  'Battery/Battery Life - 395 / 50 Months',
  'Battery/Battery Life - 395 / 50 Months',
  'Battery/Battery Life - 395 / 50 Months',
  'Battery/Battery Life - 395 / 50 Months',
  'Battery/Battery Life - 395 / 50 Months',
  'Battery/Battery life 395 / 50 months',
  'Battery/Battery life: 395 / 50 months',
  'Battery/Battery life: 395 / 50 months',
  'Bear Grylls x Luminox:',
  'Bear Grylls x Luminox:',
  'Bezel - Uni-directional rotating CARBONOX™',
  'Bezel - Uni-directional rotating CARBONOX™',
  'Bezel - Uni-directional rotating CARBONOX™',
  'Bezel - Uni-directional rotating CARBONOX™',
  'Bezel - Uni-directional rotating CARBONOX™',
  'Bezel - Uni-directional rotating CARBONOX™',
  'Bezel: 316L stainless steel with black ceramic ring, uni-directional turning bezel',
  'Bezel: 316L stainless steel with black ceramic ring, uni-directional turning bezel',
  'Bezel: CARBONOX™+, bi-directional rotating bezel',
  'Bezel: CARBONOX™+, bi-directional rotating bezel',
  'Bezel: CARBONOX™+, uni-directional turning, count-up and compass',
  'Bezel: CARBONOX™+, uni-directional turning, count-up and compass',
  'Bezel: CARBONOX™+, uni-directional turning, count-up and compass',
  'Bezel: CARBONOX™, fixed bezel',
  'Bezel: CARBONOX™, fixed bezel',
  'Bezel: CARBONOX™, uni-directional turning',
  'Bezel: CARBONOX™, uni-directional turning',
  'Bezel: CARBONOX™, uni-directional turning',
  'Bezel: Uni-directional rotating',
  'Bezel: Uni-directional rotating',
  'Bezel: Uni-directional rotating',
  'Bezel: unidirectional',
  'Bezel: unidirectional',
  'Bidirectional rotating bezel with black aluminum slide rule ring',
  'Bidirectional rotating bezel',
  'Bidirectional rotating bezel',
  'Black Carbon Compound caseback',
  'Black Carbon Compound caseback',
  'Black Carbon Compound caseback',
  'Black Carbon Compound caseback',
  'Black Genuine Rubber strap with stainless steel signature buckle, 24mm',
  'Black Kevlar strap with leather lining and accents',
  'Black Kevlar strap with leather lining and accents, 24mm',
  'Black PVD-plated stainless steel case, screw down crown &amp; case back',
  'Black Rubber signature strap with stainless steel brushed IP black signature buckle, 24/22mm',
  'Black Rubber signature strap with stainless steel brushed signature buckle, 24/22mm',
  'Black Rubber signature strap with stainless steel brushed signature buckle, 24/22mm',
  'Black dial with orange second hand',
  'Black dial with orange second hand',
  'Black genuine rubber signature strap with black textile inlay, black stitching and CARBONOX™ signature buckle, 24mm',
  'Black genuine rubber signature strap with black textile inlay, black stitching and CARBONOX™ signature buckle, 24mm',
  'Black genuine rubber signature strap with red stitching and CARBONOX™ signature buckle, 24mm',
  'Black genuine rubber signature strap with white stitching and CARBONOX™ signature buckle, 24mm',
  'Black leather strap with silver stitching and a titanium signature buckle',
  'Black signature PU strap with brushed stainless steel signature buckle, loop lock, 22mm',
  'Black signature PU strap with brushed stainless steel signature buckle, loop lock, 22mm',
  'Black signature PU strap with brushed stainless steel signature buckle, loop-lock, 19mm',
  'Black signature PU strap with brushed stainless steel signature buckle, loop-lock, 19mm',
  'Black webbing strap with brushed stainless steel signature buckle, loop-lock, 22mm',
  'Blue genuine rubber signature strap with blue textile inlay, blue stitching and CARBONOX™ signature buckle, 24mm',
  'Brushed titanium case, screw down crown &amp; case back',
  'CARBONOX™ Carbon Compound case',
  'CARBONOX™ case and',
  'CARBONOX™ case and',
  'CARBONOX™ case and',
  'CARBONOX™ case with crown protection and 316L stainless steel case back',
  'CARBONOX™ case with crown protection and 316L stainless steel case back',
  'CARBONOX™ case with crown protection and 316L stainless steel case back',
  'CARBONOX™ case with crown protection and 316L stainless steel case back',
  'CARBONOX™ case, black dial with crown protection and 316L stainless steel case back',
  'CARBONOX™ caseback',
  'CARBONOX™+ Case w/ bi-directional rotating bezel',
  'CARBONOX™, fixed bezel, at 12h fitted with a protected orange light tube as well as hour and Minutes hands.',
  'CARBONOX™, ufixed bezel',
  'CARBONOX™, ufixed bezel, at 12h fitted with a protected orange light tube as well as hour and Minutes hands.',
  'CARBONOX™, ufixed bezel, at 12h fitted with a protected orange light tube as well as hour and Minutes hands.',
  'CARBONOX™, ufixed bezel, at 12h fitted with a protected orange light tube as well as hour and Minutes hands.',
  'CARBONOX™, unidirectional rotating bezel with Super-Luminova at 12H',
  'CARBONOX™, unidirectional rotating bezel, at 12h fitted with a protected colored light tube with sapphire crystal',
  'CARBONOX™, unidirectional rotating bezel, at 12h fitted with a protected colored light tube with sapphire crystal',
  'CARBONOX™, unidirectional rotating bezel, at 12h fitted with a protected colored light tube with sapphire crystal',
  'CARBONOX™/ White fiberglass compound, with crown protection (316L stainless steel, Double-Security Gasket) and Orange Dial',
  'Carbon Compound case back',
  'Carbon Compound case back',
  'Carbon Compound case with Black Dial',
  'Carbon Compound case with Black Dial',
  'Carbon Compound case with Black Dial',
  'Carbon Compound case with White Dial',
  'Carbon Compound case',
  'Carbon Compound case',
  'Carbon Compound case',
  'Carbon Compound case',
  'Carbon Compound case',
  'Carbon Compound unidirectional turning bezel w/ aluminum ring',
  'Carbon Compound unidirectional turning bezel',
  'Carbon Compound unidirectional turning bezel',
  'Carbon Compound unidirectional turning bezel',
  'Carbon Compound unidirectional turning bezel',
  'Carbon Compound unidirectional turning bezel',
  'Carbon reinforced polycarbonate bezel',
  'Carbon reinforced polycarbonate case and case back',
  'Carbon reinforced unidirectional ratcheting bezel',
  'Carbon reinforced unidirectional turning bezel',
  'Carbon reinforced unidirectional turning bezel',
  'Case - 316L Stainless steel case',
  'Case - 316L Stainless steel case',
  'Case - 316L Stainless steel case',
  'Case - 316L Stainless steel case',
  'Case - 316L Stainless steel case',
  'Case - 316L Stainless steel case',
  'Case Back - 316l stainless steel, screwed in',
  'Case Back - 316l stainless steel, screwed in',
  'Case Back - 316l stainless steel, screwed in',
  'Case Back - 316l stainless steel, screwed in',
  'Case Back - 316l stainless steel, screwed in',
  'Case Back - 316l stainless steel, screwed in',
  'Case Back: 316L Stainless steel screw in',
  'Case Back: 316L Stainless steel screw in',
  'Case Back: 316L Stainless steel screw in',
  'Case Back: 316L Stainless steel, screw in',
  'Case Back: 316L Stainless steel, screw in',
  'Case Back: 316L Stainless steel, screw in',
  'Case Back: 316L Stainless steel, screw in',
  'Case Back: 316L Stainless steel, screw in',
  'Case Back: 316L Stainless steel, screw in',
  'Case Back: 316L Stainless steel, screw in',
  'Case Back: 316L Stainless steel, screw in',
  'Case Height: 14 mm',
  'Case Height: 14 mm',
  'Case Height: 14 mm',
  'Case Height: 14 mm',
  'Case Height: 14 mm',
  'Case Height: 14 mm',
  'Case Height: 14 mm',
  'Case Height: 14 mm',
  'Case Height: 14 mm',
  'Case Height: 14mm',
  'Case Height: 14mm',
  'Case back: 316L stainless steel, screw in',
  'Case back: 316L stainless steel, screw in',
  'Case back: 316L stainless steel, transparent, screw in',
  'Case back: 316L stainless steel, transparent, screw in',
  'Case diameter: 44 mm',
  'Case diameter: 45 mm',
  'Case material: CARBONOX™ with crown protection',
  'Case material: CARBONOX™ with crown protection',
  'Case material: CARBONOX™ with crown protection',
  'Case material: CARBONOX™',
  'Case material: CARBONOX™',
  'Case material: CARBONOX™',
  'Case material: CARBONOX™',
  'Case material: CARBONOX™',
  'Case material: CARBONOX™+',
  'Case material: CARBONOX™+',
  'Case material: CARBONOX™+',
  'Case: 316L stainless steel',
  'Case: 316L stainless steel',
  'Case: Stainless steel 316L case',
  'Case: Stainless steel 316L case',
  'Caseback: 316L stainless steel screwed on',
  'Caseback: 316L stainless steel screwed on',
  'Constant Glow for up to 25 years in any condition.',
  'Constant glow for up to 25 years in any light condition',
  'Constant glow for up to 25 years in any light condition',
  'Constant glow for up to 25 years in any light condition',
  'Constant glow for up to 25 years in any light condition',
  'Constant glow for up to 25 years in any light condition',
  'Constant glow for up to 25 years in any light condition',
  'Crown - 316L Stainless steel, screw in, protected crown',
  'Crown - 316L Stainless steel, screw in, protected crown',
  'Crown - 316L Stainless steel, screw in, protected crown',
  'Crown - 316L Stainless steel, screw in, protected crown',
  'Crown - 316L Stainless steel, screw in, protected crown',
  'Crown - 316L Stainless steel, screw in, protected crown',
  'Crown: 316L Stainless Steel, screw on',
  'Crown: 316L Stainless Steel, screw on',
  'Crown: 316L Stainless Steel, screw on',
  'Crown: 316L Stainless Steel, screw on',
  'Crown: 316L Stainless Steel, screw on',
  'Crown: 316L Stainless Steel, screw on',
  'Crown: 316L Stainless Steel, screw on',
  'Crown: 316L Stainless Steel, screw on',
  'Crown: 316L stainless steel, crown protected',
  'Crown: 316L stainless steel, crown protected',
  'Crown: 316L stainless steel, screw down, protected crown',
  'Crown: 316L stainless steel, screw down, protected crown',
  'Crown: Double security gasket, crown protected',
  'Crown: Double security gasket, crown protected',
  'Crown: Double security gasket, crown protected',
  'Crown: double seal and crown protection',
  'Crown: screwed with double seal and crown protection',
  'Crystal - Sapphire with anti-reflective coating',
  'Crystal - Sapphire with anti-reflective coating',
  'Crystal - Sapphire with anti-reflective coating',
  'Crystal - Sapphire with anti-reflective coating',
  'Crystal - Sapphire with anti-reflective coating',
  'Crystal - Sapphire with anti-reflective coating',
  'Crystal glass material: Sapphire crystal, anti-reflective coating',
  'Crystal glass material: Sapphire crystal, anti-reflective coating',
  'Crystal glass material: Sapphire crystal, anti-reflective coating',
  'Crystal: Hardened Mineral',
  'Crystal: Hardened Mineral',
  'Crystal: Hardened Mineral',
  'Crystal: Hardened Mineral',
  'Crystal: Hardened Mineral',
  'Crystal: Sapphire crystal with anti-reflection coating',
  'Crystal: Sapphire crystal with anti-reflection coating',
  'Crystal: Sapphire crystal, anti-reflective coating',
  'Crystal: Sapphire crystal, anti-reflective coating',
  'Crystal: Sapphire crystal, anti-reflective coating',
  'Crystal: Sapphire with anti-reflection coating',
  'Crystal: Sapphire with anti-reflection coating',
  'Dark Midnight Green enamel dial',
  'Description',
  'Description:',
  'Description:',
  'Dial ring with tachymetric scale',
  'Established in 2000 to serve U.S. Navy SEALs, Special Warfare Combatant-craft Crewmen, Naval Special Warfare support personnel and their families. The Navy SEAL Foundation provides a comprehensive set of programs specifically designed to improve health and welfare, build and enhance resiliency, empower and educate families and provide critical support during times of illness, injury, loss and transition.',
  'For the busy men who are always on the go, a GMT watch is a must-have in your collection. What sets a GMT watch apart from other timepieces is its ability to display two to three different timezones at once. Providing a variety of useful features in a stylish package, these watches are both functional and modern. As such, they’re perfect for all kinds of wearers from the active outdoorsman to the office worker and just about all those in between.'
  'For the busy men who are always on the go, a GMT watch is a must-have in your collection. What sets a GMT watch apart from other timepieces is its ability to display two to three different timezones at once. Providing a variety of useful features in a stylish package, these watches are both functional and modern. As such, they’re perfect for all kinds of wearers from the active outdoorsman to the office worker and just about all those in between.'
  'For the busy men who are always on the go, a GMT watch is a must-have in your collection. What sets a GMT watch apart from other timepieces is its ability to display two to three different timezones at once. Providing a variety of useful features in a stylish package, these watches are both functional and modern. As such, they’re perfect for all kinds of wearers from the active outdoorsman to the office worker and just about all those in between.'
  'Function: Time Date',
  'Function: Time Date',
  'Function: Time Date',
  'Function: time / date',
  'Function: time / date',
  'GMT Multiple Timezone Feature:',
  'GMT Multiple Timezone Feature:',
  'Genuine brown buffalo leather strap with ivory contrast stitching and signature stainless steel buckle',
  'Glass: Hardened mineral glass (550-650 Vickers)',
  'Glass: Hardened mineral glass (550-650 Vickers)',
  'Green Webbing strap with stainless steel brushed signature buckle, 24mm',
  'Height - 12mm',
  'Height - 12mm',
  'Height - 12mm',
  'Height - 12mm',
  'Height - 12mm',
  'Height - 12mm',
  'Height 12.15mm',
  'Height 14.30mm',
  'Height 14.30mm',
  'Height: 13mm',
  'Height: 13mm',
  'Height: 13mm',
  'Height: 13mm',
  'Height: 13mm',
  'Height: 13mm',
  'Height: 13mm',
  'Height: 13mm',
  'Height: 13mm',
  'Height: 14.80mm',
  'Height: 14.80mm',
  'Height: 14.80mm',
  'Height: 14mm',
  'Height: 14mm',
  'Housing material : CARBONOX ™',
  'Housing material: CARBONOX ™',
  'Luminox is the Official Partner of ICE-SAR',
  'Luminox is the Official Partner of ICE-SAR',
  'Luminox is the Official Partner of ICE-SAR',
  'Luminox is the Official Partner of ICE-SAR',
  'Luminox is the Official Partner of ICE-SAR',
  'Luminox self-powered illumination and SuperLuminova on numbers and bezel for unparalleled night visibility',
  'Luminox self-powered illumination and SuperLuminova on numbers and bezel for unparalleled night visibility',
  'Luminox self-powered illumination and SuperLuminova on numbers and bezel for unparalleled night visibility',
  'Luminox self-powered illumination',
  'Luminox self-powered illumination',
  'Luminox self-powered illumination',
  'Luminox self-powered illumination',
  'Luminox self-powered illumination',
  'Luminox self-powered illumination',
  'Luminox self-powered illumination',
  'Luminox self-powered illumination',
  'Luminox self-powered illumination',
  'Luminox self-powered illumination',
  'Luminox self-powered illumination',
  'Luminox self-powered illumination',
  'Luminox self-powered illumination',
  'Luminox self-powered illumination',
  'Luminox self-powered illumination',
  'Luminox self-powered illumination',
  'Luminox self-powered illumination',
  'Luminox self-powered illumination',
  'Luminox self-powered illumination',
  'Luminox self-powered illumination',
  'Luminox self-powered illumination',
  'Luminox self-powered illumination',
  'Luminox self-powered illumination',
  'Luminox self-powered illumination',
  'Luminox self-powered illumination',
  'Luminox self-powered illumination',
  'Luminox self-powered illumination',
  'Luminox self-powered illumination',
  'Luminox self-powered illumination, constant glow for up to 25 years in any light condition',
  'Luminox self-powered illumination, constant glow for up to 25 years in any light condition',
  'Luminox self-powered illumination, constant glow for up to 25 years in any light condition',
  'Luminox self-powered illumination, constant glow for up to 25 years in any light condition',
  'Luminox self-powered illumination, constant glow for up to 25 years in any light condition',
  'Luminox self-powered illumination, constant glow for up to 25 years in any light condition',
  'Luminox self-powered illumination, constant glow for up to 25 years in any light condition',
  'Luminox self-powered illumination, constant glow for up to 25 years in any light condition',
  'Luminox’s motto, Every Second Counts, dovetails flawlessly with Grylls’ Never Give Up. There is no better watch to be on Bear Grylls’ wrist than a Luminox.',
  'Luminox’s motto, Every Second Counts, dovetails flawlessly with Grylls’ Never Give Up. There is no better watch to be on Bear Grylls’ wrist than a Luminox.',
  'Matte gunmetal PVD-plated stainless steel case, screw case back and screw down crown',
  'Matte gunmetal PVD-plated stainless steel case, screw case back and screw down crown',
  'Movement - Ronda 515',
  'Movement - Ronda 515',
  'Movement - Ronda 515',
  'Movement - Ronda 515',
  'Movement - Ronda 515',
  'Movement - Ronda 515',
  'Movement RONDA 5030.D HH1',
  'Movement RONDA 5030.D HH1',
  'Movement RONDA 5030.D HH1',
  'Movement RONDA 515 HF 6',
  'Movement RONDA 515 HF 6',
  'Movement RONDA 515 HF 6',
  'Movement RONDA 515 HF 6',
  'Movement RONDA 515 HF 6',
  'Movement Ronda 515, HH6',
  'Movement Swiss Automatic SW220-1 HH5',
  'Movement Swiss Automatic SW220-1 HH5',
  'Movement Swiss Quartz',
  'Movement: Chronograph, RONDA 5021.D',
  'Movement: Chronograph, RONDA 5021.D',
  'Movement: RONDA 5030.D',
  'Movement: RONDA 5030.D',
  'Movement: RONDA 5030.D',
  'Movement: RONDA 515 HF 6',
  'Movement: RONDA 515 HF 6',
  'Movement: RONDA 515 HF 6',
  'Movement: Ronda 515 HF 6',
  'Movement: Ronda 515 HF 6',
  'Movement: SW-220',
  'Movement: SW-220',
  'Movement: Swiss Quartz',
  'Movement: Swiss Quartz',
  'Movement: Swiss Quartz',
  'Movement: Swiss quartz',
  'Navy Blue EPDM Rubber Strap with brushed stainless steel signature buckle',
  'Origin - Swiss Made',
  'Origin - Swiss Made',
  'Origin - Swiss Made',
  'Origin - Swiss Made',
  'Origin - Swiss Made',
  'Origin - Swiss Made',
  'Origin: Swiss Made',
  'Origin: Swiss Made',
  'Origin: Swiss Made',
  'Origin: Swiss Made',
  'Origin: Swiss Made',
  'Origin: Swiss Made',
  'Origin: Swiss Made',
  'Origin: Swiss Made',
  'Origin: Swiss Made',
  'Origin: Swiss Made',
  'Origin: Swiss Made',
  'Origin: Swiss Made',
  'Origin: Swiss Made',
  'Origin: Swiss Made',
  'Origin: Swiss Made',
  'Rubber strap with stainless steel signature buckle',
  'Sapphire Crystal w/ anti-reflective coating',
  'Sapphire Crystal with anti-reflective coating',
  'Sapphire Crystal with anti-reflective coating',
  'Sapphire Crystal with anti-reflective coating',
  'Sapphire Crystal with anti-reflective coating',
  'Sapphire Crystal with anti-reflective coating',
  'Sapphire with anti-reflection coating',
  'Sapphire with anti-reflection coating',
  'Sapphire with anti-reflection coating',
  'Sapphire with anti-reflection coating',
  'Sapphire with anti-reflection coating',
  'Signature black PU strap with stainless steel signature buckle',
  'Signature black PU strap with stainless steel signature buckle',
  'Signature black PU strap with stainless steel signature buckle',
  'Signature black PU strap with stainless steel signature buckle',
  'Signature black PU strap with stainless steel signature buckle',
  'Size of case (diameter): 42 mm',
  'Size of case (diameter): 42 mm',
  'Size of case (diameter): 42 mm',
  'Size of case (diameter): 45 mm',
  'Size of case (diameter): 45 mm',
  'Size of case (diameter): 45 mm',
  'Size of case (diameter): 45 mm',
  'Size of case (diameter): 45 mm',
  'Size of case (diameter): 45 mm',
  'Size of case (diameter): 45 mm',
  'Size of case (diameter): 45 mm',
  'Size/Diameter:  45mm',
  'Size/Diameter:  45mm',
  'Size/Diameter: 42mm',
  'Size/Diameter: 42mm',
  'Solid Steel black brushed plated bracelet with black brushed stainless steel signature buckle with security clasp',
  'Solid Steel brushed bracelet with brushed stainless steel signature buckle with security clasp',
  'Solid link black PVD-plated stainless steel bracelet with security clasp',
  'Solid link matte gunmetal PVD-plated stainless steel bracelet with security clasp',
  'Solid link stainless steel bracelet with security clasp',
  'Stainless Steel 316L caseback',
  'Stainless Steel bracelet with stainless steel brushed signature buckle, 24mm',
  'Stainless Steel case back',
  'Stainless Steel case back',
  'Stainless Steel case back',
  'Stainless Steel case back',
  'Stainless Steel case back',
  'Stainless Steel case back',
  'Stainless Steel case back',
  'Stainless steel bezel',
  'Stainless steel case, screw case back and screw down crown',
  'Stainless steel case, screw case back and screw down crown',
  'Stainless steel case, screw down crown &amp; case back',
  'Stainless steel case, screw down crown &amp; case back',
  'Stainless steel case, screw down crown &amp; case back',
  'Stainless steel case, screw down crown &amp; case back',
  'Stainless steel case, screw down crown &amp; case back',
  'Stainless steel unidirectional ratcheting bezel',
  'Stainless steel unidirectional ratcheting bezel',
  'Stainless steel unidirectional ratcheting bezel',
  'Strap / bracelet: Black Genuine rubber strap w/ stainless steel buckle',
  'Strap / bracelet: Black genuine rubber w/ stainless steel buckle',
  'Strap / bracelet: Black genuine rubber w/ stainless steel buckle',
  'Strap / bracelet: Black genuine rubber w/ stainless steel buckle',
  'Strap / bracelet: Black paracord strap w/ stainless steel buckle',
  'Strap / bracelet: Dark Grey rubber EPDM strap, stainless steel buckle',
  'Strap / bracelet: Dark Grey rubber EPDM strap, stainless steel buckle',
  'Strap / bracelet: Genuine rubber',
  'Strap / bracelet: Genuine rubber',
  'Strap / bracelet: Genuine rubber',
  'Strap / bracelet: Orange rubber EPDM strap, stainless steel buckle',
  'Strap width: 23 mm',
  'Strap width: 24 mm',
  'Strap: rubber',
  'Strap: rubber',
  'Swiss Made'
  'Swiss Made'
  'Swiss Made'
  'Swiss Made'
  'Swiss Made'
  'Swiss Made'
  'Swiss Made'
  'Swiss Made'
  'Swiss Made'
  'Swiss Made'
  'Swiss Made'
  'Swiss Made'
  'Swiss Made'
  'Swiss Made'
  'Swiss Made'
  'Swiss Made'
  'Swiss Made'
  'Swiss Made'
  'Swiss Made'
  'Swiss Made'
  'Swiss Made'
  'Swiss Made'
  'Swiss Made'
  'Swiss Made'
  'Swiss Made'
  'Swiss Made'
  'Swiss Made'
  'Swiss Made'
  'Swiss Made'
  'Swiss Made'
  'Swiss Made'
  'Swiss Made'
  'Swiss Made'
  'Swiss Made',
  'Swiss Made',
  'Swiss Made',
  'Swiss Made',
  'Swiss Made',
  'Swiss Made',
  'Tempered scratch resistant mineral crystal',
  'Tempered scratch resistant mineral crystal',
  'Tempered scratch resistant mineral crystal',
  'Tempered scratch resistant mineral crystal',
  'Tempered scratch resistant mineral crystal',
  'Tempered scratch resistant mineral crystal',
  'Tempered scratch resistant mineral crystal',
  'Tempered scratch resistant mineral crystal',
  'Tempered scratch resistant mineral crystal',
  'Tempered scratch resistant mineral crystal',
  'Tempered scratch resistant mineral crystal',
  'Tempered scratch resistant mineral crystal',
  'Tempered scratch resistant mineral crystal',
  'Tempered scratch resistant mineral crystal',
  'Tempered scratch resistant mineral crystal',
  'Tempered scratch resistant mineral crystal',
  'Tempered scratch resistantMineral especially hardened',
  'The GMT bezel came about in the 1950s with the rise in commercial air travel. To help PanAm’s transatlantic pilots and their crews keep track of the local and Greenwich Mean Time (which was then used as the international time standard)',
  'The GMT bezel came about in the 1950s with the rise in commercial air travel. To help PanAm’s transatlantic pilots and their crews keep track of the local and Greenwich Mean Time (which was then used as the international time standard)',
  'The GMT bezel came about in the 1950s with the rise in commercial air travel. To help PanAm’s transatlantic pilots and their crews keep track of the local and Greenwich Mean Time (which was then used as the international time standard)',
  'The Navy SEAL Foundation is a 501(c)(3), tax-exempt, national, non-profit benevolent organization headquartered in Virginia Beach, VA. The Foundation is a resolute cornerstone for the Naval Special Warfare community and their families in times of adversity and triumph.'
  'Ultra-light Carbon Compound link bracelet with black PVD-plated stainless steel clasp',
  'Ultra-light Carbon Compund link bracelet with black PVD-plated stainless steel clasp',
  'Uni-directional rotating bezel with Super-LumiNova dot at 12H',
  'Uni-directional rotating bezel with Super-LumiNova dot at 12H',
  'Uni-directional rotating bezel with Super-LumiNova dot at 12H',
  'Uni-directional rotating bezel with Super-LumiNova dot at 12H',

  'Uni-directional turning bezel',
  'Unidirectional ratcheting bezel',

  'Valjoux 7750 Automatic Chronograph movement',

  'Water Resistance - 200 Meters, 20 ATM, 660 feet, individually tested',
  'Water Resistance - 200 Meters, 20 ATM, 660 feet, individually tested',
  'Water Resistance - 200 Meters, 20 ATM, 660 feet, individually tested',
  'Water Resistance - 200 Meters, 20 ATM, 660 feet, individually tested',
  'Water Resistance - 200 Meters, 20 ATM, 660 feet, individually tested',
  'Water Resistance - 200 Meters, 20 ATM, 660 feet, individually tested',
  'Water Resistance: 200 meters, 20 ATM, 660 feet',
  'Water Resistance: 200 meters, 20 ATM, 660 feet',
  'Water Resistance: 200 meters, 20 ATM, 660 feet',
  'Water Resistance: 200 meters, 20 ATM, 660 feet',
  'Water Resistance: 200 meters, 20 ATM, 660 feet',
  'Water Resistance: 200 meters, 20 ATM, 660 feet',
  'Water Resistance: 200 meters, 20 ATM, 660 feet',
  'Water Resistance: 200 meters, 20 ATM, 660 feet',
  'Water Resistance: 200 meters, 20 ATM, 660 feet, individually tested',
  'Water Resistance: 200 meters, 20 ATM, 660 feet, individually tested',
  'Water Resistance: 200 meters, 20 ATM, 660 feet, individually tested',
  'Water Resistance: 200 meters, 20 ATM, 660 feet, individually tested',
  'Water Resistance: 300 meters, 30 ATM, 1000 feet',
  'Water Resistance: 300 meters, 30 ATM, 1000 feet',
  'Water Resistance: 300 meters, 30 ATM, 1000 feet',
  'Water resistance (meters, feet, ATM): 200/660/20',
  'Water resistance (meters, feet, ATM): 200/660/20',
  'Water resistant to 100 meters',
  'Water resistant to 100 meters',
  'Water resistant to 100 meters',
  'Water resistant to 100 meters',
  'Water resistant to 100 meters',
  'Water resistant to 100 meters',
  'Water resistant to 100 meters',
  'Water resistant to 100 meters, 10 ATM, 330 feet, individually tested',
  'Water resistant to 200 meters',
  'Water resistant to 200 meters',
  'Water resistant to 200 meters',
  'Water resistant to 200 meters',
  'Water resistant to 200 meters',
  'Water resistant to 200 meters',
  'Water resistant to 200 meters',
  'Water resistant to 200 meters',
  'Water resistant to 200 meters',
  'Water resistant to 200 meters',
  'Water resistant to 200 meters',
  'Water resistant to 200 meters',
  'Water resistant to 200 meters',
  'Water resistant to 200 meters',
  'Water resistant to 200 meters',
  'Water resistant to 200 meters',
  'Water resistant to 200 meters',
  'Water resistant to 200 meters',
  'Water resistant to 200 meters',
  'Water resistant to 200 meters, 20 ATM, 660 feet, individually tested',
  'Water resistant to 200 meters, 20 ATM, 660 feet, individually tested',
  'Water resistant to 200 meters, 20 ATM, 660 feet, individually tested',
  'Water resistant to 200 meters, 20 ATM, 660 feet, individually tested',
  'Water resistant to 200 meters, 20 ATM, 660 feet, individually tested',
  'Water resistant to 200 meters, 20 ATM, 660 feet, individually tested',
  'Water resistant to 200 meters, 20 ATM, 660 feet, individually tested',
  'Water resistant to 200 meters, 20 ATM, 660 feet, individually tested',
  'Water resistant to 200 meters, 20 ATM, 660 feet, individually tested',
  'Water resistant to 200 meters, 20 ATM, 660 feet, individually tested',

  'Weight - 150g'
  'Weight - 150g'
  'Weight - 150g'
  'Weight - 175g'
  'Weight - 175g'
  'Weight - 175g'
  'Weight 115gr',
  'Weight 200gr',
  'Weight 45g',
  'Weight: 185gr with stainless steel bracelet',
  'Weight: 64 g'
  'Weight: 72gr',
  'Weight: 72gr',
  'Weight: 72gr',
  'Weight: 72gr',
  'Weight: 72gr',
  'Weight: 73 g'
  'Weight: 73 g'
  'Weight: 75 g'
  'Weight: 76 g'
  'Weight: 76 g'
  'Weight: 76 g'
  'Weight: 76 g'
  'Weight: 84gr',
  'Weight: 84gr',
  'Weight: 84gr',
  'Weight: 89g'
  'Weight: 89g'
  'Weight: 95grams with leather strap',
  'Weight: 98 g'
  'Weight: 98 g'
  'Weight: 98 g'

  'White Fiberglass Case',

  'White signature silicone strap with brushed stainless steel signature buckle, loop-lock, 19mm',

  'Width of Strap: 24 mm',
  'Width of Strap: 24 mm',
  'Width of Strap: 24 mm',
  'Width of Strap: 24 mm',
  'Width of Strap: 24 mm',
  'Width of Strap: 24 mm',
  'Width of Strap: 24 mm',
  'Width of Strap: 24 mm',
  'Width of Strap: 24 mm',
  'Width of Strap: 24mm',
  'Width of Strap: 24mm',
