const u = [
"Bullet Points | Bullet indices and embossed bullet crown.",
"12mm Custom Leather | Custom leather band with a custom buckle.",
"12mm Steel | 3 link bracelet with a stainless steel locking clasp.",
"20 mm | American alligator or ostrich band with steel fasteners at the lugs and a steel deployant clasp.",
"22mm Steel 3 Link | Band with a custom solid stainless steel double locking clasp with micro adjust.",
"23mm Steel 3 Link | with 1.5mm hex head screw pins, Sport Fit extension clasp, Double locking clasp closure.",
"28-22 mm Steel 3 Link | With screw pin construction and a custom solid stainless steel butterfly clasp.",
"3-Hand | Miyota Japanese quartz 3 hand movement.",
"40 mm, 100 meter/10 ATM | Steel Case",
"44 mm, 100 meter/10 ATM | Steel Case",
"44mm, 200 meter/20 ATM | Steel Case",
"46mm, 200 meter/20 ATM | Stainless Steel",
"All In Your Chain | Unique chiseled link 30mm-23mm bracelet with custom molded band construction featuring chamfered edges.",
"Automatic Movement | Applied numbers and indices on dial & ring. Printed seconds track on ring. Hands with superlum fill",
"Band Comfort | Light 20mm injected molded polyurethane band with patented locking looper and polycarbonate buckle",
"Band | Stainless steel 5 link bracelet in black with stainless steel double locking clasp with micro adjust.",
"Basic Throwback | Reminiscent of an era when time travel seemed possible, or probable",
"Black Light Art | Hidden cover art can only be revealed with black light.",
"Bracelet Style | 19.5mm custom milanese stainless steel jewelry style bracelet and stainless steel locking clasp.",
"Bracelet Style | 32mm, 5ATM, custom stainless steel tank case with hardened mineral crystal and custom crown with Nixon icon inlay.",
"Brash with Brains | Proof that it’s possible to be simultaneously flashy and tough while still getting the job done",
"Bullet Points | Bullet indices and embossed bullet crown.",
"Business or Pleasure | A timeless 42 mm design with the modern Nixon twist of faceted applied hour indices",
"CUSTOM CASE | 34mm custom injection molded stainless steel case with perforated stainless steel speaker cover and pushers, with micro USB charging port. Dust proof case; basic splash resistance, please do not submerge Dork Too or it might geek out",
"CUSTOM DIGITAL LCD | With edge to edge crystal. Functions include time, date, alarm and EL backlight.",
"Chrono and Date | 6-hand chronograph, 24-hour subdial, printed seconds track and date window at 4 o’clock",
"Classic | 3-hand movement with applied indices and custom molded hands",
"Classic | 3-hand movement, applied indices and custom-molded hands",
"Classics Mashup | A marriage between two of our all-time best-sellers, the Time Teller and Corporal, an unpretentious, versatile appearance that works anywhere anytime",
"Clean Lines | 3 hand movement with understated contemporary appeal.",
"Color Pop | Powerful in appearance and spirit with 24 vibrant colors combinations to choose from",
"Color Pop | Powerful in appearance and spirit with 4 vibrant, translucent colors.",
"Comfort | Custom 5-link stainless steel jewelry style bracelet with sliding buckle for secure fit",
"Comfort | Jewelry-style, 5-link tapered bracelet band with sliding buckle for quick adjustment",
"Comfort | Light 20 mm injected molded polyurethane band with patented locking looper and polycarbonate buckle",
"Comfort | Tapered 5-link jewelry style bracelet with stainless steel locking clasp",
"Contemporary Dial | Clean contemporary dial features printed indices and 3-hand movement with custom molded hands",
"Cracked-up | Custom ‘Cracked’ dial and crown.",
"Custom Band | Custom leather removabel rocker cuff and strap.",
"Custom Band | Engraved links on a stainless steel bracelet.",
"Custom Band | Genuine Horween leather band with “Seek and Destroy” internal print.",
"Custom Band | Textured center links on a stainless steel bracelet.",
"Custom Dial | Custom Horween leather textured dial.",
"Custom Dial | Limited Edition with One Eye Open at 12. Custom claw hand subdials and copper planchette subdial from Ouija board.",
"Custom Dial | ‘Pushead’ artwork is printed on dial.",
"Custom Dial | ‘Ride the Lightning’ custom dial.",
"Custom Display | Customizable display layout allows you to view any two functions simultaneously. Functions include: Time of day, day/date with auto calendar through 2099, chronograph with 1/100 second resolution, timer, and alarm.",
"Custom Display | Customizable home screen, including 550 pre-programmed locations with precise tide, sun, & moon data.",
"Custom Hands | Custom ‘Nail’ hour and minutes hands.",
"Custom Hour Hand | Custom ‘Metallica Hammer’ hour hand.",
"Custom Indices | Shifted album color indices",
"Custom Seconds Hand | Custom ‘Metallica Sword’ seconds hand.",
"DESIGN | 23mm case with an edge-to-edge crystal gives you just enough design with maximum style.",
"DESIGN | A utility belt for your wrist.",
"DESIGN | Function meets comfort with a 22mm custom injection molded ultra-soft silicone band.",
"DESIGN | Good style that doesn’t take itself too seriously. The Clutch is inspired by rejecting the status quo and looking at life through your own lens.",
"DESIGN | Influenced by traditional dive watch style. It’s a classic look with more modern, multi-layered, face details and custom-designed elements like the shark tooth-knurled crown.",
"DESIGN | Inspired by classic timepiece heritage, the Time Trackers design is a fresh flip on retro. The clean, open face lets the case and band share the spotlight.",
"DESIGN | Like the control panel on a ship’s bridge, the Ascender’s movement and functionality are a nod to the gauges and dials needed for seafaring.",
"DESIGN | Modeled after heritage watches, the Medium Time Teller was created to have a timeless silhouette with a modern spin.",
"DESIGN | Modeled after watches that passed down from generation to generation, the Time Teller Medium is a classic silhouette with a modern spin.",
"DESIGN | Modeled after watches that were passed down from generation to generation, the Time Teller was created to have a classic silhouette with a modern spin.",
"DESIGN | Pushing against the notion that watches had to fade into the background of an outfit, the 51-30 is designed to go big in every sense.",
"DESIGN | Taking a classic watch design and adding elements of dimensionality and detail. It’s how Nixon does dressy.",
"DESIGN | Taking the field watch and giving it an upgrade, the Corporal is inspired by troop transports, bank vaults, and racing tachometers",
"DESIGN | The Arrow takes menswear-inspired details and pairs it with Scandanavian design cues for a strong style that isn’t overly masculine.",
"DESIGN | The Arrow takes menswear-inspired details and pairs it with Scandinavian design cues for a strong style that is perfectly feminine.",
"DESIGN | The Arrow takes menswear-inspired details and pairs it with Scandinavian design cues for a strong style that isn’t overly masculine.",
"DESIGN | The Clique plays off its namesake with the adaptability of a social butterfly, easily moving between settings and styles with grace. A wide variety of color choices means there’s something for everyone and the versatile design is ideal for dressing up or down.",
"DESIGN | The Clique plays off its namesake with the adaptability of a social butterfly, effortlessly moving between settings and styles. The silhouette is the perfect size and shape, making it easy to read and hard to ignore.",
"DURABILITY | 100m /10 ATM waterproof rating lets you go from dry to wet environments with confidence.",
"DURABILITY | 38mm custom molded polycarbonate case.",
"DURABILITY | A custom leather band and custom and custom buckle guards against the everyday impacts from the world at large.",
"DURABILITY | A custom leather band with custom buckle protects against the wear and tear of daily use.",
"DURABILITY | A custom solid stainless steel case and hardened mineral crystal guards against the everyday impacts from the world at large.",
"DURABILITY | A custom solid stainless steel case, hardened mineral crystal, triple gasket crown, and custom crown guard protect you against the elements.",
"DURABILITY | A custom stainless steel case with domed hardened mineral crystal stands up to accidental impacts. Triple-gasket crown and stainless steel, screw-down case back for added waterproofing, finished with a custom injected molded TPSiV band.",
"DURABILITY | A custom stainless steel case with domed hardened mineral crystal stands up to accidental impacts. Triple-gasket crown and stainless steel, screw-down case back for added waterproofing.",
"DURABILITY | A custom stainless steel case, hardened mineral crystal, and screw-down case back gives the Time Tracker real-world strength.",
"DURABILITY | A solid stainless steel case protects against the wear and tear of daily use.",
"DURABILITY | A solid stainless steel case with hardened mineral crystal and screw down caseback keeps you guarded against unexpected bumps and scrapes with your surroundings.",
"DURABILITY | A solid stainless steel case with hardened mineral crystal protects against the wear and tear of daily use.",
"DURABILITY | Besides the aesthetic qualities of acetate, the material is lightweight and durable. Because acetate is less rigid than other plastics, it’s more likely to bend and rebound than break.",
"DURABILITY | Custom stainless steel caseback with sliding buckle for secure fit.",
"DURABILITY | Dive-ready 300m water resistance and solid stainless steel construction make the 51-30 one of the burliest pieces in the line.",
"DURABILITY | Durable fiber-reinforced polycarbonate case stands up to everyday impacts while the Silicone over-molded bezel protects the crystal.",
"DURABILITY | Solid stainless steel case and hardened mineral crystal.",
"DURABILITY | Solid stainless steel case, hardened mineral crystal paired with a wide leather strap with 18 different dial/band combinations to choose from.",
"DURABILITY | Two-piece case construction and raised bezel to protect the recessed crystal.",
"Deadly Dial | ‘Kill ‘Em All’ custom dial.",
"Design | An aesthetic throwback to a time when a digital display was the peak of technology. The angled case and silicone over-molded pushers are nods to 1980’s design cues.",
"Design | Clear, informative, and comfortable are the three inspirations behind the Base Tide Pro. Anything that wouldn’t be helpful or functional in the water was stripped away, leaving room to pack more useful features and info.",
"Design | Engineered for a minimal profile with maximum performance, the Heats custom LCD module and timer options give athletes heavy functionality in a featherweight design.",
"Design | Exploring the outer limits of design and manufacturing, the Fifth Element looks both ahead of the curve, yet right on time.",
"Design | Like a high-quality wetsuit, the High Tide design centers around durability and comfort.",
"Design | Like a luxurious off-road SUV, the Ripley was designed to feel at home exploring the wilderness and the city.",
"Design | Medium size fights most wrists with a 32mm stainless steel case with a hardened mineral crystal.",
"Design | Modeled after heritage watches, the Time Teller was created to have a timeless silhouette with a modern spin.",
"Design | Spec-ops gear, luxury off-road SUVs, and briefcases that handcuff to your wrist inspire the raw, rugged, and refined qualities of the Regulus SS.",
"Design | Streamlined for sustainability and all-around comfort. Designed to move freely in and out of the water, its sleek profile is complemented by the soft silicone band that wraps effortlessly around your wrist.",
"Design | Sustainable materials and low-profile performance drive the Staples design cues. A pair of perfectly broken-in skate shoes is an excellent analog to this watchs all-day comfort and reliability.",
"Design | Taking cues from high-end activewear, the Siren is equal parts comfort, function, and style.",
"Design | The 42mm case is an oversized, yet functional, modern take on an heirloom look. Applied indices and custom-molded hands create depth and interest on the face.",
"Design | The Siren takes cues from sustainable, high-end activewear, and aims for equal parts comfort, function, and style.",
"Design | The amenities of life behind the VIP rope and the appreciation of the finer details are at the core of the Porter’s style.",
"Design | The little black dress of timepieces, this is one that everybody should have in their rotation. Its classic case and band shape get complimented by contemporary colors and material accents.",
"Design | The rugged functionality of tactical gear was the main driver behind the Regulus’ aesthetic. Each feature and material was deliberately chosen to meet the exceptional standards of America’s fighting elite.",
"Details | Metallica logo etched on buckle clasp",
"Dial Style | 3-hand movement with applied numerical indices and custom molded hands.",
"Dial Time | The 35mm tank case adds depth to the debutante aesthetic.",
"Dimensional Dial | Custom ‘Multilayer Cross’ dial, embossed, printed, and applied for added dimension.",
"Durability | Besides the aesthetic qualities of acetate, the material is lightweight and durable. Because acetate is less rigid than other plastics, it’s more likely to bend and rebound than break.",
"Durability | Custom TR90 case with hardened mineral crystal and custom water resistant PC pushers.",
"Durability | Custom stainless steel caseback and gasket pushers.",
"Durability | Custom-molded case made from #tide ocean plastics with stainless steel caseback and gasket pushers.",
"Durability | Features a custom stainless steel case, hardened mineral crystal, double gasket crown, and stainless steel screw-down caseback for protection against everyday wear and tear.",
"Durability | Features a custom stainless steel case, hardened mineral crystal, tapered custom leather strap, and stainless steel screw-down caseback for protection against everyday wear and tear.",
"Durability | Features surf-standard 100m waterproof rating, custom, solid stainless steel case, and hardened mineral crystal.",
"Durability | Features surf-standard 100m waterproof rating, custom, solid stainless steel case, custom leather band and hardened mineral crystal.",
"Durability | Fiber-reinforced polycarbonate case with full water-resistant functionality down to 100 meters means you don’t need to hold back when you’re wearing it",
"Durability | Made to withstand any terrain or conditions with shock-absorbent materials, a 5-year battery, and a 100m water-resistant case and pushers so it can take a plunge.",
"Durability | Poron foam between the Regulus’ brain and case gives it a shock-blocking shell, water-resistant pushers give you access to info underwater, and a five-year battery gives you the freedom to head out on any adventure with confidence.",
"Durability | Reinforced with a shock-resistant module and stainless-steel top plate to protect against unexpected impacts.",
"Durability | Solid stainless-steel case and band with hardened mineral crystal.",
"Durability | The custom solid stainless steel milanese case and hardened mineral crystal help protect against the perils of everyday wear.",
"Durability | The geniune leather custom band and stainless steel buckle help protect against the perils of everyday wear.",
"Durability | The hardened mineral crystal and stainless steel case and pushers help protect against the rigors of competitive sport.",
"Durability | The solid stainless steel case and hardened mineral crystal help protect against the perils of everyday wear.",
"Durable Comfort | Steel 3-link bracelet with stainless steel double locking clasp with micro adjust",
"Durable Construction | Highly pure, equally tough surgical-grade 316 L stainless steel case, band, bezel and dial ring",
"FULLY JUICED | Re-chargeable. Just plug it into your USB.",
"Fine Details | Custom ‘Torq Screw’ indices.",
"Flying V | ‘Flying V’ guitar seconds hand.",
"Function and Style | 100 meter/10 ATM water resistant, stainless steel case with custom molded polycarbonate gasketed pushers",
"IT SPEAKS THE TIME | A watch with a real personality, push the button and it says the time and much more. *Dork Too’s voice currently supports English language only",
"Keep it simple | A simple digital display that gives you the tide info you want and need. No more, no less.",
"Leather Band | 21 mm leather gator strap available in 5 colors, with stainless steel buckle",
"Leather Band | Genuine Horween leather band with stainless steel buckle.",
"Lightweight | Minimal case design in a versatile 40 mm package",
"Look Sharp | ‘Metallica Barb’ seconds hand.",
"MOVEMENT | 2-hand movement on a clean dial keep things easy",
"MOVEMENT | A digital watch featuring time, date, future tide times, chronograph and countdown timer.",
"MOVEMENT | Custom digital movement with negative display.",
"MOVEMENT | Miyota Japanese quartz 3 hand",
"MOVEMENT | Miyota Japanese quartz 3 hand movement and crown placement at 3 o’clock.",
"MOVEMENT | Miyota Japanese quartz 3 hand movement with date and day of the week function",
"MOVEMENT | Miyota Japanese quartz 3 hand with bilingual day and date (English/Spanish).",
"MOVEMENT | Miyota Japanese quartz 3 hand.",
"MOVEMENT | Miyota Japanese quartz 4 hand movement featuring day, date, and moon phase function.",
"MOVEMENT | Swiss-made quartz 3 hand movement with date function.",
"Modern Details | Custom molded hands and enamel filled 3 o’clock crown",
"Movement | 100 Meter / 10 ATM",
"Movement | 100 Meter/ 10 ATM",
"Movement | 100 Meter/10ATM",
"Movement | 3 hand analog with an enhanced digital module (°C/°F thermometer and m/ft altimeter)",
"Movement | Custom digital LCD module encased in a protective PU jacket and Poron foam padding.",
"Movement | Custom digital LCD module with dual independent mode loops. Functions include time of day, day/date with auto calendar through 2099, chronograph with 1/100 second resolution, timer, alarm, and EL backlight. Display layout allows for any two functions to be displayed simultaneously.",
"Movement | Custom digital LCD module. Functions include time of day, day/date with auto calendar through 2099, chronograph, pre-set timers and custom timer setting options with a 60 second SEND notification, and EL backlight which can be activated in any mode by pressing both pushers simultaneously.",
"Movement | Custom digital module",
"Movement | Custom digital module with front-lit, high-resolution MLCD.",
"Movement | Custom digital module with pre-programmed tide information for 550 beaches around the world. Functions include time of day (12 hour or 24 hour), day/date, sunrise / sunset data, future and past tide, dual time, 3 types of alarms, countdown timer, wave counter, chronograph and an EL backlight.",
"Movement | Custom multi-function digital module",
"Movement | Miyota Japanese quartz 3 hand",
"Movement | Miyota Japanese quartz 3 hand movement",
"Movement | Miyota Japanese quartz 3 hand movement and crown placement at 3 o’clock.",
"Movement | Miyota Japanese quartz 3 hand with bilingual day and date (English/Spanish).",
"Movement | Miyota Japanese quartz 3 hand.",
"Movement | Miyota Japanese quartz 6 hand with crown placement at 9 oclock",
"Movement | Premium Miyota 8215 Japanese automatic movement. Twenty-one jewel, three hand with date function. A unidirectional tungsten fly wheel winding system with a 40-hour power reserve.",
"Nothing Square About It | Custom molded rectangle dial, applied indices, custom molded hands.",
"Original Nixon Design | Our all-time best-seller taken down a notch to a 31mm case",
"Original Nixon Design | Our all-time best-seller with an unpretentious, versatile appearance that works anywhere anytime",
"Original Nixon Design, Downsized | Our all-time best-seller taken down a notch to a 31mm case",
"RETRO-MODERN | A contemporary take on a clean timeless style.",
"Rugged Band | Solid stainless steel 3-link bracelet with double locking clasp and micro adjust",
"SPECIAL FEATURE | Custom jewelry style bracelet with sliding buckle or leather band with buckle fits just about everyone.",
"SPECIAL FEATURE | Custom jewelry style, three-link acetate bracelet with double-locking clasp.",
"SPECIAL FEATURE | Custom palm tree second hand and custom Milanese stainless steel jewelry style bracelet upgrade the Time Teller to a watch with class and a hint of sass.",
"SPECIAL FEATURE | Custom palm tree second hand and striking lume accents give you details to love day or night.",
"SPECIAL FEATURE | Custom-molded hands, including an arrow-shaped second hand. Printed indices and sunray treatment on the dial.",
"SPECIAL FEATURE | Custom-molded hands, including an palm tree-shaped second hand. Printed indices and sunray treatment on the dial.",
"SPECIAL FEATURE | Dial details include applied Nixon wordmark and hour markers as well as printed numbers and custom molded hands.",
"SPECIAL FEATURE | Features a unique date subdial at 12 oclock with the day of the week subdial at 4 oclock, as well as a slinky, milanese band.",
"SPECIAL FEATURE | Simplified negative LCD for easy underwater reading.",
"SPECIAL FEATURE | Tapered lugs connect to the band, giving it a seamless look. Micro-adjusting clasp makes getting the precise fit simple.",
"SPECIAL FEATURE | Tapered, custom, solid stainless steel 3-link bracelet with double locking clasp and micro-adjust gives you a precise fit for all-day comfort.",
"SPECIAL FEATURE | The 5-panel LCD features time, day, date, alarm, chronograph, countdown timer, and thermometer. The soft, free-swing silicone band hinges at the case give you all-day wearability—in and out of the water.",
"SPECIAL FEATURE | The crown and pushers are located on the 9 oclock side of the case instead of 3 oclock to prevent wrist bite during active use. Uni-directional rotating bezel for an analog countdown timer. Six-hand chronograph with 24hr and second timer subdials.",
"SPECIAL FEATURE | The inner dial ring acts as a calendar, with days of the month tracked by the four-hand movement. Moon phase function lets you know how much moonlight you’ll have to navigate with",
"SPECIAL FEATURE | The shark tooth knurled crown is framed with the built-in crown protector. Crown is placed at 9 o’clock to prevent “wrist bite” during activities. Also features a unidirectional rotating bezel for an analog countdown timer.",
"Shifted Logo | Shifted Metallica logo.",
"Silky Smooth | 19mm SS Milanese band with custom buckle and slider for quick size adjustment.",
"Slim and Versatile | Petite 26 mm case with unique metal tones and complementary colors",
"Special Feature | 24-hour markers line the inner bezel for easy access to military time.",
"Special Feature | Basic tide high/low tide functionality, chronograph, and countdown timer. Plus, the patented Locking Looper™ keeps the band secure.",
"Special Feature | Custom jewelry style, three-link acetate bracelet with double-locking clasp.",
"Special Feature | Engraved and printed indices give the dial detail and depth.",
"Special Feature | Equipped with digital altimeter and temperature readouts, dual chronograph, day/date, second timezone, and alarm. Digital features can be turned off for a sleeker look in City Mode.",
"Special Feature | Features dual chronograph timers, three independent alarms, adjustable LED brightness for light-sensitive situations, and a silent mode that keeps you stealthy.",
"Special Feature | Pre-programmed tide information for 550 global beaches, including high/low tide time and height, as well as sunrise/sunset. Also features date, chronograph timer, three alarms, backlight, and our patented Locking Looper™. The display can toggle between tide graph and date, depending on your preference.",
"Special Feature | Pre-programmed with tide information for 550 beaches around the world with current, future, and past tide time with height coefficient, as well as sunrise/sunset data. A water-channeling pattern on the inside of the band keeps moisture from getting trapped against your skin.",
"Special Feature | Thanks to the rad new coin flip feature, The Staple makes important decisions simple. Whether it’s what’s for dinner or you next adventure The Staple knows which road to take.",
"Special Feature | The Final Countdown timer has a 60 second SEND notification to push you through the finish line.",
"Special Feature | The Re-Run covers all the basics—digital calendar, dual time, alarm, countdown timer, and light. The jewelry-style bracelet with stainless steel locking clasp adjusts to fit most wrists quickly and comfortably.",
"Special Feature | The unique two-piece design eliminates the need for a traditional caseback, while the split window gives a view of the inner workings of the automatic movement and the custom crystal shape flows seamlessly into the case with angled edges. The domed dial features LUME block indices and LUME accents on the hands for visibility even in low light conditions.",
"Special Feature | Toggle between basic tide functionality and date. It also features a chronograph, and countdown timer.",
"Special Feature | Ultra-thin, tapered case for minimal weight and maximum wearability.",
"Stands Proud | 34mm, 50 METER / 5 ATM custom stainless steel rectangle case, with a razor thin hardened mineral crystal that stands up proud away from the case, custom molded crown, stainless steel screw down case back.",
"Strap in | A 22mm custom nylon band thats made extra strong with ultra tough Velcro and a solid stainless steel buckle.",
"Swiss Made Automatic Movement | Applied indices and custom molded hands.",
"Swiss made 3 hands mechanical automatic | Concave dial ring with luminous indices and a CD textured dial with custom molded hands.",
"Swiss made 3 hands mechanical automatic | Red ruby or a real diamond set at 6 hour, a concave dial ring and custom hands.",
"The Right Fit | Medium size fights most wrists with a 32mm stainless steel case and a hardened mineral crystal.",
"Tide-teller | A custom digital module features time of day, date, basic tide, future tide, chronograph, timer and more.",
"Time and Date | All digital calendar, countdown timer, chronograph and light on a negative display LCD",
"Time, Date & More | All the essentials—time, day, date, alarm, chronograph, countdown timer and thermometer for air temp",
"Vivid Screen | Custom digital display with negative LCD display for sharp contrast",
"WATER RATING | 100 Meter / 10 ATM",
"WATER RATING | 300 Meter / 30 ATM",
"WATER RATING | 50 METER / 5 ATM",
"WATER RATING | 50 Meter / 5 ATM",
"Water Rating | 100 METER / 10 ATM",
"Water Rating | 100 Meter / 10 ATM",
"Water Rating | 100 Meter/10ATM",
"Water Rating | 30 Meter / 3 ATM",
"Water Rating | 300 Meter /30 ATM",
"Water Rating | 50 Meter / 5 ATM",
"Withstand the elements | 38mm, 100 meter/10 ATM, custom injection molded case with stainless steel accents that can take on any tide.",
];

module.exports = u;