const cfg = {
  '1': {
    "base": "https://www.rolex.com",
    "strategy": "rolex",
    "entry": "https://www.rolex.com/en/sitemap.xml",
    "brand": "Rolex",
  },
  '2': {
    "base": "https://www.tudorwatch.com",
    "strategy": "tudor",
    "entry": "https://www.tudorwatch.com/sitemap-en.xml",
    "brand": "Tudor",
  },
  '4': {
    "base": "https://www.iwc.com",
    "strategy": "iwc",
    "entry": "https://www.iwc.com/en.sitemap.xml",
    "brand": "IWC",
  },
  '16': {
    "base": "https://www.jaeger-lecoultre.com",
    "strategy": "jaegerlecoultre",
    "entry": "https://www.jaeger-lecoultre.com/us/en/home-page.html",
    "brand": "Jaeger LeCoultre",
  },
  '20': {
    "base": "https://www.omegawatches.com/en-us",
    "strategy": "omega",
    "entry": "https://www.omegawatches.com/en-us/watches",
    "brand": "Omega",
  },
  '26': {
    "base": "https://www.mauricelacroix.com",
    "strategy": "mauricelacroix",
    "entry": "https://www.mauricelacroix.com/media/sitemap_ch_en.xml",
    "brand": "Maurice Lacroix",
  },
  '32': {
    "base": "https://www.bulgari.com",
    "strategy": "bulgari",
    "entry": "https://www.bulgari.com/en-us/watches/",
    "brand": "Bvlgari",
  },
  '46': {
    "base": "https://www.hublot.com",
    "strategy": "hublot",
    "entry": "https://www.hublot.com/en-us/watches",
    "brand": "Hublot",
  },
  '52': {
    "base": "https://www.blancpain.com",
    "strategy": "blancpain",
    "entry": "https://www.blancpain.com/en/product-finder",
    "brand": "Blancpain",
  },
  '54': {
    "base": "https://www.tagheuer.com/us/en",
    "strategy": "tagheuer",
    "entry": "https://www.tagheuer.com/us/en/sitemap_1-image.xml",
    "brand": "Tag Heuer",
  },
  '56': {
    "base": "https://www.piaget.com",
    "strategy": "piaget",
    "entry": "https://www.piaget.com/sitemap.xml",
    "brand": "Piaget",
  },
  '62': {
    "base": "https://www.hamiltonwatch.com/en-us",
    "strategy": "hamilton",
    "entry": "https://www.hamiltonwatch.com/pub/mediam2/sitemap/sitemap_en_us.xml",
    "brand": "hamilton",
  },
  '70': {
    "base": "https://www.chanel.com",
    "strategy": "chanel",
    "entry": "https://www.chanel.com/us/",
    "brand": "Chanel",
  },
  '76': {
    "base": "https://www.casio.com",
    "strategy": "casio",
    "entry": "https://www.casio.com/products/watches",
    "brand": "Casio",
  },
  '82': {
    "base": "https://www.tissotwatches.com",
    "strategy": "tissot",
    "entry": "https://www.tissotwatches.com/media/sitemap/sitemap_en_en.xml",
    "brand": "Tissot",
  },
  '84': {
    "base": "https://www.grand-seiko.com/us-en/collections/",
    "strategy": "grand-seiko",
    "entry": "https://www.grand-seiko.com/__api/posts/list",
    "brand": "Grand Seiko",
  },
  '100': {
    "base": "https://www.orientwatchusa.com",
    "strategy": "orient",
    "entry": "https://www.orientwatchusa.com",
    "brand": "Orient",
  },
  '112': {
    "base": "https://www.bellross.com",
    "strategy": "bellross",
    "entry": "https://www.bellross.com/our-collections",
    "brand": "Bell & Ross",
  },
  '118': {
    "base": "https://www.breitling.com",
    "strategy": "breitling",
    "entry": "https://www.breitling.com/us-en/sitemap/collections.xml",
    "brand": "Breitling",
  },
  '120': {
    "base": "https://www.longines.com/",
    "strategy": "longines",
    "entry": "https://www.longines.com/en-us/watches",
    "brand": "Longines",
  },
  '130': {
    "base": "https://us.louisvuitton.com",
    "strategy": "lv",
    "entry": "",
    "brand": "Louis Vuitton",
  },
  '132': {
    "base": "https://www.breguet.com",
    "strategy": "breguet",
    "entry": "https://www.breguet.com/en/timepieces",
    "brand": "Breguet",
  },
  '134': {
    "base": "https://nomos-glashuette.com",
    "strategy": "nomosglashuette",
    "entry": "https://nomos-glashuette.com/en/watchfinder",
    "brand": "Nomos Glashuette",
  },
  '158': {
    "base": "https://www.parmigiani.com",
    "strategy": "parmigiani",
    "entry": "https://www.parmigiani.com/en/",
    "brand": "Parmigiani Fleurier",
  },
  '160': {
    "base": "https://www.rado.com",
    "strategy": "rado",
    "entry": "https://www.rado.com/sitemap.xml",
    "brand": "Rado",
  },
  '162': {
    "base": "https://www.ulysse-nardin.com/row_en",
    "strategy": "ulysse",
    "entry": "https://www.ulysse-nardin.com/row_en/",
    "brand": "Ulysse Nardin",
  },
  '164': {
    "base": "https://www.oris.ch/watch/",
    "strategy": "oris",
    "entry": "https://www.oris.ch/api/en/home/getcollections",
    "brand": "Oris",
  },
  '168': {
    "base": "https://www.glashuette-original.com/",
    "strategy": "glashuette",
    "entry": "https://www.glashuette-original.com/",
    "brand": "Glashuette Original",
  },
  // '172': {
  // website
  //   "base": "https://www.midowatches.com",
  //   "strategy": "mido",
  //   "entry": "https://www.midowatches.com/us/swiss-watches-collections",
  //   "brand": "mido",
  // },
  '172': {
    "base": "https://www.midowatches.com/us/",
    "strategy": "mido",
    "entry": "https://www.midowatches.com/us/sitemap.xml",
    "brand": "mido",
  },
  '178': {
    "base": "https://www.baume-et-mercier.com/us/en",
    "strategy": "baumemercier",
    "entry": "https://www.baume-et-mercier.com/us/en/sitemap.xml",
    "brand": "Baume et Mercier",
  },
  '180': {
    "base": "https://www.sinn.de",
    "strategy": "sinn",
    "entry": "https://www.sinn.de/en/",
    "brand": "Sinn",
  },
  '188': {
    "base": "https://shop.ballwatch.ch",
    "strategy": "ball",
    "entry": "https://shop.ballwatch.ch/en/watchfinder",
    "brand": "Ball",
  },
  '192': {
    "base": "https://www.hugoboss.com",
    "strategy": "hugoboss",
    "entry": "",
    "brand": "Hugo Boss",
  },
  '214': {
    "base": "https://www.marcjacobs.com",
    "strategy": "marcjacobs",
    "entry": "https://www.marcjacobs.com/the-marc-jacobs/the-accessories/watches/?start=0&sz=100",
    "brand": "Marc Jacobs",
  },
  '240': {
    "base": "https://www.skagen.com/en-us",
    "strategy": "skagen",
    "entry": "https://www.skagen.com/en-us/sitemap/",
    "brand": "Skagen",
  },
  '244': {
    "base": "https://shop.diesel.com",
    "strategy": "diesel",
    "entry": "https://shop.diesel.com/en/home",
    "brand": "Diesel",
  },
  '250': {
    "base": "https://www.guess.com/us/en",
    "strategy": "guess",
    "entry": "https://www.guess.com/us/en",
    "brand": "Guess",
  },
  '252': {
    "base": "https://usa.tommy.com",
    "strategy": "tommyhilfiger",
    "entry": "https://usa.tommy.com/static/sitemap.xml",
    "brand": "Tommy Hilfiger",
  },
  '254': {
    "base": "https://www.tutima.com",
    "strategy": "tutima",
    "entry": "https://tutima.com/sitemaps.xml",
    "brand": "Tutima",
  },
  '268': {
    "base": "https://intl.bulova.com",
    "strategy": "bulova",
    "entry": "https://intl.bulova.com/sitemap_products_1.xml?from=4298068545&to=4254557372463",
    "brand": "Bulova",
  },
  '280': {
    "base": "https://meistersinger.us/",
    "strategy": "meistersinger",
    "entry": "https://meistersinger.us/shop-tagged/single-hand-watch/",
    "brand": "MeisterSinger",
  },
  '282': {
    "base": "https://www.briston-watches.com/",
    "strategy": "briston",
    "entry": "https://www.briston-watches.com/en/watches/",
    "brand": "Briston",
  },
  '288': {
    "base": "https://alpinawatches.com/",
    "strategy": "alpina",
    "entry": "https://alpinawatches.com/sitemap_products_1.xml?from=4802581004426&to=5853158637730",
    "brand": "Alpina",
  },
  'ptime': {
    "base": "https://www.prestigetime.com",
    "strategy": "prestigetime",
    "entry": "https://www.prestigetime.com/sitemap.xml",
  },
  'mayfair': {
    "base": "https://www.watchesofmayfair.com",
    "strategy": "watchesofmayfair",
    "entry": "https://watchesofmayfair.com/watches?product_list_limit=59",
  },
  'watchmaxx': {
    "base": "https://www.watchmaxx.com",
    "strategy": "watchmaxx",
    "entry": "https://www.watchmaxx.com/sitemap.xml",
  },
  'joma': {
    "base": "https://www.jomashop.com",
    "strategy": "jomashop",
    "entry": "https://www.jomashop.com/media/sitemaps/sitemap.xml",
  },
  'kechiq': {
    "base": "https://www.kechiq.com",
    "strategy": "kechiq",
    "entry": "https://www.kechiq.com/sitemapUS.xml",
  },
};

const qCfg = {
  'indexing': {
    exchange: "scraper",
    route: "crawler",
    replyTo: 'collector',
  },
  'extraction': {
    exchange: "scraper",
    route: "origin",
    replyTo: 'scrape.data.raw',
  },
  'product': {
    exchange: "scraper",
    route: "crawler",
    replyTo: 'scrape.data.raw',
  }
};

module.exports = { cfg, qCfg };