const bandM = [
  "zzzzzzzzzzzzzzzzzzzzz Stainless Steel -18 ct Everose Gold Jubilee",
  "zzzzzzzzzzzzzzzzzzzzz Stainless Steel -18 ct Everose Gold Oyster",
  "zzzzzzzzzzzzzzzzzzzzz Stainless Steel -18 kt Everose Gold Jubliee",
  "zzzzzzzzzzzzzzzzzzzzz Stainless Steel -18kt Everose Gold Oyster",
  "zzzzzzzzzzzzzzzzzzzzz Stainless Steel 18 ct Everose Gold Oyster",
  "zzzzzzzzzzzzzzzzzzzzz Stainless Steel 18kt Everose Gold Oyster",
  "zzzzzzzzzzzzzzzzzzzzz Stainless Steel 18kt Gold",
  "zzzzzzzzzzzzzzzzzzzzz Stainless Steel 316L",
  "zzzzzzzzzzzzzzzzzzzzz Stainless Steel Mesh 18ct",
  "zzzzzzzzzzzzzzzzzzzzz Stainless Steel Rolex Jubilee with18kt Rose Gold",
  "zzzzzzzzzzzzzzzzzzzzz Stainless Steel Rolex Oyster with18kt Rose Gold",
  "zzzzzzzzzzzzzzzzzzzzz Stainless Steel Tubogas (18K Pink Gold)",
  "zzzzzzzzzzzzzzzzzzzzz Stainless Steel wiith 18kt Rose Gold",
  "zzzzzzzzzzzzzzzzzzzzz Stainless Steel wirh 18kt Yellow Gold Rolex Oyster",
  "zzzzzzzzzzzzzzzzzzzzz Stainless Steel with 18kt Yellow Gold bars and Lug",
  "zzzzzzzzzzzzzzzzzzzzz Stainless Steel with18kt Pink Gold Jubilee",
  "zzzzzzzzzzzzzzzzzzzzz Stainless Steel with18kt Rose Gold Bars",
  "zzzzzzzzzzzzzzzzzzzzz Stainless Steel with18kt Yellow Gold",
  "zzzzzzzzzzzzzzzzzzzzz Stainless Steel with18kt Yellow Gold Links",
  "zzzzzzzzzzzzzzzzzzzzz Stainless Steel with18kt Yellow Gold Rolex Jubilee",
  "zzzzzzzzzzzzzzzzzzzzz Stainless Steel- 18 ct Everose Gold Jubliee",
  "zzzzzzzzzzzzzzzzzzzzz Stainless steel and18kt Rose Gold",
];

module.exports = bandM;