const caliber = [
  "  Automatic",
  "  Manual-winding",
  " Self winding",
  "AUTOMATIC",
  "Auto-Quartz",
  "Automatic",
  "Automatic Chronometer",
  "Automatic Digital",
  "Automatic chronograph, Swiss Made",
  "Automatic mechanical",
  "Automatic with manual winding capacity",
  "Automatic with manual winding mechanism",
  "Automatic, Swiss Made",
  "Automatic, self-winding",
  "Automatik",
  "Automatik-Chronometer",
  "Eco Drive",
  "Eco-Drive",
  "GPS Solar",
  "Glashütte Original manufactory movement",
  "Glashütte Original manufactory movement, German chronometer certificate (LMET/SLME)",
  "Glashütte Original manufactory movement, Glashütte Original certificate",
  "Hand Wind",
  "Hand Winding",
  "Hand wind",
  "Hand winding, Swiss Made",
  "Hand-winding",
  "Hand-wound mechanical",
  "Handaufzug",
  "Handaufzug über Drehmomentwerkzeug",
  "Handwound",
  "MANUAL",
  "MANUALFunctions: Hours, minutes",
  "MANUALFunctions: Hours, minutes and seconds",
  "Manual",
  "Manual Wind",
  "Manual using a dynamometric starter",
  "Manual-winding",
  "Mechanical manual winding",
  "Mechanical manual-winding movement",
  "Processor",
  "QUARTZ ANALOG",
  "QUARTZ ANALOGFunctions: Hours, minutes",
  "Quartz",
  "Quartz chronograph",
  "Quartz chronograph, Swiss Made",
  "Quartz, Swiss Made",
  "Quarz",
  "Radio sync solar",
  "Self-winding",
  "Self-winding movement",
  "Skeleton, Swiss Made",
  "Solar",
  "Spring Drive",
  "Spring drive",
  "Swiss Tissot automatic chronograph",
  "Swiss automatic",
  "Swiss quartz",
  "Tissot",
  "Tourbillon, Swiss Made",
  "automatic",
  "hand wind",
  "manual",
  "manual-winding mechanical movement",
  "mechanical",
  "quartz",
  "self-winding mechanical movement"
];

module.exports = caliber;