const caseback = [
  "\"Roulette\"",
  "18K Rose Gold, Solid, secured via 8 gold screws",
  "18Kt White Gold",
  "18k Pink Gold, engraved",
  "18k Rose Gold",
  "18k Rose Gold embossed with Mille Miglia route map",
  "18k Rose Gold embossed with Mille Miglia route, secured by 8 steel screws",
  "18k Rose Gold with Sapphire Crystal Exhibition",
  "18k Rose Gold with engraving 'International Watch Co.' and Serial Number",
  "18k Rose Gold, engraved",
  "18k Yellow Gold",
  "18k Yellow Gold Engraved",
  "18kt Yellow Gold, engraved",
  "Additional 12 Hour Hand",
  "Aluminium",
  "Anti-reflective domed sapphire crystal",
  "Anti-reflective sapphire crystal",
  "Antireflective sapphire crystal",
  "Bathyscaphe Chronographe Flyback",
  "Batman medallion engraved on the case back with RJ",
  "Black",
  "Black Ceramic with Hublot Logo",
  "Black PVD",
  "Black PVD Coated Titanium",
  "Black PVD Titanium",
  "Black PVD coaeted titanium grade 2",
  "Black PVD coated Stainless Steel",
  "Black PVD sandblasted screwed case-back",
  "Black Plastic",
  "Black Titanium Screw Down back with guilloche pattern",
  "Black Titanium Screw In back with guilloche pattern",
  "Black Titanium Screw-in back with guilloche pattern",
  "Blue Translucent",
  "Blued SDemi-translucent",
  "Brushed and Polished Solid 316L Surgical Grade Silvertone Stainless Steel",
  "Burnished see-through sapphire crystal",
  "Carbon fiber engraved \"LIMITED EDITION + 100NUM\" lacquered purple. Case back glass: Sapphire with interior anti-reflective treatment, printed logo \"Womanity\"",
  "Case back with screws",
  "Case-back sapphire crystal decorated with the logo of the Principality of Monaco",
  "Checker Flag Decorated",
  "Chronographe Flyback",
  "Chronographe Flyback Pulsomètre",
  "Circular Steel fine-brushed Screw",
  "Circular Steel fine-brushed Screw In with special checked decoration",
  "Circular Steel fine-brushed Screwed In with special checked decoration",
  "Clear",
  "Closed",
  "Closed and decorated with aguilloche pattern on both sides",
  "Closed back, stainless steel",
  "Closed with 6 screws",
  "Commemorative Engraving",
  "Composite",
  "Crystal",
  "Crystal Plexi Glass",
  "DMC medallion engraved on the case back",
  "Display winning entry in the International Children's Drawing Competition",
  "Domed sapphire crystal glass back",
  "Double O-ring",
  "Double dial",
  "Double fond, transparent sapphire crystal",
  "Driven, Steel",
  "Embossed Solid",
  "Engraved",
  "Engraved GG",
  "Engraved Jaeger-LeCoultre and Aston Martin Logos",
  "Engraved Major Cities Time Zones",
  "Engraved Solid",
  "Engraved Stainless Steel",
  "Engraved Time Zones On Caseback",
  "Engraved Titanium",
  "Engraved Weight Conversion Scale",
  "Engraved Yves Behar Signature",
  "Engraved case back depicting the flame of the Liberty lighting up the stars and stripes of the American flag",
  "Engraved case-back",
  "Engraved times zones of world's major cities",
  "Engraved with anniversary inscription- outline of Aermacchi aircraft flown by Frecce Tricolori",
  "Engraved with the winning entry in the \"Time to celebrate\" drawing competition",
  "Engraved with time zones of world's major cities",
  "Erupting Eyjafjallajokull engraving",
  "Etched",
  "Exhibition",
  "Exhibition Caseback with sapphire crystal",
  "Exhibition Screw Down",
  "Exhibition See Through",
  "Exhibition Snap Down",
  "Exhibition Style See Through",
  "Exhibition screw-down",
  "Full back",
  "Gold color stainless steel",
  "Gold plated stainless steel",
  "Gold-tone Stainless Steel",
  "Grainy-textured stellar-patterned back with Moon SilverRJ medallion. RJ safety screw on the case back, exclusively accessible to watchmakers",
  "Grainy-textured stellar-patterned back with Moon medallion in MOON SilverRJ. RJ safety screw on the case back, exclusively accessible to watchmakers",
  "Grainy-textured stellar-patterned back with Moon medallion in Moon SilverRJ",
  "Grainy-textured stellar-patterned back with Moon medallion in Moon SilverRJ. RJ safety screw on the case back exclusively accessible to watchmakers",
  "Grainy-textured stellar-patterned back with Moon medallion in Moon SilverRJ. RJ safety screw on the case back, exclusively accessible to watchmakers",
  "Grainy-textured stellar-patterned back with PAC-MAN medallion. RJ safety screw on the case back, exclusively accessible to watchmakers",
  "Grainy-textured stellar-patterned back with moon silver medallion",
  "Grainy-textured stellar-patterned case back with moon silver",
  "Grainy-textured stellar-patterned case back with moon silver medallion",
  "Grainy-textured stellar-patterned with Pokemon medallion in circular-brushed steel. RJ safety screw on the case back, exclusively accessible to watchmakers",
  "Grainy-textured stellar-patterned with Super Mario Bros. medallion. RJ safety screw on the case-back, exclusively accessible to watchmakers",
  "Grainy-textured stellar-patterned with Tetris medallion. RJ safety screw on the case back, exclusively accessible to watchmakers",
  "Green Translucent",
  "Guilloche with Sapphire Window",
  "Gunmetal PVD",
  "Gunmetal PVD Stainless Steel",
  "Half Skeleton",
  "Half Stainless Steel / Skeleton",
  "High-intensity titanium and sapphire crystal",
  "Hinged Caseback Cover of Vitreous Enamel",
  "Hinged Solid",
  "Hunter",
  "Iceland map engraving",
  "Individual series number engraved on the case-back",
  "Interchangeable",
  "Interchangeable full back and sapphire crystal case back",
  "Latin Grammy Logo",
  "Light Blue",
  "Logo-Engraved Solid",
  "Luminous Green",
  "Luminous Transparent",
  "Luyminous White",
  "Mineral Crystal Skeleton",
  "Non screw-locked, two gaskets, integrated pushpiece",
  "None",
  "Octopus engraving",
  "Official Blue Angels Insignia",
  "Opalescent Sapphire Crystal",
  "Open",
  "Open case back with sapphire crystal fixed with screws",
  "Open case-back with sapphire crystal fixed with screws",
  "Open, sapphire crystal (glass)",
  "Orange",
  "Orange Skeleton",
  "Orange Transparent",
  "Other Dial",
  "Partial Exhibition",
  "Partial Exhibition Screw Down",
  "Partial Exhibition Srew Down",
  "Partial Exhibition screw-down",
  "Partial Skeleton",
  "Perforated",
  "Perpetual Calendar\n      \n    ?\n  \n  \n  \n\n\n  \n  \n    \n            Split-second flyback chronograph\n      \n    ?\n  \n  \n  \n\n\n  \n  \n    \n            Moon phases\n      \n    ?",
  "Picture of Columbus Circle engraved with exhibition window",
  "Pink Translucent",
  "Plain - Black PVD coated steel",
  "Plain - Steel",
  "Plastic",
  "Plastic Screw Down",
  "Plastic Screw-down",
  "Platinum with Sapphire Crystal Exhibition",
  "Polished Steel",
  "Polished and satin-finished stainless steel. Sapphire glass (crystal) with interior anti-reflective coating.",
  "Polished screw-in",
  "Polished stainless steel",
  "Polished stainless steel indicating model and production number",
  "Polished stainless steel with NFC chip embedded behind the globe",
  "Polished stainless steel with rose gold PVD treatment",
  "Polished stainless steel.",
  "Pressue Fitted Solid",
  "Pressure Fitted",
  "Pressure Fitted Skeleton",
  "Pressure Fitted Solid",
  "Propeller engraving",
  "Propeller style engraving",
  "Purple Translucent",
  "Red Tinted Mineral Crystal",
  "Red gold and sapphire crystal",
  "Resonant Chamber",
  "Sapphire",
  "Sapphire - Black PVD coaeted titanium grade 2",
  "Sapphire - Black PVD coaeted titanium grade 5",
  "Sapphire - Black PVD coated steel",
  "Sapphire - Scratch-resistant",
  "Sapphire - Steel",
  "Sapphire - Titanium grade 5",
  "Sapphire Crystal",
  "Sapphire Crystal - Scratch Resistant, Transparent Exhibition Back. Transfer on case-back crystal.",
  "Sapphire Crystal - Transparent Exhibition",
  "Sapphire Crystal Case Back",
  "Sapphire Crystal Case back",
  "Sapphire Crystal Display",
  "Sapphire Crystal Display Back showing Guilloche Rotor and Movement",
  "Sapphire Crystal Exhibition",
  "Sapphire Crystal Exhibition Case",
  "Sapphire Crystal See Through",
  "Sapphire Crystal See-Through",
  "Sapphire Crystal Skeleton",
  "Sapphire Crystal Transparent",
  "Sapphire Crystal case back protected by a hinged cover",
  "Sapphire Crystal display",
  "Sapphire Crystal protected by an invisibly-hinged Dust Cover",
  "Sapphire Cyrstal Display",
  "Sapphire Exhibition",
  "Sapphire Exhibition Case",
  "Sapphire Glass",
  "Sapphire Transparent Exhibition",
  "Sapphire back",
  "Sapphire case back",
  "Sapphire case-back",
  "Sapphire crystal",
  "Sapphire crystal display",
  "Sapphire crystal exhibition",
  "Sapphire crystal glass",
  "Sapphire crystal glass back",
  "Sapphire crystal, secured by 4 screws",
  "Sapphire crystal, secured by 6 screws",
  "Sapphire glass",
  "Sapphire glass (crystal)",
  "Sapphire glass (crystal), convex, anti-reflective coating",
  "Sapphire glass (crystal), convex, anti-reflective coating.",
  "Sapphire glass, secured with 6 screws, all inscriptions hand engraved",
  "Sapphire window",
  "Sapphire, none-reflecting coating",
  "Sapphire-crystal",
  "Satin-finished and engraved with the Vintage 1945 Anniversary logo",
  "Satin-finished and engraved with the Vintage 1945 anniversary logo",
  "Satinless Steel",
  "Scratch Resistant Sapphire Crystal",
  "Scratch-resistant sapphire secured with 6 screws",
  "Scre Down Stainless Steel",
  "Screw",
  "Screw Back",
  "Screw Down",
  "Screw Down Black Carbon Reinforced",
  "Screw Down Closed",
  "Screw Down Closed with Engraving",
  "Screw Down Engraved Stainless Steel",
  "Screw Down Engraved with UNITED STATES NAVY FIGHTER WEAPONS SCHOOL Logo, engraving 'Pilot's Watch' and 'INTERNATIONAL WATCH CO.'",
  "Screw Down Sapphire Crystal",
  "Screw Down Sapphire Crystal Exhibition",
  "Screw Down Sapphire Crystal Skeleton",
  "Screw Down See Through",
  "Screw Down See Through skeleton",
  "Screw Down See Through skeleton exhibition",
  "Screw Down Skeletal",
  "Screw Down Skeleton",
  "Screw Down Skeleton See Through",
  "Screw Down Skeleton See-through",
  "Screw Down Skeleton with Small Cross-wind Graph",
  "Screw Down Solid",
  "Screw Down Stainless Steel",
  "Screw Down Stainless Steel engraved",
  "Screw Down Stainless Steel engraved with Leonhard Euler portrait",
  "Screw Down Stainless steel",
  "Screw Down Steel",
  "Screw Down Transparent",
  "Screw Down close",
  "Screw Down exhibition",
  "Screw Down skeletal",
  "Screw Down solid",
  "Screw Down with Checker Motif",
  "Screw Down with Racing Flag motif",
  "Screw Down with Racing Flag motif .",
  "Screw Down with factory Engraved Logo",
  "Screw Down with special Checked Decoration",
  "Screw Down, with Sapphire Crystal",
  "Screw Dwn Stainless Steel",
  "Screw In",
  "Screw In Black Ceramic",
  "Screw In Closed",
  "Screw In Exhibition",
  "Screw In Sapphire Crystal See Through",
  "Screw In Skeleton",
  "Screw In Solid",
  "Screw In Solid with Cartier Roadster engraving and Serial Number",
  "Screw In Stainless Steel",
  "Screw In Stainless Steel with Prancing horse Logo and Geometric Guilloche Decoration",
  "Screw In solid",
  "Screw In, with sound signal resonance chamber",
  "Screw Locked",
  "Screw On",
  "Screw back",
  "Screw back cover in vulcanized rubber engraved with Admiral's Cup trophy medaillon in stainless steel",
  "Screw down",
  "Screw down Skeleton",
  "Screw down Solid",
  "Screw down stainless steel",
  "Screw down stainless steel exhibition",
  "Screw down, stainless steel",
  "Screw fastened",
  "Screw in",
  "Screw, Brushed Steel",
  "Screw, Steel",
  "Screw, Titanium",
  "Screw, Titanium with hard black coating",
  "Screw, steel",
  "Screw, titanium with black coating",
  "Screw-Down",
  "Screw-In",
  "Screw-In Closed",
  "Screw-In Sapphire Crystal Skeletal",
  "Screw-back",
  "Screw-down",
  "Screw-down Exhibition",
  "Screw-down High-Tech Ceramic",
  "Screw-down Stainless Steel",
  "Screw-down Steel",
  "Screw-down see-through",
  "Screw-down solid",
  "Screw-down stainless steel",
  "Screw-fastened",
  "Screw-in",
  "Screw-in Skeleton",
  "Screw-in Stainless Steel",
  "Screw-in with Blue engraving",
  "Screw-in, with two sapphire crystal windows",
  "ScrewDown",
  "Screwed",
  "Screwed Down",
  "Screwed Down Solid",
  "Screwed Down Stainless Steel",
  "Screwed In",
  "Screwed In Case back with Sound Signal Resonance Chamber",
  "Screwed In Solid",
  "Screwed In Stainless Steel",
  "Screwed In with Sound Resonance Chamber",
  "Screwed In, sound signal resonance chamber",
  "Screwed case back",
  "Screwed case back with wide sapphire crystal",
  "Screwed caseback with wide sapphire crystal",
  "Screwed cased back",
  "Screwed in",
  "Screwed in (Limited Edition: sapphire)",
  "Screwed in (sapphire crystal)",
  "Screwed in open back cover in 5N 18K red gold with glare proof sapphire crystal",
  "Screwed in, with sound signal resonance chamber",
  "Screw‑in crown",
  "Secured by 4 screws",
  "Secured by 6 screws",
  "See Through",
  "See Through Sapphire",
  "See Through Sapphire Crystal",
  "See Through Screw Down",
  "See Through Sealed with 6 External Screws",
  "See Through skeleton",
  "See through",
  "See through exhibition crystal",
  "See through sapphire crystal",
  "See- Through",
  "See-Through",
  "See-through",
  "See-through fastened with 6 screws",
  "See-through sapphire",
  "See-through sapphire crystal",
  "See-through sapphire glass (crystal)",
  "See-through sapphire glass back, convex, anti-reflective coating",
  "See-through sapphire-glass (crystal) back with antireflective coating",
  "See-through sapphire-glass back",
  "See-through skeleton",
  "Semi -Transparent",
  "Semi Transparent",
  "Semi-Transparent",
  "Semi-transparent",
  "SemiTransparent",
  "Signature Iconic Case Back Plate with Laser-Etched Serial Number",
  "Silver-Tone",
  "Skeletal",
  "Skeletal Sapphire",
  "Skeletom",
  "Skeleton",
  "Skeleton - Moon Phase",
  "Skeleton Brooklyn Bridge etching",
  "Skeleton Brooklyn bridge etching",
  "Skeleton Exhibition",
  "Skeleton Mineral Glass",
  "Skeleton Plastic",
  "Skeleton Saphire",
  "Skeleton Sapphire",
  "Skeleton Sapphire Crystal",
  "Skeleton Screw Down Display Back, secured by 8 screws",
  "Skeleton Screw-in",
  "Skeleton See Through",
  "Skeleton See-through",
  "Skeleton T",
  "Skeleton Transparent",
  "Skeleton Transparent Exhibition",
  "Skeleton Transparent Exhibition See Through",
  "Skeleton Window",
  "Skeleton exhibition",
  "Skeleton, Crystal Exhibition",
  "Skeleton, See-through",
  "Skeleton, exhibition case back, reveals the rotor.",
  "Smoked see-through sapphire crystal",
  "Snap Back Closed",
  "Snap Back Solid",
  "Snap Down",
  "Snap Down Skeleton",
  "Snap Down Stainless Steel",
  "Snap Down stainless steel",
  "Snap On Stainless Steel",
  "Snap Solid",
  "Snap-Down",
  "Snap-down",
  "Snap-down Stainless Steel",
  "Snap-down Sterling Silver",
  "Snap-in",
  "Snapped",
  "Snapped, Engraved Bee Motif",
  "Soli",
  "Solid",
  "Solid (Bee Motif)",
  "Solid (Bentley GT Continental Engraved)",
  "Solid (Graphic Design)",
  "Solid (Silk-printed Glass)",
  "Solid (Skeletal Window)",
  "Solid (Transparent Outer)",
  "Solid (Window Display)",
  "Solid (engraveable)",
  "Solid (with Skeletal Window)",
  "Solid (with Transparent Outer)",
  "Solid - Embossed with Tiger Woods Signature",
  "Solid - Stainless Steel",
  "Solid - with sound signal resonance chamber",
  "Solid - with transparent sub-dial",
  "Solid 18kt Rose Gold engraved",
  "Solid 18kt Rose Gold secured by 8 screws",
  "Solid 18kt White Gold",
  "Solid Asian Games logo",
  "Solid Back with Ferrari Prancing Horse Logo",
  "Solid Black Ion-plated",
  "Solid Black Polycarbonate",
  "Solid Bronze DLC Stainless Steel",
  "Solid Brown Wood",
  "Solid Brushed Steel",
  "Solid Burma Expresso Wood",
  "Solid Caribbean Map Motif",
  "Solid Dark Brown Wood",
  "Solid Engrave with the word 'LOVE'",
  "Solid Engraved",
  "Solid Engraved with Bridge Logo",
  "Solid Engraved with Zenith Aviation Instruments",
  "Solid Etched",
  "Solid Fixed Stainless Steel",
  "Solid Gold-tone",
  "Solid Gun Metal PVD Stainless Steel",
  "Solid Khaki Tan Wood",
  "Solid Logo Engraved Screw Down",
  "Solid Logo-Engraved",
  "Solid Luminous",
  "Solid Mori Moss Wood",
  "Solid NBA Logo Engraved",
  "Solid Olive Wood",
  "Solid Platinum",
  "Solid Platinum engraved \"PATEK PHILIPPE GENEVE 175th Anniversaire 1839 - 2014\"",
  "Solid Pressure Fitted",
  "Solid Red Wood",
  "Solid Rose Gold",
  "Solid Sakai Natural Wood",
  "Solid Screw Down",
  "Solid Screw In",
  "Solid Screw-down",
  "Solid Screwed In",
  "Solid Snap Down",
  "Solid Stainless Sreel",
  "Solid Stainless Steel",
  "Solid Stainless Steel Plate secured w/ screws",
  "Solid Stainless steel",
  "Solid Steel",
  "Solid Sumatra Wood",
  "Solid Titanium",
  "Solid Titanium Screw",
  "Solid Wood",
  "Solid and Transparent",
  "Solid case back",
  "Solid case back with 100th anniversary engraving",
  "Solid case back with engraving, based on a drawing by 16-year-old Eleni Partakki from Cyprus, show boys and girls playing with a ball.",
  "Solid caseback with skeleton cut-outs",
  "Solid engraved with Fish Symbol and diving mask",
  "Solid hand engraved with octopus design",
  "Solid with \"Harbour at Portofino\" engraving",
  "Solid with 2 Swiss Franc coins",
  "Solid with Constellation Observatory medallion",
  "Solid with Grammy Logo",
  "Solid with Grammy awards Logo",
  "Solid with Heuer coat-of-arms",
  "Solid with Latin Grammy logo and inscription",
  "Solid with Logo of the 17th Asian Games",
  "Solid with Skeletal Window",
  "Solid with Skeleton Window",
  "Solid with Skeleton display",
  "Solid with Temperature Conversion Table",
  "Solid with Titanic engraving",
  "Solid with World Map engraved",
  "Solid with a Skeletal Window",
  "Solid with a Skeleton Window",
  "Solid with divers Helmet logo",
  "Solid with diving-helmet relief",
  "Solid with engraved Temperature Gauge",
  "Solid with engraved with Maurice Lacroix hallmarking, serial numbers and water resistance",
  "Solid with hand-engraved octopus",
  "Solid with skeleton cut-outs",
  "Solid with special back engraving",
  "Solid with special engraving",
  "Solid with the Constellation Observatory medallion",
  "Solid, 18K Rose Gold",
  "Solid, 18k Yellow Gold secured by 8 screws",
  "Solid, Black PVD secured via 8 screws",
  "Solid, Black Steel PVD secured via 8 screws",
  "Solid, Black Titaninm",
  "Solid, Engraved with Pershing Boat",
  "Solid, Screw Down",
  "Solid, Stainless Steel secured by 8 screws",
  "Solid, Stainless Steel, Engraved",
  "Solid, Steel",
  "Solid, Titanium. World Globe Logo Engraved In Center",
  "Solid, engraved 'Pasha de Cartier', 'Automatic', 'Water Resistant 100m/330ft', 'STAINLESS STEEL'",
  "Solid, engraved with Maurice Lacroix hallmarking, serial numbers and water resistance",
  "Solid, inscribed with \"The last man on the moon - December 14, 1972\" and \"Apollo XVII 40th Anniversary\"",
  "Solid, screw-down",
  "Solid. Time set button on case back",
  "Solied",
  "Solued",
  "Special back engraving",
  "Special engraving",
  "Spider web metallized on the sapphire crystal",
  "Sport",
  "Stainles Steel, brushed, engraved, 3mm thick",
  "Stainless Steel",
  "Stainless Steel 'OFFICINE PANERAI FIRENZE 1880 Automatique' engraved",
  "Stainless Steel Engraved Diver's Helmet motif",
  "Stainless Steel Engraved Pierced with Aston Martin Logo",
  "Stainless Steel Engraved Screw Down",
  "Stainless Steel Engraved with Prancing Horse",
  "Stainless Steel Screw Down",
  "Stainless Steel Screw In",
  "Stainless Steel Screw-in",
  "Stainless Steel Skeleton",
  "Stainless Steel Snap back closed",
  "Stainless Steel Solid",
  "Stainless Steel embossed with Mille Miglia route",
  "Stainless Steel embossed with Mille Miglia route map",
  "Stainless Steel engraved diver's helmet decorated",
  "Stainless Steel engraved screw-down caseback",
  "Stainless Steel engraved with Limited Edition numbering and etching of Zinedine Zidane",
  "Stainless Steel screw-down",
  "Stainless Steel with 'OFFICINE PANERAI' engraved",
  "Stainless Steel with 'OFFICINE PANERAI' engraving, Screw Down",
  "Stainless Steel with Breitling Engraved Logo",
  "Stainless Steel with Checker Flag Decorated",
  "Stainless Steel with Checker Flag decorated",
  "Stainless Steel with Formula 1 Checkerboard patterning",
  "Stainless Steel with Vertical Patterning and Skeleton Display at 12 o'clock",
  "Stainless Steel with engraved 'OFFICINE PANERAI' engraving",
  "Stainless Steel, Engraved Batsman and '35 centuries', 'Limited Edition Sachin Tendulkar', 'ROO'",
  "Stainless Steel, Screw Down",
  "Stainless Steel, Snap Down",
  "Stainless Steel, Solid, Engraved",
  "Stainless Steel, engraved",
  "Stainless Steel, engraved 'INTERNATIONAL WATCH CO.', serial number",
  "Stainless Steel, engraved and engraveable",
  "Stainless steel",
  "Stainless steel and sapphire crystal",
  "Stainless steel case back with screws",
  "Stainless steel medallion illustrating the Artemis Racing sailing boat in racing.",
  "Stainless steel screw down exhibition",
  "Stainless steel screw in",
  "Stainless steel screw with hydraulic pressed marking",
  "Stainless steel screw-down",
  "Stainless steel secured with screws",
  "Stainless steel, Screw, See Through mineral glass",
  "Stainless steel, Screwed, see-through mineral glass",
  "Stainless steel, black DLC plated, screwed, special engravings",
  "Stainless steel, fixed with screws, See Through mineral glass",
  "Stainless steel, fixed with screws, see-through mineral glass",
  "Stainless steel, grey PVD plated, screwed, special engravings",
  "Stainless steel, screw-down",
  "Stainless steel, screw-in with two sapphire crystal windows",
  "Stainless steel, screwed",
  "Stainless steel, screwed, see-through mineral glass",
  "Stainless steel, screwed, special engravings",
  "Stainless steel, screwed, special engravings and printings",
  "Stainless steel, solid with Movado engravings",
  "Stainless steel, special engravings, screwed",
  "Stainless steel, with two sapphire crystal window, screw-in",
  "Stainless steel/Sapphire",
  "Stamped case-back featuring a diver",
  "Stamped casebackUnidirectional sapphire bezel",
  "Steel",
  "Steel Screw In back with Prancing Horse engraving and geometric pattern",
  "Steel case back with solid 18K rose gold Corum key",
  "Steel screw-down",
  "Stellar pattern back with Hello Kitty medallion",
  "Stopwatch-Feature",
  "Teak and Brushed Steel",
  "Tempered Transparent",
  "Three:24 Hours, 60 Minutes and 60 Seconds Sub-dials",
  "Titanium",
  "Titanium - with IWC/AMG engraving",
  "Titanium Case Back with Engraved Master Compressor Logo",
  "Titanium Glareproofed Sapphire",
  "Titanium case-back with Cafe Racer. Spirit engravings",
  "Titanium grade 2",
  "Titanium with Cafe Racer",
  "Titanium with Mercedes-AMG and IWC engraving",
  "Titanium with sapphire crystal, interior anti-reflection treatment with official UEFA logo",
  "Titanium, Screw, See Through mineral glass",
  "Titanium, sapphire",
  "Titanium, screwed, special engravings",
  "Translucent",
  "Translucent Plastic",
  "Transparen",
  "Transparent",
  "Transparent (Interchangeable Solid)",
  "Transparent (See Through)",
  "Transparent (See-Through)",
  "Transparent Blue",
  "Transparent Curved Sapphire",
  "Transparent Display Back",
  "Transparent E",
  "Transparent Exhibition",
  "Transparent Exhibition Case back",
  "Transparent Exhibition Display",
  "Transparent Exhibition Display Back",
  "Transparent Exhibition Display Back with gorgeous Guilloche patterned rotor",
  "Transparent Exhibition Sapphire Crystal",
  "Transparent Exhibition See Through",
  "Transparent Glareproof Sapphire",
  "Transparent Mineral",
  "Transparent Mineral Crystal",
  "Transparent Mineral Glass",
  "Transparent Offset Circle",
  "Transparent Roulette Spinning See Through",
  "Transparent S",
  "Transparent Sapphire",
  "Transparent Sapphire Crystal",
  "Transparent Sapphire Crystal Exhibition Back - Scratch Resistant",
  "Transparent Sapphire Crystal Exhibition Caseback",
  "Transparent Sapphire Crystal Exhibition back",
  "Transparent Sapphire Crystal Screw Down",
  "Transparent Sapphire Crystal See-Through",
  "Transparent Sapphire Exhibition",
  "Transparent Sapphire Exhibition Caseback showing gorgeous automatic movement",
  "Transparent Sapphire Glass",
  "Transparent Screw Down",
  "Transparent Screw In",
  "Transparent Screw-down",
  "Transparent See Through",
  "Transparent Snap Down",
  "Transparent case back made of mineral glass",
  "Transparent case back made of sapphire crystal glass",
  "Transparent case back secured by six screws",
  "Transparent exhibition",
  "Transparent exhibition case back",
  "Transparent sapphire",
  "Transparent sapphire caseback.",
  "Transparent sapphire crystal",
  "Transparent see-through crystal",
  "Transparent skeleton",
  "Transparent with Brooklyn Bridge etching",
  "Transparent with Fold Down Cover",
  "Transparent with Solid Cover",
  "Transparent with sapphire crystal",
  "Transparent, Screw Down display back",
  "Transparent, protected by hinged dust cover",
  "Transparent, sapphire crystal",
  "Transparent, screw down",
  "Transparent, screw-down",
  "Transparent, snap-down",
  "Transperant Scratch resistant sapphire",
  "Transperent Sapphire",
  "Unique pin-up painting with sapphire glass",
  "Uniquely Embossed",
  "Uniquely Embossed Solid",
  "White Plastic",
  "With screws",
  "aluminium bezel ring",
  "closed",
  "closed with a special engraving",
  "closed, secured by 4 screws",
  "engraved case-back",
  "grey tinted sapphire crystal",
  "sapphire case back",
  "sapphire crystal",
  "sapphire crystal anti-reflective 'box'",
  "sapphire crystal exhibition",
  "screw Down Stainless Steel",
  "screw, steel with PVD coating",
  "screwed",
  "screwed case back",
  "secured by 4 screws. Available space for a special engraving.",
  "secured by 6 screws",
  "secured by 6 screws, engraved with Laureato Absolute logo",
  "see through",
  "see-through sapphire crystal",
  "semi-transparent",
  "skeleton",
  "smoky sapphire crystal",
  "solid",
  "solid stainless steel",
  "stainless Steel Screw Down",
  "stainless steel and sapphire crystal",
  "transparent",
  "turbine styled Skeleton",
  "«Dia de los Muertos» engraving on the case back",
  "«Dia de los Muertos» medallion engraved",
  "«Dia de los Muertos» medallion engraved on the case back",
  "“100th anniversary” style engraving",
  "“DeLorean” engraving",
  "“Lucha Libre” style engraving",
  "“Propeller” style engraving",
  "“Steampunk” style engraving",
  "“Tattoo” style engraving",
  "“The Brother Kiss” engraving, painting by Dmitri Vrubel",
  "“The first step on the Moon” engraving",
];

module.exports = caseback;
