const crystals = [
  " Domed scratch‑resistant sapphire crystal with anti‑reflective treatment on both sides",
  "2.8 mm Thick Plexiglass",
  "Acrylic",
  "Acrylic Glass",
  "Acrylic Safety",
  "Acrylic glass",
  "Aluminosilicate Glass",
  "Amber",
  "Amber Crystal",
  "Anit-Reflective Sapphire",
  "Anit-glare Sapphire",
  "Anit-reflective Sapphire",
  "Anri-Reflective Sapphire",
  "Ant-Reflective Mineral",
  "Ant-reflective Scratch Resistant Sapphire",
  "Anti Reflective Sapphire",
  "Anti Reflective Scratch Resistant Sapphire",
  "Anti reflective Sapphire",
  "Anti reflective sapphire",
  "Anti- reflective Sapphire",
  "Anti-Refective Sapphire",
  "Anti-Reflection Sapphire",
  "Anti-Reflective Flame Fusion",
  "Anti-Reflective Flame Fusion Crystal",
  "Anti-Reflective K1",
  "Anti-Reflective Mineral",
  "Anti-Reflective Mineral Crystal",
  "Anti-Reflective Saphire",
  "Anti-Reflective Sapphire",
  "Anti-Reflective Sapphitek",
  "Anti-Reflective Scratch Resistant K1",
  "Anti-Reflective Scratch Resistant Sapphire",
  "Anti-Reflective sapphire",
  "Anti-Reflective, Scratch Resistant Sapphire",
  "Anti-Refllective, Scratch Resistant Sapphire",
  "Anti-Relective Sapphire",
  "Anti-eflective Scratch Resistant Sapphire",
  "Anti-glare Sapphire",
  "Anti-glare Scratch Resistant Sapphire",
  "Anti-reflctive Scratch Resistant Sapphire",
  "Anti-reflectice Scratch Resistant Sapphire",
  "Anti-reflection Sapphire",
  "Anti-reflective Flame Fusion",
  "Anti-reflective Mineral",
  "Anti-reflective Plexiglass",
  "Anti-reflective Sapphire",
  "Anti-reflective Scratch Resistant Sapphire",
  "Anti-reflective mineral crystal",
  "Anti-reflective sapphire",
  "Anti-reflective sapphire crystal",
  "Anti-reflective with magnifier",
  "Anti-reflectiveScratch Resistant Sapphire",
  "Anti-relfective Sapphire",
  "Anti-rflective Sapphire",
  "AntiReflective Sapphire",
  "AntiRelective Sapphire",
  "Antiglare Mineral",
  "Antireflective Sapphire",
  "Antireflective-sapphire",
  "Antireflex Sapphire",
  "Arcylic",
  "Blue Mineral Glass",
  "Blue Plexiglass",
  "Box shaped sapphire",
  "Box shaped sapphire crystal",
  "Box-shaped Hardlex",
  "Cambered Glareproof Sapphire",
  "Cambered Glareproofed Sapphire",
  "Cambered Glareproofed Sappphire",
  "Cambered Polycarbonate",
  "Cambered Saphire, Glareproof",
  "Cambered Sapphire",
  "Cambered Sapphire, Glareproof",
  "Cambered Sapphire, Glareproofed both sides",
  "Cambered sapphire, glareproofed both sides",
  "Cambired Sapphire",
  "Chambered Sapphire",
  "Chambered Sapphire Crystal",
  "Coated Acrylic",
  "Convew Sapphire",
  "Convex Hard Plexiglass",
  "Convex Hard Plexiglass Crystal",
  "Convex Hard Plexiglass With Sicralan Coating",
  "Convex Hard Plexiglass with SICRALAN Coating",
  "Convex Hard Plexiglass with SICRALAN coating",
  "Convex Hard Plexiglass with a SICRALAN Coating",
  "Convex Hard Plexiglass with a Sicralan Coating",
  "Convex Resistant Sapphire",
  "Convex Resistant Sapphire Crystal",
  "Convex Sapphire",
  "Convex Sapphire Crystal",
  "Convex hard Plexiglass with SICRALAN coating",
  "Convex hard plexiglass",
  "Convex hard plexiglass with SICRALAN coating",
  "Crystal",
  "Crystals",
  "Curved Hardened Mineral",
  "Curved Hardlex",
  "Curved Hardlex Glass",
  "Curved Mineral",
  "Curved Mineral Crystal",
  "Curved Sapphire Coated Mineral",
  "Curved hardened Mineral",
  "Curved sapphire",
  "Dome Mineral Glass With Sapphire Coating",
  "Dome Mineral with Sapphire Coating",
  "Domed",
  "Domed Acrylic",
  "Domed Anti-reflective Sapphire",
  "Domed Anti-reflective Scratch Resistant Sapphire",
  "Domed Anti-reflective, Scratch Resistant Sapphire",
  "Domed Flame Fushion",
  "Domed Flame Fusion",
  "Domed Krysterna",
  "Domed Mineral",
  "Domed Mineral Crystal",
  "Domed Mineral Glass",
  "Domed Plexi Glass",
  "Domed Sapphire",
  "Domed Sapphire Crystal",
  "Domed Scratch Resistant Antireflective Sapphire",
  "Domed Scratch Resistant Sapphire",
  "Domed Scratch Resistant Sapphire with anti-reflec",
  "Domed hardened Plastic",
  "Domed scratch-resistant sapphire",
  "Domed scratch-resistant sapphire crystal with anti",
  "Domed, Anti-reflective, Scratch Resistant Sapphire",
  "Doomed Flame Fusion",
  "Double Antireflective Sapphire",
  "Double Face Anti-Reflective Sapphire",
  "Double Face Anti-reflective Sapphire",
  "Double Face Anti-reflective sapphire",
  "Double antireflective Sapphire",
  "Double antireflective sapphire crystal",
  "Double face Anti-reflective Sapphire",
  "Double face anti-reflective sapphire",
  "Dual-curved sapphire",
  "Dual-curved sapphire crystal",
  "Durable mineral",
  "Faceted Mineral",
  "Fixed",
  "Fixed bezel set with crystals",
  "Flame / Fusion",
  "Flame Fusion",
  "Flame Fusion Anti Reflective Coating",
  "Flame Fusion Crystal- Anti-Reflective X3 Layers",
  "Flame Fusion w/ Triple Layer of Anti Reflective",
  "Flame Fusion with Anti-Reflective Coating",
  "Flame Fusion with Proctectivd leaver",
  "Flame Fusion, Anti Reflective",
  "Flame fusion",
  "Flame fusion Dome shape",
  "Flame-Fusion",
  "Flame-fusion",
  "Flat Mineral",
  "Flat Mineral Crystal",
  "Flat Sapphire",
  "Flat Scratch-Resistant Sapphire Crystal",
  "Flat Scratch-Resistant Sapphire Srystal",
  "Glare Proof Mineral",
  "Glare Proof Mineral Glass",
  "Glareproof Sapphire",
  "Glareproof sapphire",
  "Glareproofed Sapphire",
  "Glass",
  "Glass Crystal Box",
  "Green Sapphire Crystal",
  "Green Tinted Mineral Crystal",
  "Hard Plexiglass with a Sicralan Coating",
  "Hardened Anti-reflective Mineral",
  "Hardened Domed Mineral Glass",
  "Hardened K1 Mineral",
  "Hardened K1 Mineral Glass",
  "Hardened K1 Mineral glass. One-layer anti-reflective coating",
  "Hardened K1 mineral glass, one-layer anti-reflective coating",
  "Hardened K1 mineral glass. One-layer anti-reflective coating",
  "Hardened K1 mineral glassbox. One layer anti-reflective coating",
  "Hardened Mineral",
  "Hardened Mineral Crystal",
  "Hardened Mineral with Sapphire Coating",
  "Hardened Minetal",
  "Hardened Plastic Glass",
  "Hardened Polycarbonate",
  "Hardened mineral",
  "Hardex",
  "Hardles",
  "Hardlex",
  "Hardlex (used for Seiko only)",
  "Hardlex Crystal",
  "Hardlex Curved",
  "Hardlex Mineral",
  "Hardlex Mineral Crystal",
  "Hardlex with lenses",
  "Hesalit",
  "Hesalit Crystal",
  "Hesalite",
  "Hesalite Crystal",
  "Inorganic glass",
  "Iridescent Crystal",
  "Iridescent Mineral",
  "Iridescent crystal",
  "K-1",
  "K-1 Mineral",
  "K1",
  "K1 Anti- Reflective",
  "K1 Anti- Reflective Scratch Resistant",
  "K1 Anti-Reflective",
  "K1 Anti-Reflective Scratch Resistant",
  "K1 Anti-reflective, Scratch Resistant",
  "K1 Crystal",
  "K1 Crystals",
  "K1 Hardened Mineral",
  "K1 Hardened Mineral Crystal",
  "K1 Mineral",
  "K1 Mineral Crystal",
  "K1 Sapphire",
  "K1 Scratch Resistant Mineral",
  "K1 hardened mineral",
  "Krysterna",
  "Krysterna Crystal",
  "LCD Glass",
  "MIneral",
  "Metalized Domed Mineral Crysta",
  "Mienral",
  "Mimeral",
  "Min eral",
  "Mineeral",
  "Mineral",
  "Mineral Crystal",
  "Mineral Crystal with Hardened Coating",
  "Mineral Crystal with Sapphire Coating",
  "Mineral Crystal with Sapphire Layer",
  "Mineral Crystal with Sapphire coating",
  "Mineral Crystal with Sapphire layer",
  "Mineral Glass",
  "Mineral Glass / Spherical Glass",
  "Mineral Glass Flat Sapphire",
  "Mineral Glass Flat Sapphire Coated",
  "Mineral Glass Sapphire Coated",
  "Mineral Glass with Blue anti-reflex Coating",
  "Mineral Glass with Sapphire Coated",
  "Mineral Glass with Sapphire Coating",
  "Mineral Glass with Sapphire Treatment",
  "Mineral Glass with Sapphire coating",
  "Mineral Glass with blue anti-reflex coating",
  "Mineral Glass with sapphire coating",
  "Mineral Hardened Coating",
  "Mineral Lens",
  "Mineral Sapphire Coated",
  "Mineral Sapphire Coated Glass",
  "Mineral Sapphire-Coated",
  "Mineral Steel",
  "Mineral crystal with Sapphire coating",
  "Mineral crystal with hardened coating",
  "Mineral crystal with sapphire coating",
  "Mineral crystal, Hesalite crystal",
  "Mineral glass",
  "Mineral glass with sapphire coating",
  "Mineral w/ Sapphire Coating",
  "Mineral with Blue anti-reflex Coating",
  "Mineral with Hardened Coating",
  "Mineral with Hardening coating",
  "Mineral with Sapphire Coating",
  "Mineral with Sapphire Layer",
  "Mineral with Sapphire coating",
  "Mineral with Sapphire coating.",
  "Mineral with Sapphire layer",
  "Mineral with a Blue anti-reflex Coating",
  "Mineral with a Hardened Coating",
  "Mineral with a Sapphire Coating",
  "Mineral with anti-reflective coating",
  "Mineral with hardening coating",
  "Mineral with sapphire coating",
  "Mineral with sapphire coating.",
  "Mineral withSapphire coating",
  "Multi-Colored Mineral",
  "Nineral",
  "Non-Glare Mineral",
  "Non-Glare Scratch Resistant Mineral",
  "Non-Glare Scratch-Resistant Mineral",
  "Non-Reflective Mineral",
  "Non-Reflective Sapphire",
  "Orange tinted Hardened Mineral",
  "PLastic",
  "PMMA Plastic",
  "Pastic",
  "Perspex",
  "Pexiglass",
  "Plactic",
  "Plas",
  "Plastic",
  "Plastic Plexiglass",
  "Plexi",
  "Plexi with sicralan coating",
  "Plexi-Glass",
  "Plexi-glass with a Sicralan Coating",
  "Plexiglaee",
  "Plexiglas",
  "Plexiglasds",
  "Plexiglass",
  "Plexiglass with SICRALAN Coating",
  "Plexiglass with SICRALAN coating",
  "Plexiglass with Sicralan Coating",
  "Plexiglass with Sicralan coating",
  "Plexiglass with a Sicralan Coating",
  "Plexy Glass",
  "Polyamide",
  "Polymide",
  "Quartz",
  "Red Crystal Lens",
  "Red Mineral",
  "Reflective Mineral",
  "Reinforced",
  "Reinforced Mineral",
  "Reinforced Mineral Crystal",
  "Reinforced Mineral K1",
  "Reinforced Mineral K1 with Sapphire Coating",
  "Reinforced Mineral K1, with Sapphire Coating",
  "Resin Glass",
  "Resistant",
  "Round",
  "Rounded Mineral Crystal",
  "SAPPHITEK Crystal",
  "Sandblasted glass with roman number",
  "Saphhire",
  "Saphire",
  "Saphire Crystal",
  "Sapphie",
  "Sapphire",
  "Sapphire - Anti Reflective",
  "Sapphire - Anti-reflective",
  "Sapphire - Scratch Resistant",
  "Sapphire Coated",
  "Sapphire Coated Crystal",
  "Sapphire Coated Flat Mineral",
  "Sapphire Coated Flat Mineral Glass",
  "Sapphire Coated Glass",
  "Sapphire Coated Mineral",
  "Sapphire Coated Mineral Glass",
  "Sapphire Cryst",
  "Sapphire Crystal",
  "Sapphire Crystal - Scratch Resistant",
  "Sapphire Crystal Scratch Resistant",
  "Sapphire Crystal with Antireflex Treatment",
  "Sapphire Glass",
  "Sapphire Glass Scratch Anti Resistant",
  "Sapphire Lens",
  "Sapphire Made of Corundum",
  "Sapphire Scratch Resistant",
  "Sapphire With Antiglare Treatment",
  "Sapphire cabochon",
  "Sapphire coated Mineral",
  "Sapphire coated mineral",
  "Sapphire coated mineral Glass",
  "Sapphire crystal",
  "Sapphire crystal formed of corundum",
  "Sapphire formed of corundum",
  "Sapphire with Anti-reflective Treatment",
  "Sapphire with anti-reflective treatment",
  "Sapphire with antiglare treatment",
  "Sapphire with interior/exterior anti-reflection tr",
  "Sapphire with magnifier",
  "Sapphire, Anti-Reflective",
  "Sapphire, Antiglare",
  "Sapphire, Glareproofed",
  "Sapphire-Coated",
  "Sapphire-Coated Mineral",
  "Sapphire-Coated Mineral Crystal",
  "Sapphire-Coated Minetal",
  "Sapphire-Layered Mineral",
  "Sapphire-coated Mineral",
  "Sapphire-coated curved",
  "Sapphire-coated curved mineral",
  "Sapphire-coated mineral",
  "Sapphiree",
  "Sapphirev",
  "Sapphite",
  "Sapphitek",
  "Sapphitek Crystal",
  "Sapphrie",
  "Sappihre",
  "Sappire",
  "Sappitek",
  "Sappphire",
  "Scratch",
  "Scratch Convex Resistant Sapphire",
  "Scratch Reistant Sapphire",
  "Scratch Resiatant Sapphire",
  "Scratch Resistant (Edge-to-Edge) Mineral",
  "Scratch Resistant (Multi-hued Iridescent) Mineral",
  "Scratch Resistant Acrylic",
  "Scratch Resistant Amber Mineral",
  "Scratch Resistant Amber-tinted Mineral",
  "Scratch Resistant Anti-Reflective K1",
  "Scratch Resistant Anti-Reflective Sapphire",
  "Scratch Resistant Anti-reflective Sapphire",
  "Scratch Resistant Anti-reflectiveSapphire",
  "Scratch Resistant Antireflective Sapphire",
  "Scratch Resistant Arcylic",
  "Scratch Resistant Blue Mineral",
  "Scratch Resistant Blue Tinged Mineral",
  "Scratch Resistant Blue-Tinted Mineral",
  "Scratch Resistant Convex Mineral",
  "Scratch Resistant Convex Sapphire",
  "Scratch Resistant Domed Mineral",
  "Scratch Resistant Domed Sapphire",
  "Scratch Resistant Flame Fusion",
  "Scratch Resistant Flmae fusion",
  "Scratch Resistant Glareproof Sapphire",
  "Scratch Resistant Green Mineral",
  "Scratch Resistant Hard Plexiglass",
  "Scratch Resistant Hardened K1",
  "Scratch Resistant Hardened Mineral",
  "Scratch Resistant Hardlex",
  "Scratch Resistant Hardlex Mineral",
  "Scratch Resistant Hesalite",
  "Scratch Resistant Hesalite Crystal",
  "Scratch Resistant Iridescent Mineral",
  "Scratch Resistant Irridescent Mineral",
  "Scratch Resistant K!",
  "Scratch Resistant K1",
  "Scratch Resistant K1 Hardlex",
  "Scratch Resistant K1 Mineral",
  "Scratch Resistant K1 Mineral Crystal",
  "Scratch Resistant K1 mineral",
  "Scratch Resistant K1Mineral",
  "Scratch Resistant Krysterna",
  "Scratch Resistant Light Gold Mineral",
  "Scratch Resistant Magnifier Mineral",
  "Scratch Resistant Mineral",
  "Scratch Resistant Mineral K1",
  "Scratch Resistant Mineral with orange tint",
  "Scratch Resistant Mineral, Green-Tinted",
  "Scratch Resistant Plexiglas",
  "Scratch Resistant Plexiglass",
  "Scratch Resistant Reinforced Mineral",
  "Scratch Resistant Sapphier",
  "Scratch Resistant Sapphire",
  "Scratch Resistant Sapphire - antiglare treatmen",
  "Scratch Resistant Sapphire Anti Reflective",
  "Scratch Resistant Sapphire Coated",
  "Scratch Resistant Sapphire Coated Mineral",
  "Scratch Resistant Sapphire Crystal",
  "Scratch Resistant Sapphire Touch",
  "Scratch Resistant Sapphire coated Mineral",
  "Scratch Resistant Sapphire with Anti-Reflective Tr",
  "Scratch Resistant Sapphire with Anti-Reflective Treatment on Both Sides",
  "Scratch Resistant Sapphire with Arabic Numerals (i",
  "Scratch Resistant Sapphire with Frosted Color Trea",
  "Scratch Resistant Sapphire, anti-glare treatment",
  "Scratch Resistant Sapphire- Coated Minetal",
  "Scratch Resistant Sapphire-Coated",
  "Scratch Resistant Sapphire-Coated Crystal",
  "Scratch Resistant Sapphire-Coated Mineral",
  "Scratch Resistant Sapphire-Coated Minertal",
  "Scratch Resistant Sapphire-Coated Minetal",
  "Scratch Resistant Sapphire-coated Mineral",
  "Scratch Resistant Sapphitek",
  "Scratch Resistant Scratch Resistant Sapphire",
  "Scratch Resistant Scratch Resistant Sapphire Cryst",
  "Scratch Resistant Stnthetic Sapphire",
  "Scratch Resistant Synthetic Sapphire",
  "Scratch Resistant TV Screen Sapphire",
  "Scratch Resistant Tactile Sapphire",
  "Scratch Resistant Tinted Mineral",
  "Scratch Resistant Titan",
  "Scratch Resistant Touch Screen Sapphire",
  "Scratch Resistant Touch-sensitive Sapphire",
  "Scratch Resistant and Anti-reflective Sapphire",
  "Scratch Resistant plexiglas",
  "Scratch Resistant sapphire",
  "Scratch Resistant triple-coated. anti-reflective s",
  "Scratch Resistant, Anti-reflective Sapphire",
  "Scratch Resitant Sapphire",
  "Scratch resistant Flame Fusion",
  "Scratch resistant Hardlex",
  "Scratch resistant K1 mineral",
  "Scratch resistant Sapphire",
  "Scratch resistant Sapphire Crystal",
  "Scratch resistant Sapphire anti-reflective",
  "Scratch resistant flame fusion",
  "Scratch resistant mineral",
  "Scratch resistant mineral with anti-reflective coa",
  "Scratch resistant plastic",
  "Scratch resistant sapphire",
  "Scratch resistant sapphire crystal",
  "Scratch-Resistant Sapphimax",
  "Scratch-Resistant Sapphire",
  "Scratch-resistant Beveled Mineral Crystal",
  "Scratch-resistant sapphire crystal",
  "Shatter Resistant Krysterna",
  "Shatter resistant Krysterna",
  "Shatter-resistant Krysterna",
  "ShatterResistant Krysterna",
  "Shock Resistant Mineral",
  "Shock-resistance acrylic glass",
  "Silver-tone",
  "Solid Sapphire",
  "Solidified Crystal Mineral",
  "Specially Hardened Domed Mineral",
  "Specially hardened anti-reflective mineral glass",
  "Specially hardened domed mineral glass",
  "Specially hardened domed mineral glass.",
  "Specially hardened mineral glass",
  "Specially hardened mineral glass with anti-reflective coating",
  "Specially hardened mineral glass with antireflective coating",
  "Spectrum Glass",
  "Spherical",
  "Spherical Crystal",
  "Spherical Glass",
  "Spphire",
  "Ssapphire",
  "Super Harden Mineral",
  "Synthethic Sapphire",
  "Syntheti cMineral",
  "Synthetic Mineral",
  "Synthetic Saphire",
  "Synthetic Sapphire",
  "Synthetic Sapphirre",
  "Synthetic mineral",
  "Synthetic sapphire",
  "Sythnetic Sapphire",
  "TV Screen Anti-reflective Sapphire",
  "Tactile Sapphire",
  "Tactile Sapphire Crystal",
  "Tactile Scratch Resistant Sapphire",
  "Tactile Scratch-Resistant Sapphire Crystal",
  "Tactile Scratch-resistant Sapphire Crystal",
  "Tactile scratch-resistant Sapphire",
  "TapScreen Technology Mineral",
  "Tinted Flame Fusion",
  "Tinted Mineral",
  "Tinted Mineral Crystal",
  "Tinted Minerall",
  "Titan",
  "Triple Anti-reflective Flame Fusion",
  "Triple Layer of Anti Reflective Flame Fusion",
  "Triple Layered Anti-reflective Coated Flame Fusion",
  "Triple layered Anti-Reflective Coated Flame Fusion",
  "Triple-coated Anti-reflective Sa",
  "Triple-coated Anti-reflective Sapphire",
  "antireflective-sapphire",
  "cambered sapphire",
  "convex hard plexiglass with SICRALAN coating",
  "decorated sapphire",
  "domed sapphire crystal glass",
  "domed sapphire crystal glass with anti-reflective coating",
  "domed sapphire crystal glass with anti-reflective coating on inner side",
  "domed sapphire crystal with anti-reflective coating inside and out",
  "flame fusion",
  "mineral",
  "ouble Curved Mineral",
  "raised acrylic crystal",
  "sapphire",
  "sapphire crystal",
  "sapphire crystal glass",
  "sapphire crystal glass with anti-reflective coating",
  "sapphire crystal glass with anti-reflective coating on inner side",
  "seven floating dials",
  "synthetic-sapphire"
];

module.exports = crystals;