const fld = {
    'A. Lange & Sohne': 'alange',
    'About Vintage': 'av',
    'Alpina': 'alpina',
    'Audemars Piguet': 'ap',
    'Ball': 'ball',
    'Baume et Mercier': 'baume',
    'Bell & Ross': 'bellross',
    'Blancpain': 'blancpain',
    'Breguet': 'breguet',
    'Breitling': 'breitling',
    'Bremont': 'bremont',
    'Briston': 'briston',
    'Bulova': 'bulova',
    'Bvlgari': 'bulgari',
    'Bulova': 'bulova',
    'Cartier': 'cartier',
    'Casio': 'casio',
    'Chanel': 'chanel',
    'Chopard': 'chopard',
    'Citizen': 'citizen',
    'Cvstos': 'cvstos',
    'Daniel Wellington': 'dw',
    'Diesel': 'diesel',
    'Emporio Armani': 'armani',
    'Festina': 'festina',
    'Fossil': 'fossil',
    'Frederique Constant': 'frederique',
    'Garmin': 'garmin',
    'Girard-Perregaux': 'gp',
    'Glashuette Original': 'go',
    'Grand Seiko': 'gseiko',
    'Gucci': 'gucci',
    'Guess': 'guess',
    'Hamilton': 'hamilton',
    'Hublot': 'hublot',
    'Hugo Boss': 'hugoboss',
    'IWC': 'iwc',
    'Jaeger LeCoultre': 'jlc',
    'Jaguar': 'jaguar',
    'Jaquet Droz': 'jdroz',
    'Longines': 'longines',
    'Louis Vuitton': 'lv',
    'Luminox': 'luminox',
    'Maserati': 'maserati',
    'Maurice Lacroix': 'maurice',
    'MeisterSinger': 'meister',
    'Memorigin': 'memorigin',
    'Michael Kors': 'mkors',
    'Mido': 'mido',
    'Montblanc': 'montblanc',
    'Muehle Glashuette': 'muehle',
    'Nixon': 'nixon',
    'Omega': 'omega',
    'Orient': 'orient',
    'Oris': 'oris',
    'Panerai': 'panerai',
    'Parmigiani Fleurier': 'parmigiani',
    'Patek Philippe': 'patek',
    'Piaget': 'piaget',
    'Rado': 'rado',
    'Rolex': 'rolex',
    'Seiko': 'seiko',
    'Sevenfriday': 'sf',
    'Sinn': 'sinn',
    'Skagen': 'skagen',
    'TAG Heuer': 'tagheuer',
    'Tissot': 'tissot',
    'Tudor': 'tudor',
    'Tutima Glashuette': 'tutima',
    'Ulysse Nardin': 'ulysse',
    'Victorinox': 'victorinox',
    'Zenith': 'zenith',
};

module.exports = fld;