const bandM = [
  " Multi-Band Atomic Timekeeping (US, UK, Germany, Japan, China)\n Receives time calibration radio signals which keep the displayed time accurate\n Auto receive function (up to 6 times per day/up to 5 times per day for China)\n Manual receive function\n Signal:  US WWVB, UK MSF, Germany DCF77, Japan JJY40/JJY60, China BPC\n Frequency:  US 60kHz, UK 60kHz, Germany 77.5kHz, Japan 40/60kHz, BPC 68.5kHz",
  " Multi-Band Atomic Timekeeping (US, UK, Germany, Japan, China)\n Receives time calibration radio signals which keep the displayed time accurate\n Auto receive function (up to 6 times per day/up to 5 times per day for China)\n Manual receive function\n Signal:  US WWVB, UK MSF, Germany DCF77, Japan JJY40/JJY60, China BPC\n Frequency:  US 60kHz, UK 60kHz, Germany 77.5kHz, Japan 40/60kHz, China BPC 68.5kHz",
  " Multi-Band Atomic Timekeeping (US, UK, Germany, Japan, China)\n Receives time calibration radio signals which keep the displayed time accurate\n Auto receive function (up to 6 times per day/up to 5 times per day for China)\n Manual receive function\n Signal:  US WWVB, UK MSF, Germany DCF77, Japan JJY40/JJY60, China BPC\n Frequency:  US 60kHz, UK 60kHz, Germany 77.5kHz, Japan 40/60kHz, China BPC 68.5kHz\n",
  " Multi-Band Atomic Timekeeping (US, UK, Germany, Japan, China)\n Receives time calibration radio signals which keep the displayed time accurate\n Auto receive function up to 6 times per day (up to 5 times per day for China)\n Manual receive function\n Signal:  US WWVB, UK MSF, Germany DCF77, Japan JJY40/JJY60, China BPC\n Frequency:  US 60kHz, UK 60kHz, Germany 77.5kHz, Japan 40/60kHz, China BPC 68.5kHz",
  " Solid Band",
  " grey PVD bracelet with Interlocking Gs",
  "\"MILANAISE BRACELET CLASSIC\"",
  "\"SHELL CORDOVAN BLACK\"",
  "\"SHELL CORDOVAN BROWN\"",
  "\"SHELL CORDOVAN COGNAC\"",
  "(High-tech) Ceramos",
  "(Transparent) Plexiglas Bangle",
  "1 Colored fabric/textile; 2 Satin",
  "1 Colored fabric; 2 Satin strap",
  "1 Woven colored strap; 2 Black satin",
  "1) Black rubber 2) Brown alligator",
  "1) Blue alligator strap; 2) Black structured lined rubber strap",
  "1) White alligator strap 2) Black rubber strap",
  "1) black rubber and grey Schedoni leather strap; 2) Additional black Schedoni leather straps with grey stitchings",
  "1) red Schedoni leather with black rubber lining 2) black Schedoni leather with red stitching and rubber lining.",
  "1. Steel bracelet; 2. Textile strap.",
  "1/100th of a second Chronograph movement||Exclusive dynamic signature of one rotation per second for the Chrono hand||1 escapement for the Watch (36,000 VpH - 5 Hz) ; 1 escapement for the Chronograph (360,000 VpH - 50Hz)||Certified Chronometer",
  "1/100th of a second Double Tourbillon Chronograph movement||1 Tourbillon escapement for the Watch (36,000 VpH - 5 Hz) ; 1 Tourbillon escapement for the Chronograph (360,000 VpH - 50Hz)||Exclusive dynamic signature of one rotation per second for the Chrono hand||Certified Chronometer",
  "12\" Green Silk Cord",
  "36mm navy case and bracelet",
  "36mm taupe case and bracelet",
  "38mm blue case and bracelet",
  "41-MM Black Ceramic case||In house Elite skeletonised movement||Silicon escape-wheel and lever",
  "41-MM Blue Ceramic case||In house Elite skeletonised movement||Silicon escape-wheel and lever",
  "41-MM Brushed Titanium case with 18-carat rose gold bezel||In house Elite skeletonised movement||Silicon escape-wheel and lever",
  "41-MM White Ceramic case||In house Elite skeletonised movement||Silicon escape-wheel and lever",
  "44mm black ion-plated case and bracelet",
  "44mm ion-plated case and bracelet",
  "> Discover the S.A.R. Rescue-Timer \"SK Hamburg\" at Juwelier Wempe",
  "Acetate",
  "Acrylic",
  "Aero Classic",
  "Alcantara",
  "Alcantara Strap",
  "Alligator Leather",
  "Alloy",
  "Allpy",
  "Aluminium",
  "Anthracite Military",
  "Approx. Weight (including band): 83 g (2.9 oz)",
  "Automatic El Primero column-wheel chronograph movement||El Primero Calibre 400: 278 components, 31 jewels and 36,000 VpH||Iconic colours of the legendary historical El Primero||Date indication at 6 o'clock||Tachymetric scale on the inner bezel ring",
  "Band Length: 145mm - 205mm",
  "Band Length: 145mm - 215mm",
  "Band Not Included",
  "Band not included",
  "Bangle",
  "Base Metal",
  "Beige",
  "Beige Gold",
  "Beige velour",
  "Bentley III (Black)",
  "Bicolor",
  "Bimaterial",
  "Black",
  "Black Alcantara",
  "Black Carbon-reinforced Polymer",
  "Black Dial",
  "Black Diver Pro",
  "Black Diver Pro II",
  "Black Felt",
  "Black Galusha",
  "Black Grosgrain",
  "Black Ion-plated with Silver-tone accents",
  "Black Kevlar",
  "Black Lea",
  "Black Learher",
  "Black PVD",
  "Black PVD coating",
  "Black Plexiglas Bracelet",
  "Black Polyvinyl",
  "Black Pro Diver",
  "Black Rolyurethane",
  "Black TR90 Composite",
  "Black TR90 Polymer",
  "Black Toile de Voile",
  "Black Velvet",
  "Black and Yellow Elastomer",
  "Black dial",
  "Black ion plated band",
  "Black ocean racer II",
  "Black polymer material",
  "Black stain",
  "Black velvet",
  "Black/White PVD",
  "Blue",
  "Blue Gel and extra Clear Gel",
  "Blue Pro Diver",
  "Blue dial",
  "Blue jeans",
  "Blue transparent structured lined strap",
  "Blue velvet",
  "Bordeaux stain",
  "Bracelet",
  "Bracelet Sport",
  "Bracelet set with 78 Akoya pearls (~48",
  "Bracelet, black pvd",
  "Brass",
  "Bronze",
  "Bronze Case that will develop his own patina||Arabic numerals entirely made of SuperLuminova||Case-back engraved with Zenith flying instruments logo||Inspired by the legendary Zenith aviation watches",
  "Bronze Case that will develop his own patina||Arabic numerals entirely made of SuperLuminova||Inspired by the legendary Zenith aviation watches",
  "Bronze Case that will develop his own patina||Automatic El Primero column-wheel chronograph movement||Arabic numerals entirely made of SuperLuminova||Case-back engraved with Zenith flying instruments logo",
  "Brown",
  "Brown & Yellow",
  "Brown Galuchat",
  "Brown Military",
  "Brown stain",
  "Brushed/Polished Silvertone and Rose Goldtone",
  "CORAMID",
  "Caiman",
  "Calfskin Leather",
  "Canvas",
  "Carbon",
  "Carbon Fiber",
  "Carbon Texture",
  "Carbon bracelet",
  "Cavnas",
  "Ceramic",
  "Ceramos",
  "Chain",
  "Charm Bracelet ( Key, Leaf, tree, clover, logo)",
  "Charm Bracelet (Purse, shoe, heart, clov",
  "Chevrol Cable with attached jewelry chain",
  "Chevron Cable with attached jewelry chain",
  "Chevron cable, textured chevron cable patter",
  "Cinturino bicolore in acciaio inossidabile lucidato placcato oro rosa.",
  "Cinturino bicolore in acciaio inossidabile placcato oro giallo con 7 maglie.",
  "Cinturino bicolore in acciaio inossidabile placcato oro rosa",
  "Cinturino bicolore in acciaio inossidabile placcato oro rosa.",
  "Cinturino bicolori in acciaio inossidabile e placcato oro rosa",
  "Cinturino di acciaio inossidabile - 3 maglie.",
  "Cinturino di metallo",
  "Cinturino di pelle blu brillante.",
  "Cinturino di pelle blu scuro.",
  "Cinturino di pelle blu.",
  "Cinturino di pelle bordeaux brillante.",
  "Cinturino di pelle brillante.",
  "Cinturino di pelle di vitello blu",
  "Cinturino di pelle di vitello marrone chiaro",
  "Cinturino di pelle di vitello marrone scuro",
  "Cinturino di pelle di vitello motif coccodrillo blu",
  "Cinturino di pelle di vitello motif coccodrillo blu scuro.",
  "Cinturino di pelle di vitello motif coccodrillo grigio.",
  "Cinturino di pelle di vitello motif coccodrillo marrone nero.",
  "Cinturino di pelle di vitello motif coccodrillo marrone.",
  "Cinturino di pelle di vitello motif coccodrillo nero",
  "Cinturino di pelle di vitello motif coccodrillo nero.",
  "Cinturino di pelle di vitello nero",
  "Cinturino di pelle marrone",
  "Cinturino di pelle marrone chiaro.",
  "Cinturino di pelle marrone scuro",
  "Cinturino di pelle marrone scuro.",
  "Cinturino di pelle marrone.",
  "Cinturino di pelle nero.",
  "Cinturino di pelle.",
  "Cinturino in acciaio inossidabile",
  "Cinturino in acciaio inossidabile - 3 maglie con raccordo placcato oro rosa.",
  "Cinturino in acciaio inossidabile bicolore placcato oro rosa.",
  "Cinturino in acciaio inossidabile placcato oro rosa",
  "Cinturino in acciaio inossidabile, bicolore, con 7 maglie e un legame placcato oro rosa.",
  "Cinturino in acciaio inossidabile, un cinturino di gomma in più è fornito con l'orologio",
  "Cinturino in acciaio inossidabile.",
  "Cinturino in metallo.",
  "Clear",
  "Clear Lucite",
  "Codura Band",
  "Composite",
  "Cord",
  "Cordura, black",
  "Cordura®",
  "Cotton Twill",
  "Cow Steer",
  "Creation of the watch depicted in the Original japanese manga \"Lupin the Third\"||Original 1969 case with 37 mm diameter||Automatic El Primero column-wheel chronograph movement",
  "Crocodile Leather",
  "Crystal",
  "Cultured pearls bracelet",
  "Cuoio Nautico",
  "Custom 22mm Silver IP plated",
  "Dark Brown Velour",
  "Dark Green",
  "Dark blue stain",
  "Dark blue techno silk",
  "Dark brown polymer material",
  "Dark grey stain",
  "Demin",
  "Diamond",
  "Diver Pro II",
  "Diver Pro II (Blue)",
  "Diver Pro II (White)",
  "Diver Pro II Black",
  "Diver Pro II Strap Black",
  "Diver Pro II White",
  "Diver Pro III",
  "Diver Pro III (Black)",
  "Diver Pro III (Blue)",
  "Diver Pro III Black",
  "Diver Pro III Blue",
  "Dusty Galuchat",
  "Dylan",
  "Elastic",
  "Elastomer",
  "Enamel",
  "Entirely redesigned movement to pay tribute to the 50th Anniversary of the legendary El Primero movement||Automatic El Primero column-wheel chronograph able to measure and display the 1/10th of a second||1/10th of a second indication on the ceramic bezel||Increased power reserve of 60 hours||Stop second mechanism",
  "Entirely restyled case & dial : Redefine the codes of Elegance||Automatic Elite calibre beating at 28,800 VpH||Date indication at 6 o'clock||Stop second mechanism",
  "Entirely skeletonised movement : El Primero 8812 S||\"Gravity Control\" gyroscopic module that ensures horizontal positioning of the regulating organ||Now occupies only 30% of its initial volume||Inspired by the legendary marine chronometers||Openworked dial",
  "Everose Gold",
  "Exclusive combination : Tourbillon Fusee-Chain Calibre||Chain made of 575 components||Manual winding El Primero Tourbillon with Fusée-Chain escapement||Constant force fusée-chain transmission connected to the barrel",
  "Fabric",
  "Fiber",
  "First all-carbon bracelet : the entire watch weighs 65 grams||New 41-MM Black Carbon case||In house Elite skeletonised movement||Silicon escape-wheel and lever",
  "Fold-over clasp",
  "Four Strand Pearl Style",
  "Full Carbon model : Case, crown and buckle head||Exclusive combination : Tourbillon Fusee-Chain Calibre||Chain made of 575 components||Manual winding El Primero Tourbillon with Fusée-Chain escapement||Constant force fusée-chain transmission connected to the barrel",
  "Full Carbon model : Case, pushers, crown and buckle head||1/100th of a second Chronograph movement||Exclusive dynamic signature of one rotation per second for the Chrono hand||1 escapement for the Watch (36,000 VpH - 5 Hz) ; 1 escapement for the Chronograph (360,000 VpH - 50Hz)||Certified Chronometer",
  "Full Carbon model : Case, pushers, crown and buckle head||1/100th of a second Double Tourbillon Chronograph movement||1 Tourbillon escapement for the Watch (36,000 VpH - 5 Hz) ; 1 Tourbillon escapement for the Chronograph (360,000 VpH - 50Hz)||Exclusive dynamic signature of one rotation per second for the Chrono hand||Certified Chronometer",
  "Full Carbon model : Case, pushers, crown and buckle head||Carbon bezel with Patrick Mouratoglou's Motto engraved and filled with SuperLuminova||1/100th of a second Chronograph movement||Certified Chronometer",
  "Full Carbon model : Case, pushers, crown and buckle head||Carbon bezel with SuperLuminova||Small second disk shaped like a record vinyl||1/100th of a second Chronograph movement||Certified Chronometer",
  "Galuchat",
  "Galusha",
  "Gel",
  "Gel Strap",
  "Gem set",
  "Genuine Shell",
  "Genuine blue jeans with grey stitching strap",
  "Glass",
  "Gold",
  "Gold-Plated",
  "Gold-tone Bangle",
  "Green",
  "Green stain",
  "Grey",
  "Grey Alcantara®",
  "Grey Kevlar",
  "Grey Lilac Velvet",
  "Grey dial",
  "Grey jeans",
  "Grey synthetic",
  "Grey textil",
  "Gunmetal",
  "Hardmetal",
  "Hardmetal and Yellow Gold-plated",
  "High Tech Material",
  "High-Tech Material",
  "High-tech material",
  "Horn-shell Plasteramic",
  "Horne Acetace",
  "Horween Genuine Shell Cordovan black",
  "Horween Genuine Shell Cordovan black, remborde",
  "Horween Genuine Shell Cordovan black, remborde, cushioned",
  "Horween Genuine Shell Cordovan black, remborde, with quick-change spring bars",
  "Horween Genuine Shell Cordovan black, with quick-change spring bars",
  "Horween Genuine Shell Cordovan brown",
  "Horween Genuine Shell Cordovan brown with red stitching",
  "Horween Genuine Shell Cordovan brown, remborde, cushioned",
  "Horween Genuine Shell Cordovan brown, remborde, with quick-change spring bars",
  "Horween Genuine Shell Cordovan dark brown, remborde, cushioned",
  "Hunter Green Plasteramic",
  "IPRG",
  "IPYG",
  "Ice (white) Plasteramic",
  "In house Elite skeletonised movement||41-MM Brushed Titanium case||Silicon escape-wheel and lever",
  "In house Elite skeletonised movement||Silicon escape-wheel and lever",
  "Inspired by the spirit of the 1960's||Exclusive & Limited Edition for North America||Original 1969 case with 37 mm diameter||Automatic El Primero column-wheel chronograph movement",
  "Interchangeable",
  "Interchangeable : Black, Brown, yellow and white L",
  "Interchangeable Strap and Bracelet",
  "Interchangeable straps: white, Black, burgundy, re",
  "Iron Chain",
  "Iron chain",
  "Italian Lorica Strap",
  "Ivory silk",
  "Jubilee",
  "Kelvar",
  "Kevlar",
  "King Gold",
  "Leather",
  "Light Mint Green",
  "Light brown with white stitching",
  "Lilac Gel Strap and extra Clear Gel",
  "Lilac Velvet",
  "MILANAISE BRACELET CLASSIC",
  "Milanese",
  "Milanese band",
  "Military",
  "Military (Anthracite)",
  "Military (Khaki Green)",
  "Military Anthracite",
  "Military Black",
  "Military Brown",
  "Military Khaki Green",
  "Mille Mailles bracelet",
  "Mint Green",
  "Mother of Pearl",
  "Multi-Band Atomic Timekeeping (US, UK, Germany, Japan, China",
  "Multi-Band Atomic Timekeeping (US, UK, Germany, Japan, China Receives time calibration radio signals which keep the displayed time accurate Auto receive function (up to 6 times per day) Manual receive function Signal: US WWVB, UK MSF, Germany DCF77, Japan JJY40/JJY60, China BPC Frequency: US 60kHz, UK 60kHz, Germany 77.5kHz, Japan 40/60kHz, China BPC 68.5kHz",
  "Multi-Band Atomic Timekeeping (US, UK, Germany, Japan, China)",
  "Multi-Band Atomic Timekeeping (US, UK, Germany, Japan, China)\n    Receives time calibration radio signals which keep the displayed time accurate\n    Auto receive function up to 6 times per day (up to 5 times per day for the Chinese calibration signal)\n    Manual receive function\n    Signal:  US WWVB, UK MSF, Germany DCF77, Japan JJY40/JJY60, China BPC\n    Frequency:  US 60kHz, UK 60kHz, Germany 77.5kHz, Japan 40/60kHz, BPC 68.5kHz",
  "Multi-Band Atomic Timekeeping (US, UK, Germany, Japan, China)\n Receives time calibration radio signals which keep the displayed time accurate\n Auto receive function (up to 6 times per day/up to 5 times per day for China)\n Manual receive function\n Signal:  US WWVB, UK MSF, Germany DCF77, Japan JJY40/JJY60, China BPC\n Frequency:  US 60kHz, UK 60kHz, Germany 77.5kHz, Japan 40/60kHz, China BPC 68.5kHz",
  "Multi-Band Atomic Timekeeping (US, UK, Germany, Japan, China)\nReceives time calibration radio signals which keep the displayed time accurate\nAuto receive function (up to 6 times per day/up to 5 times per day for China)\nManual receive function\nSignal:  US WWVB, UK MSF, Germany DCF77, Japan JJY40/JJY60, China BPC\nFrequency:  US 60kHz, UK 60kHz, Germany 77.5kHz, Japan 40/60kHz, BPC 68.5kHz",
  "Multi-Band Atomic Timekeeping (US, UK, Germany, Japan, China)Receives time calibration radio signals which keep the displayed time accurateAuto receive function (up to 6 times per day/up to 5 times per day for China)Manual receive functionSignal: US WWVB, UK MSF, Germany DCF77, Japan JJY40/JJY60, China BPCFrequency: US 60kHz, UK 60kHz, Germany 77.5kHz, Japan 40/60kHz, BPC 68.5kHz",
  "Multi-Strand Cultured Akoya Pearl",
  "Multi-colored Bead",
  "Multi-strand Akoya Cultured Pearls",
  "Multicolor Polyester",
  "Nano strap",
  "Nautilus fold-over clasp",
  "Navitimer (Navitimer)",
  "Navy Blue",
  "Navy Synthetic",
  "New 36-MM case dedicated for Women||Gradient dial with starry sky pattern||New Interchangeable strap system||Strap box included : 3 different colors straps + a folding buckle",
  "New 44-MM Microblasted titanium case||1/100th of a second Chronograph movement||Special linear power reserve indicator||Limited Edition of 250 units with a second strap included||Certified Chronometer",
  "New 45-MM Brushed steel case||Case-back engraved with Zenith flying instruments logo||Inspired by the legendary Zenith aviation watches",
  "No Bracelet",
  "Nylon",
  "Ocean Racer",
  "Ocean Racer (Black)",
  "Ocean Racer (Blue)",
  "Ocean Racer Black",
  "Ocean Racer Blue",
  "Ocean Racer II (Blue)",
  "Ocean Racer II (White)",
  "Ocean Racer II Black",
  "Ocean Racer II Blue",
  "Ocean Racer II Blue Marine",
  "Ocean Racer II White",
  "Opening revealing the legendary beating heart of the El Primero movement||Silicon escape-wheel and lever||Automatic El Primero column-wheel chronograph with large date",
  "Ore, Minuti, Secondi, Conto alla rovescia.",
  "Original Revival of the 1969 Reference A384||Original 1969 case with 37 mm diameter||Automatic El Primero column-wheel chronograph movement||Original Revival of the \"Gay Frères\" ladder bracelet",
  "Oyster",
  "Oysterflex",
  "PVD",
  "Palladium",
  "Palladiun",
  "Paracord",
  "Pearl bracelet",
  "Pearly beige polymer material",
  "Perforated Black Elastomer",
  "Perlon",
  "Pilot (Two-tone)",
  "Pilot Two-tone",
  "Pink",
  "Pink Galuchat",
  "Pink Gold",
  "Pink Ribbon",
  "Pink Silk",
  "Plasteramic",
  "Plastic",
  "Plated",
  "Plated Bico",
  "Plated Pearlmaster",
  "Platinum",
  "Plexiglas",
  "Plexiglas Bangle",
  "Polished",
  "Polycarbon",
  "Polyester",
  "Polyurethane",
  "Powdered violet strap",
  "Prong buckle",
  "Purple Jean",
  "Recycled PET",
  "Recycled PET Black",
  "Recycled PET Dark blue",
  "Red Gold",
  "Red PVD coating",
  "Reinvention of Huygens sprung balance principle||A new monolithic oscillator made out of Silicon||Frequency of 18Hz (129,600 vibrations per hour)||Insensitive to temperature, gravity and magnetic fields",
  "Resin",
  "Ribbon",
  "Rifle",
  "Riubber",
  "Rolex Oysterflex",
  "Rolex Pearlmaster",
  "Rose Gold",
  "Rose Gold PVD",
  "Rose Gold Plated",
  "Rose Gold-PVD",
  "Rose Gold-plated",
  "Rose Gold-tone Plated",
  "RoseGold-Plated",
  "Rubber",
  "SHELL CORDOVAN BLACK",
  "SHELL CORDOVAN BROWN",
  "SHELL CORDOVAN COGNAC",
  "Sahara (Black)",
  "Sahara (Blue Marine)",
  "Sahara (Orange)",
  "Sahara (Red)",
  "Sahara (Rose)",
  "Sahara Black",
  "Sahara Blue Marine",
  "Sahara Brown",
  "Sahara Orange",
  "Sahara Red",
  "Sahara White",
  "Sand Plasteramic",
  "Sand Tan",
  "Sapphire",
  "Satan",
  "Satin",
  "Satin-Covered",
  "Seamless Elastic Strap",
  "Sedna Gold",
  "Set of 5 interchangeable straps",
  "Set with Brilliants",
  "Shagreen Strap",
  "Silicone",
  "Silione",
  "Silk",
  "Silk strap",
  "Silver",
  "Silver-tone Charm Bracelet (purse, shoe, heart, cl",
  "Smoked transparent structured lined",
  "Sport",
  "Spun Silk",
  "Stainless Steel",
  "Steel",
  "Strap",
  "Strap 1: 18K 5N pink gold; Strap 2: Alligator leather; Strap 3: Rubber.",
  "Strap 1: 18K white gold; Strap 2: Alligator leather; Strap 3: Rubber.",
  "Strap 1: Alligator leather; Strap 2: Rubber",
  "Strap 1: Alligator leather; Strap 2: Rubber.",
  "Strap 1: Stainless steel; Strap 2: Alligator leather; Strap 3: Rubber.",
  "Strap Not Included",
  "Strp zebra",
  "Synthetic",
  "Taupe Brown",
  "Techno Silk",
  "Techno-Silk",
  "Technological silk",
  "Titanium",
  "Titanuim",
  "Toile de Voile",
  "Transparent Structured Lined",
  "Transparent structured lined",
  "Transparent structured lined strap",
  "Tri-tone (Black, Silver-tone and Yellow Gold-tone)",
  "Tri-tone (White, Gold-tone and Silver-tone) Stainl",
  "Tropical Composite",
  "Tungsten",
  "Tweed",
  "Two Tone Jubilee",
  "Two-tone",
  "Two-tone (Black Ion-plated and Rose Gold-tone) Sta",
  "Two-tone (Black and Industrial Green Ion-plated) S",
  "Two-tone (Blue and Gunmetal Ion-plated)",
  "Two-tone (Gold-tone and Black Ion-plated) Stainle",
  "Two-tone (Gold-tone and Gunmetal Ion-plated)",
  "Two-tone (Rose Gold-tone and Grey Ion-plated) Stai",
  "Two-tone (Rose Gold-tone and Gunmetal Ion-plated)",
  "Two-tone (Silver-tone and 18kt Rose Gold-tone) Sta",
  "Two-tone (Silver-tone and 18kt Yellow Gold PVD)",
  "Two-tone (Silver-tone and Black Ion-plated) Stainl",
  "Two-tone (Silver-tone and Black ion-plated) Stainl",
  "Two-tone (Silver-tone and Gunmatal Ion-plated) Sta",
  "Two-tone (Silver-tone and Gunmetal ) Silver",
  "Two-tone (Silver-tone and Gunmetal Ion-plated) Sta",
  "Two-tone Silver-tone and Gold-tone PVD",
  "VINTAGE HAND SEAM BROWN",
  "Veal Strap",
  "Vegan Blush",
  "Vegan Nude",
  "Vegan Rose Sand",
  "Velcro",
  "Velvet",
  "Watch 1: dark brown calf Ponte Vecchio leather with beige stitching ; Watch 2: Blue alligator leather",
  "White",
  "White Gel Strap",
  "White Gold",
  "White Sahara",
  "White Veal",
  "White devil rays strap",
  "White stain",
  "Wood",
  "Yellow",
  "Yellow Elastic",
  "Yellow Gold",
  "Yellow Gold PVD",
  "Yellow Gold Plated",
  "Yellow Gold Tone",
  "Yellow Gold-PVD",
  "Yellow Gold-plated",
  "Yellow Gold-tone",
  "Yellow Gold-tone Expansion",
  "Yellow Gold-tone Expansion band",
  "Yellow PVD coating",
  "Yellow Sand Blue ilicone",
  "YellowGold-Plated",
  "Zucchino FF",
  "bi-material",
  "pink patent bracelet",
];

module.exports = bandM;