const dial_color =
  [
    "",
    " Blue Sunray patterned",
    "Abyss blue",
    "Alec Monopoly decoration",
    "Aletsch blue",
    "Amber Sunray",
    "Anthracite",
    "Anthracite Brushed",
    "Anthracite Skeleton",
    "Anthracite Sun Brushed Clous de Paris",
    "Anthracite Sun Brushed Clous de Paris dial",
    "Anthracite Sunray",
    "Anthracite sun brushed Clous de Paris dial",
    "Aqua (Flowers)",
    "Ardoise Grey",
    "Aubergine",
    "Aubergine set with diamonds",
    "Authentic Enamel",
    "Azure",
    "Beige",
    "Black",
    "Black ",
    "Black  with luminescence",
    "Black \"barleycorn\"",
    "Black & Silver",
    "Black (Four Time Zone)",
    "Black - Three Tome Zone",
    "Black Dual Time",
    "Black Dual Time Zone",
    "Black Gold",
    "Black Iridescent",
    "Black Jubilee",
    "Black Jubilee design set with diamonds",
    "Black Lacquered",
    "Black Mother of Pearl",
    "Black Ombre",
    "Black Ombre (Four Time Zone)",
    "Black Sun Brushed",
    "Black Sun Brushed ",
    "Black Sun Brushed  Clous de Paris",
    "Black Sun Brushed Clous de Paris",
    "Black Sun Brushed Squares",
    "Black Sun brushed Clous de Paris",
    "Black Sunbrushed",
    "Black and Grey (Dual Time Zone)",
    "Black and Multicolor",
    "Black and Rose Gold (Four Time Zone)",
    "Black and pink",
    "Black carbon",
    "Black carved",
    "Black dial",
    "Black guilloche",
    "Black lacquered polished",
    "Black matt",
    "Black mother-of-pearl",
    "Black mother-of-pearl Jubilee design set with diamonds",
    "Black mother-of-pearl set with diamonds",
    "Black set with diamonds",
    "Black set with diamonds and rubies",
    "Black skeleton",
    "Black sun brushed Clous de Paris",
    "Black sun brushed dial",
    "Black sunbrushed",
    "Black, diagonal motif",
    "Black, domed",
    "Blue",
    "Blue ",
    "Blue Computer",
    "Blue Dual Time Zone",
    "Blue Enamel",
    "Blue Gradient",
    "Blue Guilloché",
    "Blue Mother of Pearl",
    "Blue Skeleton",
    "Blue Sun Brushed",
    "Blue Sun Brushed ",
    "Blue Sun Brushed Squares",
    "Blue Sun Brushed and Sandblasted",
    "Blue Sun Brushed Clous de Paris",
    "Blue Sun brushed Clous de Paris",
    "Blue Sunbrushed",
    "Blue Sunburst",
    "Blue Sunray",
    "Blue Textured",
    "Blue azzurro",
    "Blue carved",
    "Blue dial",
    "Blue guilloche",
    "Blue set with diamonds",
    "Blue steel",
    "Blue sunbrushed Dial",
    "Blue with a guilloché design in the center",
    "Blue/Black",
    "Blush",
    "Bordeaux",
    "Bronze",
    "Bronze floral motif",
    "Bronze waves set with diamonds",
    "Brown",
    "Brown Camouflage",
    "Brown Floral",
    "Brown Sunburst",
    "Bue",
    "Burgundy",
    "Camouflage",
    "Carousel of green jade",
    "Champagne",
    "Champagne Dual Time Zone",
    "Champagne gold",
    "Champagne-colour",
    "Champagne-colour jacquard",
    "Champagne-colour set with diamonds",
    "Champagne-colour, raised floral motif",
    "Cherry",
    "Chocolate",
    "Chocolate Brown",
    "Chocolate set with diamonds",
    "Chrome",
    "Chrome White",
    "Cognac",
    "Copper",
    "Cream",
    "Crystal Pave",
    "Crystal Pave (MK Logo)",
    "Crystal Pave with Oversized MK logo",
    "Crystal Paved",
    "Dark Blue",
    "Dark Grey",
    "Dark Rhodium",
    "Dark Rodium Raised Floral Motif",
    "Dark grey",
    "Dark rhodium",
    "Dark rhodium set with diamonds",
    "Dark rhodium, raised floral motif",
    "Dark rhodium, stripe motif",
    "Diamond",
    "Diamond Pave",
    "Diamond Set",
    "Digital",
    "Digital Touch Display",
    "Enamel-white",
    "Floral Cutout",
    "Fuchsia Crystal Pave",
    "GG Motif Hologram",
    "GG Supreme Canvas",
    "Galvanized White and Grey Silver-plated",
    "Galvanized, Ruthenium-Plated",
    "Gilt",
    "Gold",
    "Gold Crystal Paved",
    "Gold Sunray",
    "Gold Tone",
    "Gold Tone Sunray",
    "Gold-tone",
    "Gradient Brown",
    "Grained white",
    "Graphite",
    "Green",
    "Green \r\n",
    "Green Sun Brushed",
    "Green dial",
    "Grey",
    "Grey ",
    "Grey (Four Time Zone)",
    "Grey (Partial Skeletal)",
    "Grey Dual Time Zone",
    "Grey Sunburst",
    "Grey Sunray",
    "Grey and white camouflage pattern",
    "Grey dial",
    "Grey lacquered",
    "Grey mother of pearl",
    "Grey pyramid-textured",
    "Guilloched Silvery Gray",
    "Gunmetal",
    "Gunmetal Grey",
    "Havana",
    "Ice Blue",
    "Ice blue",
    "Ivory",
    "Ivory-coloured",
    "Jupiter",
    "Khaki",
    "Khaki green ",
    "Lacquered Silver Guilloche",
    "Lavender",
    "Light Anthracite Hand Brushed ",
    "Light Blue",
    "Light Brown",
    "Light Champagne with MK logo",
    "Light Grey",
    "Light Tan",
    "Mat Black",
    "Mat Black Dial",
    "Matt Black",
    "Matte black ",
    "Mega Tapisserie Pattern",
    "Meteor Grey",
    "Meteorite",
    "Meteorite set with diamonds",
    "Midnight blue",
    "Military Camouflage",
    "Mint green set with diamonds",
    "Mother Of Pearl",
    "Mother of Pear",
    "Mother of Pearl",
    "Mother of Pearl Crystal-set",
    "Mother of pearl",
    "Mother-of-pearl",
    "Mother-of-pearl dial",
    "Multi-color",
    "Multicolour",
    "Navy",
    "Navy Blue",
    "Off White",
    "Olive",
    "Olive Green",
    "Olive green",
    "Olive green set with diamonds",
    "Opalin-silver",
    "Opaline",
    "Opaline-Silver",
    "Openworked ",
    "Openworked like a Range Rover rim",
    "Orange",
    "Orange (Degrade Effect)",
    "Pale mint green",
    "Pearl",
    "Pearlescent",
    "Pink",
    "Pink Jubilee design set with diamonds",
    "Pink Mother of Pearl",
    "Pink Mother-of-pearl",
    "Pink and black",
    "Pink floral motif",
    "Pink mother-of-pearl",
    "Pink mother-of-pearl set with diamonds",
    "Pink set with diamonds",
    "Pink waves set with diamonds",
    "Pink, raised floral motif",
    "Puple",
    "Purple",
    "Purple set with diamonds",
    "Red",
    "Red grape",
    "Rhodium",
    "Rhodium set with diamonds",
    "Rhodium waves",
    "Rose",
    "Rose Gold",
    "Rose Gold-tone",
    "Rose gold",
    "Rose gold skeleton",
    "Rose set with diamonds",
    "Ruthenium",
    "Sable",
    "Salmon-colored ",
    "Sandy Champagne",
    "Sapphire",
    "Silver",
    "Silver \"barleycorn\"",
    "Silver \"flinqué\"",
    "Silver (Mega-Tapestry)",
    "Silver Clous De Paris",
    "Silver Crystal-set",
    "Silver Dial",
    "Silver Galvanised Rhodium",
    "Silver Grained",
    "Silver Grande Tapisserie",
    "Silver Jubilee",
    "Silver Jubilee design set with diamonds",
    "Silver Opaline",
    "Silver Squares",
    "Silver Sun Brushed and Sandblasted",
    "Silver Sunray",
    "Silver Sunray with Skeletal Display",
    "Silver White",
    "Silver carved",
    "Silver dial",
    "Silver floral motif",
    "Silver guilloche",
    "Silver lacquered",
    "Silver set with diamonds",
    "Silver squares",
    "Silver sun brushed Clous de Paris dial",
    "Silver-Coloured",
    "Silver-plated",
    "Silver-tone",
    "Silver-toned sunray-patterned",
    "Silver-white",
    "Silvered Opaline",
    "Silvery Opaline",
    "Silvery White",
    "Silvery-white ",
    "Silvery-white guilloche",
    "Silvery-white guilloché ",
    "Skeletal",
    "Skeleton",
    "Skeleton dial",
    "Skeletonized",
    "Slate",
    "Slate Grey",
    "Slate Mega-Tapestry Waffle-pattern",
    "Slate-grey",
    "Slate-grey-toned sunray-patterned  ",
    "Smoked Sapphire dial",
    "Steel",
    "Steel and black",
    "Striped Silver",
    "Sun-Brushed Chestnut",
    "Sun-brushed",
    "Sunburst Blue",
    "Sundust",
    "Sundust set with diamonds",
    "Sunray Blue",
    "Sunray Brown",
    "Sunray Bue",
    "Sunray black",
    "Sunray blue",
    "Sunray grey",
    "Sunray silver",
    "Tempest Gray",
    "Transparent",
    "Turquoise",
    "Varnished Silver Graine",
    "Volcano Black",
    "Wavy blue",
    "White",
    "White ",
    "White  with luminescence",
    "White (Floral Motif)",
    "White Crystal Pave",
    "White Dual Time Zone",
    "White Guilloche",
    "White Lacquered",
    "White Lacquered ",
    "White Matt",
    "White Mother Of Pearl ",
    "White Mother of Pearl",
    "White Mother of Pearl ",
    "White Mother of Pearl with Crystals",
    "White Mother-of-pearl",
    "White Pearlized",
    "White Satin",
    "White Silver-plated",
    "White dial",
    "White dial with a guilloche pattern",
    "White lacquered polished",
    "White matt",
    "White mother of pearl",
    "White mother-of-pearl",
    "White mother-of-pearl set with diamonds",
    "White set with diamonds",
    "White silver",
    "White silver-plated",
    "World Map Motif",
    "Yellow",
    "Yellow Gold",
    "beige",
    "black",
    "black lacquered dial",
    "blue",
    "brown",
    "brown gradient",
    "carbon fibre",
    "champagne",
    "champagne gold",
    "digital",
    "galvanized, white silver-plated",
    "gold",
    "gray mother-of-pearl",
    "green",
    "grenadine red",
    "grey",
    "ivory",
    "matcha green",
    "mother of pearl",
    "mother-of-pearl guilloché",
    "multicolored",
    "ruthenium-plated",
    "silver",
    "siren blue",
    "skeleton",
    "white",
    "white dial with roman numerals",
    "white mother-of-pearl",
    "white silver-plated"
  ];

module.exports = dial_color;