const u = [
    "t-touch|T-Touch|function",
    "tachymeter|Tachyemter|function",
    "tachyneter|Tachymeter|function",
    "temperature Gauge|Thermometer|function",
    "temperature gauge|Thermometer|function",
    "text and calendar notifications|Text|function",
    "text and calendar notifications|Calendar|function",
    "texts|Text|function",
    "thermo|Thermometer|function",
    "thermometer|Thermometer|function",
    "third moonphase indication on the back for setting purposes|Moon Phase|function",
    "three-hand movement and digital display|Three Hand Movement|function",
    "three-hand movement and digital display|Digital Display|function",
    "three-handmovement|Three Hand Movement|function",
    "tide|Tide|function",
    "tide and moon graphs|Tide Graph|function",
    "tide and moon graphs|Moon Graph|function",
    "time|Time|function",
    "time 1 / time 2|Dual Time|function",
    "time 2, date, activity tracker, sleep tracker, smart notifications, alarm, link functions|Dual Time|function",
    "time 2, date, activity tracker, sleep tracker, smart notifications, alarm, link functions|Date|function",
    "time 2, date, activity tracker, sleep tracker, smart notifications, alarm, link functions|Activity Tracker|function",
    "time 2, date, activity tracker, sleep tracker, smart notifications, alarm, link functions|Sleep Tracker|function",
    "time 2, date, activity tracker, sleep tracker, smart notifications, alarm, link functions|Smart Notifications|function",
    "time 2, date, activity tracker, sleep tracker, smart notifications, alarm, link functions|Alarm|function",
    "time 2, date, activity tracker, sleep tracker, smart notifications, alarm, link functions|Link Function|function",
    "time city|Time City|function",
    "time zone and calendar syncing|Time Zone|function",
    "time zone and calendar syncing|Calendar Syncing|function",
    "timer|Timer|function",
    "times|Timer|function",
    "total score|Total Score|function",
    "touchscreen functionality|Touch Screen|function",
    "tourbillion|Tourbillon|function",
    "tourbillon|Tourbillon|function",
    "tracking of steps and sleep rhythm|Activity Tracker|function",
    "tracking of steps and sleep rhythm|Sleep Tracker|function",
    "tracks speed|Tracks Speed|function",
    "true beat seconds|Beat Seconds|function",
    "true beat seconds at 8 o'clock|Beat Seconds|function",
    "twin power reserve indicator|Power Reserve Indicator|function",
    "two big perpetual moon|Perpetual Moon|function",
    "two hand movement|Two Hand Movement|function",
    "units of ±1 hPa.||function",
    "universal hour|Universal Hour|function",
    "up to 12 hours|12 Hour|function",
    "utc time|UTC Time|function",
    "vfull auto-calendar|Full Auto Calendar|function",
    "voice translation|Voice Translation|function",
    "weather|Weather|function",
    "with stop function)|Stop Function|function",
    "with weeks indication|Weeks Indicator|function",
    "woodpecker neck regulation||function",
    "world time|World Time|function",
    "world time (48 cities)|World Time|function",
    "world time (48 cities+31 time zones) 1/100 second stopwatch|World Time|function",
    "world time (48 cities+31 time zones) 1/100 second stopwatch|Stopwatch|function",
    "world times|World Time|function",
    "worldtime||function",
    "year|Year|function",
    "zodiac calendar|Zodiac Calendar|function",
    "~ Countdown timer|Countdown Timer|function",
    "•Power reserve indicator|Power Reserve Indicator|function",

];