const u = [
    "2.8 mm Thick Plexiglass | crystal",
    "Acrylate | crystal",
    "Acrylic | crystal",
    "Acrylic / Plexiglass | crystal",
    "Acrylic Glass | crystal",
    "Acrylic Safety | crystal",
    "Aluminosilicate Glass | crystal",
    "Amber | crystal",
    "Amber Crystal | crystal",
    "Anit-glare Sapphire | crystal",
    "Ant-Reflective Mineral | crystal",
    "Ant-reflective Scratch Resistant Sapphire | crystal",
    "Anti Reflective Scratch Resistant Sapphire | crystal",
    "Anti-Reflective Flame Fusion | crystal",
    "Anti-Reflective Flame Fusion Crystal | crystal",
    "Anti-Reflective K1 | crystal",
    "Anti-Reflective Mineral | crystal",
    "Anti-Reflective Mineral Crystal | crystal",
    "Anti-Reflective Sapphire | crystal",
    "Anti-Reflective Sapphitek | crystal",
    "Anti-Reflective Scratch Resistant K1 | crystal",
    "Anti-Reflective Scratch Resistant Sapphire | crystal",
    "Anti-Reflective sapphire | crystal",
    "Anti-Reflective, Scratch Resistant Sapphire | crystal",
    "Anti-Refllective, Scratch Resistant Sapphire | crystal",
    "Anti-eflective Scratch Resistant Sapphire | crystal",
    "Anti-glare Sapphire | crystal",
    "Anti-glare Scratch Resistant Sapphire | crystal",
    "Anti-glare two faces | crystal",
    "Anti-reflctive Scratch Resistant Sapphire | crystal",
    "Anti-reflectice Scratch Resistant Sapphire | crystal",
    "Anti-reflective Flame Fusion | crystal",
    "Anti-reflective Mineral | crystal",
    "Anti-reflective Plexiglass | crystal",
    "Anti-reflective Sapphire | crystal",
    "Anti-reflective Scratch Resistant Sapphire | crystal",
    "Anti-reflective mineral crystal | crystal",
    "Anti-reflective sapphire | crystal",
    "Anti-reflective with magnifier | crystal",
    "Anti-reflectiveScratch Resistant Sapphire | crystal",
    "Antiglare Mineral | crystal",
    "Antireflective Sapphire | crystal",
    "Antireflective coating for chronograph and gent models | crystal",
    "Antireflective-sapphire | crystal",
    "Antireflex Sapphire | crystal",
    "Arcylic | crystal",
    "Blue Mineral Glass | crystal",
    "Blue Plexiglass | crystal",
    "Box-shaped Hardlex | crystal",
    "Cambered Glareproof Sapphire | crystal",
    "Cambered Glareproofed Sapphire | crystal",
    "Cambered Glareproofed Sappphire | crystal",
    "Cambered Polycarbonate | crystal",
    "Cambered Saphire, Glareproof | crystal",
    "Cambered Sapphire | crystal",
    "Cambered Sapphire, Glareproof | crystal",
    "Cambered Sapphire, Glareproofed both sides | crystal",
    "Cambered sapphire with anti-reflective coating on | crystal",
    "Cambered sapphire, glareproofed both sides | crystal",
    "Cambired Sapphire | crystal",
    "Chambered Sapphire | crystal",
    "Chambered Sapphire Crystal | crystal",
    "Coated Acrylic | crystal",
    "Confex Hard Plexiglass | crystal",
    "Confex Hard Plexiglass with a Sapphire Coating | crystal",
    "Confex Sapphire | crystal",
    "Convew Sapphire | crystal",
    "Convex Hard Plexiglass | crystal",
    "Convex Hard Plexiglass  with a SICRALAN Coating | crystal",
    "Convex Hard Plexiglass With Sicralan Coating | crystal",
    "Convex Hard Plexiglass with SICRALAN | crystal",
    "Convex Hard Plexiglass with SICRALAN Coating | crystal",
    "Convex Hard Plexiglass with SICRALAN coating | crystal",
    "Convex Hard Plexiglass with Sapphire Coating | crystal",
    "Convex Hard Plexiglass with Sicralan Coating | crystal",
    "Convex Hard Plexiglass with a Coating | crystal",
    "Convex Hard Plexiglass with a SICRALAN | crystal",
    "Convex Hard Plexiglass with a SICRALAN Coating | crystal",
    "Convex Hard Plexiglass with a SICRALAN coating | crystal",
    "Convex Hard Plexiglass with a Sapphire Coating | crystal",
    "Convex Hard Plexiglass with a Sapphire Crystal | crystal",
    "Convex Hard Plexiglass with a Sicralan Coating | crystal",
    "Convex Hard Plexiglass with a Sicralan coating | crystal",
    "Convex Plexiglass | crystal",
    "Convex Plexiglass and SICRALAN | crystal",
    "Convex Plexiglass with a SICRALAN Coating | crystal",
    "Convex Resistant Sapphire | crystal",
    "Convex Resistant Sapphire Crystal | crystal",
    "Convex Sapphire | crystal",
    "Convex Sapphire Crystal | crystal",
    "Convex hard Plexiglass with SICRALAN coating | crystal",
    "Convex hard plexiglass with SICRALAN coating | crystal",
    "Crystal | crystal",
    "Crystals | crystal",
    "Curved Hard Plexiglass | crystal",
    "Curved Hard Plexiglass with a SICRALAN coated | crystal",
    "Curved Hardened Mineral | crystal",
    "Curved Hardlex | crystal",
    "Curved Hardlex Glass | crystal",
    "Curved Mineral | crystal",
    "Curved Mineral Crystal | crystal",
    "Curved Sapphire Coated Mineral | crystal",
    "Curved hardened Mineral | crystal",
    "Dome Mineral Glass With Sapphire Coating | crystal",
    "Dome Mineral with Sapphire Coating | crystal",
    "Domed Acrylic | crystal",
    "Domed Anti-reflective Sapphire | crystal",
    "Domed Anti-reflective Scratch Resistant Sapphire | crystal",
    "Domed Anti-reflective, Scratch Resistant Sapphire | crystal",
    "Domed Flame Fushion | crystal",
    "Domed Flame Fusion | crystal",
    "Domed Hard Plexiglass | crystal",
    "Domed K1 | crystal",
    "Domed K1 Hardened | crystal",
    "Domed Krysterna | crystal",
    "Domed Mineral | crystal",
    "Domed Mineral Glass | crystal",
    "Domed Plexi Glass | crystal",
    "Domed Sapphire | crystal",
    "Domed Sapphire Crystal | crystal",
    "Domed Scratch Resistant  Antireflective Sapphire | crystal",
    "Domed Scratch Resistant Sapphire | crystal",
    "Domed Scratch Resistant Sapphire  with anti-reflec | crystal",
    "Domed hardened Plastic | crystal",
    "Domed scratch-resistant sapphire crystal | crystal",
    "Domed scratch-resistant sapphire crystal with anti | crystal",
    "Domed, Anti-reflective, Scratch Resistant Sapphire | crystal",
    "Domed, scratch-resistant sapphire crystal with ant | crystal",
    "Double Antireflective Sapphire | crystal",
    "Double Domed Mineral | crystal",
    "Double Face Anti-Reflective Sapphire | crystal",
    "Double Face Anti-reflective Sapphire | crystal",
    "Double Face Anti-reflective sapphire | crystal",
    "Double antireflective Sapphire | crystal",
    "Double antireflective sapphire crystal | crystal",
    "Double face Anti-reflective Sapphire | crystal",
    "Double face anti-reflective sapphire | crystal",
    "Durable mineral | crystal",
    "Faceted Mineral | crystal",
    "Fixed bezel set with crystals | crystal",
    "Flame Fusion | crystal",
    "Flame Fusion Anti Reflective Coating | crystal",
    "Flame Fusion Crystal- Anti-Reflective X3 Layers | crystal",
    "Flame Fusion w/ Triple Layer of Anti Reflective | crystal",
    "Flame Fusion with Anti-Reflective Coating | crystal",
    "Flame Fusion with Proctectivd leaver | crystal",
    "Flame Fusion, Anti Reflective | crystal",
    "Flame fusion | crystal",
    "Flame fusion Dome shape | crystal",
    "Flat Mineral | crystal",
    "Flat Mineral Crystal | crystal",
    "Flat Sapphire | crystal",
    "Flat Scratch-Resistant Sapphire Crystal | crystal",
    "Flat Scratch-Resistant Sapphire Srystal | crystal",
    "Glare Proof Mineral | crystal",
    "Glare Proof Mineral Glass | crystal",
    "Glareproof Sapphire | crystal",
    "Glareproof sapphire | crystal",
    "Glareproofed Sapphire | crystal",
    "Glass | crystal",
    "Glass Crystal Box | crystal",
    "Gorilla Glass | crystal",
    "Green Sapphire Crystal | crystal",
    "Green Tinted Mineral Crystal | crystal",
    "Hard Plexiglass | crystal",
    "Hard Plexiglass with SICRALAN Coating | crystal",
    "Hard Plexiglass with Sapphire Coating | crystal",
    "Hard Plexiglass with a SICRALAN Coating | crystal",
    "Hard Plexiglass with a Sapphire Coating | crystal",
    "Hard Plexiglass with a Sicralan Coating | crystal",
    "Hardened Anti-reflective Mineral | crystal",
    "Hardened Domed K1 Crystal | crystal",
    "Hardened Domed Mineral Glass | crystal",
    "Hardened K1 Mineral | crystal",
    "Hardened Mineral | crystal",
    "Hardened Mineral Crystal | crystal",
    "Hardened Mineral with Sapphire Coating | crystal",
    "Hardened Minetal | crystal",
    "Hardened Plastic Glass | crystal",
    "Hardened Polycarbonate | crystal",
    "Hardened mineral | crystal",
    "Hardex | crystal",
    "Hardles | crystal",
    "Hardlex | crystal",
    "Hardlex Curved | crystal",
    "Hesalit | crystal",
    "Hesalit Crystal | crystal",
    "Hesalite | crystal",
    "Hesalite Crystal | crystal",
    "Inorganic glass | crystal",
    "Iridescent Crystal | crystal",
    "Iridescent Mineral | crystal",
    "Iridescent crystal | crystal",
    "K-1 | crystal",
    "K-1 Mineral | crystal",
    "K1 | crystal",
    "K1  Sapphire | crystal",
    "K1 Anti- Reflective | crystal",
    "K1 Anti- Reflective Scratch Resistant | crystal",
    "K1 Anti-Reflective | crystal",
    "K1 Anti-Reflective Scratch Resistant | crystal",
    "K1 Anti-reflective, Scratch Resistant | crystal",
    "K1 Crystal | crystal",
    "K1 Crystals | crystal",
    "K1 Hardened Mineral | crystal",
    "K1 Mineral | crystal",
    "K1 Mineral Crystal | crystal",
    "K1 Mineral Glass | crystal",
    "K1 Scratch Resistant Mineral | crystal",
    "Krysterna | crystal",
    "Krysterna Crystal | crystal",
    "LCD Glass | crystal",
    "Luxury | crystal",
    "Mens: Saphire-Covered Mineral. Ladies Mineral | crystal",
    "Metalized Domed Mineral Crysta | crystal",
    "Mienral | crystal",
    "Mimeral | crystal",
    "Min eral | crystal",
    "Mineeral | crystal",
    "Mineral | crystal",
    "Mineral  with Sapphire Coating | crystal",
    "Mineral / Spherical Glass | crystal",
    "Mineral Crystal | crystal",
    "Mineral Crystal with Hardened Coating | crystal",
    "Mineral Crystal with Sapphire Coating | crystal",
    "Mineral Crystal with Sapphire Layer | crystal",
    "Mineral Crystal with Sapphire coating | crystal",
    "Mineral Crystal with Sapphire layer | crystal",
    "Mineral Crystal with a Hardened Coating | crystal",
    "Mineral Crystal with a Sapphire Coating | crystal",
    "Mineral Crystal witha Hardened Coating | crystal",
    "Mineral Glass | crystal",
    "Mineral Glass / Spherical Glass | crystal",
    "Mineral Glass Flat Sapphire | crystal",
    "Mineral Glass Flat Sapphire Coated | crystal",
    "Mineral Glass Sapphire Coated | crystal",
    "Mineral Glass with Blue Anti-reflex Coating | crystal",
    "Mineral Glass with Blue anti-reflex Coating | crystal",
    "Mineral Glass with Sapphire Coated | crystal",
    "Mineral Glass with Sapphire Coating | crystal",
    "Mineral Glass with Sapphire Treatment | crystal",
    "Mineral Glass with Sapphire coating | crystal",
    "Mineral Glass with a Blue Anti-reflex Coating | crystal",
    "Mineral Glass with a Sapphire Coating | crystal",
    "Mineral Glass with blue anti-reflex coating | crystal",
    "Mineral Glass with sapphire coating | crystal",
    "Mineral Hardened Coating | crystal",
    "Mineral Lens | crystal",
    "Mineral Sapphire Coated | crystal",
    "Mineral Sapphire Coated Glass | crystal",
    "Mineral Sapphire-Coated | crystal",
    "Mineral Steel | crystal",
    "Mineral a with Hardened Coating | crystal",
    "Mineral crystal with Sapphire coating | crystal",
    "Mineral crystal with hardened coating | crystal",
    "Mineral crystal with sapphire coating | crystal",
    "Mineral crystal, Hesalite crystal | crystal",
    "Mineral glass with sapphire coating | crystal",
    "Mineral w/ Sapphire Coating | crystal",
    "Mineral with Blue anti-reflex Coating | crystal",
    "Mineral with Hardened Coating | crystal",
    "Mineral with Hardening coating | crystal",
    "Mineral with Sapphire Coating | crystal",
    "Mineral with Sapphire Layer | crystal",
    "Mineral with Sapphire coating | crystal",
    "Mineral with Sapphire coating. | crystal",
    "Mineral with Sapphire layer | crystal",
    "Mineral with a Blue anti-reflex Coating | crystal",
    "Mineral with a Hardened Coating | crystal",
    "Mineral with a Sapphire Coating | crystal",
    "Mineral with a Sapphire coating | crystal",
    "Mineral with anti-reflective coating | crystal",
    "Mineral with hardening coating | crystal",
    "Mineral with sapphire coating | crystal",
    "Mineral with sapphire coating. | crystal",
    "Mineral withSapphire coating | crystal",
    "Mineral- Spherical Glass | crystal",
    "Multi-Colored Mineral | crystal",
    "Nineral | crystal",
    "Non-Glare Mineral | crystal",
    "Non-Glare Scratch Resistant Mineral | crystal",
    "Non-Glare Scratch-Resistant Mineral | crystal",
    "Non-Reflective Mineral | crystal",
    "Non-Reflective Sapphire | crystal",
    "Not Water Resistant | crystal",
    "Orange tinted Hardened Mineral | crystal",
    "PLastic | crystal",
    "PMMA Plastic | crystal",
    "Pastic | crystal",
    "Perspex | crystal",
    "Pexiglass | crystal",
    "Plactic | crystal",
    "Plas | crystal",
    "Plastic | crystal",
    "Plastic Plexiglass | crystal",
    "Plexi | crystal",
    "Plexi-Glass | crystal",
    "Plexi-Glass with a Sicralan Coating | crystal",
    "Plexi-glass with a Sicralan Coating | crystal",
    "Plexiglaee | crystal",
    "Plexiglas | crystal",
    "Plexiglasds | crystal",
    "Plexiglass | crystal",
    "Plexiglass with SICRALAN Coating | crystal",
    "Plexiglass with SICRALAN coating | crystal",
    "Plexiglass with Sapphire Coating | crystal",
    "Plexiglass with Sicralan Coating | crystal",
    "Plexiglass with Sicralan coating | crystal",
    "Plexiglass with a SICRALAN Coating | crystal",
    "Plexiglass with a Sicralan Coating | crystal",
    "Plexiglass with a Sicralan coating | crystal",
    "Plexiglass with an Anti-reflection Coating | crystal",
    "Plexiglass' | crystal",
    "Plexy Glass | crystal",
    "Polyamide | crystal",
    "Polymide | crystal",
    "Quartz | crystal",
    "Red Crystal Lens | crystal",
    "Red Mineral | crystal",
    "Reflective Mineral | crystal",
    "Reinforced Mineral | crystal",
    "Reinforced Mineral Crystal | crystal",
    "Reinforced Mineral K1 | crystal",
    "Reinforced Mineral K1 with Sapphire Coating | crystal",
    "Reinforced Mineral K1, with Sapphire Coating | crystal",
    "Resin Glass | crystal",
    "Resistant | crystal",
    "Round | crystal",
    "Rounded Mineral Crystal | crystal",
    "SAPPHITEK Crystal | crystal",
    "Saphhire | crystal",
    "Saphire | crystal",
    "Sapphie | crystal",
    "Sapphire | crystal",
    "Sapphire - Anti Reflective | crystal",
    "Sapphire - Anti-reflective | crystal",
    "Sapphire - Scratch Resistant | crystal",
    "Sapphire Coated | crystal",
    "Sapphire Coated  Mineral | crystal",
    "Sapphire Coated Crystal | crystal",
    "Sapphire Coated Flat Mineral | crystal",
    "Sapphire Coated Flat Mineral Glass | crystal",
    "Sapphire Coated Glass | crystal",
    "Sapphire Coated Mineral | crystal",
    "Sapphire Coated Mineral Glass | crystal",
    "Sapphire Cryst | crystal",
    "Sapphire Crystal | crystal",
    "Sapphire Crystal Scratch Resistant | crystal",
    "Sapphire Crystal with Antireflex Treatment | crystal",
    "Sapphire Glass | crystal",
    "Sapphire Glass Scratch Anti Resistant | crystal",
    "Sapphire Lens | crystal",
    "Sapphire Made of Corundum | crystal",
    "Sapphire Scratch Resistant | crystal",
    "Sapphire With Antiglare Treatment | crystal",
    "Sapphire cabochon | crystal",
    "Sapphire coated  mineral | crystal",
    "Sapphire coated Mineral | crystal",
    "Sapphire coated Mineral Glass | crystal",
    "Sapphire coated mineral | crystal",
    "Sapphire coated mineral Glass | crystal",
    "Sapphire crystal formed of corundum | crystal",
    "Sapphire formed of Corundum | crystal",
    "Sapphire formed of corundum | crystal",
    "Sapphire with Anti-reflective Treatment | crystal",
    "Sapphire with anti-reflective treatment | crystal",
    "Sapphire with antiglare treatment | crystal",
    "Sapphire with interior/exterior anti-reflection tr | crystal",
    "Sapphire, Anti-Reflective | crystal",
    "Sapphire, Antiglare | crystal",
    "Sapphire, Glareproofed | crystal",
    "Sapphire, domed on both sides, anti-reflective coa | crystal",
    "Sapphire-Coated | crystal",
    "Sapphire-Coated Krysterna | crystal",
    "Sapphire-Coated Mineral | crystal",
    "Sapphire-Coated Mineral Crystal | crystal",
    "Sapphire-Coated Minetal | crystal",
    "Sapphire-Layered Mineral | crystal",
    "Sapphire-coated Mineral | crystal",
    "Sapphire-coated curved | crystal",
    "Sapphire-coated curved mineral | crystal",
    "Sapphire-coated mineral | crystal",
    "Sapphiree | crystal",
    "Sapphirev | crystal",
    "Sapphite | crystal",
    "Sapphitek | crystal",
    "Sapphitek Crystal | crystal",
    "Sapphrie | crystal",
    "Sappihre | crystal",
    "Sappire | crystal",
    "Sappitek | crystal",
    "Sappphire | crystal",
    "Scratch | crystal",
    "Scratch Convex Resistant Sapphire | crystal",
    "Scratch Reistant Sapphire | crystal",
    "Scratch Resistant  Anti-reflective Sapphire | crystal",
    "Scratch Resistant  Flame Fusion | crystal",
    "Scratch Resistant  Touch-sensitive Sapphire | crystal",
    "Scratch Resistant (Edge-to-Edge) Mineral | crystal",
    "Scratch Resistant (Multi-hued Iridescent) Mineral | crystal",
    "Scratch Resistant (TV Screen) Sapphire | crystal",
    "Scratch Resistant Acrylic | crystal",
    "Scratch Resistant Amber  Mineral | crystal",
    "Scratch Resistant Amber Mineral | crystal",
    "Scratch Resistant Amber-tinted Mineral | crystal",
    "Scratch Resistant Anti-Reflective K1 | crystal",
    "Scratch Resistant Anti-Reflective Sapphire | crystal",
    "Scratch Resistant Anti-reflective Sapphire | crystal",
    "Scratch Resistant Anti-reflectiveSapphire | crystal",
    "Scratch Resistant Antireflective Sapphire | crystal",
    "Scratch Resistant Arcylic | crystal",
    "Scratch Resistant Blue Mineral | crystal",
    "Scratch Resistant Blue Tinged Mineral | crystal",
    "Scratch Resistant Blue-Tinted Mineral | crystal",
    "Scratch Resistant Blue-tint Mineral | crystal",
    "Scratch Resistant Convex Mineral | crystal",
    "Scratch Resistant Convex Sapphire | crystal",
    "Scratch Resistant Domed Mineral | crystal",
    "Scratch Resistant Domed Sapphire | crystal",
    "Scratch Resistant Flame Fusion | crystal",
    "Scratch Resistant Flmae fusion | crystal",
    "Scratch Resistant Glareproof Sapphire | crystal",
    "Scratch Resistant Green Mineral | crystal",
    "Scratch Resistant Hard Plexiglass | crystal",
    "Scratch Resistant Hardened K1 | crystal",
    "Scratch Resistant Hardened Mineral | crystal",
    "Scratch Resistant Hardlex | crystal",
    "Scratch Resistant Hesalite | crystal",
    "Scratch Resistant Hesalite Crystal | crystal",
    "Scratch Resistant Iridescent Mineral | crystal",
    "Scratch Resistant Irridescent Mineral | crystal",
    "Scratch Resistant K! | crystal",
    "Scratch Resistant K1 | crystal",
    "Scratch Resistant K1 Hardlex | crystal",
    "Scratch Resistant K1 Mineral | crystal",
    "Scratch Resistant K1 Mineral Crystal | crystal",
    "Scratch Resistant K1 mineral | crystal",
    "Scratch Resistant K1Mineral | crystal",
    "Scratch Resistant Krysterna | crystal",
    "Scratch Resistant Light Gold Mineral | crystal",
    "Scratch Resistant Magnifier Mineral | crystal",
    "Scratch Resistant Mineral | crystal",
    "Scratch Resistant Mineral K1 | crystal",
    "Scratch Resistant Mineral with orange tint | crystal",
    "Scratch Resistant Mineral, Green-Tinted | crystal",
    "Scratch Resistant Plexiglas | crystal",
    "Scratch Resistant Plexiglass | crystal",
    "Scratch Resistant Reinforced Mineral | crystal",
    "Scratch Resistant Sapphier | crystal",
    "Scratch Resistant Sapphire | crystal",
    "Scratch Resistant Sapphire - antiglare treatmen | crystal",
    "Scratch Resistant Sapphire Anti Reflective | crystal",
    "Scratch Resistant Sapphire Coated | crystal",
    "Scratch Resistant Sapphire Coated Mineral | crystal",
    "Scratch Resistant Sapphire Touch | crystal",
    "Scratch Resistant Sapphire coated Mineral | crystal",
    "Scratch Resistant Sapphire with Anti-Reflective Tr | crystal",
    "Scratch Resistant Sapphire with Arabic Numerals (i | crystal",
    "Scratch Resistant Sapphire with Frosted Color Trea | crystal",
    "Scratch Resistant Sapphire, anti-glare treatment | crystal",
    "Scratch Resistant Sapphire- Coated Minetal | crystal",
    "Scratch Resistant Sapphire-Coated | crystal",
    "Scratch Resistant Sapphire-Coated Crystal | crystal",
    "Scratch Resistant Sapphire-Coated Mineral | crystal",
    "Scratch Resistant Sapphire-Coated Minertal | crystal",
    "Scratch Resistant Sapphire-Coated Minetal | crystal",
    "Scratch Resistant Sapphire-coated Mineral | crystal",
    "Scratch Resistant Sapphitek | crystal",
    "Scratch Resistant Scratch Resistant Sapphire | crystal",
    "Scratch Resistant Scratch Resistant Sapphire Cryst | crystal",
    "Scratch Resistant Stnthetic Sapphire | crystal",
    "Scratch Resistant Synthetic Sapphire | crystal",
    "Scratch Resistant TV Screen Sapphire | crystal",
    "Scratch Resistant Tactile Sapphire | crystal",
    "Scratch Resistant Tinted Mineral | crystal",
    "Scratch Resistant Titan | crystal",
    "Scratch Resistant Touch Screen Sapphire | crystal",
    "Scratch Resistant Touchscreen | crystal",
    "Scratch Resistant Touchscreen Mineral | crystal",
    "Scratch Resistant and Anti-reflective Sapphire | crystal",
    "Scratch Resistant plexiglas | crystal",
    "Scratch Resistant sapphire | crystal",
    "Scratch Resistant triple-coated. anti-reflective s | crystal",
    "Scratch Resistant, Anti-reflective Sapphire | crystal",
    "Scratch Resitant Sapphire | crystal",
    "Scratch resistant Flame Fusion | crystal",
    "Scratch resistant Hardlex | crystal",
    "Scratch resistant K1 mineral | crystal",
    "Scratch resistant Sapphire | crystal",
    "Scratch resistant Sapphire anti-reflective | crystal",
    "Scratch resistant flame fusion | crystal",
    "Scratch resistant mineral | crystal",
    "Scratch resistant mineral acrylic | crystal",
    "Scratch resistant mineral with anti-reflective coa | crystal",
    "Scratch resistant plastic | crystal",
    "Scratch resistant sapphire | crystal",
    "Scratch-Resistant Sapphimax | crystal",
    "Scratch-resistant Beveled Mineral Crystal | crystal",
    "Scratch-resistant sapphire crystal | crystal",
    "Shatter Resistant Krysterna | crystal",
    "Shatter resistant Krysterna | crystal",
    "Shatter-resistant Krysterna | crystal",
    "ShatterResistant Krysterna | crystal",
    "Shock Resistant Mineral | crystal",
    "Silver-tone | crystal",
    "Solid  Sapphire | crystal",
    "Solidified Crystal Mineral | crystal",
    "Specially Hardened Domed Mineral | crystal",
    "Spectrum Glass | crystal",
    "Spherical | crystal",
    "Spherical Crystal | crystal",
    "Spherical Glass | crystal",
    "Spphire | crystal",
    "Ssapphire | crystal",
    "Stainless Steel | crystal",
    "Super Harden Mineral | crystal",
    "Synthethic Sapphire | crystal",
    "Syntheti cMineral | crystal",
    "Synthetic Mineral | crystal",
    "Synthetic Saphire | crystal",
    "Synthetic Sapphire | crystal",
    "Synthetic Sapphirre | crystal",
    "Synthetic mineral | crystal",
    "Synthetic sapphire | crystal",
    "Sythnetic Sapphire | crystal",
    "TV Screen Anti-reflective Sapphire | crystal",
    "Tactile Sapphire | crystal",
    "Tactile Sapphire Crystal | crystal",
    "Tactile Scratch Resistant Sapphire | crystal",
    "Tactile Scratch Resistant Sapphire Crystal | crystal",
    "Tactile Scratch-Resistant Sapphire | crystal",
    "Tactile Scratch-Resistant Sapphire Crystal | crystal",
    "Tactile Scratch-resistant Sapphire Crystal | crystal",
    "Tactile scratch-resistant Sapphire | crystal",
    "TapScreen Technology Mineral | crystal",
    "Tinted Flame Fusion | crystal",
    "Tinted Mineral | crystal",
    "Tinted Mineral Crystal | crystal",
    "Tinted Minerall | crystal",
    "Titan | crystal",
    "Touchscreen Scratch Resistant Mineral | crystal",
    "Triple Anti-reflective Flame Fusion | crystal",
    "Triple Layer of Anti Reflective Flame Fusion | crystal",
    "Triple Layered Anti-reflective Coated Flame Fusion | crystal",
    "Triple layered Anti-Reflective Coated Flame Fusion | crystal",
    "Triple-coated Anti-reflective Sa | crystal",
    "Triple-coated Anti-reflective Sapphire | crystal",
    "Two-face antiglare | crystal",
    "Ultra-Domed Plexi Crystal | crystal",
    "antireflective-sapphire | crystal",
    "cambered sapphire | crystal",
    "cambered sapphire crystal with anti-reflective coa | crystal",
    "decorated sapphire | crystal",
    "flame fusion | crystal",
    "ouble Curved Mineral | crystal",
    "plexiglass | crystal",
    "raised acrylic crystal | crystal",
    "seven floating dials | crystal",
    "synthetic-sapphire | crystal",
];

module.exports = u;