const u = [
    "3-Hand Movement|Three Hand Movement|movement",
    "3-hand movement|Three Hand Movement|movement",
    "Ana-Digi|Analog-Digital|movement",
    "Analog|Analog|movement",
    "Auto-Quartz|Automatic|movement",
    "Automatic|Automatic|movement",
    "Big Calendar\nChronograph|Chronograph|movement",
    "Chronograph|Chronograph|movement",
    "Chronograph Movement|Chronograph|movement",
    "Digital|Digital|movement",
    "Dual Time|NOT MAPPED|movement",
    "Eco-Drive|Eco-Drive|movement",
    "Functions: Hours, minutes|NOT MAPPED|movement",
    "Hand Movement||movement",
    "Hand Wind|Manual|movement",
    "Hand-wind|Manual|movement",
    "Kinetic|Kinetic|movement",
    "MMT-187|NOT MAPPED|movement",
    "MMT-284 CONNECTED CALIBER.|NOT MAPPED|movement",
    "Manual|Manual|movement",
    "Mechanical|Mechanical|movement",
    "Mechanical Twist|Mechanical|movement",
    "Multifunction|Multifunction|movement",
    "Multifunction Movement|Multifunction|movement",
    "None|NOT MAPPED|movement",
    "Not specified|NOT MAPPED|movement",
    "Other|NOT MAPPED|movement",
    "Power reserve indicator|NOT MAPPED|movement",
    "Quartz|Quartz|movement",
    "Seconds subdial|NOT MAPPED|movement",
    "Skeleton, Swiss Made|NOT MAPPED|movement",
    "Smart Watch|Smart Watch|movement",
    "Smartwatch|Smart Watch|movement",
    "Solar power|Solar Power|movement",
    "Spring Drive|Spring Drive|movement",
    "Swiss mechanical|Swiss Mechanical|movement",
    "Three Hand|Three Hand Movement|movement",
    "Three-Hand Movement|Three Hand Movement|movement"
];

module.exports = u;