const u = [
    // "Moonphase, Power Reserve and Date||subDial",
    // "One - 1/100 of a minute at the 9 o'clock Position||subDial",
    // "One - 12 Hour||subDial",
    // "One - 12 Hour (Dual Time) at the 6 o'clock position||subDial",
    // "One - 12 Hour/60 Minute||subDial",
    // "One - 12 Hour/60 Second||subDial",
    // "One - 12 Hours (inner 60 Minute)||subDial",
    // "One - 12 Hours/60 Minute (Second Time Zone)||subDial",
    // "One - 12 hour with Day/Night Indicator||subDial",
    // "One - 24 Hour||subDial",
    // "One - 24 Hour (GMT)||subDial",
    // "One - 24 Hour (GMT) at the 10 o'clock position||subDial",
    // "One - 24 Hour/Moonphase||subDial",
    // "One - 24 Hours||subDial",
    // "One - 24 hour||subDial",
    // "One - 30 Minute||subDial",
    // "One - 30 Minute at the 6 o'clock position||subDial",
    // "One - 30 Minutes||subDial",
    // "One - 60 Second||subDial",
    // "One - 60 Seconds||subDial",
    // "One - 60 minute||subDial",
    // "One - 60 second||subDial",
    // "One - Analogue Thermometer||subDial",
    // "One - Combined Date and Moonphase at the 6 o'clock position||subDial",
    // "One - Crystal-set Small Second||subDial",
    // "One - Date||subDial",
    // "One - Date (inner moonphase)||subDial",
    // "One - Date / Moonphase||subDial",
    // "One - Date and Moonphase||subDial",
    // "One - Date/Moon Phase||subDial",
    // "One - Date/Moonphase||subDial",
    // "One - Day||subDial",
    // "One - Day of the Week||subDial",
    // "One - Day/Night Indicator||subDial",
    // "One - Digital||subDial",
    // "One - Dual Time zone||subDial",
    // "One - Dual time zone at the 6 o'clock position||subDial",
    // "One - Moon Phase||subDial",
    // "One - Moon Phase/24 Hour||subDial",
    // "One - Moon Phase/Small Second||subDial",
    // "One - Moon phase/Date||subDial",
    // "One - Moonphase||subDial",
    // "One - Moonphase on back||subDial",
    // "One - Moonphase/24 Hour at the 6 o'clock position||subDial",
    // "One - Moonphase/Date||subDial",
    // "One - Moonphase/Small Second||subDial",
    // "One - Open Heart||subDial",
    // "One - Power Reserve Indicator||subDial",
    // "One - Power Reserve Indicator at the 6 o'clock position||subDial",
    // "One - Result Display||subDial",
    // "One - Retrograde 24 Hour at the 6 o'clock position||subDial",
    // "One - Retrograde Minute||subDial",
    // "One - Retrograde Small Second||subDial",
    // "One - Second Time Zone||subDial",
    // "One - Seconds sub-dial between 9 and 10 o'clock||subDial",
    // "One - Small SEcond||subDial",
    // "One - Small Second||subDial",
    // "One - Small Second and 24 hour on other Side||subDial",
    // "One - Small Second at 6 o'clock||subDial",
    // "One - Small Second at the 6 o'clock position||subDial",
    // "One - Small Second at the 9 o'clock position||subDial",
    // "One - Small Second/Moonphase||subDial",
    // "One - Small Seconds||subDial",
    // "One - Small second||subDial",
    // "One - Thermometric Indication at the 6 o'clock position||subDial",
    // "One - Tourbillon||subDial",
    // "One - Tourbillon/Moonphase||subDial",
    // "One - Tourbillon/Small Second||subDial",
    // "One Date||subDial",
    // "One Small Second/Moonphase at the 6 o'clock position||subDial",
    // "One Sub-dial at the 6 o'clock position displaying Moonphases and 24 Hours||subDial",
    // "One Sub-dial at the 6 o'clock position displaying Moonphases and AM/PM||subDial",
    // "One- 12 Hours||subDial",
    // "One- 60 Minutes||subDial",
    // "One- 60 Seconds||subDial",
    // "One- Date||subDial",
    // "One- Month||subDial",
    // "One- Moonphase||subDial",
    // "One- Power Reserve||subDial",
    // "One- Small Second||subDial",
    // "One- Small Seconds||subDial",
    // "One-- Small Seconds||subDial",
    // "One-60 Seconds||subDial",
    // "One-Seconds||subDial",
    // "One-minute Flying Tourbillon||subDial",
    // "Open Heart||subDial",
    // "Power Reserve||subDial",
    // "Power Reserve Display||subDial",
    // "Power Reserve Indicator||subDial",
    // "Power Reserve Indicator Sub-dial at the 7 o'clock position||subDial",
    // "Power Reserve Indicator at the 7 o'clock position||subDial",
    // "Power Reserve Sub-dial||subDial",
    // "Power Reserve Sub-dial at the 7,30 position||subDial",
    // "Power Reserve and Tourbillon Carriage Small Second with Date||subDial",
    // "Power Reserve, Alarm On Off and Date||subDial",
    // "Power Reserve, Seconds, Retrograde Calendar||subDial",
    // "Power Rserve||subDial",
    // "Powere Reserve||subDial",
    // "Recessed||subDial",
    // "Retrograde 24 Hour Indicator||subDial",
    // "Retrograde 24 Hour Indicator Sub-dial||subDial",
    // "Retrograde Date||subDial",
    // "Retrograde Date indicator||subDial",
    // "Retrograde Date, Small Second, Moonphase||subDial",
    // "Rose Gold-plated||subDial",
    // "Second Time Zone||subDial",
    // "Seconds||subDial",
    // "Seconds Sin-dial at the 6 o'clock position||subDial",
    // "Seconds Sub-dial above the 6 o'clock position||subDial",
    // "Seconds Sub-dial above the 6 o'clock position. Three Displays: Date, Day of the Week and Month||subDial",
    // "Seconds Sub-dial above the 6 o'clock positions||subDial",
    // "Seconds Sub-dial appears at the 6 o'clock position||subDial",
    // "Seconds Sub-dial at the 6 o'clock position||subDial",
    // "Seconds Sub-dial at the 7 o'clock position||subDial",
    // "Seconds Sub-dial at the 9 o'clock position||subDial",
    // "Seconds Sub-dial near the 8 o'clock position||subDial",
    // "Seconds Sub-dial. Power Reserve Display||subDial",
    // "Seconds and 24 Hour||subDial",
    // "Seconds and 30 Minute||subDial",
    // "Seconds and 60 Minute||subDial",
    // "Seconds and 60 Second||subDial",
    // "Seconds and Month and Day of the Week||subDial",
    // "Seconds and Moonphase||subDial",
    // "Seconds and Power Reserve||subDial",
    // "Seconds at the 6 o'clock position||subDial",
    // "Seconds at the 9 o'clock position||subDial",
    // "Seconds sub-dial||subDial",
    // "Seconds sub-dial at 6 o'clock||subDial",
    // "Seconds, 12 Hours and Moonphase||subDial",
    // "Seconds, 12 Hours and Power Reserve||subDial",
    // "Seconds, 12 Hours, 24 Hour and Flyback Chronograph||subDial",
    // "Seconds, 24 Hour and Power Reserve||subDial",
    // "Seconds, 30 Minute and 12 Hours||subDial",
    // "Seconds, 30 Minute and 6 Hours||subDial",
    // "Seconds, 30 Minute and Day of the Week||subDial",
    // "Seconds, 30 Minute and Moonphase||subDial",
    // "Seconds, 30 Minute and Power Reserve||subDial",
    // "Seconds, 60 Minute and 12 Hours||subDial",
    // "Seconds, 60 Minute and Moonphase||subDial",
    // "Seconds, 60 Second and 12 Hours||subDial",
    // "Seconds, 60 Second and 24 Hour||subDial",
    // "Seconds, 60 Second and 30 Minute||subDial",
    // "Seconds, 60 Second, 30 Minute and Date||subDial",
    // "Seconds, 60 Second, 30 Minute and Power Reserve||subDial",
    // "Seconds. Dual Time||subDial",
    // "Signal Reception Indicator, Summer Time Indicator||subDial",
    // "Smal Seconds||subDial",
    // "Small 60 Seconds||subDial",
    // "Small Second||subDial",
    // "Small Second at the 6 o'clock position||subDial",
    // "Small Second, GMT||subDial",
    // "Small Second, Power Reserve Indicator||subDial",
    // "Small Second, Power Reserve Indicator on the back||subDial",
    // "Small Second. Second Time Zone||subDial",
    // "Small Seconds||subDial",
    // "Small Seconds  and 12 Hours||subDial",
    // "Small Seconds  and 15 Minute and 6 Hour||subDial",
    // "Small Seconds  and 24 Hour||subDial",
    // "Small Seconds  and 30 Minute||subDial",
    // "Small Seconds  and 60 Minute||subDial",
    // "Small Seconds  and 60 Second||subDial",
    // "Small Seconds  and Date||subDial",
    // "Small Seconds  and Dual Time||subDial",
    // "Small Seconds  and Flyback Chronograph||subDial",
    // "Small Seconds  and Month and Day of the Week||subDial",
    // "Small Seconds  and Moonphase||subDial",
    // "Small Seconds  and Power Reserve||subDial",
    // "Small Seconds , 12 Hours and 24 Hour||subDial",
    // "Small Seconds , 12 Hours and Power Reserve||subDial",
    // "Small Seconds , 12 hours (GMT) and Power Reserve||subDial",
    // "Small Seconds , 30 Minute and 12 Hours||subDial",
    // "Small Seconds , 30 Minute and 12 hours (GMT)||subDial",
    // "Small Seconds , 30 Minute and Day of the Week||subDial",
    // "Small Seconds , 30 Minute and Power Reserve||subDial",
    // "Small Seconds , 30 Minute, 12 Hours and Power Reserve||subDial",
    // "Small Seconds , 60 Minute and 12 Hours||subDial",
    // "Small Seconds , 60 Second and 12 Hours||subDial",
    // "Small Seconds , 60 Second and 30 Minute||subDial",
    // "Small Seconds , 60 Second, 30 Minute and Power Reserve||subDial",
    // "Small Seconds , 60 Second, Power Reserve and Date||subDial",
    // "Small Seconds , Month and Day of the Week and Moonphase||subDial",
    // "Small Seconds , Moonphase and Power Reserve||subDial",
    // "Small Seconds , Moonphase, Power Reserve and Date||subDial",
    // "Small Seconds , Power Reserve and AM/PM Indicator||subDial",
    // "Small Seconds / Moonphase||subDial",
    // "Small Seconds Sub dial at the 9 o'clock position||subDial",
    // "Small Seconds Sub-dial||subDial",
    // "Small Seconds Sub-dial above the 6 o'clock position||subDial",
    // "Small Seconds Sub-dial and Moonphase above the 6 o'clock position||subDial",
    // "Small Seconds Sub-dial at the 6 o'clock position||subDial",
    // "Small Seconds Sub-dial at the 7 o'clock position||subDial",
    // "Small Seconds Sub-dial at the 9 o'clock position||subDial",
    // "Small Seconds Sub-dial. Power Reserve Indicator||subDial",
    // "Small Seconds Sub-dials||subDial",
    // "Small Seconds and 24-hour indicator||subDial",
    // "Small Seconds and Power Reserve Indicator||subDial",
    // "Small Seconds at the 6 o'clock position||subDial",
    // "Small Seconds at the 9 o'clock position||subDial",
    // "Small Seconds sub-dial at the 5 o'clock position||subDial",
    // "Small Seconds sub-dial at the 6 o'clock position||subDial",
    // "Small Seconds. Date Scale||subDial",
    // "Small Seconds. Power Reserve||subDial",
    // "Small Seconds. Power Reserve Indicator||subDial",
    // "Small seconds at the 3 o'clock position, Chrono 30 minute counter at the 9 o'clock position||subDial",
    // "Small seconds sub-dial at the 9 o'clock position||subDial",
    // "Sun / Moon||subDial",
    // "Sun And Moon||subDial",
    // "Sun and Moon||subDial",
    // "Swarovski Crystal-set 60 Second||subDial",
    // "Swarovski Crystal-set Seconds||subDial",
    // "Swarovski Crystal-set Small Seconds||subDial",
    // "Sweep second hand, 30 minute counter at the 9 o'clock position||subDial",
    // "Taupe Dial||subDial",
    // "Thee - Date, Day, 24 Hour||subDial",
    // "Thermometer (Celsius and Fahrenheit)||subDial",
    // "Thermometer Display||subDial",
    // "Thermometric Indication||subDial",
    // "Three||subDial",
    // "Three - 1/10 second, 60 Second and 60 Minute||subDial",
    // "Three - 1/10 second, 60 second and 30 minute||subDial",
    // "Three - 1/10 seconds, 60 second, 60 minute||subDial",
    // "Three - 12 Hour, 30 Minute and 24 Hour||subDial",
    // "Three - 12 Hour, 30 Minute and 60 Second||subDial",
    // "Three - 12 Hour, 30 Minute and Small Second||subDial",
    // "Three - 12 Hour, 30 Minute, 60 Second||subDial",
    // "Three - 12 Hour, 60 Minute and 60 Second||subDial",
    // "Three - 12 Hour/60 Minute, 24 Hour, Result display||subDial",
    // "Three - 12 Hours, 30 Minutes, 60 Seconds||subDial",
    // "Three - 12 Hours, 30 Minutes, Small Seconds||subDial",
    // "Three - 12 Hours, 60 Minute and 1/10th of a Second||subDial",
    // "Three - 24 Hour (GMT) , Date and Day of the Week||subDial",
    // "Three - 24 Hour (GMT), 12 Hours and 60 Second||subDial",
    // "Three - 24 Hour (GMT), Date and Day of the Week||subDial",
    // "Three - 24 Hour / 60 Seconds, 30 Minute and 1/10th of a Second/Moonphase||subDial",
    // "Three - 24 Hour, 1/10th of a Second and Function||subDial",
    // "Three - 24 Hour, 24 Hour and Day of the Week||subDial",
    // "Three - 24 Hour, 24 Hour, Day||subDial",
    // "Three - 24 Hour, 30 Minute and 60 Second||subDial",
    // "Three - 24 Hour, 60 Minute, 60 Second||subDial",
    // "Three - 24 Hour, 60 Second and 30 Minute||subDial",
    // "Three - 24 Hour, Date and Day of the Week||subDial",
    // "Three - 24 Hour, Date and Day of the Weekm||subDial",
    // "Three - 24 Hour, Date and Day of the Weelk||subDial",
    // "Three - 24 Hour, Date and Day of the week||subDial",
    // "Three - 24 Hour, Date and Retrograde Day||subDial",
    // "Three - 24 Hour, Date and day of the Week||subDial",
    // "Three - 24 Hour, Date, Day||subDial",
    // "Three - 24 Hour, Date, Retrograde Day||subDial",
    // "Three - 24 Hour, Day & Date||subDial",
    // "Three - 24 Hour, Day and Date||subDial",
    // "Three - 24 Hour, Day of the Week and Power Reserve Indicator||subDial",
    // "Three - 24 Hour, Month and Day of the Week||subDial",
    // "Three - 24 Hour, Retrograde Date and 24 Hour||subDial",
    // "Three - 24 Hour, Retrograde Date and Retrograde 24 Hour||subDial",
    // "Three - 24 Hour, Retrograde Date, Retrograde Day||subDial",
    // "Three - 24 Hour, Small Second and Tourbillon||subDial",
    // "Three - 24 Hour, date and Day of the Week. Power Reserve||subDial",
    // "Three - 24 Hour, date and Day of the Week. Power Reserve Indicator||subDial",
    // "Three - 24 Hour,24 Hours and Days of the week||subDial",
    // "Three - 24 Hour. Date and Day of the Week||subDial",
    // "Three - 24 Hour/60 Second, 30 Minute and Power Reserve Indicator||subDial",
    // "Three - 24 Hours, 30 Minutes and 60 Seconds||subDial",
    // "Three - 24 Hours, 30 Minutes, 60 Seconds||subDial",
    // "Three - 24 Hours, 60 Minutes, 60 Seconds||subDial",
    // "Three - 24 Hours, Date and Day of the Week||subDial",
    // "Three - 24 Hours, Date andDay of the Week||subDial",
    // "Three - 24 Hours, Dated and Day of the Week||subDial",
    // "Three - 24 Hours, Day and Date||subDial",
    // "Three - 24 Hours, Day of the Week and Date||subDial",
    // "Three - 24 Hours, Day, Date||subDial",
    // "Three - 24 Hous, 60 Minutes, 60 Seconds||subDial",
    // "Three - 24 hour (GMT), Date and Day of the Week||subDial",
    // "Three - 24 hour (GMT), Date and Day of the week||subDial",
    // "Three - 24 hour (GMT), Date, Day of the week||subDial",
    // "Three - 24 hour, Date and Day of the Week||subDial",
    // "Three - 24 hour, Date, Day of the week||subDial",
    // "Three - 24 hour, Day of the Week and Date||subDial",
    // "Three - 24 hours, Date and Day of the Week||subDial",
    // "Three - 2nd Time Zone, Half Time Zone Indicator and AM/PM Indicator||subDial",
    // "Three - 30 Minute 12 Hours and 60 Second Tourbillon||subDial",
    // "Three - 30 Minute, 12 Hour and 24 Hour Sub-dials||subDial",
    // "Three - 30 Minute, 12 Hours, and 1/100th of a Second||subDial",
    // "Three - 30 Minute, 24, Hour and 12 Hour (inner moonphase)||subDial",
    // "Three - 30 Minute, 24, Hours and 12 Hours (inner moonphase)||subDial",
    // "Three - 30 Minute, 60 Second, 1/10th of a second||subDial",
    // "Three - 30 Minute, 60 Second, 12 Hour Sub dials||subDial",
    // "Three - 30 Minute, dual 12 Hour / Moonphase and dual 24 Hour / 60 Seconds||subDial",
    // "Three - 30 Minutes, dual 12 Hours / Moonphase and a dual 24 hour / 60 Seconds||subDial",
    // "Three - 60 Minute, 12 Hour and 24 Hour||subDial",
    // "Three - 60 Minute, 60 Second and 1/10 Second||subDial",
    // "Three - 60 Minute, 60 Second and 12 Hour||subDial",
    // "Three - 60 Minute, 60 Second and 24 Hour||subDial",
    // "Three - 60 Minute, 60 Second, 12 Hour||subDial",
    // "Three - 60 Minute, 60 Second, 24 Hour||subDial",
    // "Three - 60 Minutes, 60 Seconds and 1/10 seconds||subDial",
    // "Three - 60 Minutes, 60 Seconds and 1/110th of a Second||subDial",
    // "Three - 60 Minutes, 60 Seconds and 24 Hours||subDial",
    // "Three - 60 Minutes, 60 Seconds, 12 Hours||subDial",
    // "Three - 60 Minutes, 60 Seconds, 24 Hours||subDial",
    // "Three - 60 Mnutes, 60 Seconds and 24 Hours||subDial",
    // "Three - 60 Mnutes, 60 Seconds, 24 Hours||subDial",
    // "Three - 60 Second (Inner Moonphase), 30 Minute and 12 Hour||subDial",
    // "Three - 60 Second (inner 12 Hour), 30 Minute and Moonphase||subDial",
    // "Three - 60 Second / Moonphase, 30 Minute and 12 Hour||subDial",
    // "Three - 60 Second / Tachymeter, 60 Minute and 24 Hour||subDial",
    // "Three - 60 Second and 30 Minute and 24 Hour||subDial",
    // "Three - 60 Second and 30 Minute and Day of the Week||subDial",
    // "Three - 60 Second and 30 Minute and Tourbillon||subDial",
    // "Three - 60 Second and 30 Minute, Day of the Week||subDial",
    // "Three - 60 Second and 60 Minute and Date||subDial",
    // "Three - 60 Second, 1/100th Second and 24 Hour||subDial",
    // "Three - 60 Second, 1/10th Second and 12 Hour||subDial",
    // "Three - 60 Second, 1/10th of a Second and 12 Hour||subDial",
    // "Three - 60 Second, 1/10th of a Second, and 12 Hours||subDial",
    // "Three - 60 Second, 1/20th Second and 12 Hour||subDial",
    // "Three - 60 Second, 12 Hour and 1/10th of a Second||subDial",
    // "Three - 60 Second, 12 Hour and 24 Hour (GMT)||subDial",
    // "Three - 60 Second, 12 Hour and 24 hour (GMT)||subDial",
    // "Three - 60 Second, 12 Hour, Day/Night Indicator||subDial",
    // "Three - 60 Second, 12 Hour/60 Minute and 1/10th of a Second||subDial",
    // "Three - 60 Second, 12 Hours and 24 Hours||subDial",
    // "Three - 60 Second, 12 Hours, and 24 Hours||subDial",
    // "Three - 60 Second, 12 hour and 1/20th of a Second||subDial",
    // "Three - 60 Second, 12, Hour, 24 Hour||subDial",
    // "Three - 60 Second, 15 Minute and 6 Hour Totalizer||subDial",
    // "Three - 60 Second, 24 Hour and 12 Hour||subDial",
    // "Three - 60 Second, 24 Hour and Dual 1/100th of a Second/Day of the Week||subDial",
    // "Three - 60 Second, 30 Minute||subDial",
    // "Three - 60 Second, 30 Minute & 24 Hour||subDial",
    // "Three - 60 Second, 30 Minute and 1/10 Second||subDial",
    // "Three - 60 Second, 30 Minute and 1/10 Second Counter||subDial",
    // "Three - 60 Second, 30 Minute and 1/10th of a Second||subDial",
    // "Three - 60 Second, 30 Minute and 1/10th of a Second, Retrograde Day of the Week||subDial",
    // "Three - 60 Second, 30 Minute and 1/10th of a Second. Retrograde Day||subDial",
    // "Three - 60 Second, 30 Minute and 1/10th of a Second. Retrograde Day of the Week||subDial",
    // "Three - 60 Second, 30 Minute and 1/10th of a SecondOne- Small Seconds||subDial",
    // "Three - 60 Second, 30 Minute and 1/20th of a Second||subDial",
    // "Three - 60 Second, 30 Minute and 10 Hour||subDial",
    // "Three - 60 Second, 30 Minute and 10 Hours||subDial",
    // "Three - 60 Second, 30 Minute and 12||subDial",
    // "Three - 60 Second, 30 Minute and 12 Hour||subDial",
    // "Three - 60 Second, 30 Minute and 12 Hours||subDial",
    // "Three - 60 Second, 30 Minute and 12 Hous||subDial",
    // "Three - 60 Second, 30 Minute and 12 hour||subDial",
    // "Three - 60 Second, 30 Minute and 12 hours||subDial",
    // "Three - 60 Second, 30 Minute and 24 Hour||subDial",
    // "Three - 60 Second, 30 Minute and 24 Hours||subDial",
    // "Three - 60 Second, 30 Minute and 24 hour||subDial",
    // "Three - 60 Second, 30 Minute and 6 Hour||subDial",
    // "Three - 60 Second, 30 Minute and 6 Hours||subDial",
    // "Three - 60 Second, 30 Minute and 60 Second||subDial",
    // "Three - 60 Second, 30 Minute and Date||subDial",
    // "Three - 60 Second, 30 Minute and Date (inner moonphase)||subDial",
    // "Three - 60 Second, 30 Minute and Date/Moonphase||subDial",
    // "Three - 60 Second, 30 Minute and Day||subDial",
    // "Three - 60 Second, 30 Minute and Day of the Week||subDial",
    // "Three - 60 Second, 30 Minute and Moonphase||subDial",
    // "Three - 60 Second, 30 Minute and Tourbillion||subDial",
    // "Three - 60 Second, 30 Minute and Tourbillon,||subDial",
    // "Three - 60 Second, 30 Minute and day||subDial",
    // "Three - 60 Second, 30 Minute and12 Hour||subDial",
    // "Three - 60 Second, 30 Minute, 24 Hour||subDial",
    // "Three - 60 Second, 40 Minute and 1/100th of a Second||subDial",
    // "Three - 60 Second, 60 Minute (inner 12 Hours) and Moonphase||subDial",
    // "Three - 60 Second, 60 Minute and 1/10 of a Second||subDial",
    // "Three - 60 Second, 60 Minute and 1/10th of a Second||subDial",
    // "Three - 60 Second, 60 Minute and 1/20th of a Second||subDial",
    // "Three - 60 Second, 60 Minute and 1/5th of a Second||subDial",
    // "Three - 60 Second, 60 Minute and 12 Hour||subDial",
    // "Three - 60 Second, 60 Minute and 12 Hour (Alarm)||subDial",
    // "Three - 60 Second, 60 Minute and 12 Hour/60 Minute||subDial",
    // "Three - 60 Second, 60 Minute and 12 Hours||subDial",
    // "Three - 60 Second, 60 Minute and 12/24 Hour||subDial",
    // "Three - 60 Second, 60 Minute and 24 Hour||subDial",
    // "Three - 60 Second, 60 Minute and 24 Hour (Alarm)||subDial",
    // "Three - 60 Second, 60 Minute and 24 Hour (GMT)||subDial",
    // "Three - 60 Second, 60 Minute and 24 Hour. Power Reserve||subDial",
    // "Three - 60 Second, 60 Minute and 24 Hour. Power Reserve Indicator||subDial",
    // "Three - 60 Second, 60 Minute and 24 Hours||subDial",
    // "Three - 60 Second, 60 Minute and 24 hours||subDial",
    // "Three - 60 Second, 60 Minute and Date/Moonphase||subDial",
    // "Three - 60 Second, 60 Minute and Day/Night Indicator||subDial",
    // "Three - 60 Second, 60 Minute and Match Phase counter (used to time all phases of a football [soccer] match||subDial",
    // "Three - 60 Second, 60 Minute and Moonphase||subDial",
    // "Three - 60 Second, 60 Minute and Moonphase/Average Length of Lunar Cycle Indicator||subDial",
    // "Three - 60 Second, 60 Minute and Quarter||subDial",
    // "Three - 60 Second, 60 Minute and Soccor Period||subDial",
    // "Three - 60 Second, 60 Minute and12 Hour||subDial",
    // "Three - 60 Second, 60 Minute, 24 Hour||subDial",
    // "Three - 60 Second, 60 Minute/12 Hour and Day of the Week||subDial",
    // "Three - 60 Second, 60 Minutes / Tachymeter and 24 Hour||subDial",
    // "Three - 60 Second, Date and Day of the Week||subDial",
    // "Three - 60 Second, Date and Power Reserve Indicator||subDial",
    // "Three - 60 Second, Date, Equation Of Time||subDial",
    // "Three - 60 Second, Day and Date||subDial",
    // "Three - 60 Second, Day and Power Reserve||subDial",
    // "Three - 60 Second, Dual 12 Hour / 60 Minute and 1/20th of a Second||subDial",
    // "Three - 60 Second, Dual 12 Hour/30 Minute and 1/10th of a Second||subDial",
    // "Three - 60 Second, GMT 24 Hour and 12 Hour||subDial",
    // "Three - 60 Second, dual 30 Minute / 12 Hour and 1/10th of a second||subDial",
    // "Three - 60 Second, dual 60 Minute / 12 Hour and 24 Hour||subDial",
    // "Three - 60 Second, dual 60 Minute/12 Hour and 24 Hour||subDial",
    // "Three - 60 Second/Month, 30 Minute and 12 Hour||subDial",
    // "Three - 60 Seconds, 12 Hours, and 24 Hours||subDial",
    // "Three - 60 Seconds, 24 Hour with AM/PM Indicator,||subDial",
    // "Three - 60 Seconds, 30 Minute, and 12 Hours||subDial",
    // "Three - 60 Seconds, 30 Minute, and 24 Hours||subDial",
    // "Three - 60 Seconds, 30 Minutes and||subDial",
    // "Three - 60 Seconds, 30 Minutes and 1/10th of a Second||subDial",
    // "Three - 60 Seconds, 30 Minutes and 1/20th of a Second||subDial",
    // "Three - 60 Seconds, 30 Minutes and 12 Hours||subDial",
    // "Three - 60 Seconds, 30 Minutes and 12 hours||subDial",
    // "Three - 60 Seconds, 30 Minutes and 24 Hours||subDial",
    // "Three - 60 Seconds, 30 Minutes and 24 Hours Sub-dials||subDial",
    // "Three - 60 Seconds, 30 Minutes and 6 Hours||subDial",
    // "Three - 60 Seconds, 30 Minutes, 12 Hours||subDial",
    // "Three - 60 Seconds, 30 Minutes, 24 Hours||subDial",
    // "Three - 60 Seconds, 30 Minutes, 6 Hours||subDial",
    // "Three - 60 Seconds, 30 Minutes, and 12 Hours||subDial",
    // "Three - 60 Seconds, 30 Minutes, and Day of the Week||subDial",
    // "Three - 60 Seconds, 60 Minutes and 1/10th of a Second||subDial",
    // "Three - 60 Seconds, 60 Minutes and 12 hours (Alarm)||subDial",
    // "Three - 60 Seconds, 60 Minutes and 24 Hours||subDial",
    // "Three - 60 Seconds, 60 Minutes and 24 hours||subDial",
    // "Three - 60 Seconds, 60 Minutes, and 24 Hours||subDial",
    // "Three - 60 Seconds, 60 Minutes, and Day/Night Indicator||subDial",
    // "Three - 60 Seconds, Date and Day of the Week||subDial",
    // "Three - 60 Small Second, 24 Hour, 30 Minute||subDial",
    // "Three - 60 Small Second, 30 Minute, 24 Hour||subDial",
    // "Three - 60 Small Second, 60 Minute and 24 Hour||subDial",
    // "Three - 60 Small Second, 60 Minute, 24 Hour||subDial",
    // "Three - 60 Small Second, 60 Minute/12 Hour and Day||subDial",
    // "Three - 60 minute, 60 second, 1/10 seconds||subDial",
    // "Three - 60 minutes, 60 Seconds, 24 Hours||subDial",
    // "Three - 60 minutes, 60 seconds and 1/20 of a second||subDial",
    // "Three - 60 second, 30 Minute and 12 Hour||subDial",
    // "Three - 60 second, 30 minute and 1/10 seconds||subDial",
    // "Three - 60 second, 30 minute and 12 hour||subDial",
    // "Three - 60 second, 60 minute and 24 hour||subDial",
    // "Three - 60 second, 60 minute and Day||subDial",
    // "Three - 60 second, 60 minute, 12 Hour (Alarm)||subDial",
    // "Three - 60 seconds, 30 minutes and 1/10th of a second||subDial",
    // "Three - 60 seconds, 30 minutes and 24 hours||subDial",
    // "Three - 60 seconds, 30 minutes and 24 hours.||subDial",
    // "Three - 60 seconds, 60 Minutes and 24 Hours||subDial",
    // "Three - 60 seconds, 60 minutes and 24 hours||subDial",
    // "Three - 60 seconds, 60 minutes and 24 hours.||subDial",
    // "Three - 60-Minute, 60-Second, 1/10 seconds||subDial",
    // "Three - AM/PM Indicator, 12 Hour/60 Minute and Open Heart||subDial",
    // "Three - AM/PM Indicator, 24 Hour and Open Heart||subDial",
    // "Three - Chrono, 60 Seconds and 1/20th of a Second||subDial",
    // "Three - Date (inner Moonphase), Month, Day of the Week (inner leap year)||subDial",
    // "Three - Date, 12 Hour and Power Reserve Indicator||subDial",
    // "Three - Date, 12 Hour and Power Reserve. Additional 24 Time-Zone indicated at the 6 o'clock position||subDial",
    // "Three - Date, 12 Hours and Moonphase||subDial",
    // "Three - Date, 24 Hour, Day/Night Indicator and Open Heart||subDial",
    // "Three - Date, 24 hour and 24 hour||subDial",
    // "Three - Date, 60 Second and 24 Hour||subDial",
    // "Three - Date, 60 Second, and Power Indicator||subDial",
    // "Three - Date, Day and 24 Hour||subDial",
    // "Three - Date, Day and 24-hour||subDial",
    // "Three - Date, Day and Moonphase||subDial",
    // "Three - Date, Day and Small Second||subDial",
    // "Three - Date, Day of the Week , and 24 Hour||subDial",
    // "Three - Date, Day of the Week and 24 Hour||subDial",
    // "Three - Date, Day of the Week and 24 Hours||subDial",
    // "Three - Date, Day of the Week and 24-hour||subDial",
    // "Three - Date, Day of the Week and Day/Night Indicator Display||subDial",
    // "Three - Date, Day of the Week and Monnphase||subDial",
    // "Three - Date, Day of the Week and Month||subDial",
    // "Three - Date, Day of the Week and Moon Phase||subDial",
    // "Three - Date, Day of the Week and Moonphase||subDial",
    // "Three - Date, Day of the Week and Night/Day Indicator||subDial",
    // "Three - Date, Day of the Week and Small Second||subDial",
    // "Three - Date, Day of the Week and Small Seconds||subDial",
    // "Three - Date, Day of the Week and Sun and Moon||subDial",
    // "Three - Date, Day of the Week, 24 Hours||subDial",
    // "Three - Date, Day of the Week, and 24 Hours||subDial",
    // "Three - Date, Day of the Week, and Moonphase||subDial",
    // "Three - Date, Day of the Week\\, and 24 Hour||subDial",
    // "Three - Date, Day of the week, and 24 Hours||subDial",
    // "Three - Date, Day, 24 Hour||subDial",
    // "Three - Date, Day, 60 Second||subDial",
    // "Three - Date, Day, of the Week and 24 Hour||subDial",
    // "Three - Date, Dayof the Week, and Moonphase||subDial",
    // "Three - Date, Retrograde Day of the Week and Power Reserve Indicator||subDial",
    // "Three - Date, Retrograde Day, 24 Hour||subDial",
    // "Three - Date, Retrograde Day, 60 second||subDial",
    // "Three - Date/Moon Phase, Day/24 Hour Indicator and Month/Leap Year Cycle||subDial",
    // "Three - Date/Moonphase, Day/24 Hour Indicator, Month/Leap Year Cycle||subDial",
    // "Three - Date/Small Second, 12 hour/60 minute, Moon Phase||subDial",
    // "Three - Day of The Week, Month, Moonphase||subDial",
    // "Three - Day of the Week , Date and 24 Hours||subDial",
    // "Three - Day of the Week, 24 Hour and 60 Minute||subDial",
    // "Three - Day of the Week, 60 Second and 30 Minute||subDial",
    // "Three - Day of the Week, 60 Second and 30 Minute. Day of the Week||subDial",
    // "Three - Day of the Week, Date and 24 Hour||subDial",
    // "Three - Day of the Week, Date and 24 Hour. Moonphase||subDial",
    // "Three - Day of the Week, Date and 24 Hours||subDial",
    // "Three - Day of the Week, Date and 24 hour||subDial",
    // "Three - Day of the Week, Date and 24 hour (GMT)||subDial",
    // "Three - Day of the Week, Date and 60 Second||subDial",
    // "Three - Day of the Week, Date and Combined dual 24 Hour and Night/Day Indicator||subDial",
    // "Three - Day of the Week, Date and Day/Night Indicator||subDial",
    // "Three - Day of the Week, Date and Moon Phase||subDial",
    // "Three - Day of the Week, Date and Moonphase||subDial",
    // "Three - Day of the Week, Date, and 24 Hour||subDial",
    // "Three - Day of the Week, Month and 24 Hour||subDial",
    // "Three - Day of the Week, Month, and 24 Hour||subDial",
    // "Three - Day of the Week, Month, and 24 Hours||subDial",
    // "Three - Day of the Week, Seconds and Date||subDial",
    // "Three - Day of the week, Date, and 24 Hour||subDial",
    // "Three - Day, 24 Hour and 60 Minute||subDial",
    // "Three - Day, 24 Hour, Dual Time||subDial",
    // "Three - Day, 30 Minutees, 60 Seconds||subDial",
    // "Three - Day, 30 Minutes, 60 Seconds||subDial",
    // "Three - Day, Date and 24 Hour||subDial",
    // "Three - Day, Date and 24 Hour Sub-dials||subDial",
    // "Three - Day, Date and 24 hour||subDial",
    // "Three - Day, Date, 24 Hour||subDial",
    // "Three - Day, Date, 24 Hours||subDial",
    // "Three - Day, Date, 24 hour||subDial",
    // "Three - Day, Date, Moon Phase||subDial",
    // "Three - Day, Date, MoonPhase||subDial",
    // "Three - Day, Date, Moonphase||subDial",
    // "Three - Day, Date, and 24 Hour||subDial",
    // "Three - Day, Date. 24 Hour||subDial",
    // "Three - Day, Month, and 24 Hour||subDial",
    // "Three - Day. 30 Minutes, 60 Seconds||subDial",
    // "Three - Days of the Week, 24 hours and Date||subDial",
    // "Three - Dual 24 Hour/60 Second, 30 Minute and 12 Hour/Moon Phase||subDial",
    // "Three - Dual 60 Second / 12 Hour , 60 Minute and 1/20th of a Second||subDial",
    // "Three - Dual 60 Second / 24 Hour , 12 Hour/ Moonphase and 30 Minute||subDial",
    // "Three - Dual 60 Second / 24 Hour, Dual 12 Hour / Moonphase and 30 Minutes||subDial",
    // "Three - Dual 60 Second / Tachymeter, 60 Minute and 24 Hour||subDial",
    // "Three - Dual 60 Seconds / 12 Hour, 60 Minutes and 1/20th of a Second||subDial",
    // "Three - Dual 60 Seconds / 24 Hours, 30 Minutes and 12 Hours. Moonphase Display||subDial",
    // "Three - Dual Date / Day of the Week, Month, Dual Moonphase/ Small Seconds||subDial",
    // "Three - Function, 24 Hour (Dual Time) and 1/20th of a Second||subDial",
    // "Three - GMT, 30 Minute and 12 Hour (Moonphase)||subDial",
    // "Three - Hours/minutes, flying tourbillon, power reserve||subDial",
    // "Three - Minute, Second, Moonphase||subDial",
    // "Three - Month, Day and 24 Hour||subDial",
    // "Three - Month, Day and 24 Hour Sub-dials||subDial",
    // "Three - Month, Day and Date||subDial",
    // "Three - Month, Day and Open Heart||subDial",
    // "Three - Month, Day of the Week and 24 Hour||subDial",
    // "Three - Month, Day of the Week and 24 Hour (GMT)||subDial",
    // "Three - Month, Day of the Week and Date. Power Reserve||subDial",
    // "Three - Month, Day of the Week and Moonphase||subDial",
    // "Three - Month, Day of the Week and Small Second||subDial",
    // "Three - Month, Day of the Week and Small Seconds||subDial",
    // "Three - Month, Day of the Week and dual Date / Moonphase||subDial",
    // "Three - Month, Day of the Week, and Moonphase||subDial",
    // "Three - Month, Day of the week, Moonphase||subDial",
    // "Three - Month, Day, 24 Hour||subDial",
    "Three - Month, Day, Date/Moonphase||subDial",
    "Three - Month, Day, Moonphase||subDial",
    "Three - Moon Phase, Small Second and Power Reserve Indicator||subDial",
    "Three - Power Reserve, 2nd Time Zone and Date||subDial",
    "Three - Power Reserve, Dual Time and Date||subDial",
    "Three - Retograde Day, Retrograde Date, 24 Hour||subDial",
    "Three - Retrograde 20 Seconds Indicators||subDial",
    "Three - Retrograde Date, 24 hour and Retrograde 24 hour||subDial",
    "Three - Retrograde Date, Retrograde 24 hour and 24 hour||subDial",
    "Three - Retrograde Date, Retrograde Day of the Week and 24 Hour||subDial",
    "Three - Second, 30 Minute and 12 Hour||subDial",
    "Three - Second, 60 Minute and 24 Hour (GMT)||subDial",
    "Three - Seconds / Day-Night Indicator, Days of the Week and Date||subDial",
    "Three - Seconds / Moonphase, Date and Day of the Week||subDial",
    "Three - Seconds, 30 Minute and 12 Hour||subDial",
    "Three - Seconds, Date and Day of the Week||subDial",
    "Three - Seconds, Power Reserve and 12/24 Hour||subDial",
    "Three - Small Running Seconds, 30 Minute and 12 Hour||subDial",
    "Three - Small Second, 60 Minute / 12 Hour (Alarm). Day of the Week||subDial",
    "Three - Small Second, 60 Minute, 12 Hour||subDial",
    "Three - Small Second, 60 Minute/12 Hour and Day of the Week||subDial",
    "Three - Small Second, Date/Moonphase, Power Reserve Indicator||subDial",
    "Three - Small Second, Small Second 12 Hour||subDial",
    "Three - Time Second / Chronograph Second Hand, Chronograph Minute/1/20 second hand hand, Mode||subDial",
    "Three - Tourbillon, 24 Hour and Power Reserve Indicator||subDial",
    "Three - Tourbillon, 60 minute and Date||subDial",
    "Three - Tourbillon, Power Reserve and Retrograde 24 Hour Indicator||subDial",
    "Three - Week, 60 Second, 30 Minute||subDial",
    "Three - date, 60 second and 30 minute timer||subDial",
    "Three - date, day and 24 hour||subDial",
    "Three - dual 60 Second / 24 Hour , 30 Minute and 12 Hour||subDial",
    "Three - dual 60 Second / Tachymeter, 60 Minute and 24 Hour||subDial",
    "Three - dual 60 Seconds / 24 Hour, 30 Minute and dual 12 Hour / Moonphase||subDial",
    "Three - dual Seconds / 24 Hour, 30 Minute and 12 Hour / Monnphase||subDial",
    "Three - dual Seconds / Moonphase, Date and Day of the Week||subDial",
    "Three - small seconds at the 9 o'clock position, chronograph 30 minute counter at the 12 o'clock position and a 12 hour counter at the 6 o'clock position||subDial",
    "Three -24 Hour, Date and Day of the Week||subDial",
    "Three -24-Hour, Date and Day of the Week||subDial",
    "Three -Date, Day, 24 Hour||subDial",
    "Three -Day of the Week, Date, and 24 Hour||subDial",
    "Three -Day,Date and 24 Hour||subDial",
    "Three 24 Hour, 60 Minute and 60 Second||subDial",
    "Three Combination Sub-dials Displaying: Day and 12 Hours, Month and Leap Year, and Date and Moonphases||subDial",
    "Three Digital - Second, Date and Day of the Week||subDial",
    "Three Digital - Seconds, Date and Day of the Week||subDial",
    "Three Digital - Seconds, Date and Function||subDial",
    "Three subdials: date, day and 24 hour indicator||subDial",
    "Three- 1/100 Second Chronograph, Perpetual Calendar, and Power Reserve||subDial",
    "Three- 12 Hour, 60 Seconds, 1/100 Seconds||subDial",
    "Three- 12 Hours, AM/PM Indicator, Flywheel||subDial",
    "Three- 12/24 Hours, Functions and Day of the Week||subDial",
    "Three- 24 Hour, Date and Day of the Week||subDial",
    "Three- 24 Hours, 60 Minutes, 60 Seconds||subDial",
    "Three- 24 Hours, 60 Seconds and Multi-Function||subDial",
    "Three- 24 Hours, Date and Day of the Week||subDial",
    "Three- 24 hours,Days of the week,Date||subDial",
    "Three- 24 hours. Days of the Week and Date||subDial",
    "Three- 30 Minute, 60 Seconds, 12 Hours||subDial",
    "Three- 60 Minutes, 60 Minutes, and 24 Hours||subDial",
    "Three- 60 Minutes, 60 Seconds, and 24 Hour||subDial",
    "Three- 60 Second Tourbillon 30 Minute and 12 Hours||subDial",
    "Three- 60 Seconds, 1/20-second, and 12/24-hour time||subDial",
    "Three- 60 Seconds, 12 Hours, and 24 Hours||subDial",
    "Three- 60 Seconds, 24 Hours, and 12 Hours||subDial",
    "Three- 60 Seconds, 30 Miniutes, and 24 Hours||subDial",
    "Three- 60 Seconds, 30 Minute and 12 Hours||subDial",
    "Three- 60 Seconds, 30 Minute, 12 Hours||subDial",
    "Three- 60 Seconds, 30 Minute, and 12 Hours||subDial",
    "Three- 60 Seconds, 30 Minute, and 24 Hour||subDial",
    "Three- 60 Seconds, 30 Minute, and Moonphase||subDial",
    "Three- 60 Seconds, 30 Minutes, 12 Hours||subDial",
    "Three- 60 Seconds, 30 Minutes, and 12 Hours||subDial",
    "Three- 60 Seconds, 30 Minutes, and 24 Hours||subDial",
    "Three- 60 Seconds, 30 Minutes, and Date||subDial",
    "Three- 60 Seconds, 30 Minutes, and Day of the Week||subDial",
    "Three- 60 Seconds, 60 Minute, and 24 Hours||subDial",
    "Three- 60 Seconds, 60 Minutes, (inner 12/24 Hours), Alarm||subDial",
    "Three- 60 Seconds, 60 Minutes, and 24 Hours||subDial",
    "Three- 60 seconds,60 minutes, 24 hours||subDial",
    "Three- Date (inner Moonphase), Month, Day of the Week (inner leap year)||subDial",
    "Three- Date /day of the Week, Month, Moonphase/ Small Seconds||subDial",
    "Three- Date, Day of the Week and 24 Hours||subDial",
    "Three- Date, Day of the Week and Power Reserve||subDial",
    "Three- Date, Day of the Week, Month||subDial",
    "Three- Date, Day of the Week, and 24 Hours||subDial",
    "Three- Date, Day of the Week, and Month||subDial",
    "Three- Date, Day of the week, and 24 Hours||subDial",
    "Three- Day of the Week, Month, and 24 Hours||subDial",
    "Three- Days of the Week,24 Hours and Date||subDial",
    "Three- Dual 60 Seconds / Day-Night Indicator, Days of the Week and Date||subDial",
    "Three- Month, Day of the Week, and 24 Hours||subDial",
    "Three: 12 Hours, 1/20th Seconds and 60 Seconds Sub-dials||subDial",
    "Three: 12 Hours, 30 Minutes and 60 Seconds||subDial",
    "Three: 12 Hours, 30 Minutes, 60 Seconds||subDial",
    "Three: 12 Hours, 30 Minutes, 60 Seconds Sub-dials||subDial",
    "Three: 12 Hours, 30 Minutes, Small Seconds||subDial",
    "Three: 12 Hours, 30 Minutes, and 60 Seconds Sub-dials||subDial",
    "Three: 24 Hour, Date ans Day of the Week||subDial",
    "Three: 24 Hours, 60 Minutes and 60 Seconds Sub-dials||subDial",
    "Three: 24 Hours, 60 Minutes, 60 Seconds||subDial",
    "Three: 24 Hours, 60 Minutes, 60 Seconds Sub-dials||subDial",
    "Three: 24 Hours, 60 Seconds, and Combined Functions and Time Zones S||subDial",
    "Three: 24 Hours, Date and Day of the Week||subDial",
    "Three: 30 Minutes, 60 Seconds and 1/10 Seconds||subDial",
    "Three: 30 Minutes, 60 Seconds, 1/10th of a Second Sub dials||subDial",
    "Three: 30 minutes, 60 seconds, 1/10th of a second||subDial",
    "Three: 60 Second, 30 Minute and 1/10th of a Second. Retrograde Day of the Week||subDial",
    "Three: 60 Second, 60 Minute and 24 Hour||subDial",
    "Three: 60 Seconds, 15 Minutes and 6 Hour Totalizer||subDial",
    "Three: 60 Seconds, Date and Day of the Week||subDial",
    "Three: 60 second, 60 minute timer, and 24 hour||subDial",
    "Three: Date, Day of the Week and 24 Hour||subDial",
    "Three: Date, Day of the Week and Moonphase||subDial",
    "Three: Date, Day of the Week and Small Second||subDial",
    "Three: Month, Day of the Week and GMT (24 Hours)||subDial",
    "Three: Seconds, Date and Day of the Week||subDial",
    "Three:1/10th of a Second, 30 Minutes and 60 Seconds||subDial",
    "Tourbillon||subDial",
    "Tourbillon Carriage Small Second with Date||subDial",
    "Tree - 60 Seconds, 30 Minutes,and 12 Hours||subDial",
    "Two - 1/8th Second and 30 Minute||subDial",
    "Two - 12 Hour (Dual Time) and 60 Seconds||subDial",
    "Two - 12 Hour (Dual Time) and Small Second||subDial",
    "Two - 12 Hour (GMT). Power Reseve||subDial",
    "Two - 12 Hour and 24 Hour||subDial",
    "Two - 12 Hour and 30 Minute||subDial",
    "Two - 12 Hour and 30 Minute. 24 Hour (GMT)||subDial",
    "Two - 12 Hour and 30 Second||subDial",
    "Two - 12 Hour and 60 Minute Sub-dials||subDial",
    "Two - 12 Hour and 60 Seconds||subDial",
    "Two - 12 Hour and Day / Night Display||subDial",
    "Two - 12 Hour and Day / Night Indicator||subDial",
    "Two - 12 Hour and Moonphase||subDial",
    "Two - 12 Hour and Small Second||subDial",
    "Two - 12 Hour, 12 Hour||subDial",
    "Two - 12 Hour/60 Minite and Retrograde Date||subDial",
    "Two - 12 Hour/60 Minute and Day/Night Indicator||subDial",
    "Two - 12 Hour/60 Minute, and Day/Night Indicator||subDial",
    "Two - 12 Hours and 24 Hours||subDial",
    "Two - 12 Hours and 30 Minutes||subDial",
    "Two - 12 Hours and Date. Moonphase||subDial",
    "Two - 12 Hours and Power Reserve Indicator||subDial",
    "Two - 12 Hours, Sun & Moon||subDial",
    "Two - 12 hour/60 minute and 24 Hour-Day/Night Indicator||subDial",
    "Two - 24 Hour (Dual Time) and Power Reserve Indicator||subDial",
    "Two - 24 Hour (GMT) and Month||subDial",
    "Two - 24 Hour Digital UTC time display||subDial",
    "Two - 24 Hour and 24 Hour||subDial",
    "Two - 24 Hour and 24 Hour (Dual Time)||subDial",
    "Two - 24 Hour and 60 Second||subDial",
    "Two - 24 Hour and Date||subDial",
    "Two - 24 Hour and Date. Retrograde Day||subDial",
    "Two - 24 Hour and Date. Retrograde Day of the Week||subDial",
    "Two - 24 Hour and Day of the Week||subDial",
    "Two - 24 Hour and Function||subDial",
    "Two - 24 Hour and Month||subDial",
    "Two - 24 Hour and Month / Leap Year||subDial",
    "Two - 24 Hour and Month/Leap Year||subDial",
    "Two - 24 Hour and Open Heart||subDial",
    "Two - 24 Hour and Power Reserve||subDial",
    "Two - 24 Hour and Small Second||subDial",
    "Two - 24 Hour and Small Seconds||subDial",
    "Two - 24 Hour,||subDial",
    "Two - 24 Hour, 24 Hour||subDial",
    "Two - 24 Hour, 60 Minute||subDial",
    "Two - 24 Hour, 60 Second||subDial",
    "Two - 24 Hour, Date||subDial",
    "Two - 24 Hour, Fly-wheel||subDial",
    "Two - 24 Hour, Open Heart||subDial",
    "Two - 24 Hour, Power Reserve||subDial",
    "Two - 24 Hour, Small Second||subDial",
    "Two - 24 Hour/60 Minute and Power Reserve Indicator||subDial",
    "Two - 24 Hour/Moonphase and OpenHeart||subDial",
    "Two - 24 Hours and Date||subDial",
    "Two - 24 Hours and day of the Week||subDial",
    "Two - 24 Hours, 60 Seconds||subDial",
    "Two - 24 hour and 24 hour||subDial",
    "Two - 24 hour and Retrograde 24 Hour||subDial",
    "Two - 24 hours and Month||subDial",
    "Two - 30 Minute and 12 Hour||subDial",
    "Two - 30 Minute and 12 Hours||subDial",
    "Two - 30 Minute and 6 Hours||subDial",
    "Two - 30 Minute and 60 Second||subDial",
    "Two - 30 Minute and Second||subDial",
    "Two - 30 Minute, and 12 Hours||subDial",
    "Two - 30 Minutes and 12 Hours||subDial",
    "Two - 30 Minutes and 12 hour||subDial",
    "Two - 30 Minutes and 60 Seconds||subDial",
    "Two - 30 Minutes, 12 Hours||subDial",
    "Two - 30 Minutes, and 12 Hours||subDial",
    "Two - 30 Seconds and 12 Hour||subDial",
    "Two - 45 Minute and 60 Seconds||subDial",
    "Two - 60 Minute & 24 Hour||subDial",
    "Two - 60 Minute and 12 Hour||subDial",
    "Two - 60 Minute and 24 Hour||subDial",
    "Two - 60 Minute and 24 hour||subDial",
    "Two - 60 Minute and 60 Second||subDial",
    "Two - 60 Minute and Power Reserve Indicator||subDial",
    "Two - 60 Minute/12 Hour and Power Reserve Indicator||subDial",
    "Two - 60 Minutes, 60 Seconds||subDial",
    "Two - 60 Secods, 24 Hour with AM/PM Indicator||subDial",
    "Two - 60 Second (inner 12 Hour) and 30 Minute. Moonphase||subDial",
    "Two - 60 Second (inner 12 Hours) and 30 Minute||subDial",
    "Two - 60 Second and 12 Hour||subDial",
    "Two - 60 Second and 12 Hour (Alarm)||subDial",
    "Two - 60 Second and 12 Hour (Second Time Zone). Day / Night (AM/PM) indicator||subDial",
    "Two - 60 Second and 12 Hours||subDial",
    "Two - 60 Second and 12 Minute||subDial",
    "Two - 60 Second and 24 Hour||subDial",
    "Two - 60 Second and 24 Hour (Dual Time)||subDial",
    "Two - 60 Second and 24 Hour (GMT)||subDial",
    "Two - 60 Second and 24 hour||subDial",
    "Two - 60 Second and 24 hour (Dual Time)||subDial",
    "Two - 60 Second and 30 Minute||subDial",
    "Two - 60 Second and 30 Minute (inner 12 Hour)||subDial",
    "Two - 60 Second and 30 Minute. Date||subDial",
    "Two - 60 Second and 30 Minute. Date Sub-dial||subDial",
    "Two - 60 Second and 30 Minute. Date Sub-dial at the 6 o'clock position||subDial",
    "Two - 60 Second and 30 Minute. Date at the 6 o'clock position||subDial",
    "Two - 60 Second and 30 Minute. Day / Night Indicator||subDial",
    "Two - 60 Second and 30 Minute. Day of the Week||subDial",
    "Two - 60 Second and 30 Minute. Day of the Week Sub-dial||subDial",
    "Two - 60 Second and 30 Minute. Day of the Week Sub-dial at the 6 o'clock position||subDial",
    "Two - 60 Second and 30 Minute. Day of the Week Sub-dial at the 9 o'clock position||subDial",
    "Two - 60 Second and 30 Minute. Day of the Week sub-dial||subDial",
    "Two - 60 Second and 30 Minute. Day of the Weel||subDial",
    "Two - 60 Second and 30 Minute. Day of the Weelk||subDial",
    "Two - 60 Second and 30 Minute. Day of the week Sub-dial at 6 o'clock||subDial",
    "Two - 60 Second and 30 Minute. Day of the week sub-dial||subDial",
    "Two - 60 Second and 30 Minute. Moonphase||subDial",
    "Two - 60 Second and 30 Minute. Power Reserve||subDial",
    "Two - 60 Second and 45 Minute||subDial",
    "Two - 60 Second and 60 Minute||subDial",
    "Two - 60 Second and 60 Minute / 12 Hours (Alarm). Day of the Week||subDial",
    "Two - 60 Second and 60 Minute / Moonphase||subDial",
    "Two - 60 Second and 60 Minute. Date Sub-dial above the 6 o'clock position||subDial",
    "Two - 60 Second and Date||subDial",
    "Two - 60 Second and Dual 12 Hour / 30 Minute||subDial",
    "Two - 60 Second and Moonphase||subDial",
    "Two - 60 Second and Power Reserve||subDial",
    "Two - 60 Second and Power Reserve Indicator||subDial",
    "Two - 60 Second and dual 30 Minute / 12 Hour||subDial",
    "Two - 60 Second, 30 Minute||subDial",
    "Two - 60 Second, 30 Minute. Date||subDial",
    "Two - 60 Second, 60 Minute||subDial",
    "Two - 60 Second, 60 Minute / 24 Hour (Alarm). Day of the Week Display below the 12 o'clock position||subDial",
    "Two - 60 Second, and 30 Minute||subDial",
    "Two - 60 Seconds and 12 Hours||subDial",
    "Two - 60 Seconds and 12 hours||subDial",
    "Two - 60 Seconds and 24 Hour||subDial",
    "Two - 60 Seconds and 24 Hours (dual time)||subDial",
    "Two - 60 Seconds and 24 hour||subDial",
    "Two - 60 Seconds and 30 Minute||subDial",
    "Two - 60 Seconds and 30 Minutes||subDial",
    "Two - 60 Seconds and 30 Minutes. Three-ring Tachymeter in central part of dial||subDial",
    "Two - 60 Seconds and 45 Minutes||subDial",
    "Two - 60 Seconds and 60 Minutes||subDial",
    "Two - 60 Seconds and Date||subDial",
    "Two - 60 Seconds and Dual 30 Minute / 12 Hours||subDial",
    "Two - 60 Seconds and a dual 60 Minutes and 12 Hours||subDial",
    "Two - 60 Seconds, 12 Hours||subDial",
    "Two - 60 Seconds, 24 Hour with AM/PM Indicator||subDial",
    "Two - 60 Seconds, 30 Minute||subDial",
    "Two - 60 Seconds, and 12 Hours||subDial",
    "Two - 60 Seconds, and 30 Minute||subDial",
    "Two - 60 Seconds, and 30 Minutes||subDial",
    "Two - 60 Seconds, and 45 Minutes||subDial",
    "Two - 60 minute and 24 hour||subDial",
    "Two - 60 minute and 24 hour (GMT)||subDial",
    "Two - 60 minute, and 24 hour||subDial",
    "Two - 60 second and 24 hour||subDial",
    "Two - 60 second and 24 hour (Dual Time)||subDial",
    "Two - 60 second and 60 minute timer||subDial",
    "Two - 60 second,and 24 hour||subDial",
    "Two - 60-second, 7 day power reserve||subDial",
    "Two - 7 Day Power Reserve and 60 Second||subDial",
    "Two - AM/PM Indicator , Dual Time||subDial",
    "Two - AM/PM Indicator and 24 Hour (Dual Time)||subDial",
    "Two - AM/PM Indicator and Dual Time||subDial",
    "Two - AM/PM Indicator, 24 Hour||subDial",
    "Two - AM/PM Indicator, Dual Time||subDial",
    "Two - Calander Week and Power Reserve Indicator||subDial",
    "Two - Combined 60 Minute and 12 Hour and 60 Second||subDial",
    "Two - Combined Hour and Minute Totalizer and Small Hacking Seconds Sub-dials||subDial",
    "Two - Date / Moon Phase||subDial",
    "Two - Date / Moonphase and 24 hours||subDial",
    "Two - Date and 24 Hour||subDial",
    "Two - Date and 24 Hour (GMT)||subDial",
    "Two - Date and 24 Hours||subDial",
    "Two - Date and Day||subDial",
    "Two - Date and Day of the Week||subDial",
    "Two - Date and Day of the week||subDial",
    "Two - Date and Moonphase||subDial",
    "Two - Date and Power Reserve||subDial",
    "Two - Date and Power Reserve Indicator||subDial",
    "Two - Date, 24 Hour||subDial",
    "Two - Date, Day||subDial",
    "Two - Date, Day of the Week||subDial",
    "Two - Date, Power Reserve Indicator||subDial",
    "Two - Date, and 12 Hours||subDial",
    "Two - Date, and Day of the Week||subDial",
    "Two - Date/Moon Phase and Open Herat||subDial",
    "Two - Date/Moon phase and Open Heart||subDial",
    "Two - Day and 24 Hour||subDial",
    "Two - Day and 24 Hour / Moonphase||subDial",
    "Two - Day and Date||subDial",
    "Two - Day and Day of the Week||subDial",
    "Two - Day and Month||subDial",
    "Two - Day of the Week and 24 Hour||subDial",
    "Two - Day of the Week and 24 Hours||subDial",
    "Two - Day of the Week and Date||subDial",
    "Two - Day of the Week and Day/Night Indicator||subDial",
    "Two - Day of the Week and Month||subDial",
    "Two - Day of the Week and Sun / Moon indicator||subDial",
    "Two - Day of the Week and Sun and Moon||subDial",
    "Two - Day of the Week and Sun and Moon Indicator||subDial",
    "Two - Day of the Week and Sun-Moon||subDial",
    "Two - Day of the Week with Sun / Moon indicator||subDial",
    "Two - Day of the Weel and Date||subDial",
    "Two - Day, 24 Hour||subDial",
    "Two - Day, 24 Hours||subDial",
    "Two - Day, Day/Night Indicator||subDial",
    "Two - Day/ Night Indicator & Dual Time||subDial",
    "Two - Day/Night Indicator & Dual Time||subDial",
    "Two - Day/Night Indicator & Dual Time Zone||subDial",
    "Two - Day/Night Indicator & Dual Time zone||subDial",
    "Two - Days and Sun/Moon||subDial",
    "Two - Dual Time and 24 Hour||subDial",
    "Two - Dual Time at the 8 o'clock position and 24 Hour at the 9 o'clock position||subDial",
    "Two - Dual Time, 24 Hours||subDial",
    "Two - Dual Time, Small Seconds||subDial",
    "Two - Month and 24 Hour||subDial",
    "Two - Month and 24 Hour (GMT)||subDial",
    "Two - Month and Day||subDial",
    "Two - Month and Day Sub-dials||subDial",
    "Two - Month, Day||subDial",
    "Two - Month/60 Second and Power Reserve Indicator||subDial",
    "Two - Moon Phase, Day/Night Indicator||subDial",
    "Two - Moonphase and 24 Hour Sub-dials||subDial",
    "Two - Moonphase and Small Second||subDial",
    "Two - Power Reserve Indicator and Tourbillon||subDial",
    "Two - Power Reserve Indicator, Small Second||subDial",
    "Two - Power Reserve and 24 Hour||subDial",
    "Two - Power Reserve and Flying Tourbillon||subDial",
    "Two - Retrograde Date and Day of the Week||subDial",
    "Two - Retrograde Date and Retrograde Day||subDial",
    "Two - Retrograde Date, Day||subDial",
    "Two - Second and 12 Hour (Second Time zone)||subDial",
    "Two - Seconds and 24 Hour (GMT)||subDial",
    "Two - Seconds and 24 Hours||subDial",
    "Two - Seconds and 24 Hours (GMT)||subDial",
    "Two - Seconds and Power Reserve||subDial",
    "Two - Seconds, 24 Hour||subDial",
    "Two - Small Hour and Small Second||subDial",
    "Two - Small Secon and Retrograde Day||subDial",
    "Two - Small Second and 12 Hour||subDial",
    "Two - Small Second and 24 Hour||subDial",
    "Two - Small Second and 30 Minute||subDial",
    "Two - Small Second and Moon Phase||subDial",
    "Two - Small Second and Moonphase||subDial",
    "Two - Small Second and Power Reserve Indicator||subDial",
    "Two - Small Second and Power Reserve Indicator on Caseback||subDial",
    "Two - Small Second and Power Reserved Indicator||subDial",
    "Two - Small Second at the 6 o'clock position and Power Reserve Indicator||subDial",
    "Two - Small Second, 12 Hour||subDial",
    "Two - Small Second, Moon Phase||subDial",
    "Two - Small Second, Power Reserve||subDial",
    "Two - Small Second, Power Reserve Indicator||subDial",
    "Two - Small Second, Retrograde Day||subDial",
    "Two - Small Second, Retrograde Day of the Week||subDial",
    "Two - Small Seconds||subDial",
    "Two - Small Seconds and 12 Hour||subDial",
    "Two - Small Seconds and 24 Hours||subDial",
    "Two - Small Seconds and Moon Phase||subDial",
    "Two - Small Seconds and Moonphase||subDial",
    "Two - Small Seconds and Power Reserve||subDial",
    "Two - Small Seconds and Power Reserve Indication||subDial",
    "Two - Small Seconds and Power Reserve Indicator. Moonphase||subDial",
    "Two - Small Seconds, 24 Hours||subDial",
    "Two - Small Seconds, Power Reserve||subDial",
    "Two - Small second at the 6 o'clock position, and Tourbillon at the 9 o'clock position||subDial",
    "Two - Small second, 12 hour/60 minute||subDial",
    "Two - Tourbillon and Power Reserve Indicator||subDial",
    "Two - Tourbillon and Small Second||subDial",
    "Two - Tourbillon ans Astronomy Orbital Display||subDial",
    "Two - Tourbillon, Moon Phase||subDial",
    "Two - Tourbillon, Power Reserve Indicator||subDial",
    "Two - date and Day||subDial",
    "Two -1/10 second, 1/100 second||subDial",
    "Two -60 Second and Power Reserve Indicator||subDial",
    "Two -AM/PM Indicator , Dual Time||subDial",
    "Two Date and Day||subDial",
    "Two Digital: Date and Chronograph||subDial",
    "Two Time Zone||subDial",
    "Two- 12 Hours and Small Second||subDial",
    "Two- 12 Hours, Small Second||subDial",
    "Two- 24 Hours, 60 Seconds||subDial",
    "Two- 24 Hours, Power Reserve||subDial",
    "Two- 24 Hours, Small Second||subDial",
    "Two- 30 Minutes, and 24 Hours||subDial",
    "Two- 60 Second, 12 Hour||subDial",
    "Two- 60 Second, 30 Minute||subDial",
    "Two- 60 Seconds and 12 Hour (Alarm)||subDial",
    "Two- 60 Seconds and 12 Hours||subDial",
    "Two- 60 Seconds and 24 Hours||subDial",
    "Two- 60 Seconds and 45 Minutes||subDial",
    "Two- 60 Seconds and Power Reserve||subDial",
    "Two- 60 Seconds, Power Reserve||subDial",
    "Two- 60 Seconds, and 12 Hours||subDial",
    "Two- 60 Seconds, and 24 Hours||subDial",
    "Two- 60 Seconds, and 30 Minute||subDial",
    "Two- 60 Seconds, and 30 Minutes||subDial",
    "Two- 60 Seconds, and 45 Minutes||subDial",
    "Two- Date and Day||subDial",
    "Two- Date and Day of the Week||subDial",
    "Two- Date and Day of the Week. Moonphase||subDial",
    "Two- Date and Power Reserve Indicator||subDial",
    "Two- Date, Day of the Week||subDial",
    "Two- Date, and 24 Hours||subDial",
    "Two- Date, and Day of the Week||subDial",
    "Two- Day and Date||subDial",
    "Two- Day of the Week and Date||subDial",
    "Two- Day of the Week and Day/Night Indicator||subDial",
    "Two- Day of the Week, and Day / Night Indicator||subDial",
    "Two- Month, Day of the Week||subDial",
    "Two- Power Reserve and Small Seconds||subDial",
    "Two- Power Reserve, and 24 Hour||subDial",
    "Two- Power Reserve, and 60 Second||subDial",
    "Two- Seconds and Power Reserve||subDial",
    "Two- Small Second, Power Reserved Indicator||subDial",
    "Two- Small Seconds and Power Reserve||subDial",
    "Two- Small Seconds, and 12 Hours||subDial",
    "Two- Small Seconds, and 24 Hours||subDial",
    "Two- Small Seconds, and Power Reserve||subDial",
    "Two- Tourbillon and Small Second||subDial",
    "Two-, Date, Day/Night Indicator||subDial",
    "Two: 12 Hours and 30 Minutes||subDial",
    "Two: 24 Hour and Date. Retrograde Day of the Week||subDial",
    "Two: 60 Second and 24 Hour (Dual Time)||subDial",
    "Two: 60 Second and 30 Minute. Day of the Week||subDial",
    "Two: 60 minute and 24 hour||subDial",
    "Two: 60 second and 24 hour (Dual Time)||subDial",
    "Two: Date and 24 Hour||subDial",
    "Two: Date and 24 Hour. Retrograde Day of the Week||subDial",
    "Two: Day of the Week and Date||subDial",
    "Word Time, Day/Night Indicator||subDial",
];

const check = (inp, exp, res) => {
    const ex = new RegExp(exp, 'i');
    if (inp.value.match(ex)) {
        if (inp.sd.indexOf(res) < 0)
            inp.sd.push(res);
        inp.value = inp.value.replace(ex, '');
        // return inp;
    }
}

for (let i = 0; i < u.length; i++) {
    const v = u[i].replace(/ and /g, ',').replace(/at (.*) position|^two: |^two- |^two - |^tree - |^three: |^three- |^three - |^thee - |^one: |^one- |^one - /ig, '');
    console.log(`   ${u[i]}`)
    // console.log(`   ${v}`)
    let result = { sd: [], value: v };
    v.split('|')[0].split(',').forEach(val => {
        check(result, "s?mall seconds?", "Small Seconds");
        check(result, "chronograph", "Chronograph");
        check(result, "worl?d ?time", "World Time");
        check(result, "12[ -]?hours?", "12 Hour");
        check(result, "24[ -]?hours?", "24 Hour");
        check(result, "60[ -]?seconds?", "60 Second");
        check(result, "60[ -]?minutes?", "60 Minute");
        check(result, "45[ -]?minutes?", "45 Minute");
        check(result, "30[ -]?minutes?", "30 Minute");
        check(result, "moon[ -]?phase", "Moonphase");
        check(result, "two[ -]?time|two[ -]?zone|dual[ -]?time|dual[ -]?zone", "Dual Time Zone");
        check(result, "three[ -]?time|three[ -]?zone|three[ -]?time|three[ -]?zone", "Three Time Zone");
        check(result, "moon[ -]?phase", "Moonphase");
        check(result, "\(GMT\)|GMT", "GMT");
        check(result, "1\/10(th)?( of)?( the)?( seconds?)", "1/10th Second");
        check(result, "1\/20(th)?( of)?( the)?( seconds?)", "1/20th Second");
        check(result, "1\/100(th)?( of)?( the)?( seconds?)", "1/100th Second");
        check(result, "seconds?", "Seconds");
        check(result, "Power Reserve( Indicator)?", "Power Reserve Indicator");
        check(result, "AM ?\/ ?PM( Indicator)?", "AM/PM Indicator");
        check(result, "Day ?\/ ?Night( Indicator)?|Night ?\/ ?Day( Indicator)?", "Day / Night Indicator");
        check(result, "Retograde date", "Retograde Date");
        check(result, "date", "Date");
        check(result, "Retograde Days? of( the)? week", "Retograde Day of Week")
        check(result, "Tourbilli?on", "Tourbillon");
        check(result, "Days? of the Week", "Day of Week");
        check(result, "Sun ?(and|\/) ?Moon( indicator)?|Moon ?(and|\/) ?Sun( indicator)?", "Sun / Moon Indicator");
        check(result, "Retograde Day", "Retograde Day")
        check(result, "day", "Day");
        check(result, "Retograde Month", "Retograde Month")
        check(result, "Month", "Month");
        check(result, "perpetual calendar", "Perpetual Calendar");
        check(result, "calendar", "Calendar");
        check(result, "digital", "Digital");
        check(result, "alarm", "Alarm");
        check(result, "timer", "Timer");
        check(result, "altimeter", "Altimeter");
        check(result, "thermo|thermometer", "Thermometer");
        check(result, "stop[ -]watch", "Stop-watch");
        check(result, "timer", "Timer");

        check(result, "Sun (and|\/) Moon( indicator)?", "Sun / Moon Indicator");
        check(result, "Sun (and|\/) Moon( indicator)?", "Sun / Moon Indicator");
        // console.log(result)
    })
    result.sd.forEach(d => {
        console.log(u[i].split('|')[0] + '|' + d + '|subDial');
    })
    console.log()
}
console.log()
console.log('done')
